
<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('REGISTER')); 
	echo $this->headTitle(''); 
	$frm =  $this->form_search;
?>	
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'foundation','controller'=>'register','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table style="width:100%">
	  <tr> 
			<td> <input dojoType="dijit.form.TextBox"   id="adv_search" name="adv_search" placeholder="Search....." value="<?php echo $this->adv_search['adv_search']; ?>" class="fullside" type="text"></td>
		   <td> <?php echo $frm->getElement("study_year");?></td>
		   <td> <?php echo $frm->getElement("degree_all");?></td>
		   <td> <?php echo $frm->getElement("grade_all");?></td>
		   <td> <?php echo $frm->getElement("session");?></td>
		   <td> <?php echo $frm->getElement("room");?></td>
	  </tr>
	  <tr>
	  	<td> <input dojoType="dijit.form.DateTextBox" class="fullside" id="start_date" name="start_date" value="<?php echo $this->adv_search['start_date']; ?>"  type="text"></td>
 		<td><input dojoType="dijit.form.DateTextBox" required="true" class="fullside" id="end_date" name="end_date" value="<?php echo $this->adv_search['end_date'];?>" type="text"></td>
		<td> <?php echo $frm->getElement("user");?></td>
		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
	  </tr>
	 </table>
</form>
<?php echo $this->list;?>
