<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_STUDENT_SERVICE_PAYMENT')); 
	$base_url = Application_Form_FrmMessage::getUrl("/");
// 	print_r($this->service);exit();
?>	
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/convertion.js"></script>
<?php /*?><script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.14.1/moment.min.js"></script> <?php */ ?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>

<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require('dojox.form.BusyButton');
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dojo.store.Memory");
	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.form.Textarea");
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.CheckBox");
	
	var service_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->service));?>);
	dojo.ready(function(){ 
		displayNoneAddRow();
		addRow();
		changeControl();
		getNewCarId('');
		
		document.getElementById('hideAddRow').style.display="none";
	
		new dijit.form.FilteringSelect({
			store: service_store,
			autoComplete: false,
			queryExpr: "*${0}*",                        
		    id: "service",
		    name: "service",
			value:-1,
		    class: 'fullside',  
		   // placeHolder:"Selected service", 
		    onChange: function() {  
			    service = dijit.byId('service').get('value');
			    if(service==-2){
					dijit.byId('popup_add_service').show();
			    }
		    	getservicefee();
				getServiceCate(service);
				if(dijit.byId('student_type').get('value')!=1){
					//getStartDateService();
				}
				getCarIdByService();
		    } 
		}, "service");

		getValidate(1);
		
////////////////////////////////////////////// get student by branch ///////////////////////////////////////////////////////////////////////////

		
		new dijit.form.FilteringSelect({
		    autoComplete: false,
			queryExpr: "*${0}*",                       
		    id: "student_name_new",
		    name: "student_name_new",           
		    class: 'fullside',  
		    required: false,
		    placeHolder:"----- select student id -----",          
		    onChange: function() {  
		    	getStudentInfo();
		    }
		}, "student_name_new");

		
		new dijit.form.FilteringSelect({
		    autoComplete: false,
			queryExpr: "*${0}*",                        
		    id: "student_name_old",
		    name: "student_name_old",           
		    class: 'fullside',  
		    required: false,
		    placeHolder:"----- select student name -----",          
		    onChange: function() {  
				setID(1);
		    }
		}, "student_name_old");

		new dijit.form.FilteringSelect({
		    autoComplete: false,
			queryExpr: "*${0}*",                         
		    id: "old_car_id",
		    name: "old_car_id",           
		    class: 'fullside',  
		    required: false,
		    placeHolder:"----- select student name -----",          
		    onChange: function() {  
		    	getStudentInfo();
		    }
		}, "old_car_id");


		new dijit.form.FilteringSelect({
		    autoComplete: false,
			queryExpr: "*${0}*",                        
		    id: "stu_drop_name",
		    name: "stu_drop_name",           
		    class: 'fullside',  
		    required: false,
		    placeHolder:"----- select student name -----",          
		    onChange: function() {  
				setID(2);
		    }
		}, "stu_drop_name");

		new dijit.form.FilteringSelect({
		    autoComplete: false,
			queryExpr: "*${0}*",                        
		    id: "stu_drop_id",
		    name: "stu_drop_id",           
		    class: 'fullside',  
		    required: false,
		    placeHolder:"----- select student name -----",          
		    onChange: function() {  
		    	getStudentInfo();
		    }
		}, "stu_drop_id");
		
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////		
		
	});	
	
	
	var new_student_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_new_student = '<?php echo $this->url(array('module'=>'accounting','controller'=>'studentservicepayment','action'=>'get-new-student-by-branch')); ?>';
	function getAllNewStudentByBranch(){
		
		dijit.byId('student_name_new').attr('value','');
		branch_id = dijit.byId('branch').get('value');
		if(branch_id>0){
			dojo.xhrPost({
				url:url_new_student,
				content:{
					'branch_id':branch_id
					},
				handleAs:"json",
				load: function(data) {
					//alert(data);
					new_student_store  = getDataStorefromJSON('id','name', data);
					dijit.byId('student_name_new').set('store',new_student_store);   
				},
				error: function(err) {
					alert(err);
				}
			});
		}
	}
	
	
	var old_car_student_id_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var old_car_student_name_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	
	var url_old_student = '<?php echo $this->url(array('module'=>'accounting','controller'=>'studentservicepayment','action'=>'get-old-student-by-branch')); ?>';
	
	function getAllOldStudentByBranch(){
		
		branch_id = dijit.byId('branch').get('value');
		if(branch_id>0){
			dojo.xhrPost({
				url:url_old_student,
				content:{
					'branch_id':branch_id
					},
				handleAs:"json",
				load: function(data) {
					//alert(data);
					old_car_student_name_store  = getDataStorefromJSON('id','name', data[1]);
					dijit.byId('student_name_old').set('store',old_car_student_name_store);   
					
					old_car_student_id_store  = getDataStorefromJSON('id','name', data[0]);
					dijit.byId('old_car_id').set('store',old_car_student_id_store);  
				},
				error: function(err) {
					alert(err);
				}
			});
		}
	}


	var drop_student_id_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var drop_student_name_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	
	var url_drop_student = '<?php echo $this->url(array('module'=>'accounting','controller'=>'studentservicepayment','action'=>'get-drop-student-by-branch')); ?>';
	
	function getAllDropStudentByBranch(){
		
		branch_id = dijit.byId('branch').get('value');
		if(branch_id>0){
			dojo.xhrPost({
				url:url_drop_student,
				content:{
					'branch_id':branch_id
					},
				handleAs:"json",
				load: function(data) {
					//alert(data);
					drop_student_name_store  = getDataStorefromJSON('id','name', data[1]);
					dijit.byId('stu_drop_name').set('store',drop_student_name_store);   
					
					drop_student_id_store  = getDataStorefromJSON('id','name', data[0]);
					dijit.byId('stu_drop_id').set('store',drop_student_id_store);  
				},
				error: function(err) {
					alert(err);
				}
			});
		}
	}
	
	
	
</script>
<style>
select{ width:100%;}
fieldset{  background:none;}
.red{ color: red; padding-left:5px;}
.head-td{font-size: 12px;}
</style>
<?php $register = $this->frm_register;
//print_r($register);
?>
<form id='office_receipt' action="<?php echo $this->url(array('module'=>'accounting','controller'=>'studentservicepayment','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">   

	stu_type = dijit.byId('student_type').get('value');
	if(stu_type==1){
		stu_id = dijit.byId('student_name_new').get('value');
		if(stu_id==-1){
			dijit.byId('student_name_new').focus();
			return false;
		}
	}else{
		stu_id = dijit.byId('student_name_old').get('value');
		if(stu_id==-1){
			dijit.byId('student_name_old').focus();
			return false;
		}
	}

	total_payment = dijit.byId('total_payment').get('value');
	paid_amount = dijit.byId('paid_amount').get('value');
	if(paid_amount>total_payment){
		alert('You can not pay more than total payment')
		dijit.byId('paid_amount').focus();
		return false;
	}
    else if(this.validate()) {
    	return true;
    }else {
    	return false;
    }
</script>
	<table id="head_tbl"  cellspacing="10" style="margin: 0 auto; width: 100%;white-space:nowrap;">
		<tr>
			<td width="33%" valign="top">
				<fieldset>
					<legend align="center"><strong​ style="font-size: 18px;"><?php echo $tr->translate("STUDENT_INFO");?></strong></legend>
					<table style="margin: 0 auto; width: 100%;padding:10px;" cellspacing="7" cellpadding="10px" >
						<tr>
							<td><?php echo $tr->translate("BRANCH");?></td>
							<td>
								<select name="branch" id="branch" class="fullside" autoComplete="false" queryExpr="*${0}*" onchange="getAllNewStudentByBranch();getAllOldStudentByBranch();getAllDropStudentByBranch();getNewReceiptNo('','');" dojoType="dijit.form.FilteringSelect" type="text" >
									<option value="-1">----- select branch -----</option>
									<?php if(!empty($this->branch_id)){foreach ($this->branch_id as $branch){?>
									<option value="<?php echo $branch['id'];?>"><?php echo $branch['name'];?></option>
									<?php }}?>
								</select>
							</td>
						</tr>
						
						<tr>
							<td width="20%"><?php echo $tr->translate("STUDENT_TYPE");?></td>
							<td width="80%">
								<select name="student_type" id="student_type" onchange="changeControl();getStudentInfo();" autoComplete="false" queryExpr="*${0}*" class="fullside" dojoType="dijit.form.FilteringSelect" >
									<option value="3">Old Student</option>
									<option value="1">New Student</option>
									<option value="4">Drop Student</option>
								</select>
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("STUDENT_NAME");?></td>
							<td>
								<div id="new_name">
									<input id="student_name_new" />
								</div>	
								<div id="old_name">
									<input id="student_name_old" />
								</div>	
								<div id="drop_name">
									<input id="stu_drop_name" />
								</div>
							</td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("STUDENT_ID");?></td>
							<td>
								<div id="new_id">
									<input type="text" name="new_car_id" style="color:red;" id="new_car_id" class="fullside" dojoType="dijit.form.TextBox" >     
								</div>
								<div id="old_id">
									<input id="old_car_id" />
								</div>
								<div id="drop_id">
									<input id="stu_drop_id" />
								</div>
							</td>
						</tr>
						
						<tr>
							<td><?php echo $tr->translate("NAME_EN");?></td>
							<td><?php echo $register->getElement('en_name');?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("NAME_KH");?></td>
							<td><?php echo $register->getElement('kh_name');?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("SEX");?></td>
							<td ><?php echo $register->getElement('sex');?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("PHONE");?></td>
							<td><input type="text" readOnly="readOnly"  class="fullside" name="phone" id="phone" dojoType="dijit.form.TextBox" /></td>
						</tr>
					</table>	
				</fieldset>		
			</td>
			
			<td width="33%" valign="top">
				<fieldset>
					<legend align="center"><strong​ style="font-size: 18px;"><?php echo $tr->translate("SERVICE_INFO");?></strong></legend>
					<table style="margin: 0 auto; width: 100%;padding:10px;" cellspacing="7" cellpadding="10px" >
						<tr>
							<td><?php echo $tr->translate('SERVICE');?></td>
							<td> 
								<input id="service" />
							</td>
							<input type="hidden" name="car_id" id="car_id" dojoType="dijit.form.TextBox" />
							<input type="hidden" name="service_cate" id="service_cate" dojoType="dijit.form.TextBox" />
							<input type="hidden" name="balance_id" id="balance_id" dojoType="dijit.form.TextBox" />
						</tr>
						<tr>		
							<td><?php echo $tr->translate('PAYMENT_TERM');?></td>
							<td>
								<select class="fullside" class="fullside" name="term" id="term" onchange="getservicefee();getValidate(1);" autoComplete="false" queryExpr="*${0}*" dojoType="dijit.form.FilteringSelect" type="text"   >
									<?php if(!empty($this->payment_term)){foreach ($this->payment_term as $key => $term){?>
										<option value="<?php echo $key?>"><?php echo $term;?></option>
									<?php  }}?>
									<option value="5"><?php echo $tr->translate('DAY');?></option>
								</select>
							</td>
						</tr>
						<tr>	
							<td ><?php echo $tr->translate('QTY');?></td>
							<td> 
								<input class="fullside" name="qty" id="qty" onkeyup="calculateTotalPayment();getValidate(1);netTotal();" dojoType="dijit.form.TextBox" value="1" type="text"   >
							</td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate('START_DATE');?></td>
							<td> 
								<input class="fullside" name="start_date" id="start_date" constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" onchange="getValidate(1);" value="now" type="text" >
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate('END_DATE');?></td>
							<td> 
								<input class="fullside" name="end_date" id="end_date" onchange="getValidate(2);" constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" type="text"   >
							</td>
						</tr>
						<tr>
							<td ><?php echo $tr->translate('NOTE');?></td>
							<td> 
								<input class="fullside" name="other" id="other" dojoType="dijit.form.TextBox" type="text" >
							</td>
						</tr>
						<tr>
							<td colspan="2" align="left">
								<table>
									<tr>
										<td><input type="checkBox" dojoType="dijit.form.CheckBox" value="07:30 am" id="time1" name="time1" onclick="getValue();" />07:30 am</td>
										<td><input type="checkBox" dojoType="dijit.form.CheckBox" value="10:30 am" id="time2" name="time2" onclick="getValue();" />10:30 am</td>
									</tr>
								</table>
							</td>
						</tr>
						<tr>
							<td colspan="2" align="left">
								<table>
									<tr>
										<td><input type="checkBox" dojoType="dijit.form.CheckBox" value="01:30 pm" id="time3" name="time3" onclick="getValue();" />01:30 pm</td>
										<td><input type="checkBox" dojoType="dijit.form.CheckBox" value="04:30 pm" id="time4" name="time4" onclick="getValue();" />04:30 pm</td>
										<input type="hidden" id="time_identity" name="time_identity" />
									</tr>
								</table>
							</td>
						</tr>
					</table>	
				</fieldset>		
			</td>
			
			<td width="33%" valign="top">
				<fieldset>
					<legend align="center"><strong​ style="font-size: 18px;"><?php echo $tr->translate("PAYMENT_INFO");?></strong></legend>
					<table style="margin: 0 auto; width: 100%;padding:10px;" cellspacing="7" cellpadding="10px" >
						
						<tr>
							<td width="20%"><?php echo $tr->translate("RECEIPT_NO");?></td>
							<td width="80%"><?php echo $register->getElement('reciept_no');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate('SERVICE_FEE');?></td>
							<td> 
								<input class="fullside" value="0" name="service_fee" id="service_fee" onkeyup="calculateTotalPayment();netTotal();" dojoType="dijit.form.TextBox" type="text" >
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate('MATERIAL_FEE');?></td>
							<td> 
								<input class="fullside" value="0" name="material_fee" id="material_fee" onkeyup="calculateTotalPayment();netTotal();" dojoType="dijit.form.NumberTextBox" type="text" >
							</td>
						</tr>
						<tr>
							<td ><?php echo $tr->translate('DISCOUNT');?></td>
							<td> 
								<table width="100%">
									<tr>
										<td width="10%">(%)&nbsp;</td>
										<td width="40%">
											<input class="fullside" name="discount" id="discount" onkeyup="calculateTotalPayment();netTotal();" dojoType="dijit.form.NumberTextBox" value="0" type="text"   >
										</td>
										<td width="10%">&nbsp;($)&nbsp;</td>
										<td width="40%">
											<input class="fullside" name="discount_fix" id="discount_fix" onkeyup="calculateTotalPayment();netTotal();" dojoType="dijit.form.NumberTextBox" value="0" type="text"   >
										</td>
									</tr>
								</table>
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate('TOTAL_PAYMENT');?></td>
							<td> 
								<input class="fullside" name="total_payment" id="total_payment" readOnly="readOnly" dojoType="dijit.form.TextBox" type="text" >
							</td>
						</tr>
						<tr>
							<td ><?php echo $tr->translate('PAID_AMOUNT');?></td>
							<td> 
								<input class="fullside" name="paid_amount" id="paid_amount" onkeyup="calculatBalanceAndReturn();netTotal();" dojoType="dijit.form.TextBox" type="text"   >
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate('BALANCE');?></td>
							<td> 
								<input class="fullside" name="balance" id="balance"  readOnly="readOnly" dojoType="dijit.form.TextBox" type="text" >
							</td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("CREATE_DATE");?></td>
							<td>
								<input type="text" name="create_date" id="create_date" dojoType="dijit.form.DateTextBox" class="fullside" value="now" constraints="{datePattern:'dd/MM/yyyy'}" />
							</td>
						</tr>
						
						
					</table>	
				</fieldset>		
			</td>
		</tr>
		
		<input type="hidden" id="identity" name="identity" />
		
		<tr>
			<td colspan="3" align="left">
				<div id="hideAddRow">
					<input type="checkbox" value="1" onchange="displayNoneAddRow();netTotal();" name="buy_product" id="buy_product" dojoType="dijit.form.CheckBox"  /> Buy Product
				</div>	
			</td>
		
		</tr>
		
		<tr>
			<div id="addrow" >
				<td colspan="3">
					<table width="100%" border="1" id="table_row" style="border-collapse: collapse; border:1px solid #ccc;white-space: nowrap;">
							<tr id="head-title" class="head-td" align="right"></tr>
					</table>
				</td>
			</div>
		</tr>
		<tr>
			<td colspan="3" align="right">
				<table style="width:400px;border-collapse: collapse;white-space:nowrap;" cellpadding="10" cellspacing="10" >
					<tr>
						<td ><?php echo $tr->translate("EXCHANGE_RATE")." (៛)";?></td>
						<td align="right">
							<input type="text" name="ex_rate" id="ex_rate" readonly value="<?php echo $this->exchange_rate ;?>" dojoType="dijit.form.NumberTextBox" />
						</td>
					</tr>
					<tr>
						<td ><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
						<td align="right"><input type="text" readonly="readonly" onkeyup="calculatBalanceAndReturn();"  name="grand_total" id="grand_total" dojoType="dijit.form.NumberTextBox" /></td>
					</tr>
					<tr>	
						<td><?php echo $tr->translate("CONVERT_TO_RIELS");?> (៛)</td>
						<td align="right"><input  type="text" readonly="readonly"  name="convert_to_riels" id="convert_to_riels" dojoType="dijit.form.NumberTextBox" /></td>
					</tr>
					<tr>	
						<td><?php echo $tr->translate("RECEIVED_AMOUNT");?></td>
						<td align="right"><input  type="text" readonly="readonly" onkeyup="calculatBalanceAndReturn();" required="true"  name="total_received" id="total_received" dojoType="dijit.form.NumberTextBox" /></td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("BALANCE");?></td>
						<td align="right"><input type="text"  readonly="readonly" name="total_balance" value="<?php echo 0?>" id="total_balance" dojoType="dijit.form.NumberTextBox" /></td>
					</tr>
				</table>
			</td>
		</tr>
		
		<tr>
			<td colspan="3" align="center">
				<input type="button" name="save_close" id="save_close" onclick="submitDataClose();" value="រក្សាទុក" label="<?php echo $tr->translate('SAVE_CLOSE');?>"  dojoType="dijit.form.Button" 
					iconClass="dijitEditorIcon dijitEditorIconSave" />
				<input type="button" name="save_new" id="save_new" onclick="submitDataAddNew();" value="រក្សាទុក" label="<?php echo $tr->translate('SAVE_NEW');?>"  dojoType="dijit.form.Button" 
					iconClass="dijitEditorIcon dijitEditorIconSave" />
			</td>
		</tr>
	</table>	
</form>



<script type="text/javascript">

function submitDataClose(){
	
	stu_type = dijit.byId('student_type').get('value');
	if(stu_type==1){
		stu_id = dijit.byId('student_name_new').get('value');
		if(stu_id<1){
			dijit.byId('student_name_new').focus();
			return false;
		}
	}else if(stu_type==3){
		stu_id = dijit.byId('student_name_old').get('value');
		if(stu_id<1){
			dijit.byId('student_name_old').focus();
			return false;
		}
	}else if(stu_type==4){
		stu_id = dijit.byId('drop_name').get('value');
		if(stu_id<1){
			dijit.byId('drop_name').focus();
			return false;
		}
	}

	total_payment = dijit.byId('total_payment').get('value');
	paid_amount = dijit.byId('paid_amount').get('value');
	if(paid_amount>total_payment){
		alert('You can not pay more than total payment')
		dijit.byId('paid_amount').focus();
		return false;
	}
	
	if(document.getElementById('buy_product').checked){
		condition = checkValidateAddRow();
		if(condition==false){
			alert("Please select service or product !!! ");
			return false;
		}
	}
		
	if(dijit.byId('office_receipt').validate()) {
		
		dijit.byId('save_new').set('disabled',true);
		dijit.byId('save_close').set('disabled',true);
	
		var url_submit = '<?php echo $this->url(array('module'=>'accounting','controller'=>'studentservicepayment','action'=>'add')); ?>';
		loading();
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("office_receipt"),		    
			load: function(data) {
				document.getElementsByClassName("overlay")[0].style.display="none";	
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/accounting/studentservicepayment";
			},
			error: function(e) {
			}
		});
	}
}

function submitDataAddNew(){
	
	stu_type = dijit.byId('student_type').get('value');
	if(stu_type==1){
		stu_id = dijit.byId('student_name_new').get('value');
		if(stu_id<1){
			dijit.byId('student_name_new').focus();
			return false;
		}
	}else if(stu_type==3){
		stu_id = dijit.byId('student_name_old').get('value');
		if(stu_id<1){
			dijit.byId('student_name_old').focus();
			return false;
		}
	}else if(stu_type==4){
		stu_id = dijit.byId('drop_name').get('value');
		if(stu_id<1){
			dijit.byId('drop_name').focus();
			return false;
		}
	}

	total_payment = dijit.byId('total_payment').get('value');
	paid_amount = dijit.byId('paid_amount').get('value');
	if(paid_amount>total_payment){
		alert('You can not pay more than total payment')
		dijit.byId('paid_amount').focus();
		return false;
	}
	
	if(document.getElementById('buy_product').checked){
		condition = checkValidateAddRow();
		if(condition==false){
			alert("Please select service or product !!! ");
			return false;
		}
	}
	
	if(dijit.byId('office_receipt').validate()) {
	
		dijit.byId('save_new').set('disabled',true);
		dijit.byId('save_close').set('disabled',true);
		
		var url_submit = '<?php echo $this->url(array('module'=>'accounting','controller'=>'studentservicepayment','action'=>'add')); ?>';
		loading();
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("office_receipt"),		    
			load: function(data) {
				document.getElementsByClassName("overlay")[0].style.display="none";		
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/accounting/studentservicepayment/add";
			},
			error: function(e) {
			}
		});
	}
}

function checkValidateAddRow(){
	var rowId = $('#identity').val();
	//alert(rowId);
	if(rowId!=''){
		var rowIDArray = rowId.split(',');
		for(var n = 0; n < rowIDArray.length; n++) {
			product_id = dijit.byId('product_'+rowIDArray[n]).get('value');
			if(product_id==''){
				return false;
			}
		}
	}
	return true;
}


function loading(){
    document.getElementsByClassName("overlay")[0].style.display="block";
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

function setID(type){

	if(type==1){
		stu_id = dijit.byId('student_name_old').get('value');
		dijit.byId('old_car_id').attr('value',stu_id);
	}else{
		stu_id = dijit.byId('stu_drop_name').get('value');
		dijit.byId('stu_drop_id').attr('value',stu_id);
	}
}


function changeControl(){
	stu_type = dijit.byId('student_type').get('value');
	if(stu_type==1){
		document.getElementById('new_id').style.display="block";
		document.getElementById('new_name').style.display="block";
		document.getElementById('old_id').style.display="none";
		document.getElementById('old_name').style.display="none";
		document.getElementById('drop_name').style.display="none";
		document.getElementById('drop_id').style.display="none";
		
	}else if(stu_type==3){
		document.getElementById('new_id').style.display="none";
		document.getElementById('new_name').style.display="none";
		document.getElementById('old_id').style.display="block";
		document.getElementById('old_name').style.display="block";
		document.getElementById('drop_name').style.display="none";
		document.getElementById('drop_id').style.display="none";
	}else if(stu_type==4){
		document.getElementById('new_id').style.display="none";
		document.getElementById('new_name').style.display="none";
		document.getElementById('old_id').style.display="none";
		document.getElementById('old_name').style.display="none";
		document.getElementById('drop_name').style.display="block";
		document.getElementById('drop_id').style.display="block";
	}
}
	
var url_get_new_car_id = '<?php echo $this->url(array('module'=>'accounting','controller'=>'studentservicepayment','action'=>'get-new-car-id')); ?>';
function getNewCarId(condition){
	dojo.xhrPost({
		url:url_get_new_car_id,
		content:{
			
			},
		handleAs:"json",
		load: function(data) {
			// alert(data);
			if(data){
				dijit.byId('new_car_id').attr('value',data);
			}	
			
			if(condition==1){
				getNewReceiptNo(data,1);
			}
			
		},
		error: function(err) {
			alert(err);
		}
	});
	
}





</script>



<script>


//save daata when sub button print 
function printSubmit(){
	//$('#office_receipt').submit();
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
}

function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    dijit.byId("terms").hide();	//hideDialog();
}


</script>
<script type="text/javascript">

var url_get_start_date = '<?php echo $this->url(array('module'=>'accounting','controller'=>'studentservicepayment','action'=>'get-start-date-service')); ?>';
function getStartDateService(){
	stu_type = dijit.byId('student_type').get('value');
	if(stu_type!=1){
		service_id = dijit.byId('service').get('value');
		if(stu_type==3){
			stu_id = dijit.byId('student_name_old').get('value');
		}else{
			stu_id = dijit.byId('stu_drop_name').get('value');
		}
		if(service_id>0 && stu_id>0){
			dojo.xhrPost({
				url:url_get_start_date,
				content:{
					'service_id':service_id,
					'stu_id':stu_id
					},
				handleAs:"json",
				load: function(data) {
					//alert(data);
					if(data){
						dijit.byId('start_date').attr('value',data);
						getValidate(1);
					}else{
						//getCurrentDate();
					}	
					
				},
				error: function(err) {
					alert(err);
				}
			});
		}
	}
}

var url_get_service_cate = '<?php echo $this->url(array('module'=>'accounting','controller'=>'studentservicepayment','action'=>'get-service-cate')); ?>';
function getServiceCate(service_id){
		//alert(service_id);
	if(service_id>0){
		dojo.xhrPost({
				url:url_get_service_cate,
				content:{
					'service_id':service_id
					},
				handleAs:"json",
				load: function(data) {
					dijit.byId('service_cate').attr('value',data)					 
				},
				error: function(err) {
					alert(err);
				}
		});
	}
}



var url_getreceiptno = '<?php echo $this->url(array('module'=>'registrar','controller'=>'coursestudy','action'=>'get-receipt-no')); ?>';
	function getNewReceiptNo(new_stu_id,condition){
		type = 3 ;// transport payment 
		branch_id = dijit.byId('branch').get('value');
		dojo.xhrPost({
				url:url_getreceiptno,
				content:{
					'type':type,
					'branch_id':branch_id,
					},
				handleAs:"json",
				load: function(data) {
					//alert(data);
					//url_getstuno  = getDataStorefromJSON('id','name', data);
					 dijit.byId('reciept_no').attr('value',data);   
					 if(condition==1){
						printSave(new_stu_id,data);
					 }
				},
				error: function(err) {
					alert(err);
				}
			});
			
	}

function showPopupDept() {
	if(dijit.byId('faculty').value==-1){
		dijit.byId("popup_dept").show();
	}
}
function hideDialog() {		
	dijit.byId("terms").hide();
}

function calculateTotalPayment(){
	service_fee = dijit.byId('service_fee').get('value');
	qty = dijit.byId('qty').get('value');
	qty = isNaN(qty)?1:qty;
	
	material_fee = dijit.byId('material_fee').get('value');
	material_fee = isNaN(material_fee)?0:material_fee;
	
	service_fee = service_fee * qty;
	
	discount = dijit.byId('discount').get('value');
	discount = isNaN(discount)?0:discount;
	
	discount_fix = dijit.byId('discount_fix').get('value');
	discount_fix = isNaN(discount_fix)?0:discount_fix;
	
	total_payment = ((service_fee-discount_fix)-((service_fee-discount_fix)*discount/100)) + parseFloat(material_fee);
	
	dijit.byId('total_payment').attr('value',total_payment.toFixed(2));
	dijit.byId('paid_amount').attr('value',total_payment.toFixed(2));
	
	calculatBalanceAndReturn();
	
	netTotal();
}

function calculatBalanceAndReturn(){
	total_payment = dijit.byId('total_payment').get('value');
	paid_amount = dijit.byId('paid_amount').get('value');

	if(paid_amount>total_payment){
		//dijit.byId('return').attr('value',paid_amount-total_payment);
		
		dijit.byId('balance').attr('value',0);
	}
	else{
		dijit.byId('balance').attr('value',total_payment-paid_amount);
		//dijit.byId('return').attr('value',0);
	}
}

var url_student_info = "<?php echo $this->url(array('module'=>'accounting','controller'=>'studentservicepayment','action'=>'get-student')); ?>";
function getStudentInfo(){
	stu_type = dijit.byId('student_type').get('value');

	if(stu_type==1){
		studentid = dijit.byId('student_name_new').get('value');
	}else if(stu_type==3){
		studentid = dijit.byId('old_car_id').get('value');
		dijit.byId('student_name_old').attr('value',studentid);
	}else{
		studentid = dijit.byId('stu_drop_id').get('value');
		dijit.byId('stu_drop_name').attr('value',studentid);
	}
	
	if(studentid!=''){
		dojo.xhrPost({
			url:url_student_info,
			content:{
				'studentid':studentid
				},
			handleAs:"json",
			load: function(data) {
				//alert(data.tel);
				dijit.byId("kh_name").attr("value",data.stu_khname);
				dijit.byId("en_name").attr("value",data.stu_enname);
				dijit.byId("sex").attr("value",data.sex);
				dijit.byId("phone").attr("value",data.tel);
				if(stu_type!=1){
					dijit.byId("service").attr("value",data.service_id);
					getStartDateService();
				}
			},
			error: function(err) {
				//alert(err);
			}
		});
	}
}
var url_service_fee = "<?php echo $this->url(array('module'=>'accounting','controller'=>'studentservicepayment','action'=>'get-price')); ?>";
function getservicefee(){
	
	student_type = dijit.byId('student_type').get('value');
	if(student_type==1){
		studentid = dijit.byId('student_name_new').get('value');
	}else if(student_type==3){
		studentid = dijit.byId('student_name_old').get('value');
	}else if(student_type==4){
		studentid = dijit.byId('stu_drop_name').get('value');
	}
	
	service = dijit.byId('service').get('value');
	term = dijit.byId('term').get('value');
	//year = dijit.byId('study_year').get('value');
	if(studentid>0 && service>0 && term>0){
		dojo.xhrPost({
			url:url_service_fee,
			content:{
				'term':term,
				'service':service,
				'studentid':studentid,
			//	'year':year,
				},
			handleAs:"json",
			load: function(data) {
				if(data.balance>0){
					clear();
					dijit.byId("service_fee").attr("value",data.balance);
					dijit.byId("other").attr("value",'លុយជំពាក់ពីមុន');
					dijit.byId("start_date").attr("value",data.start_date);
					dijit.byId("end_date").attr("value",data.validate);
					dijit.byId("balance_id").attr("value",data.id);
					calculateTotalPayment();
					setDateReadOnly();
					//alert(1);
				}else{
					clear();
					dijit.byId("service_fee").attr("value",data.price_fee);
					calculateTotalPayment();
					//getCurrentDate();
					removeDateReadOnly();
				}
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}
function clear(){
	dijit.byId("balance_id").attr("value",'');
	dijit.byId("service_fee").attr("value",0);
	//dijit.byId("discount").attr("value",0);
	dijit.byId("total_payment").attr("value",0);
	dijit.byId("paid_amount").attr("value",0);
	dijit.byId("balance").attr("value",0);
	//dijit.byId("return").attr("value",0);
	//dijit.byId("other").attr("value",'');
}
function setDateReadOnly(){
	//document.getElementById('start_date').readOnly = true;
	//document.getElementById("start_date").setAttribute("readonly", true);
	dijit.byId("start_date").set('readOnly',true);
	dijit.byId("end_date").set('readOnly',true);
}
function removeDateReadOnly(){
	dijit.byId("start_date").set('readOnly',false);
	dijit.byId("end_date").set('readOnly',false);
}
function getCurrentDate(){
	var currentDate = new Date();
    var day = currentDate.getDate();
	if(day<10){
		day='0'+day;
	}
    var month = currentDate.getMonth() + 1;
	if(month<10){
		month='0'+month;
	}
    var year = currentDate.getFullYear();
    var my_date = day+"/"+month+"/"+year;
    document.getElementById("start_date").value = my_date;
    getValidate();
}

function getValidate(type){
	 
	 if(type==1){
		 term = dijit.byId('term').get('value');
		 qty = dijit.byId('qty').get('value');
		 qty = isNaN(qty)?1:qty;
		 start_date = dijit.byId('start_date').get('value');
		 
		 var a = new Date(start_date);
		 
		 if(term==1){
			 mm = a.getMonth()+(1*qty)+1;
			 var dd = a.getDate();
			 if(dd<10){
			   dd = "0"+dd;
			 }
			 if(mm<10){
			   mm = "0"+mm;
			 }
			 var y = a.getFullYear(); 
			 var epx_date = y + '-' + mm + '-' + dd ;
			 dijit.byId('end_date').attr('value',epx_date);
		 }
		 else if(term==2){
			 mm = a.getMonth()+(3*qty)+1;
			 var dd = a.getDate();
			 if(dd<10){
			   dd = "0"+dd;
			 }
			 if(mm<10){
			   mm = "0"+mm;
			 }
			 var y = a.getFullYear(); 
			 var epx_date = y + '-' + mm + '-' + dd ;
			 dijit.byId('end_date').attr('value',epx_date);
		 }
		 else if(term==3){
			 mm = a.getMonth()+(6*qty)+1;
			 var dd = a.getDate();
			 if(dd<10){
			   dd = "0"+dd;
			 }
			 if(mm<10){
			   mm = "0"+mm;
			 }
			 var y = a.getFullYear(); 
			 var epx_date = y + '-' + mm + '-' + dd ;
			 dijit.byId('end_date').attr('value',epx_date);
		 }
		 else if(term==4){
			 mm = a.getMonth()+(12*qty)+1;
			 var dd = a.getDate();
			 if(dd<10){
			   dd = "0"+dd;
			 }
			 if(mm<10){
			   mm = "0"+mm;
			 }
			 var y = a.getFullYear(); 
			 var epx_date = y + '-' + mm + '-' + dd ;
			 dijit.byId('end_date').attr('value',epx_date);
		 }else if(term==5){
			var amount_day = dijit.byId('qty').get('value');;
			var start_date = dijit.byId('start_date').get('value');
			var year = start_date.getFullYear();
			var month = start_date.getMonth();
			var date = start_date.getDate();
			for(var i=0; i<amount_day; i++){
				  var epx_date = new Date(year, month, date + i);
			}
			dijit.byId('end_date').attr('value',epx_date); 
		 }
	 }else{
		 term = dijit.byId('term').get('value');
		 if(term == 5){
			start_date = dijit.byId('start_date').get('value');
			end_date = dijit.byId('end_date').get('value');
			var timeDiff = (end_date.getTime() - start_date.getTime());
			if(timeDiff>=0){
				var diffDays = Math.ceil(timeDiff / (1000 * 3600 * 24)) + 1 ; // +1 because they also count the first day that register
				dijit.byId('qty').attr('value',diffDays);
			}else{
				dijit.byId('qty').attr('value',0);
			}
			calculateTotalPayment();netTotal();
		}
	 }
}
function getValue(){
	seperater='';
	i=0;
	$("#time_identity").val('');
	for(i=1;i<=4;i++){
		if(dijit.byId('time'+i).checked){
			//alert(dijit.byId('time'+i).get('value'));
			if($("#time_identity").val()!="") {
				var time_identity = $("#time_identity").val();
				$("#time_identity").val(time_identity+','+i);
			} else {$("#time_identity").val(i);}
		}
	}
}

var url_add_service = '<?php echo $this->url(array("module"=>"accounting","controller"=>"studentservicepayment","action"=>"add-popup-service")); ?>';
function addService(){
	dojo.xhrPost({
			url:url_add_service,
			form: dojo.byId("frm_add_service"),
			handleAs:"json",
			load: function(data) {
				//alert(data); 
				var Itemmake = { 
				     id: data,
					         name: dijit.byId('service_name').get('value')
					   };
		 	addDataToSelectbox(dijit.byId('service'), service_store, Itemmake, data);
		    dijit.byId('frm_add_service').reset();
		    dijit.byId("popup_add_service").hide();
				
			},
			error: function(err) {
				alert(err);
			}
	});
}

function hidePopup() {		
	dijit.byId("popup_add_service").hide();
}


///////////////////////////////////////////////////////////// Add Row /////////////////////////////////////////////////////////

var template = '';
var service = '';
var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
date_format = '"dd/MM/yyyy"';
function addRow() {
		col++;no++;
		template='';
		if(title!=1){
			temp+='<th ><?php echo $tr->translate("DEL");?></th>';
			temp+='<th ><?php echo $tr->translate("N_O");?></th>';
			temp+='<th ><?php echo $tr->translate("PRODUCT");?></th>';
			temp+='<th  ><?php echo $tr->translate("PRICE");?></th>';
			temp+='<th  ><?php echo $tr->translate("AMOUNT");?></th>';
			temp+='<th  ><?php echo $tr->translate("DISCOUNT");?> %</th>';
			temp+='<th  ><?php echo $tr->translate("SUBTOTAL");?></th>';
			temp+='<th><?php echo $tr->translate("REMARK");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
			template+='<td align="center"  style="width:3%"><img onclick="deleteRecord('+col+');calculateTotal('+col+');" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td align="center" style="width:3%;">'+no+'</td>';
			
			template+='<td style="width:30%"><input type="hidden" dojoType="dijit.form.TextBox" name="id_balance_record_'+col+'" id="id_balance_record_'+col+'"/>';
			template+='<select style="width:100%"  onchange="getProductPrice('+col+');" dojoType="dijit.form.FilteringSelect" id="product_'+col+'" name="product_'+col+'">';
				template+='<option value="">Select </option>';
				<?php if(!empty($this->all_product)){foreach($this->all_product as $product){?>
					template+='<option value="'+<?php echo $product['id']?>+'"><?php echo $product['name'];?></option>';
				<?php }}?>
			template+='</select></td>';	

			
			column = 0;
			template+='<td style="width:10%"> <input class="fullside"  type="text"  onkeyup="calculateTotal('+col+');" name="price_'+col+'" id="price_'+col+'" dojoType="dijit.form.NumberTextBox" " /><label id="subsub"></label></td>';	
			template+='<td style="width:10%"> <input class="fullside" type="text"  onkeyup="calculateTotal('+col+');" name="qty_'+col+'" id="qty_'+col+'" value="1" dojoType="dijit.form.NumberTextBox" /><label id="qty"></label></td>';			
					
			template+='<td style="width:10%"> <input class="fullside"  type="text" onkeyup="calculateTotal('+col+');" name="discount_'+col+'" value="<?php echo 0;?>" id="discount_'+col+'" dojoType="dijit.form.NumberTextBox" /><label id="subsub"></label></td>';
			template+='<td style="width:10%"> <input class="fullside"  type="text"  readonly="readonly" name="subtotal_'+col+'" id="subtotal_'+col+'" dojoType="dijit.form.NumberTextBox"/><label id="qty"></label></td>';
			template+='<td style="width:24%"> <input class="fullside"  type="text" name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ" /><label id="subsub"></label></td>';

								//constraints="{datePattern:'dd/MM/yyyy'}"
			
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);

		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
		//getValidate(col);
 }
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
	if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
}



///////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////



/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

var url_getproductprice = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-product-price')); ?>';
function getProductPrice(index){
	
	product = dijit.byId('product_'+index).get('value');
	qty = dijit.byId('qty_'+index).get('value');
	discount = dijit.byId('discount_'+index).get('value');
	
	dojo.xhrPost({
		url:url_getproductprice,
		content:{
			'product':product,
			},
		handleAs:"json",
		load: function(data) {
			if(data){
				//alert(data);
				
				fee_discount = data * qty * (discount/100);
				//alert(fee_discount);
				
				dijit.byId('price_'+index).attr('value',data);
				dijit.byId('subtotal_'+index).attr('value',(data * qty) - fee_discount);
				
				netTotal();
			}
		},
		error: function(err) {
			//alert(err);
		}
	});
}

function calculateTotal(index){
	price = dijit.byId('price_'+index).get('value');
	qty = dijit.byId('qty_'+index).get('value');
	qty=isNaN(qty)?1:qty;
	//if(qty==1){dijit.byId('qty_'+index).attr('value',qty);}
	total = price*qty;
	discount = dijit.byId('discount_'+index).get('value');
	discount = isNaN(discount)?0:discount;
	dijit.byId('subtotal_'+index).attr('value',total-(total*(discount/100)));
	netTotal();
}

function netTotal() {
	// alert(1);
		var netTotal=0;
		var netPaidAmount=0;
		var rowId = $('#identity').val();
		var rowIDArray = rowId.split(',');
		//alert(rowIDArray);
		
		//tuition_fee = dijit.byId('tuitionfee').get('value');
		paid_amount = dijit.byId('paid_amount').get('value');
		total_payment = dijit.byId('total_payment').get('value');
		
		if(document.getElementById('buy_product').checked){
			for(var n = 0; n < rowIDArray.length; n++) {
				//netTotal += Number($('#subtotal_'+rowIDArray[n]).val());
				netTotal += dijit.byId('subtotal_'+rowIDArray[n]).get('value');
				netPaidAmount += dijit.byId('subtotal_'+rowIDArray[n]).get('value');
			}
		}
		
		grand_total_payment = parseFloat(netTotal) + parseFloat(total_payment) ;
		grand_total_paid = parseFloat(netPaidAmount) + parseFloat(paid_amount) ;
				
		ex_rate = dijit.byId('ex_rate').get('value');
		
		dijit.byId('grand_total').attr('value',grand_total_payment);
		dijit.byId('convert_to_riels').attr('value',grand_total_payment * ex_rate);
		dijit.byId('total_received').attr('value',grand_total_paid);
		
		dijit.byId('total_balance').attr('value',grand_total_payment - grand_total_paid);
		
		//calculatBalanceAndReturn();
}

function displayNoneAddRow(){
	
	//document.getElementById('term').style.display="none";
	
	if(document.getElementById('buy_product').checked){
		document.getElementById('table_row').style.display="block";
	}else{
		document.getElementById('table_row').style.display="none";
	}
	
}

var url_getCarIdByService = '<?php echo $this->url(array('module'=>'accounting','controller'=>'studentservicepayment','action'=>'get-car-id-by-service')); ?>';
function getCarIdByService(){
	service_id = dijit.byId('service').get('value');
	if(service_id>0){
		dojo.xhrPost({
			url:url_getCarIdByService,
			content:{
				'service_id':service_id,
				},
			handleAs:"json",
			load: function(data) {
				//alert(data);
				if(data){
					dijit.byId('car_id').attr('value',data);
				}
			},
			error: function(err) {
				//alert(err);
			}
		});
	}
	
}


///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////




</script>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:40%;" id="popup_add_service" >
		<form style="background-color: buttonface; width:100%;" id='frm_add_service' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
			<tr>
				<td>
					<fieldset style="background-color: buttonface;">
					<legend align="center" ><?php echo $tr->translate('ADD_SERVICE');?></legend><br />
						<table style="margin: 0 auto; width: 100%;  padding:10px;" cellspacing="7" >
							<tr>
								<td style="width:100px"><?php echo $tr->translate("SERVICE_TYPE")?></td>
								<td>
									<select dojoType="dijit.form.FilteringSelect"   class="fullside" id="service_type" name="service_type" value="" type="text">
										<?php if(!empty($this->service_type)){ foreach ($this->service_type as $service_type){?>
											<option value="<?php echo $service_type['id']?>"><?php echo $service_type['name']?></option>
										<?php }}?>
									</select>
								</td>
							</tr>
							<tr>
								<td style="width:100px"><?php echo $tr->translate("PROGRAM_TITLE")?></td>
								<td>
									<input dojoType="dijit.form.TextBox"  class="fullside" id="service_name" name="service_name" value="" type="text">
								</td>
							</tr>
							<tr>
							<tr>
								<td style="width: 5px"><?php echo $tr->translate("DISCRIPTION")?></td>
								<td>
									<input dojoType="dijit.form.TextBox"  class="fullside" id="description" name="description" value="" type="text">
								</td>
							</tr>
							<tr>
								<td style="width: 5px"><?php echo $tr->translate("STATUS")?></td>
								<td>
									<select name="status_popup" id="status_popup" dojoType="dijit.form.FilteringSelect"   class="fullside">
	    								<option value="1" label="active">Active</option>
	    								<option value="0" label="deactive">Deactive</option>
									</select>
								</td>
							</tr>
							<tr>
								<td colspan="4" align="center">
									<input type="button" value="ចាកចេញ" label="Close" id="close" name="close" dojoType="dijit.form.Button" 
									​ ​​iconClass="dijitIconUndo" onclick="hidePopup();"/>
									<input type="button" value="save" label="SAVE" id="save" name="save" dojoType="dijit.form.Button" 
									 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addService();"/>
								</td>
							</tr>
							
						</table>
				</fieldset>
				</td>
			</tr>
		</table>

		</form>
	</div>
</div>


<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>	
<style>
.overlay {display: none;position: absolute;width: 100%;height: 150%;top: 0px;left: 0px;background: #FCFCFC;z-index: 1001;opacity: .5;}
.overlay-load {width: 350px;height: 100px;margin: auto;top: 0px;bottom: 0px;position: absolute;left: 0px;right: 0px;
           text-align: center;
           background: #fff url("<?php echo $this->baseUrl()?>/images/loading.gif") 50% 25%;
           background-repeat: no-repeat;          
}
.overlay-msg{margin-bottom: 10px;bottom: 0px;position: absolute;font-style: italic;color: rgb(19, 19, 19);} 
</style>
