<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("ADD_RENTAL_PAYMENT"));
	//print_r($this->reil);
?>	
<style>
 
</style>
<script type="text/javascript" src="js/dojo/dojo.js" djConfig="isDebug: true, parseOnLoad: true"></script>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>

	<script type="text/javascript">
		dojo.require("dojo.NodeList-manipulate");
		dojo.require("dojo.parser");
		dojo.require("dijit.form.Textarea");
		dojo.require("dijit.form.CheckBox");
		dojo.require("dojox.form.BusyButton");
		dojo.require("dojo.data.ItemFileWriteStore");
		
		dojo.ready(function(){	
			
			hidendOldCus();
			
			new dijit.form.FilteringSelect({
				autoComplete: false,
				queryExpr: "*${0}*",                        
				id: "old_cus",
				name: "old_cus",
				required: false,           
				class: 'fullside',  
				placeHolder:"----- select customer -----",          
				onChange: function() {  
					getOldCustomerInfo();
					setCusName();
				}
			}, "old_cus");
		
		});
		
		
		var customer_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
		var url_customer = '<?php echo $this->url(array('module'=>'accounting','controller'=>'customerpayment','action'=>'get-old-customer-by-branch')); ?>';
		function getOldCustomerByBranch(){
			branch_id = dijit.byId('branch').get('value');
			//alert(branch_id);
			if(branch_id>0){
				dojo.xhrPost({
					url:url_customer,
					content:{
						'branch_id':branch_id
						},
					handleAs:"json",
					load: function(data) {
						//alert(data);
						customer_store  = getDataStorefromJSON('id','name', data);
						dijit.byId('old_cus').set('store',customer_store);   
					},
					error: function(err) {
						alert(err);
					}
				});
			}
		}
		
		var url_customer_id = '<?php echo $this->url(array('module'=>'accounting','controller'=>'customerpayment','action'=>'get-customer-id-by-branch')); ?>';
		function getCustomerIDByBranch(){
			branch_id = dijit.byId('branch').get('value');
			new_cus = dijit.byId('is_new_cu').get('value');
			//alert(branch_id);
			if(branch_id>0 && new_cus==1){
				dojo.xhrPost({
					url:url_customer_id,
					content:{
						'branch_id':branch_id
						},
					handleAs:"json",
					load: function(data) {
						//alert(data);
						dijit.byId('cus_id').attr('value',data);   
					},
					error: function(err) {
						alert(err);
					}
				});
			}
		}
		
		var url_receipt = '<?php echo $this->url(array('module'=>'accounting','controller'=>'customerpayment','action'=>'get-receipt-by-branch')); ?>';
		function getReceiptByBranch(){
			branch_id = dijit.byId('branch').get('value');
			//alert(branch_id);
			if(branch_id>0){
				dojo.xhrPost({
					url:url_receipt,
					content:{
						'branch_id':branch_id
						},
					handleAs:"json",
					load: function(data) {
						//alert(data);
						dijit.byId('receipt_no').attr('value',data);   
					},
					error: function(err) {
						alert(err);
					}
				});
			}
		}
		
		
	</script>

<form  id='frm_book' action="" dojoType="dijit.form.Form" method="post"  enctype="multipart/form-data" >
		<script type="dojo/method" event="onSubmit" enctype="multipart/form-data">			
			if(this.validate()) {
			   dijit.byId('save_new').set('disabled',true);
			   dijit.byId('save_close').set('disabled',true);
			   return true;
			} else {
				return false;
			}
		</script>
		
	<table cellspacing="2" width="100%" style="margin: 0 auto; ">
		<tr>
			<td width="33%;" valign="top">
				<fieldset>
					<legend align="center" ><strong><?php echo $tr->translate("CUSTOMER_INFO")?></strong></legend>
					<table style="margin: 0 auto; width: 100%;text-align: right;" cellspacing="2"  >
							<tr>
								<td><?php echo $tr->translate("BRANCH");?></td>
								<td>
									<select dojoType='dijit.form.FilteringSelect' id="branch" name="branch" class="fullside" onChange="getOldCustomerByBranch();getCustomerIDByBranch();getReceiptByBranch();" ​​>
										<option value=""><?php echo $tr->translate("Select Branch");?></option>
										<?php if(!empty($this->branch)){foreach($this->branch as $branch){?>
											<option value="<?php echo $branch['id']?>"><?php echo $branch['name']?></option>
										<?php }}?>
									</select>
								</td>
							</tr>
							
							<tr>
								<td><?php echo $tr->translate("OLD_CUS");?></td>
								<td>
									<select dojoType='dijit.form.FilteringSelect' class="fullside" ​​name="is_new_cu" id="is_new_cu" onchange="hidendOldCus();getCustomerIDByBranch();">
										<option value="0"><?php echo $tr->translate("Old Customer");?></option>
										<option value="1"><?php echo $tr->translate("New Customer");?> </option>
									</select>
								</td>
							</tr>
							
							<tr>
								<td><?php echo $tr->translate("CUS_ID");?></td>
								<td><input type="text" name="cus_id" class="fullside" id="cus_id" style="color:red;" dojoType="dijit.form.ValidationTextBox" required="required" /> </td> 
							</tr>
							<tr>
								<td><?php echo $tr->translate("CUS_NAME");?></td>
								<td>
									<div id="cus_name_div">
										<input type="text" name="cus_name" class="fullside" id="cus_name" dojoType="dijit.form.ValidationTextBox" required="required"/> 
									</div>
									<!-- old Customer  -->
									<div id="old_cus_div">
										
										<input id="old_cus" />
										
									</div>
									<!-- /end old Customer  -->
								</td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("SEX");?></td>
								<td>
									<select dojoType='dijit.form.FilteringSelect' id="sex" name="sex"   class="fullside"  ​​  placeholder=" ">
										<option value="1"><?php echo $tr->translate("MALE");?></option>
										<option value="2"><?php echo $tr->translate("FEMALE");?> </option>
									</select>
								</td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("PHONE");?></td>
								<td><input type="text" name="phone" class="fullside" id="phone"   dojoType="dijit.form.TextBox" /> </td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("START_DATE");?></td>
								<td><input type="text" name="start_date" class="fullside" id="start_date"   dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now"/> </td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("END_DATE");?></td>
								<td><input type="text" name="end_date" class="fullside" id="end_date"   dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now"/> </td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("EMAIL");?></td>
								<td><input type="text" name="email" class="fullside" id="email"   dojoType="dijit.form.TextBox" /> </td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("ADDRESS");?></td>
								 <td><textarea class="fullside"  style=" height: 30px !important;" tabindex="20" dojoType=""  id="address" name="address"  ></textarea> </td>  
							</tr>
					</table>	
				</fieldset>	
			</td>
			<td width="33%;" valign="top">
				<fieldset>
					<legend align="center" ><strong><?php echo $tr->translate("WATER_INFO")?></strong></legend>
					<table style="margin: 0 auto; width: 100%;text-align: right;" cellspacing="2"  >
							<tr>
								<td><?php echo $tr->translate("OLd_CONGTOR");?></td>
								<td><input type="text" name="water_old_congtor" class="fullside" id="water_old_congtor"   dojoType="dijit.form.NumberTextBox" required="required" onkeyup="getQtyPariceWater();"/> </td> 
							</tr>
							<tr>
								<td><?php echo $tr->translate("NEW_CONGTOR");?></td>
								<td><input type="text" name="water_new_congtor" class="fullside" id="water_new_congtor"   dojoType="dijit.form.NumberTextBox" required="required" onChange="getQtyPariceWater();"/> </td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("QUANTITY");?>(M<sup>3</sup>)</td>
								<td><input type="text" name="water_qty" class="fullside" id="water_qty"   dojoType="dijit.form.NumberTextBox" readonly="true" /> </td> 
							</tr>
							<tr>
								<td><?php echo $tr->translate("COST");?>(៛)</td>
								<td><input type="text" name="water_cost" class="fullside" id="water_cost"   dojoType="dijit.form.NumberTextBox" onKeyup="getQtyPariceWater();"/> </td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("TOTAL");?>(៛)</td>
								<td><input type="text" name="water_total" class="fullside" id="water_total"   dojoType="dijit.form.NumberTextBox" readOnly="true" /> </td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("START_DATE");?></td>
								<td><input type="text" name="water_start_date" class="fullside" id="water_start_date"   dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now"/> </td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("END_DATE");?></td>
								<td><input type="text" name="water_end_date" class="fullside" id="water_end_date"   dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now"/> </td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("EXC_RATE");?>($)</td>
								<td><input type="text" name="water_exc_rate" class="fullside" id="water_exc_rate"   dojoType="dijit.form.NumberTextBox" onKeyup="getQtyPariceWater();" placeholder="" readOnly="true"/></td>
							</tr>
					</table>
						
				</fieldset>	
			</td>
			<td width="33%;" valign="top">
				<fieldset>
					<legend align="center" ><strong><?php echo $tr->translate("FIRE_INFO")?></strong></legend>
					<table style="margin: 0 auto; width: 100%;text-align: right;" cellspacing="2"  >
							<tr>
								<td><?php echo $tr->translate("OLd_CONGTOR");?></td>
								<td><input type="text" name="fire_old_congtor" class="fullside" id="fire_old_congtor"   dojoType="dijit.form.NumberTextBox" required="required" onKeyup="getQtyPariceFire();"/> </td> 
							</tr>
							<tr>
								<td><?php echo $tr->translate("NEW_CONGTOR");?></td>
								<td><input type="text" name="fire_new_congtor" class="fullside" id="fire_new_congtor"   dojoType="dijit.form.NumberTextBox" required="required" onChange="getQtyPariceFire();"/> </td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("QUANTITY");?>(M<sup>3</sup>)</td>
								<td><input type="text" name="fire_qty" class="fullside" id="fire_qty"   dojoType="dijit.form.NumberTextBox" readonly="true" /> </td> 
							</tr>
							<tr>
								<td><?php echo $tr->translate("COST");?>(៛)</td>
								<td><input type="text" name="fire_cost" class="fullside" id="fire_cost"   dojoType="dijit.form.NumberTextBox" onKeyup="getQtyPariceFire();"/> </td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("TOTAL");?>(៛)</td>
								<td><input type="text" name="fire_total" class="fullside" id="fire_total"   dojoType="dijit.form.NumberTextBox" readOnly="true"/> </td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("START_DATE");?></td>
								<td><input type="text" name="fire_start_date" class="fullside" id="fire_start_date"   dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now"/> </td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("END_DATE");?></td>
								<td><input type="text" name="fire_end_date" class="fullside" id="fire_end_date"   dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now"/> </td>
							</tr>
							<tr>
								 <td><?php echo $tr->translate("EXC_RATE");?>($) </td>
								 <td><input type="text" name="fire_exc_rate" class="fullside" id="fire_exc_rate"   dojoType="dijit.form.NumberTextBox" onKeyup="getQtyPariceWater();" readOnly="true"/>    </td>
							</tr>
					</table>	
				</fieldset>	
			</td>
		</tr>
		<tr>
			<td width="33%;" valign="top">
				<fieldset>
					<legend align="center" ><strong><?php echo $tr->translate("​ទូទាត់សេវាជួលតូប")?></strong></legend>
					<table style="margin: 0 auto; width: 100%;text-align: right;" cellspacing="2"  >
							<tr>
								<td><?php echo $tr->translate("ថ្ងៃបង់ប្រាក់");?></td>
								<td><input type="text" name="rent_date" class="fullside" id="rent_date"   dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now" /> </td> 
							</tr>
							<tr>
								<td><?php echo $tr->translate("លេខបង្កាន់ដៃ");?></td>
								<td><input type="text" name="receipt_no" class="fullside" id="receipt_no" style="color:red;"  dojoType="dijit.form.ValidationTextBox" required="required" value="<?php echo $this->receipt_no;?>"/> </td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("ទឹកប្រាក់");?>($)</td>
								<td><input type="text" name="rent_paid" class="fullside" id="rent_paid" value="0"  dojoType="dijit.form.NumberTextBox"  onKeyup="getTotal();"/> </td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("ថ្ងៃចាប់ផ្តើម");?></td>
								<td><input type="text" name="rent_start_date" class="fullside" id="rent_start_date"   dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now"/> </td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("ថ្ងៃផុតកំណត់");?></td>
								<td><input type="text" name="rent_end_date" class="fullside" id="rent_end_date"   dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now"/> </td>
							</tr>
					</table>	
				</fieldset>	
			</td>
			<td width="33%;" valign="top">
				<fieldset>
					<legend align="center" ><strong><?php echo $tr->translate("ទូទាត់សេវាអនាម័យ")?></strong></legend>
					<table style="margin: 0 auto; width: 100%;text-align: right;" cellspacing="2"  >
							<tr>
								<td><?php echo $tr->translate("តម្លៃ");?>($)</td>
								<td><input type="text" name="hygiene_price" class="fullside" id="hygiene_price"  value="0" dojoType="dijit.form.NumberTextBox" onKeyup="getTotal();"/> </td> 
							</tr>
							<tr>
								<td><?php echo $tr->translate("ថ្ងៃចាប់ផ្តើម");?></td>
								<td><input type="text" name="hygiene_start_date" class="fullside" id="hygiene_start_date"   dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now"/> </td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("ថ្ងៃផុតកំណត់");?></td>
								<td><input type="text" name="hygiene_end_date" class="fullside" id="hygiene_end_date"   dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now" /> </td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("NOTE");?></td>
								<td><input type="text" name="hygiene_note" class="fullside" id="hygiene_note"   dojoType="dijit.form.TextBox" /> </td> 
							</tr>
					</table>	
				</fieldset>	
			</td>
			<td width="33%;" valign="top">
				<fieldset>
					<legend align="center" ><strong><?php echo $tr->translate("OTHERS")?></strong></legend>
					<table style="margin: 0 auto; width: 100%;text-align: right;" cellspacing="2"  >
							<tr>
								<td><?php echo $tr->translate("តម្លៃ");?>($)</td>
								<td><input type="text" name="other_price" class="fullside" id="other_price" value="0"  dojoType="dijit.form.NumberTextBox" onKeyup="getTotal();"/> </td> 
							</tr>
							<tr>
								<td><?php echo $tr->translate("ថ្ងៃចាប់ផ្តើម");?></td>
								<td><input type="text" name="other_start_date" class="fullside" id="other_start_date"   dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now"/> </td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("ថ្ងៃផុតកំណត់");?></td>
								<td><input type="text" name="other_end_date" class="fullside" id="other_end_date"   dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now" /> </td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("NOTE");?></td>
								<td><input type="text" name="other_note" class="fullside" id="other_note"   dojoType="dijit.form.TextBox" /> </td> 
							</tr>
					</table>	
				</fieldset>
			</td>
		</tr>
		
		<tr>
			<td width="33%;" valign="top">
				<fieldset>
					<legend align="center" ><strong><?php echo $tr->translate("PAID_AMOUN")?></strong></legend>
					<table style="margin: 0 auto; width: 100%;text-align: right;" cellspacing="2"  >
							<tr>
								<td><?php echo $tr->translate("ទឹកប្រាក់សរុប");?>($)​</td>
								<td><input type="text" name="all_total_amount" class="fullside" id="all_total_amount"  value="0" dojoType="dijit.form.NumberTextBox" readOnly="true"/> </td> 
							</tr>
							<tr>
								<td><?php echo $tr->translate("ប្រាក់បានបង់");?>($)</td>
								<td><input type="text" name="paid" class="fullside" id="paid" value="0"  dojoType="dijit.form.NumberTextBox" required="true" onKeyup="getTotal()"/> </td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("ប្រាក់ជំពាក់");?>($)</td>
								<td><input type="text" name="balance" class="fullside" id="balance" value="0"  dojoType="dijit.form.NumberTextBox" readOnly="true"/> </td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("CREATE_DATE");?></td>
								<td><input type="text" name="create_date" class="fullside" id="create_date"   dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now"/> </td>
							</tr>
							<tr>
								<td><?php echo $tr->translate("NOTE");?></td>
								<td><input type="text" name="note" class="fullside" id="note"   dojoType="dijit.form.TextBox" /> </td> 
							</tr>
							
							<tr>
								<td><?php echo $tr->translate("STATUS");?></td>
								<td>
									<select dojoType='dijit.form.FilteringSelect' id="status" name="status"   class="fullside"  ​​  placeholder=" ">
										<option value="1"><?php echo $tr->translate("ACTIVE");?></option>
										<option  value="0"><?php echo $tr->translate("DEACTIVE");?> </option>
									</select>
								</td>
							</tr>
							
					</table>	
				</fieldset>	
			</td>
		</tr>
		
		<tr>
			<td colspan="4" align="center" style="padding-left:40px;">
				<input iconClass="dijitIconClear" type="reset" value="clear" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
				<input type="submit" value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" 
					iconClass="dijitEditorIcon dijitEditorIconSave" />
				<input type="submit" value="save_new" name="save_new"  id="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" 
					 iconClass="dijitEditorIcon dijitEditorIconSave" />
			</td>
		</tr>
	</table>	
</form>
<script>
var reil_exc="<?php echo $this->reil['reil']?>";

function hidendOldCus(){
	if(dijit.byId('is_new_cu').get('value')==0){
		$('#old_cus_div').show();
		$("#cus_name_div").hide();
		//dijit.byId("old_cus").attr("value",'0');
	}else {
		$("#cus_name_div").show();
		$('#old_cus_div').hide();
		clearCusOld();
	}
}

function clearCusOld(){
	dijit.byId("water_old_congtor").attr("value","");
	dijit.byId("water_new_congtor").attr("value","");
	dijit.byId("fire_old_congtor").attr("value","");
	dijit.byId("fire_new_congtor").attr("value","");
	//dijit.byId("cus_id").attr('value','<?php echo $this->cus_id;?>');
	dijit.byId("cus_name").attr("value","");
	dijit.byId("phone").attr("value","");
	dijit.byId("email").attr("value","");
	$("#address").val("");
}

function setCusName(){
	 dijit.byId("cus_name").attr('value',dijit.byId("old_cus").attr('displayedValue'));
}

//functon water info
function getQtyPariceWater(){
	var old_c=dijit.byId("water_old_congtor").get("value");
	var new_c=dijit.byId("water_new_congtor").get("value");
	dijit.byId("water_qty").attr("value",parseFloat(new_c-old_c));
	if(new_c <= old_c){
		alert("value new number can't smaller then old number! ");
		dijit.byId("water_new_congtor").attr("value",parseFloat(old_c+1));
		new_c=dijit.byId("water_new_congtor").get("value");
		old_c=dijit.byId("water_old_congtor").get("value");
		dijit.byId("water_qty").attr("value",parseFloat(new_c-old_c));
	}

	 if(!isNaN(dijit.byId("water_cost").get("value"))){
		  var qty=dijit.byId("water_qty").get("value");
		  var cost=dijit.byId("water_cost").get("value");
		  dijit.byId("water_total").attr("value",parseFloat(qty*cost));
		  //convert reil to dollar 
		  var reil_total=dijit.byId("water_total").get("value");
		  dijit.byId("water_exc_rate").attr("value",parseFloat(reil_total/reil_exc));
	 }else{
		 dijit.byId("water_total").attr("value",0);
		 dijit.byId("water_exc_rate").attr("value",0);
	 }
	 getTotal();
}

//functon fire info
function getQtyPariceFire(){
	var old_c=dijit.byId("fire_old_congtor").get("value");
	var new_c=dijit.byId("fire_new_congtor").get("value");
	dijit.byId("fire_qty").attr("value",parseFloat(new_c-old_c));
	if(new_c <= old_c){
		alert("value new number can't smaller then old number! ");
		dijit.byId("fire_new_congtor").attr("value",parseFloat(old_c+1));
		new_c=dijit.byId("fire_new_congtor").get("value");
		old_c=dijit.byId("fire_old_congtor").get("value");
		dijit.byId("fire_qty").attr("value",parseFloat(new_c-old_c));
	}

	 if(!isNaN(dijit.byId("fire_cost").get("value"))){
		  var qty=dijit.byId("fire_qty").get("value");
		  var cost=dijit.byId("fire_cost").get("value");
		  dijit.byId("fire_total").attr("value",parseFloat(qty*cost));
		  //convert reil to dollar 
		  var reil_total=dijit.byId("fire_total").get("value");
		  dijit.byId("fire_exc_rate").attr("value",parseFloat(reil_total/reil_exc));
	 }else{
		 dijit.byId("fire_exc_rate").attr("value",0);
		 dijit.byId("fire_total").attr("value",0);
	 }
	 getTotal();
}

//functon get sum money All total
function getTotal(){
	var total=0;
	var water=dijit.byId("water_exc_rate").get("value");
	var fire=dijit.byId("fire_exc_rate").get("value");
	var rent_paid=dijit.byId("rent_paid").get("value");
	var hygiene_price=dijit.byId("hygiene_price").get("value");
	var other_price=dijit.byId("other_price").get("value");
	if(isNaN(water)){
		water=0;
	}
	if(isNaN(fire)){
		fire=0;
	}
	if(isNaN(rent_paid)){
		rent_paid=0;
	}
	if(isNaN(hygiene_price)){
		hygiene_price=0;
	}
	if(isNaN(other_price)){
		other_price=0;
	}
	total=parseFloat(water+fire+rent_paid+hygiene_price+other_price);
	dijit.byId("all_total_amount").attr("value",total);
	dijit.byId("paid").attr("value",total);

	if(!isNaN(dijit.byId("paid").get("value"))){
		var amount=dijit.byId("all_total_amount").get("value");
		var paid=dijit.byId("paid").get("value");
		dijit.byId("balance").attr("value",parseFloat(amount-paid));
		if(amount<paid){
			alert("Paid can't bigger than amount!!!");
			dijit.byId("paid").attr("value",amount);
			dijit.byId("balance").attr("value",0);
		}
	}else{
		dijit.byId("balance").attr("value",0);
	}
}

//get old customer info 
var url_getcusinfo = '<?php echo $this->url(array('module'=>'accounting','controller'=>'customerpayment','action'=>'get-customer-info')); ?>';
function getOldCustomerInfo(){
	var old_cus = dijit.byId("old_cus").get('value');
	if(old_cus==0 || old_cus==''){
		return  false;
	}
	dojo.xhrPost({
		url:url_getcusinfo,
		content:{
			'cus_id':old_cus
			},
		handleAs:"json",
		load: function(data) {
			 //set customer 
			dijit.byId("cus_id").attr("value",data.customer_code); 
			dijit.byId("cus_name").attr("value",data.first_name);	
			dijit.byId("sex").attr("value",data.sex);
			dijit.byId("phone").attr("value",data.phone);
			//dijit.byId("start_date").attr("value",data.start_date);
			//dijit.byId("end_date").attr("value",data.end_date);
			dijit.byId("email").attr("value",data.email);
			$("#address").val(data.address);

			//set water old congtor 
			dijit.byId("water_old_congtor").attr("value",data.water_new_congtor); 
			dijit.byId("water_cost").attr("value",data.water_cost);
			
			//set water old congtor 
			dijit.byId("fire_old_congtor").attr("value",data.fire_new_congtor);
			dijit.byId("fire_cost").attr("value",data.fire_cost);
			
		},
		error: function(err) {
			alert(err);
		}
	});
}

</script>
