<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate('EDIT_STUDENT_TEST'));
//print_r($this->session);
?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
 <script>
		require(["dijit/form/DateTextBox","dijit/form/Textarea"]);
 </script>
 
 
 <script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	var grade_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->dept));?> );
	
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
			store: grade_store,
			autoComplete: true,                        
			required: false,
			id: "grade_result",
			name: "grade_result",           
			class: "fullside", 
			placeHolder:"Select grade",          
			onChange: function() {  
				// dept_id = dijit.byId('grade_result').get('value');
				// if(dept_id==-1){
					// dijit.byId("popup_add_dept").show();
				// }
			}
		}, "grade_result");
		
		getAllGrade();
		readMoneyInKhmer();
		getDegreeType();
	});
	
</script>
 
 
<form id='frm_teststudent' action="<?php echo $this->url(array('module'=>'accounting','controller'=>'studenttest','action'=>'edit')); ?>" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			}else {
				return false;
			}
	</script>
	
	<table cellspacing="10" class='fullside' >
		<tr>
			<td>
				<fieldset>
					<legend><strong><?php echo $tr->translate('EDIT_STUDENT_TEST')?></strong></legend>
						<table cellspacing="10"  width="100%">
							<tr>
								<td valign="top" width="33%">
									<table cellspacing="5"  width="100%">
										<tr>
											<td><?php echo $tr->translate("BRANCH");?></td>
											<td>
												<select name="branch" id="branch" class="fullside" autoComplete="false" queryExpr="*${0}*" readonly onchange="getReceiptNumber();" dojoType="dijit.form.FilteringSelect" type="text" >
													<option value="-1">----- select branch -----</option>
													<?php if(!empty($this->branch_id)){foreach ($this->branch_id as $branch){?>
													<option value="<?php echo $branch['id'];?>" <?php if($this->rs['branch_id']==$branch['id']){echo 'selected="selected"';}?>><?php echo $branch['name'];?></option>
													<?php }}?>
												</select>
											</td>
										</tr>
										
										<tr>
											<td><?php echo $tr->translate("NAME_KH")?></td>
											<td><input value="<?php echo $this->rs['kh_name']?>" type="text" name="kh_name" id="kh_name" required="1" class="fullside" dojoType="dijit.form.ValidationTextBox"   />
												<input value="<?php echo $this->rs['id']?>" type="hidden" name="id" id="id" dojoType="dijit.form.ValidationTextBox" />
											</td>
										</tr>
										<tr>
											<td style="white-space: nowrap;"><?php echo $tr->translate("NAME_EN")?></td>
											<td><input value="<?php echo $this->rs['en_name']?>" type="text" name="en_name" id="en_name" required="1"  class="fullside" dojoType="dijit.form.ValidationTextBox" /></td>
										</tr>
										<tr>
											<td><?php echo $tr->translate("SEX")?></td>
											<td>
												<select name="sex" id="sex" class="fullside" dojoType="dijit.form.FilteringSelect"  >
													<option value="1" <?php if($this->rs['sex']==1){echo 'selected="selected"';}?>><?php echo $tr->translate('MALE')?></option>
													<option value="2" <?php if($this->rs['sex']==2){echo 'selected="selected"';}?>><?php echo $tr->translate('FEMALE')?></option>
												</select>
											</td>						
										</tr>
										<tr>
											<td><?php echo $tr->translate("DOB")?></td>
											<td><input type="text" value="<?php echo $this->rs['dob']?>" name="dob" id="dob" class="fullside"  value="now" constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox"   /></td>
										</tr>
										<tr>
											<td><?php echo $tr->translate("PHONE")?></td>
											<td><input value="<?php echo $this->rs['phone']?>" type="text" name="phone" id="phone" class="fullside" dojoType="dijit.form.TextBox"   /></td>
										</tr>
										<tr>
										    <td><?php echo $tr->translate("ADDRESS")?></td>
											<td><textarea style="height:50px;font-family:'Khmer OS Battambang';font-size: 15px;" class="fullside" name="address" id="address" dojoType="dijit.form.Textarea" ><?php echo $this->rs['address']?></textarea></td>
										</tr>
									</table>
								</td>
								<td valign="top" width="33%">
									<table cellspacing="5"  width="100%">
										<tr>
										    <td><?php echo $tr->translate("RECEIPT")?></td>
											<td><input readonly type="text" name="receipt" id="receipt" class="fullside" dojoType="dijit.form.TextBox"  value="<?php echo $this->rs['receipt']?>"/></td>
										</tr>
										<!-- 
										<tr>
										    <td><?php //echo $tr->translate("SERIAL")?></td>
											<td><input type="text" value="<?php //echo $this->rs['serial']?>" name="serial" id="serial" class="fullside" dojoType="dijit.form.TextBox"   /></td>
										</tr>
										 -->
										<tr>
										    <td><?php echo $tr->translate("DEGREE")?></td>
											<td>
												<select name="degree" id="degree" class="fullside" dojoType="dijit.form.FilteringSelect" onchange="getDegreeType();"  >
													<?php if(!empty($this->degree)){foreach($this->degree as $rs){?>
														<option value="<?php echo $rs['id'];?>" <?php if($this->rs['degree']==$rs['id']){echo"selected";}?>><?php echo $rs['name'];?></option>
													<?php }}?>
												</select>
												<input type="hidden" dojoType="dijit.form.TextBox" name="degree_type" id="degree_type"/>
											</td>
										</tr>
										<!-- 
										<tr>
											<td><?php //echo $tr->translate("OLD_SCHOOL")?></td>
											<td><input type="text" value="<?php //echo $this->rs['old_school']?>" name="old_school" id="old_school" class="fullside" dojoType="dijit.form.TextBox"   /></td>
										</tr>
										<tr>
											 <td><?php //echo $tr->translate("OLD_GRADE")?></td>
											 <td><input type="text" value="<?php //echo $this->rs['old_grade']?>" name="old_grade" id="old_grade" class="fullside" dojoType="dijit.form.TextBox" /></td>
										</tr>
										 -->
										<tr>
											 <td><?php echo $tr->translate("PRICE")?></td>
											 <td><input onkeyup="readMoneyInKhmer();" value="<?php echo $this->rs['total_price']?>" type="text" readonly name="test_cost" required="1"  id="test_cost" class="fullside" dojoType="dijit.form.NumberTextBox"   /></td>
										</tr>
										<tr>
											<td><?php echo $tr->translate("STATUS")?></td>
											<td>
												<select type="text" name="status" id="status"  class="fullside" dojoType="dijit.form.FilteringSelect" >
													<option value="1" <?php if($this->rs['status']==1){echo"selected";}?>><?php echo $tr->translate('ACTIVE')?></option>
													<option value="0" <?php if($this->rs['status']==0){echo"selected";}?>><?php echo $tr->translate('DEACTIVE')?></option>								
												</select>
											</td>
										</tr>
									</table>
								</td>
								<td valign="top" width="33%">
									<table cellspacing="0"  width="100%">
										<tr>
											<td valign="top"><?php echo $tr->translate("NOTE")?></td>
											<td><textarea style="height:100px !important;font-family:'Khmer OS Battambang';font-size: 15px;"  class="fullside" name="note" id="note" dojoType="dijit.form.Textarea" ><?php echo $this->rs['note']?></textarea></td>
										</tr>
										
										<tr>
											<td colspan="2">
												<fieldset> 
													<legend align="center" ><strong><?php echo $tr->translate("RESULT");?></strong></legend>
														<table width="100%">
															<tr>
																<td>
																	<tr>
																		<td><?php echo $tr->translate("DEGREE")?></td>
																		<td>
																			<select name="degree_result" id="degree_result" readonly class="fullside" dojoType="dijit.form.FilteringSelect"  >
																				<?php if(!empty($this->degree)){foreach($this->degree as $rs){?>
																					<option value="<?php echo $rs['id'];?>" <?php if($this->rs['degree']==$rs['id']){echo"selected";}?>><?php echo $rs['name'];?></option>
																				<?php }}?>
																			</select>
																		</td>
																	</tr>
																	<tr>
																		<td><?php echo $tr->translate("GRADE")?></td>
																		<td>
																			<input id="grade_result" />
																		</td>
																	</tr>
																	<tr>
																		<td><?php echo $tr->translate("SESSION")?></td>
																		<td>
																			<select name="session_result" id="session_result" class="fullside" dojoType="dijit.form.FilteringSelect"  >
																				<?php if(!empty($this->session)){foreach($this->session as $session){?>
																						<option value="<?php echo $session['id'];?>" <?php if($session['id']==$this->rs['session_result']){echo"selected";}?>><?php echo $session['name'];?></option>
																				<?php }}?>
																			</select>
																		</td>
																	</tr>
																</td>
															</tr>
														</table>
												</fieldset>
											</td>
										</tr>
									</table>
								</td>
							</tr>
						</table>
				</fieldset>
			</td>
		</tr>		
		<tr>
			<td align="center">
				<input label="<?php echo $tr->translate("GO_EDIT")?>" onclick="submitData();" name='savenew' id='savenew' value='savenew' dojoType="dijit.form.Button"  type="submit" iconClass="dijitIconNewTask"/>
			</td>
		</tr>	
	</table>
</form>

<script>

function submitData(){
	if(dijit.byId('frm_teststudent').validate()) {
		dijit.byId('savenew').set('disabled',true);
		dijit.byId('frm_teststudent').submit();
	}
}

var url_get_grade = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-grade')); ?>';
function getAllGrade(){
	dept_id = dijit.byId('degree_result').get('value');
	if(dept_id==''){
		return false;
	}
	
	old_grade = '<?php echo $this->rs['grade_result']?>';
	
	dojo.xhrPost({
		url:url_get_grade,
		content:{
			'dept_id':dept_id
			},
		handleAs:"json",
		load: function(data) {
			grade_store  = getDataStorefromJSON('id','name', data);
			dijit.byId('grade_result').set('store',grade_store);  
			
			if(old_grade!=''){
				dijit.byId('grade_result').attr('value',old_grade);
			}
			
		},
		error: function(err) {
			alert(err);
		}
	});
}
var url_getdegree = '<?php echo $this->url(array('module'=>'registrar','controller'=>'studenttest','action'=>'getdegreetype')); ?>';
function getDegreeType(){
	degree = dijit.byId('degree').get('value');
	dojo.xhrPost({
		url:url_getdegree,
		content:{
			'degree':degree
			},
		handleAs:"json",
		load: function(data) {
			
			if(data!=''){
				dijit.byId('degree_type').attr('value',data);
			}
			
		},
		error: function(err) {
			alert(err);
		}
	});
}
 </script>