<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('SRMS_WUREGISTER')); 
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>	
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.8.3.min.js"></script>
<!-- <script type="text/javascript"  src="<?php //echo $this->baseUrl();?>/js/convertion.js"></script> -->
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dojo.store.Memory");
	
	
	var dept_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->all_dept));?> );
	dojo.ready(function(){ displayNoneAddRow();addRow();
		changControll();getStudentNo(1,'');displayAmountSection();
		
	new dijit.form.FilteringSelect({
	    store: dept_store,
	    autoComplete: true,                        
	    required: true,
	    id: "dept",
	    name: "dept",           
	    class: 'fullside',  
	    placeHolder:"Selected Degree",          
	    onChange: function() {  
	    	dept_id = dijit.byId('dept').get('value');
	    	dijit.byId('grade').attr('value','');
	    	getallModel(dept_id,a=''); 
	    	getStudentNo(dept_id,'');
	    	setHourDefault();
			
			oldStudentChangeDegree();
			
	    }
	}, "dept");
	
	new dijit.form.FilteringSelect({
	    //store: dept_store,
	    autoComplete: true,                        
	    id: "grade",
	    name: "grade",           
	    class: 'fullside', 
	    placeHolder:"Selected Grade",          
	    onChange: function() {  
	    	make_id = dijit.byId('grade').get('value');
	    	paymentTerm();
	    	dijit.byId('discount').attr('value','0');
	    	dijit.byId('books').attr('value','0');
	    	dijit.byId('addmin_fee').attr('value','0');
	    	dijit.byId('remaining').attr('value','0');
	    	dijit.byId('remark').attr('value','0');
	    	//dijit.byId('char_price').attr('value','0');
	    	dijit.byId('not').attr('value','');
	    	getTotale();
	    }
	}, "grade");
	
	dijit.byId('dept').attr('value','<?php echo $this->degree_row['degree'];?>');
	getDateTerm();
	});	
	
	var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_dept = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-grade')); ?>';
	function getallModel(dept_id,a){
		
			dojo.xhrPost({
				url:url_dept,
				content:{
					'dept_id':dept_id
					},
				handleAs:"json",
				load: function(data) {
					//alert(data);
					grade_store  = getDataStorefromJSON('id','name', data);
				    dijit.byId('grade').set('store',grade_store);  
				    if(a!=""){
				    	dijit.byId('grade').attr('value',a);
			        } 
				},
				error: function(err) {
					//alert(err);
				}
			});
	}
	var url_getstuno = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-stu-no')); ?>';
	function getStudentNo(dept_id,condition){
		  if(dept_id==''){
			return false;
			}
			dojo.xhrPost({
				url:url_getstuno,
				content:{
					'dept_id':dept_id,
					'branch_id':0,
					},
				handleAs:"json",
				load: function(data) {
					  dijit.byId('stu_id').attr('value',data);   
					  if(condition==1){
						  getNewReceiptNo(data);
					  }
					
				},
				error: function(err) {
					alert(err);
				}
			});
	}
	
	var url_getreceiptno = '<?php echo $this->url(array('module'=>'registrar','controller'=>'coursestudy','action'=>'get-receipt-no')); ?>';
	function getNewReceiptNo(new_stu_id){
		
		dojo.xhrPost({
				url:url_getreceiptno,
				content:{
					'dept_id':1
					},
				handleAs:"json",
				load: function(data) {
					//alert(data);
					//url_getstuno  = getDataStorefromJSON('id','name', data);
					 dijit.byId('reciept_no').attr('value',data);   
					if(new_stu_id!=''){
						printSave(new_stu_id,data);
					}
				},
				error: function(err) {
					alert(err);
				}
			});
			
	}
	
	function paymentTerm(){
		generat=dijit.byId('study_year').get('value');
		payment_term=dijit.byId('payment_term').get('value');
		grade=dijit.byId('grade').get('value');
		//time=dijit.byId('time').get('value');
		session=dijit.byId('session').get('value');
		student_type=dijit.byId('student_type').get('value');
		if(student_type==3){
			old_studens=dijit.byId('old_studens').get('value');
			if(old_studens != -1 ){
				getBalancePrice(4,old_studens);
			}else
			{
				if(generat!='' && payment_term !='' && grade !='' && session !=''){
					getPaymentTerms(generat,payment_term,grade,session);
				}
			}
		}else{
			if(generat!='' && payment_term !='' && grade !='' && session !=''){
				getPaymentTerms(generat,payment_term,grade,session);
			}
		}
		getDateTerm();
		
	}
	function paymentTerms(){
		generat=dijit.byId('study_year').get('value');
		payment_term=dijit.byId('payment_term').get('value');
		//payment_term=payment_term-1;
		grade=dijit.byId('grade').get('value');
		//time=dijit.byId('time').get('value');
		session=dijit.byId('session').get('value');
		if(generat!='' && payment_term !='' && grade !='' && session !=''){
			getPaymentTerms(generat,payment_term,grade,session);
			
		}
	}
	var payment_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_getpaymentterm = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-payment-term')); ?>';
	function getPaymentTerms(generat,payment_term,grade,session){//time (full/part time)
		dijit.byId('tuitionfee').attr('value',0);
    	dijit.byId('total').attr('value',0);
    	dijit.byId('books').attr('value',0);

    	if(payment_term==5){ // if pay by section => show amount of section 
			document.getElementById('amount_section').style.display="block";
			document.getElementById('label_amount').style.display="block";
			
		}else{ // pay by other => hide amount of section
			document.getElementById('amount_section').style.display="none";
			document.getElementById('label_amount').style.display="none";
		}
    	
			dojo.xhrPost({
				url:url_getpaymentterm,
				content:{
					'generat_id':generat,
					'pay_id':payment_term,
					'grade_id':grade,
					//'time':time,
					'session':session
					},
				handleAs:"json",
				load: function(data) {
				      if(data !=''){
				    	 // dijit.byId('tuitionfee').attr('value',data.price_fee);
				    	dijit.byId('tuitionfee').attr('value',data.tuition_fee);
				    	dijit.byId('total').attr('value',data.tuition_fee);
				    	dijit.byId('books').attr('value',data.tuition_fee);
				    	dijit.byId('price_per_section').attr('value',data.tuition_fee);
				      }else {
				    	 dijit.byId('tuitionfee').attr('value','0'); 
				    	 dijit.byId('total').attr('value','0'); 
				    	 dijit.byId('discount').attr('value','0');
				    	 dijit.byId('books').attr('value','0');
					     dijit.byId('addmin_fee').attr('value','0');
					     dijit.byId('remaining').attr('value','0');
					     dijit.byId('remark').attr('value','0');
					 //    dijit.byId('char_price').attr('value','0');
					     dijit.byId('not').attr('value','');
				      }
					  
					  netTotal();
					  
				 /*     a = dojo.number.format(data.tuition_fee);
					  money_khmer=read_money_in_khmer(a);
					  dijit.byId('char_price').attr('value',money_khmer.trim()+'ដុល្លាគត់');
					  */
				},
				error: function(err) {
					//alert(err);
				}
			});
	}
	//get price balance
	var url_balance = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-banlance-price')); ?>';
	function getBalancePrice(servce_id,student_id){
			type=1; // from register (k1 - g12)
			dojo.xhrPost({
				url:url_balance,
				content:{
					'servce_id':servce_id,
					'student_id':student_id,
					'type':type,
					},
				handleAs:"json",
				load: function(data) {
				      if(data){
				    	  dijit.byId('tuitionfee').attr('value',data.balance);
				    	  dijit.byId('id_balance_record').attr('value',data.id);
				     	  dijit.byId('total').attr('value',data.balance);
				    	  dijit.byId('books').attr('value',data.balance);
				    	  dijit.byId('not').attr('value',data.sms);
				    	  dijit.byId('study_year').attr('value',data.year);
				    	  dijit.byId('session').attr('value',data.session);
				    	  dijit.byId('payment_term').attr('value',data.payment_term);
				    	  dijit.byId('start_date').attr('value',data.start_date);
				    	  dijit.byId('end_date').attr('value',data.validate);
				    	  setReadOnly();
				    	  netTotal();
				     }else {
				    	 dijit.byId('id_balance_record').attr('value','');
				    	 removeReadOnly();
				    	 paymentTerms();
				      }
				},
				error: function(err) {
					alert(err);
				}
			});
	}

	// set field to readonly when balance>0 for get all old information of student
	function setReadOnly(){
		dijit.byId("start_date").set('readOnly',true);
		dijit.byId("end_date").set('readOnly',true);
		dijit.byId("study_year").set('readOnly',true);
		dijit.byId("dept").set('readOnly',true);
		dijit.byId("grade").set('readOnly',true);
		dijit.byId("session").set('readOnly',true);
		dijit.byId("study_hour").set('readOnly',true);
		dijit.byId("payment_term").set('readOnly',true);
	}
	// Remove field readonly when balance <= 0 for get all old information of student
	function removeReadOnly(){
		dijit.byId("start_date").set('readOnly',false);
		dijit.byId("end_date").set('readOnly',false);
		dijit.byId("study_year").set('readOnly',false);
		dijit.byId("dept").set('readOnly',false);
		dijit.byId("grade").set('readOnly',false);
		dijit.byId("session").set('readOnly',false);
		dijit.byId("study_hour").set('readOnly',false);
		dijit.byId("payment_term").set('readOnly',false);
	}

	
	//set value totale 
	function getTotale(){
		//old % totale
		payment_term = dijit.byId('payment_term').get('value');
		if(payment_term==5){
			tuitionfee = dijit.byId('tuitionfee').get('value');
			amount_section = dijit.byId('amount_section').get('value');
			
			tuitionfee = tuitionfee * amount_section;
		}else{
			tuitionfee = dijit.byId('tuitionfee').get('value');
			tuitionfee = isNaN(tuitionfee)?0:tuitionfee;
		}
		
		
		
		discount=dijit.byId('discount').get('value');
		pc=discount/100;
		ds=tuitionfee*pc;
		old_totale=tuitionfee - ds;
		//alert('hello');
		remark=dijit.byId('remark').get('value');
		remark=isNaN(remark)?0:remark;
		addmin_fee=dijit.byId('addmin_fee').get('value');
		addmin_fee=isNaN(addmin_fee)?0:addmin_fee;
		totals=parseFloat(old_totale)+parseFloat(remark)+parseFloat(addmin_fee);
		  dijit.byId('total').attr('value',totals.toFixed(2));
		  dijit.byId('books').attr('value',totals.toFixed(2));
		  getRemaining();
	}
	//set value remaining
	function getRemaining(){
		  total=dijit.byId('total').get('value');
		  total=isNaN(total)?0:total;
		  books=dijit.byId('books').get('value');
		  books=isNaN(books)?0:books;
		  remaining=parseFloat(total) - parseFloat(books);
		  if(total<books){
			 alert('Deposit must be smaller than the total money!');
			 dijit.byId('books').attr('value',total);
			 dijit.byId('remaining').attr('value','0');
		  }else{
		     dijit.byId('remaining').attr('value',remaining.toFixed(2));
		  }
		  //CheckAmount();
	}
	function getDisccount(){
		books=dijit.byId('books').get('value');
		books=isNaN(books)?0:books;
	
		tuitionfee=dijit.byId('tuitionfee').get('value');
		tuitionfee=isNaN(tuitionfee)?0:tuitionfee;
		discount=dijit.byId('discount').get('value');
		pc=discount/100;
		ds=tuitionfee*pc;
		totale=tuitionfee - ds;
		if(discount<=100){
			   dijit.byId('total').attr('value',totale.toFixed(2));
			//   dijit.byId('remaining').attr('value','0');
			}else{ 
				alert('No more than a hundred of disccount!');
				dijit.byId('discount').attr('value','100');
				//getTotale();
			  //  dijit.byId('remaining').attr('value','0');
			}
	}
	
	
//calculator date by select term_payment
	function getDateTerm() {
		// alert(1);
		payment_term=dijit.byId('payment_term').get('value');
		start_date=dijit.byId('start_date').get('value');
		
		amount_section = dijit.byId('amount_section').get('value');
		
		if(payment_term==1){
			 var a = new Date(start_date);
			  mm = a.getMonth()+(1)+1;

			 var dd = a.getDate();
			  if(dd<10){
			   dd = "0"+dd;
			 }
			  if(mm<10){
			   mm = "0"+mm;
			 }
			 var y = a.getFullYear();
			 
			 var epx_date = y + '-' + mm + '-' + dd ;

			 //alert(epx_date);
			 dijit.byId('end_date').attr('value',epx_date);
		 }
		 else if(payment_term==2){
			 var a = new Date(start_date);
			  mm = a.getMonth()+(3)+1;

			 var dd = a.getDate();
			  if(dd<10){
			   dd = "0"+dd;
			 }
			  if(mm<10){
			   mm = "0"+mm;
			 }
			 var y = a.getFullYear();
			 var epx_date = y + '-' + mm + '-' + dd ;

			 //alert(epx_date);
			 dijit.byId('end_date').attr('value',epx_date);
		 }
		 else if(payment_term==3){
			 var a = new Date(start_date);
			  mm = a.getMonth()+(6)+1;

			 var dd = a.getDate();
			  if(dd<10){
			   dd = "0"+dd;
			 }
			  if(mm<10){
			   mm = "0"+mm;
			 }
			 var y = a.getFullYear();
			 var epx_date = y + '-' + mm + '-' + dd ;

			 //alert(epx_date);
			 dijit.byId('end_date').attr('value',epx_date);
		 }
		 else if(payment_term==4){
			 var a = new Date(start_date);
			  mm = a.getMonth()+(12)+1;

			 var dd = a.getDate();
			  if(dd<10){
			   dd = "0"+dd;
			 }
			  if(mm<10){
			   mm = "0"+mm;
			 }
			 var y = a.getFullYear();
			 
			 var epx_date = y + '-' + mm + '-' + dd ;

			 //alert(epx_date);
			 dijit.byId('end_date').attr('value',epx_date);
		 }else if(payment_term==5){
			var a = new Date(start_date);
			dd = a.getDate()+parseInt(amount_section); 
			 
			 if(dd<10){
			   dd = "0"+dd;
			 }
			 mm = a.getMonth()+1;
			 if(mm<10){
			   mm = "0"+mm;
			 }
			 var y = a.getFullYear(); 
			 var epx_date = y + '-' + mm + '-' + dd ;
			 
			 dijit.byId('end_date').attr('value',epx_date);
		 }	
	}
	
</script>
<style>
select{ width:100%;}
fieldset{  background:none;}
.red{ color: red; padding-left:5px;}
</style>
<?php $register = $this->frm_register;?>
<form id='office_receipt' action="<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">   
   if(this.validate()) {
    year = dijit.byId('study_year').get('value');
    if(year==-1){
         dijit.byId("study_year").focus();
         return false;
    }
    return true;
   }else {
    return false;
   }
</script>
<table  cellspacing="10" style="margin: 0 auto; width: 100%;">
	<tr>
		<td>
  		<fieldset> 
			
					<legend align="center"><strong><?php echo $tr->translate("OFFICIAL_RECEIPT");?></strong></legend> 
					<table style="margin: 0 auto; width: 100%;padding:0px 10px 10px 10px;" cellspacing="5" >
						<tr>
							<td colspan="4">
								<input type="checkbox" value="1" onchange="displayNoneAddRow();netTotal();" name="buy_product" id="buy_product" dojoType="dijit.form.CheckBox"  /> Buy Product
							</td>
						</tr>
						<input type="hidden" name="ex_rate" id="ex_rate" value="<?php echo $this->exchange_rate ;?>" dojoType="dijit.form.TextBox" />
					    <tr>
					        <td colspan="4"​ style="border-bottom:1px solid #ccc;"><strong><?php echo $tr->translate("STUDENT_INFO");?></strong></td>
					    </tr>
						<tr>
							<td style="width: 160px"><?php echo $tr->translate("STUDENT_TYPE");?></td>
							<td>
								<input type="hidden" name="id_balance_record" id="id_balance_record" dojoType="dijit.form.TextBox" />
								<?php echo $register->getElement('student_type');?>
							</td>
							<td><?php echo $tr->translate("RECEIPT_NO");?></td>
							<td><?php echo $register->getElement('reciept_no');?>
							    <?php echo $register->getElement('id');?>
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("STUDENT_ID");?></td>
							<td>
								<div id="student_old"><?php echo $register->getElement('old_studens');?></div>
								<div id="id_stu"><?php echo $register->getElement('stu_id');?></div>
							</td>
							<td style="width: 160px"><?php echo $tr->translate("STUDENT_NAME");?></td>
							<td>
								<div id="student_old_name"><?php echo $register->getElement('old_stu_name');?></div>
								<div id="name_stu"><?php echo $register->getElement('stu_name');?></div>
								<?php //echo $register->getElement('old_stu_name'); ?>
								<?php //$register->getElement('stu_name');?>
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NAME_EN");?></td>
							<td><?php echo $register->getElement('en_name');?></td>
							<td><?php echo $tr->translate("NAME_KH");?></td>
							<td><?php echo $register->getElement('kh_name');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("SEX");?></td>
							<td><?php echo $register->getElement('sex');?></td>
							
							<td><?php echo $tr->translate("DOB");?></td>
							<td><input type="text"  class="fullside" name="dob" id="dob" value="now" constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" /></td>
							
						</tr>
						
						<tr>
							<td><?php echo $tr->translate("ADDRESS");?></td>
							<td><input type="text"  class="fullside" name="address" id="address" dojoType="dijit.form.TextBox" /></td>
							
							<td><?php echo $tr->translate("PHONE");?></td>
							<td><input type="text" name="phone" id="phone" class="fullside" dojoType="dijit.form.TextBox" /></td>
						</tr>
						<tr>
					        <td colspan="4"​ style="border-bottom:1px solid #ccc;"><strong><?php echo $tr->translate("STUDY_INFO");?></strong></td>
					    </tr>
						
						<tr>
							<td style="width: 160px"><?php echo $tr->translate("ACADEMIC_YEAR");?></td>
							<td><?php echo $register->getElement('study_year');?></td>
							<td><?php echo $tr->translate("ROOM_NAME");?><label class="red">*</label></td>
							<td>
								<select type="text" class="fullside" name="room" id="room" dojoType="dijit.form.FilteringSelect" />
									<option value='-1'>---------- select room ----------</option>
									<?php if(!empty($this->room)){foreach($this->room as $room){?>
										<option value="<?php echo $room['id'];?>"><?php echo $room['name'];?></option>
									<?php }}?>
								</select>
							</td>
						</tr>
						
					    <tr>
							<input type="hidden" name="old_stu_code" id="old_stu_code" dojoType="dijit.form.TextBox" />
							<input type="hidden" name="old_degree" id="old_degree" dojoType="dijit.form.TextBox" />
							<input type="hidden" name="old_grade" id="old_grade" dojoType="dijit.form.TextBox" />
							
							<td><?php echo $tr->translate("DEGREE");?><label class="red">*</label></td>
							<td><input id="dept" /></td>
							<td><?php echo $tr->translate("CLASS");?><label class="red">*</label></td>
							<td><input id="grade" /><?php //echo $register->getElement('metion');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("SESSION");?></td>
							<td><?php echo $register->getElement('session');?></td>
							<td style="white-space: nowrap;"><?php echo $tr->translate("TIME");?></td>
							<td>
							    <input dojoType="dijit.form.TextBox"  class="fullside" id="study_hour" name="study_hour"  type="text">
							<!--	<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside"  id="time" name="time" type="text" onchange="paymentTerm();">								
										<option value="2"><?php //echo $tr->translate("FULL_TIME");?></option>
										<option value="1"><?php //echo $tr->translate("PART_TIME");?></option>
								</select>-->
							</td>
					     </tr>
						<tr>
						    <td><?php echo $tr->translate("PAYMENT_TERM");?><label class="red">*</label></td>
							<td><?php echo $register->getElement('payment_term');?></td>
						    <td><?php echo $tr->translate("TUITION_FEE");?></td>
							<td><?php echo $register->getElement('tuitionfee');?></td>
						</tr>
						<input type="hidden" name="price_per_section" id="price_per_section" dojoType="dijit.form.TextBox" >
						<tr>
						    <td>
						    	<div id="label_amount">
						    		<?php echo $tr->translate("AMOUNT_SECTION");?>
						    	</div>
						    </td>
							<td>
								<div id="amount_section">
									<input name="amount_section" id="amount_section" onkeyup="calculateTotalFee();netTotal();getDateTerm();" dojoType="dijit.form.TextBox" value="1" class="fullside" type="text"/>
								</div>
							</td>
						</tr>
						<tr>
					        <td colspan="4"​ style="border-bottom:1px solid #ccc;"><strong><?php echo $tr->translate("PAYMENT_INFO");?></strong></td>
					    </tr>
						<tr>
						    <td><?php echo $tr->translate("DISCOUND");?></td>
							<td title='Ex: 20 or 10%'><?php echo $register->getElement('discount');?></td>
							<td><?php echo $tr->translate("OTHERS_PRICE");?></td>
							<td><?php echo $register->getElement('remark');;?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("ADMIN_FEE");?></td>
							<td title='Ex: 20 or 10%'><?php echo $register->getElement('addmin_fee');?></td>	
							<td><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
							<td title='Ex: 20 or 10%'><?php echo $register->getElement('total');?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("PAID_AMOUNT");?></td>
							<td><?php echo $register->getElement('books');;?></td>
							<td><?php echo $tr->translate("BALANCE");?></td>
							<td><?php echo $register->getElement('remaining');;?></td>
						</tr>
						<tr>	
						    <td><?php echo $tr->translate("NOT");?></td>
							<td title='Ex: 20 or 10%' ><?php echo $register->getElement('not');?></td>	
							<td><?php echo $tr->translate("START_DATE");?></td>
							<td><?php echo $register->getElement('start_date');?></td>
						</tr>
						<tr>
							<td><?php //echo $tr->translate("CHAR_PRICE");?></td>
							<td title='Ex: 20 or 10%' ><?php //echo $register->getElement('char_price');?></td>
							<td><?php echo $tr->translate("END_DATE");?></td>
							<td><?php echo $register->getElement('end_date');?></td>
						</tr>
						
						<input type="hidden" id="identity" name="identity" />
						<tr>
							<td colspan="4" align="left">
								<input type="button" label="<?php echo $tr->translate('ADD_ROW');?>" dojoType="dijit.form.Button" 
									iconClass="dijitIconEditProperty" onclick="addRow();" />
							</td>
						</tr>
						<tr>
							<td colspan="4">
								<table width="100%" border="1" id="table_row" style="border-collapse: collapse; border:1px solid #ccc;white-space: nowrap;">
										<tr id="head-title" class="head-td" align="right"></tr>
								</table>
							</td>
						</tr>
						<tr>
							<td colspan="6" align="right">
								<table style="width:400px;border-collapse: collapse;white-space:nowrap;" cellpadding="10" cellspacing="10" >
									<tr>
										<td ><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
										<td align="right"><input type="text" readonly="readonly" onkeyup="calculatBalanceAndReturn();"  name="grand_total" id="grand_total" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
									<tr>	
										<td><?php echo $tr->translate("CONVERT_TO_RIELS");?> (៛)</td>
										<td align="right"><input  type="text" readonly="readonly"  name="convert_to_riels" id="convert_to_riels" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
									<tr>	
										<td><?php echo $tr->translate("RECEIVED_AMOUNT");?></td>
										<td align="right"><input  type="text" readonly="readonly" onkeyup="calculatBalanceAndReturn();" required="true"  name="total_received" id="total_received" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("BALANCE");?></td>
										<td align="right"><input type="text"  readonly="readonly" name="total_balance" value="<?php echo 0?>" id="total_balance" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
<!-- 									<tr> -->
										<td><?php //echo $tr->translate("RETURN");?></td>
<!-- 										<td align="right"><input type="text" readonly="readonly" name="total_return" id="total_return" dojoType="dijit.form.NumberTextBox" /></td> -->
<!-- 									</tr> -->
								</table>
							</td>
						</tr>
						<tr>
							<td colspan="4" align="center">
							    <input type="submit" name="save_close" id="save_close" value="រក្សាទុក  &ចាកចេញ" label="<?php echo $tr->translate('SAVE_CLOSE');?>"   dojoType="dijit.form.Button" 
								 iconClass="dijitEditorIcon dijitEditorIconSave" />
								<input type="submit" name="save_new" id="save_new" value="រក្សាទុក" label="<?php echo $tr->translate('SAVE_NEW');?>"  dojoType="dijit.form.Button" 
								 iconClass="dijitEditorIcon dijitEditorIconSave" />
								 <input type="button" value="បោះពុម្ព" label="<?php echo $tr->translate('PRINT');?>" id="busyButton" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="printSave('','');"/> 
							</td>
						</tr>
					</table>	
 	</fieldset>		 
		</td>
	</tr>
</table>	
</form>
<script type="text/javascript">

///////////////////////////////////////////////////////////// Add Row /////////////////////////////////////////////////////////

var template = '';
var service = '';
var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
date_format = '"dd/MM/yyyy"';
function addRow() {
		col++;no++;
		template='';
		if(title!=1){
			temp+='<th ><?php echo $tr->translate("DEL");?></th>';
			temp+='<th ><?php echo $tr->translate("N_O");?></th>';
			temp+='<th ><?php echo $tr->translate("PRODUCT");?></th>';
			temp+='<th  ><?php echo $tr->translate("PRICE");?></th>';
			temp+='<th  ><?php echo $tr->translate("AMOUNT");?></th>';
			temp+='<th  ><?php echo $tr->translate("DISCOUNT");?> %</th>';
			temp+='<th  ><?php echo $tr->translate("SUBTOTAL");?></th>';
			temp+='<th><?php echo $tr->translate("REMARK");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
			template+='<td align="center"  style="width:3%"><img onclick="deleteRecord('+col+');calculateTotal('+col+');" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td align="center" style="width:3%;">'+no+'</td>';
			
			template+='<td style="width:30%"><input type="hidden" dojoType="dijit.form.TextBox" name="id_balance_record_'+col+'" id="id_balance_record_'+col+'"/>';
			template+='<select style="width:100%"  onchange="getProductPrice('+col+');" dojoType="dijit.form.FilteringSelect" id="product_'+col+'" name="product_'+col+'">';
				template+='<option value="">Select </option>';
				<?php if(!empty($this->all_product)){foreach($this->all_product as $product){?>
					template+='<option value="'+<?php echo $product['id']?>+'"><?php echo $product['name'];?></option>';
				<?php }}?>
			template+='</select></td>';	

			
			column = 0;
			template+='<td style="width:10%"> <input class="fullside"  type="text"  onkeyup="calculateTotal('+col+');" name="price_'+col+'" id="price_'+col+'" dojoType="dijit.form.NumberTextBox" " /><label id="subsub"></label></td>';	
			template+='<td style="width:10%"> <input class="fullside" type="text"  onkeyup="calculateTotal('+col+');" name="qty_'+col+'" id="qty_'+col+'" value="1" dojoType="dijit.form.NumberTextBox" /><label id="qty"></label></td>';			
					
			template+='<td style="width:10%"> <input class="fullside"  type="text" onkeyup="calculateTotal('+col+');" name="discount_'+col+'" value="<?php echo 0;?>" id="discount_'+col+'" dojoType="dijit.form.NumberTextBox" /><label id="subsub"></label></td>';
			template+='<td style="width:10%"> <input class="fullside"  type="text"  readonly="readonly" name="subtotal_'+col+'" id="subtotal_'+col+'" dojoType="dijit.form.NumberTextBox"/><label id="qty"></label></td>';
			template+='<td style="width:24%"> <input class="fullside"  type="text" name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ" /><label id="subsub"></label></td>';

								//constraints="{datePattern:'dd/MM/yyyy'}"
			
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);

		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
		//getValidate(col);
 }
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
	if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
}



///////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////




var url_get_start_date = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-start-date-register')); ?>';
function getStartDate(){
	service_id = 4; // 4 => get validate only student register
	stu_id = dijit.byId('old_studens').get('value');
	dojo.xhrPost({
		url:url_get_start_date,
		content:{
			'service_id':service_id,
			'stu_id':stu_id
			},
		handleAs:"json",
		load: function(data) {
			if(data){
				dijit.byId('start_date').attr('value',data);
			}else{
				dijit.byId('start_date').attr('value','<?php echo date('Y-m-d');?>');
			}	
		},
		error: function(err) {
			alert(err);
		}
	});
}

function getMonthByNumber(m){
	var monthName=[
		 "01",
		 "02",
		 "03",
		 "04",
		 "05",
		 "06",
		 "07",
		 "08",
		 "09",
		 "10",
		 "11",
		 "12",
		];
		return (monthName[m-1]);
}

function calculateTotalFee(){
	// price_per_sec = dijit.byId('price_per_section').get('value');
	// amount_sec = dijit.byId('amount_section').get('value');

	// total_fee = price_per_sec * amount_sec;
	// dijit.byId('tuitionfee').attr('value',total_fee);
	getDisccount();getTotale();
}

function displayAmountSection(){
	payment_term = dijit.byId('payment_term').get('value');
	if(payment_term==5){
		document.getElementById('amount_section').style.display="block";
		document.getElementById('label_amount').style.display="block";
		
	}else{
		document.getElementById('amount_section').style.display="none";
		document.getElementById('label_amount').style.display="none";
		//alert(222);
	}
	
}


function printSave(new_stu_id,new_receipt_no){		
	if(dijit.byId('office_receipt').validate()) {
		 
		if(dijit.byId('study_year').get('value')==-1){
		   dijit.byId("study_year").focus();
		   return false;
		}
		 
		 degree = dijit.byId('dept').get('value');
		 old_degree = dijit.byId('old_degree').get('value');
		
		 stu_type = dijit.byId('student_type').get('value');
		 
		 if(stu_type==1){ 
			 if(new_stu_id==''){
				 getStudentNo(degree,1);
			 }else{
				 dojo.byId("lb_receipt_no").innerHTML = new_receipt_no;
				 dojo.byId("lb_stu_id").innerHTML = new_stu_id;
			 }
		 }else{
			 
			 if(old_degree!=degree){ // old student change degree => generate new stu_code by degree
				 if(new_stu_id==''){
					getStudentNo(degree,1);
				 }else{
					dojo.byId("lb_receipt_no").innerHTML = new_receipt_no;
					dojo.byId("lb_stu_id").innerHTML = new_stu_id;
				 }
			 
			 }else{  // generate new receipt before print
				if(new_receipt_no==''){
					getNewReceiptNo(1);
				}else{
					dojo.byId("lb_receipt_no").innerHTML = new_receipt_no;
					dojo.byId("lb_stu_id").innerHTML = dijit.byId("old_studens").attr('displayedValue');
				} 
				
			 }
			 
			 //dojo.byId("lb_receipt_no").innerHTML = dijit.byId("reciept_no").get('value');
			 //dojo.byId("lb_stu_id").innerHTML = dijit.byId("old_studens").attr('displayedValue');
		 }
		
		
		 dojo.byId("lb_kh_name").innerHTML = dijit.byId("kh_name").get('value');
		 dojo.byId("lb_en_name").innerHTML = dijit.byId("en_name").get('value');
		 dojo.byId("lb_sex").innerHTML = dijit.byId("sex").attr('displayedValue');
		 
		 dojo.byId("lb_phone").innerHTML = dijit.byId("phone").attr('displayedValue');
		 dojo.byId("lb_address").innerHTML = dijit.byId("address").attr('displayedValue');
		 
		 room_id = dijit.byId("room").get('value');
		 if(room_id>0){
			dojo.byId("lb_room").innerHTML = dijit.byId('room').attr('displayedValue');
		 }else{
			dojo.byId("lb_room").innerHTML = '';
		 }
		 
		 dojo.byId("lb_hour").innerHTML = dijit.byId('study_hour').attr('displayedValue');
		// //var mkh = new Array('មករា', 'កុម្ភៈ', 'មីនា', 'មេសា', 'ឧសភា', 'មិថុនា', 'កក្កដា', 'សីហា', 'កញ្ញា', 'តុលា', 'វិច្ឆិកា', 'ធ្នូរ');
		 dojo.byId("lb_dob").innerHTML = dijit.byId('dob').attr('displayedValue');
		 dojo.byId("lb_grade").innerHTML = dijit.byId("grade").attr('displayedValue');
		// dojo.byId("lb_tuitionfee").innerHTML ="$ "+dijit.byId('tuitionfee').get('value').toFixed(2);
		// dojo.byId("lb_payment_term").innerHTML = dijit.byId("payment_term").attr('displayedValue');
		// //សិក្សាបើ discount=0 កុំអោយវាចេញ​​ (blank) , if discount>0 it show discount%
		 // var discount = dijit.byId("discount").get('value');
		 // if(discount == 0){
			// discount = '';
		 // }else{
			 // discount = discount+" %";
		 // }
		// dojo.byId("lb_discount").innerHTML = discount;
		// dojo.byId("lb_remark").innerHTML ="$ "+ dijit.byId('remark').attr('value').toFixed(2);
		// dojo.byId("lb_total").innerHTML ="$ "+dijit.byId('total').attr('value');
		// dojo.byId("lb_books").innerHTML = "$ "+dijit.byId("books").get('value').toFixed(2);
		// dojo.byId("lb_addmin_fee").innerHTML ="$ "+dijit.byId("addmin_fee").get('value').toFixed(2);
		// dojo.byId("lb_remaining").innerHTML = "$ "+dijit.byId("remaining").get('value');
		
		 // dojo.byId("lb_note").innerHTML = dijit.byId("not").get('value');
		 // //dojo.byId("lb_char").innerHTML = dijit.byId("char_price").get('value');
		 // //var d = dojo.byId("start_date").value.split('/');
		 // var d = dijit.byId("start_date").get('value');
		 // var day = d.getDate();
		 // var x = d.toDateString().substr(4,3);
		 // var year = d.getFullYear();
		 // dojo.byId("lb_start_date").innerHTML  = day+'-'+x+'-'+year;
		// // dojo.byId("lb_start_date").innerHTML = Ext.Date.format(date, "d-M-Y");//d[1] + "/" + d[0] +"/"+d[2]; 
		 // //var d = dojo.byId("end_date").value.split('/');
		 // var d = dijit.byId("end_date").get('value');
		 // var day = d.getDate();
		 // var x = d.toDateString().substr(4,3);
		 // var year = d.getFullYear();
		 // dojo.byId("lb_end_date").innerHTML  = day+'-'+x+'-'+year;
		 
		 
		 
		 
		 
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////		 
		
		var rowId = $('#identity').val();
		var rowIDArray = rowId.split(',');
		
		temp='<table cellpadding="0" cellspacing="0" align="center" style=" width: 100%; padding: 0px; margin-top: 10px !important; border-collapse: collapse; border: 1px solid #000;font-family:Khmer OS Battambang !important;white-space:nowrap;  " id="table">'
			  temp+='<tr style=" font-size:12px; text-align:center;">';
				  temp+='<td rowspan="2" style="border:1px solid #000;"> <strong style="font-family: Khmer OS Battambang;color:#000;font-size: 10px;">ល.រ<div class="tab_row fonteng">N<sup>o</sup></div></strong></td>';
				  temp+='<td  rowspan="2" style="border:1px solid #000;><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 10px;">បរិយាយ<div class="tab_row fonteng">Description</div></strong></td>';
				  temp+='<td colspan="3" style="border:1px solid #000;><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 6px;">សុពលភាព/Payment Date</strong></td>';
				  temp+='<td rowspan="2" style="border:1px solid #000;><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 10px;">ទឹកប្រាក់ <div class="tab_row fonteng">Amount</div></strong></td>';
				  temp+='<td rowspan="2" style="border:1px solid #000;><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 10px;">បញ្ចុះតម្លៃ <div class="tab_row fonteng">Discount</div></strong></td>';
				  temp+='<td rowspan="2" style="border:1px solid #000;><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 10px;">ទឹកប្រាក់សរុប <div class="tab_row fonteng">Total Amount</div></strong></td>';
				  temp+='<td rowspan="2" style="border:1px solid #000;><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 10px;">ផ្សេងៗ <div class="tab_row fonteng">Others</div></strong></td>';
				  //temp+='<td rowspan="2" style="border:1px solid #000;><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 10px;">ឈ្មោះបេឡាទទួលប្រាក់<div class="tab_row fonteng">Cashier Name</div></strong></td>';
			  
			  temp+='</tr>';
			  
			  temp+='<tr style=" font-size:11px; text-align:center;">';
				  temp+='<td style="border:1px solid #000;><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 11px;">ថ្ងៃចាប់ផ្តើម <div class="tab_row fonteng">Start Date</div></strong></td>';
				  temp+='<td style="border:1px solid #000;><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 11px;">ថ្ងៃបញ្ចប់ <div class="tab_row fonteng">End Date</div></strong></td>';
				  temp+='<td style="border:1px solid #000;><strong style="font-family: Khmer OS Battambang;color:#000;font-size: 11px;">រយះពេល <div class="tab_row fonteng">Duration</div></strong></td>';
			  
			  temp+='</tr>';
		
		
				
			  temp+='<tr style="font-size:12px !important;height: 20px;border:1px solid #000; ">';
				  temp+='<td align="center" style="border:1px solid #000;">1</td>';
				  temp+='<td style="border:1px solid #000;">&nbsp;&nbsp;'+"ថ្លៃសិក្សា("+dijit.byId('grade').attr('displayedValue')+")"+'</td>';
				  
			
			///////////////////    format date 	//////////////////////// 
			
				  var b = new Date(dijit.byId("start_date").get('value'));
					mm = b.getMonth()+1;
					var dd = b.getDate();
					if(dd<10){
						dd = "0"+dd;
					}
					var mon = getMonthByNumber(mm);
					if(mm<10){
						mm = "0"+mm;
					}
					var y = b.getFullYear();
					var start_date = dd + '-' + mon + '-' + y ;
					
				  temp+='<td align="center" style="border:1px solid #000;"> '+start_date+'</td>';

					var a = new Date(dijit.byId("end_date").get('value'));
					mm = a.getMonth()+1;
					var dd = a.getDate();
					if(dd<10){
						dd = "0"+dd;
					}
					var months = getMonthByNumber(mm);
					if(mm<10){
						mm = "0"+mm;
					}
					var y = a.getFullYear();
					var epx_date = dd + '-' +months + '-' + y ;
					
				  //temp+='<td align="center" style="border:1px solid #000;"> ' + start_date + ' </td>';
				  temp+='<td align="center" style="border:1px solid #000;"> ' + epx_date + ' </td>';
				  
				  
				  payment_term_id = dijit.byId('payment_term').get('value');
				  if(payment_term_id!=5){
					  tuition_fee = dijit.byId('tuitionfee').get('value');
					  payment_term = "1 "+dijit.byId('payment_term').attr('displayedValue');
				  }else{
					 
					  tuition_fee = dijit.byId('tuitionfee').get('value') * dijit.byId('amount_section').get('value');
					  payment_term = dijit.byId('amount_section').get('value') + ' ' +  dijit.byId('payment_term').attr('displayedValue');
				  
				  }
				  
				  
				  temp+='<td align="center" style="border:1px solid #000;">'+ payment_term +'</td>';
				  
				  temp+='<td align="center" style="border:1px solid #000;">$ '+tuition_fee+'</td>';
				  
				  temp+='<td align="center" style="border:1px solid #000;">'+dijit.byId('discount').get('value')+' %</td>';
				  temp+='<td align="center" style="border:1px solid #000;">$ '+dijit.byId('total').get('value')+'</td>';
				  temp+='<td align="center" style="border:1px solid #000;">'+dijit.byId('not').get('value')+'</td>';
			  temp+='</tr>';
			
			
		i=2;
		if(dijit.byId('buy_product').checked){
			
		<?php ?>
			
			for(var n = 0; n < rowIDArray.length; n++) {
				 
			  temp+='<tr style=" font-size:12px !important;height: 20px;"​ align="center">';
			  temp+='<td align="center" style="border:1px solid #000;">'+i+'</td>';
			  temp+='<td align="left" style="border:1px solid #000;max-width:200px !important;line-height:18px;">&nbsp;&nbsp;'+dijit.byId("product_"+rowIDArray[n]).attr('displayedValue')+'</td>'; 
		
			  temp+='<td style="border:1px solid #000;"> </td>';
			  temp+='<td align="center" style="border:1px solid #000;"> </td>';
			  temp+='<td align="center" style="border:1px solid #000;"> </td>';
			  
			  temp+='<td style="border:1px solid #000;">$ '+dijit.byId("price_"+rowIDArray[n]).get('value')+'</td>';
			 
			  temp+='<td style="border:1px solid #000;">'+dijit.byId("discount_"+rowIDArray[n]).get('value')+' %</td>';
			  temp+='<td style="border:1px solid #000;">$ '+dijit.byId("subtotal_"+rowIDArray[n]).get('value')+'</td>';
			   temp+='<td style="border:1px solid #000;">'+dijit.byId("remark"+rowIDArray[n]).get('value')+'</td>';
			  i++;
			  temp+='</tr>';
			}
		} 
		
		//alert(i);
		
		for(i;i<=5;i++){
			//alert(i);
			temp+='<tr style=" font-size:12px !important;height: 20px;"​ align="center"><td align="center" style="border:1px solid #000;">'+i+'</td>';
			  temp+='<td align="left" style="border:1px solid #000;max-width:200px !important;line-height:18px;">&nbsp;&nbsp;</td>'; 
		
			  temp+='<td style="border:1px solid #000;"> </td>';
			  temp+='<td align="center" style="border:1px solid #000;"> </td>';
			  temp+='<td align="center" style="border:1px solid #000;"> </td>';
			  
			  temp+='<td style="border:1px solid #000;"></td>';
			 
			  temp+='<td style="border:1px solid #000;"></td>';
			  temp+='<td style="border:1px solid #000;"></td>';
			   temp+='<td style="border:1px solid #000;"></td>';
			  //i++;
			temp+='</tr>';
		}
		
		temp+='<tr style=" font-size:12px !important;height: 20px;"​ align="center">';
			
			temp+='<td colspan="7" align="center" style="border:1px solid #000;">ទឹកប្រាក់សរុប/Total Amount</td>';
			temp+='<td style="border:1px solid #000;">'+'$ '+dijit.byId("grand_total").get('value')+'</td>';
			temp+='<td style="border:1px solid #000;"><?php //echo date('l , jS / m / Y , H:i:s ',strtotime(Zend_Date::now()));?></td>';

  	    temp+='</tr>';
		
	<?php ?>	
		
		temp+='</table>';
		
		dojo.byId('t_amountmoneytype').innerHTML = temp;
		 
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////		 
		 
		 
		 
		dijit.byId("terms").show();	
	}
	
}
</script>
<div class="dijitHidden" style="width: 23cm !important; height: 11cm ; padding: 0px; margin: 0px;">
<?php $keycode = $this->keycode;?>
	<div data-dojo-type="dijit.Dialog" style="width:24cm;" align="center" data-dojo-props="title:'<?php echo $tr->translate("");?>'" id="terms" >
		
		<div id="divPrint" style="width: 23cm !important; height: 12cm ; padding: 0px; margin: 0px;">
			<style>
				.fontbig{
					font-size: 15px;	
				}
				.fonttel{
					font-size: 18px;	
				}
				.pleft{
					width: 110px;	
				}
				.label{ font-weight: bold;font-size: 22px;}
				.value{ font:bold 12px 'Khmer OS Battambang';border: 1px solid rgba(14, 0, 107, 1); height: 25px; padding: 0 2px;width: 98%; display: block;
						margin-top: -25px; line-height: 25px;
					    text-align: center;
						}
				.values{ border: 1px solid rgba(14, 0, 107, 1);; height: 25px; padding: 0 10px;display: block;
						line-height: 25px;}
				.h{ margin-top: -8px;/*margin-left:4px;*/}
​​               .print td{ font:bold 12px 'Khmer OS Battambang';}
			   .khmerbold{font:bold 12px 'Khmer OS Battambang';}
			   .khmer{font:12px 'Khmer OS Battambang';}
			   .one{white-space:nowrap;}
			   
				.underline{margin-top: -18px;text-align:center;}
				.data{font-size:13px;font-weight:bold;}
				.receiptno{font-size:15px;font-weight:bold;}
				.tab_row{ margin-top: -8px;}
				.fonteng{font-size:12px;}
				
			</style>	
			<table border="0"  class="print" cellspacing="0"  cellpadding="0" style="white-space: nowrap;font-size:12px;font-family:'Khmer OS Battambang';line-height: 21px;">
				<tr>
				    <td colspan="10"  align="center" style="">
						<table width="100%" style="white-space:nowrap; font-family:Khmer OS Battambang;margin-top:-10px;font-weight:bold;">
							<tr>
								<td width="25%" align="center" style="font-size:11px;"><?php echo date('l , jS / m / Y , H:i:s ',strtotime(Zend_Date::now()));?></td>
								<td width="50%" align="center" style="font-size:16px;">បង្កាន់ដៃទទួលប្រាក់ RECEIPT</td>
								<td width="25%" align="center" style="font-size:17px;color:red;">N<sup>o</sup> : <label id="lb_receipt_no" class="receiptno" ></label></td>
							</tr>
						</table>
						
				    </td>
				</tr>
				
				<tr>
					<td width="15%"></td>
					<td width="10%"></td>
					<td width="5%"></td>
					<td width="10%"></td>
					<td width="10%"></td>
					<td width="10%"></td>
					<td width="10%"></td>
					<td width="10%"></td>
					<td width="10%"></td>
					<td width="10%"></td>
				</tr>
				
				<tr>
					<td>ឈ្មោះភាសាខ្មែរ/Name in Khmer</td>
					<td colspan="3" >
						&nbsp;:&nbsp; <label id="lb_kh_name"  class="data" ></label>
						<div class="underline">............................................................</div>
					</td>
					<td> អក្សរឡាតាំង/Latin&nbsp;</td>
					<td colspan="3">
						:&nbsp; <label id="lb_en_name" class="data" ></label>
						<div class="underline">.........................................................</div>
					</td>
					<td align="center">ភេទ/Sex</td>
					<td >
						&nbsp;:&nbsp; <label id="lb_sex" class="data" ></label>
						<div class="underline">.............................</div>
					</td>
				</tr>
				
				<tr>
					<td>ថ្ងៃខែឆ្នាំកំណើត/Date of Birth</td>
					<td>
						&nbsp;:&nbsp; <label id="lb_dob" class="data" ></label>
						<div class="underline">......................</div>
					</td>
					<td align="center">&nbsp;អត្តលេខ/ID&nbsp;</td>
					<td>
						:&nbsp; <label id="lb_stu_id" class="data" ></label>
						<div class="underline">...................</div>
					</td>
					<td align="center">កម្រិត/Level</td>
					<td>
						:&nbsp; <label id="lb_grade" class="data" ></label>
						<div class="underline">...................</div>
					</td>
					<td align="center"> &nbsp;បន្ទប់/Room&nbsp; </td>
					<td>
						:&nbsp; <label id="lb_room" class="data" ></label>
						<div class="underline">..................</div>
					</td>
					<td align="center"> &nbsp;ម៉ោងសិក្សា/Time&nbsp; </td>
					<td>
						&nbsp;:&nbsp; <label id="lb_hour" class="data" ></label>
						<div class="underline">..............................</div>
					</td>
				</tr>
				
				<tr>
					<td>អាសយដ្ឋាន/Address</td>
					<td colspan="9">
						&nbsp;:&nbsp; <label id="lb_address" class="data" ></label>
						<div class="underline">.............................................................................................................................................................................................................</div>
					</td>
				</tr>
				<tr>
					<td>លេខទូរស័ព្ទ/Phone Number</td>
					<td colspan="9">
						&nbsp;:&nbsp; <label id="lb_phone" class="data" ></label>
						<div class="underline">.............................................................................................................................................................................................................</div>
					</td>
				</tr>
				
				<tr>
					<td colspan="10">
						<div id="t_amountmoneytype"></div>
					</td>
				</tr>
				
				<tr>
					<td colspan="10">
						<table width="100%" style="white-space:nowrap; font-size:12px;font-family:Khmer OS Muol;font-weight:bold;">
							<tr>
								<td width="25%" align="center">អគ្គនាយក/Director General</td>
								<td width="25%" align="center">អ្នកបង់ប្រាក់/Payer</td>
								<td width="25%" align="center">បេឡា/Cashier</td>
								<td width="25%" align="center">អ្នកផ្តល់ព័ត៌មាន​/Receiptionist</td>
							</tr>
							
							
							<tr>
								<td colspan="4" align="center">&nbsp;</td>
							</tr>
							<tr>
								<td align="center" style="font-size:12px;">ឯកឧត្តម ស៊ី លាង</td>
								<td align="center"></td>
								<td align="center">
									<div style=" font-size: 12px;"> 
										<?php 
										   $session_user=new Zend_Session_Namespace('auth');
										   $last_name=$session_user->last_name;
										   $username = $session_user->first_name;
										   echo $last_name." ".$username;
										?>
									</div>
								</td>
								<td align="center"></td>
							</tr>
						</table>
					</td>
				</tr>	
				<tr>
					<td colspan="10" >
						<table width="100%" style="margin-top:5px; font-family:Khmer OS Battambang; font-size:10px;white-space:nowrap;">
							<tr>
								<td width="3%" valign="top" style="font-family:Khmer OS Muol;">បញ្ជាក់ៈ</td>
								<td width="53%">
									&nbsp; ប្រាក់ដែលបង់ហើយមិនអាចដកវិញបានឡើយ។ <span style="font-weight:bold;">Notice:</span> Your payment is non-returnable.<br />
								</td>
								<td width="7%" valign="top">លេខទូរស័ព្ទ/Tel:</td>
								<td width="37%">
									- 010 277 869 (ការិយាល័យផ្តល់ព័ត៌មាន/Information Office)<br />
								</td>
							</tr>
							
							<tr>
								<td></td>
								<td>
									- រាល់ការបង់ប្រាក់ត្រូវមានបង្កាន់ដៃទទួលប្រាក់ និងហត្ថលេខារបស់អគ្គនាយក ទើបយើងខ្ញុំទទួលខុសត្រូវ<br />
								</td>
								<td></td>
								<td>
									- 077 211 546 (ការិយាល័យសិក្សាផ្នែកខ្មែរ/Khmer academic office)<br />
								</td>
							</tr>
							
							<tr>
								<td></td>
								<td>
									&nbsp; We are responsible for all paymentwith receipt and signature from Director General only.<br />
								</td>
								<td></td>
								<td>
									- 088 700 6789 (ការិយាល័យសិក្សាផ្នែកអង់គ្លេស/English academic office)
								</td>
							</tr>
							
							<tr>
								<td></td>
								<td colspan="3">
									- តម្លៃសិក្សាខាងលើ សម្រាប់តែសេវាអប់រំតែប៉ុណ្ណោះ/  This fee is for education service only.<br />
								</td>
							</tr>
							
							<tr>
								<td></td>
								<td colspan="3">
									- មតិអាណាព្យាបាល សូមទំនាក់ទំនងតាមលេខទូរស័ព្ទ/  Parent/Guadians comment Please call : 016 59 9999 / 097 55 66666 / 097 88 66666
								</td>
							</tr>
							
						</table>
					</td>
				</tr>
							
			</table>
		</div>
		
		<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>	
		<button dojoType="dijit.form.Button" label="Cancel" iconClass="dijitEditorIcon dijitEditorIconCancel"
			showLabel="true" type="button" onclick="hideDialog();">Cancel</button>
		<button dojoType="dijit.form.Button" label="Print" showLabel="true" iconClass="dijitEditorIcon dijitEditorIconPrint"
			 type="button" onclick="printSubmit();">Print</button>
	</div>
</div>

<script>
//set hour defuale
function setHourDefault(){
	dept=dijit.byId('dept').get('value');
	session=dijit.byId('session').get('value');
	if(dept==1 && session==1){
		dijit.byId('study_hour').attr('value','7:30AM - 10:50AM');
	}else if(dept==1 && session==2){
		dijit.byId('study_hour').attr('value','1:30PM - 4:50PM');
	}else if(session==1){
		dijit.byId('study_hour').attr('value','7:00AM - 11:00AM');
	}else if(session==2){
		dijit.byId('study_hour').attr('value','1:00PM - 5:00PM');
	}else if(session==5){
		dijit.byId('study_hour').attr('value','7:30AM - 4:30PM');
	}else{
		dijit.byId('study_hour').attr('value','');
	}
}
//save daata when sub button print 
function printSubmit(){
	
	//$('#office_receipt').submit();
	 
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    //dijit.byId("terms").hide();	//hideDialog();
}
function hideDialog(){
	dijit.byId('terms').hide();
}

function changControll(){
	student_type=dijit.byId('student_type').get('value');
	 if(student_type==3){
		 document.getElementById('student_old').style.display="block";
		 document.getElementById('student_old_name').style.display="block";
		 document.getElementById('id_stu').style.display="none";
		 document.getElementById('name_stu').style.display="none";
		 clearControll();
	}else{
		 document.getElementById('student_old').style.display="none";
		 document.getElementById('student_old_name').style.display="none";
		 document.getElementById('id_stu').style.display="block";
		 document.getElementById('name_stu').style.display="block";
		 clearControll();
	} 
}

function setID(){
	stu_id = dijit.byId('old_stu_name').get('value');
	//alert(stu_id);
	dijit.byId('old_studens').attr('value',stu_id);
}

//
function clearControll(){
	dijit.byId('kh_name').attr('value','');
	dijit.byId('en_name').attr('value','');
}
///get Gerneral old student
function getGeneralOldStudentById(){
	var url_getalldstudent = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-general-old-student')); ?>';
	student_id=dijit.byId('old_studens').get('value');
	dijit.byId('kh_name').attr('value','');
	dijit.byId('en_name').attr('value','');
	dijit.byId('sex').attr('value','');
	dijit.byId('dept').attr('value','');
	dijit.byId('grade').attr('value','');
	
	dijit.byId('old_stu_name').attr('value',student_id);
		dojo.xhrPost({
			url:url_getalldstudent,
			content:{
				'student_id':student_id,
				},
			handleAs:"json",
			load: function(data) {
				   if(data){
					   //alert(data.room);
			    	dijit.byId('kh_name').attr('value',data.stu_khname);
			    	dijit.byId('en_name').attr('value',data.stu_enname);
			    	dijit.byId('sex').attr('value',data.sex);
					dijit.byId('study_year').attr('value',data.academic_year);
					
					if(data.room!=null){
						dijit.byId('room').attr('value',data.room);
			    	}else{
						dijit.byId('room').attr('value',-1);
					}
					
					dijit.byId('dept').attr('value',data.degree);
					
					dijit.byId('old_stu_code').attr('value',data.stu_code);
					dijit.byId('old_degree').attr('value',data.degree);
					dijit.byId('old_grade').attr('value',data.grade);
					
			    	dijit.byId('session').attr('value',data.session);
					dijit.byId('dob').attr('value',data.dob);
					dijit.byId('address').attr('value',data.address);
					dijit.byId('phone').attr('value',data.tel);
			    	getallModel(data.degree,data.grade);
			    	
			    	 //dijit.byId('grade').attr('value',data.grade);
			      }else {
			    	
			      } 
			},
			error: function(err) {
				//alert(err);
			}
		});
}
		
var url_getproductprice = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-product-price')); ?>';
function getProductPrice(index){
	
	product = dijit.byId('product_'+index).get('value');
	qty = dijit.byId('qty_'+index).get('value');
	discount = dijit.byId('discount_'+index).get('value');
	
	dojo.xhrPost({
		url:url_getproductprice,
		content:{
			'product':product,
			},
		handleAs:"json",
		load: function(data) {
			if(data){
				//alert(data);
				
				fee_discount = data * qty * (discount/100);
				//alert(fee_discount);
				
				dijit.byId('price_'+index).attr('value',data);
				dijit.byId('subtotal_'+index).attr('value',(data * qty) - fee_discount);
				
				netTotal();
			}
		},
		error: function(err) {
			//alert(err);
		}
	});
}

function calculateTotal(index){
	price = dijit.byId('price_'+index).get('value');
	qty = dijit.byId('qty_'+index).get('value');
	qty=isNaN(qty)?1:qty;
	//if(qty==1){dijit.byId('qty_'+index).attr('value',qty);}
	total = price*qty;
	discount = dijit.byId('discount_'+index).get('value');
	discount = isNaN(discount)?0:discount;
	dijit.byId('subtotal_'+index).attr('value',total-(total*(discount/100)));
	netTotal();
}

function netTotal() {
	// alert(1);
		var netTotal=0;
		var netPaidAmount=0;
		var rowId = $('#identity').val();
		var rowIDArray = rowId.split(',');
		//alert(rowIDArray);
		
		tuition_fee = dijit.byId('tuitionfee').get('value');
		paid_amount = dijit.byId('books').get('value');
		total_payment = dijit.byId('total').get('value');
		
		if(document.getElementById('buy_product').checked){
			for(var n = 0; n < rowIDArray.length; n++) {
				//netTotal += Number($('#subtotal_'+rowIDArray[n]).val());
				netTotal += dijit.byId('subtotal_'+rowIDArray[n]).get('value');
				netPaidAmount += dijit.byId('subtotal_'+rowIDArray[n]).get('value');
			}
		}
		
		grand_total_payment = parseFloat(netTotal) + parseFloat(total_payment) ;
		grand_total_paid = parseFloat(netPaidAmount) + parseFloat(paid_amount) ;
				
		ex_rate = dijit.byId('ex_rate').get('value');
		
		dijit.byId('grand_total').attr('value',grand_total_payment);
		dijit.byId('convert_to_riels').attr('value',grand_total_payment * ex_rate);
		dijit.byId('total_received').attr('value',grand_total_paid);
		
		dijit.byId('total_balance').attr('value',grand_total_payment - grand_total_paid);
		
		//calculatBalanceAndReturn();
}

function displayNoneAddRow(){
	
	if(document.getElementById('buy_product').checked){
		document.getElementById('table_row').style.display="block";
	}else{
		document.getElementById('table_row').style.display="none";
	}
	
}

function oldStudentChangeDegree(){
	
	student_type = dijit.byId('student_type').get('value');
	old_degree = dijit.byId('old_degree').get('value');
	degree = dijit.byId('dept').get('value');
	
	if(student_type==3 ){
		if(old_degree!=degree){
		 document.getElementById('student_old').style.display="none";
		 //document.getElementById('student_old_name').style.display="none";
		 document.getElementById('id_stu').style.display="block";
		 //document.getElementById('name_stu').style.display="block";
		 //clearControll();
		 }
		else{
			 document.getElementById('student_old').style.display="block";
			 //document.getElementById('student_old_name').style.display="block";
			 document.getElementById('id_stu').style.display="none";
			 //document.getElementById('name_stu').style.display="none";
		} 
	}
	
}


</script>