<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('SRMS_WUREGISTER')); 
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>	
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require('dojox.form.BusyButton');
	dojo.require("dojo.NodeList-manipulate");
	var dept_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->all_dept));?> );
	dojo.ready(function(){
		
		changControll();
		Initialize();
		displayAmountSection();
		
		new dijit.form.FilteringSelect({
			store: dept_store,
			autoComplete: true,                        
			required: true,
			id: "dept",
			name: "dept",           
			class: 'fullside',  
			placeHolder:"Selected Class",          
			onChange: function() {  
				dept_id = dijit.byId('dept').get('value');
				dijit.byId('grade').attr('value','');
				getallModel(dept_id,a=''); 
				setHourDefaul();
				//getStudentNo(dept_id);
			}
		}, "dept");
		new dijit.form.FilteringSelect({
			//store: dept_store,
			autoComplete: true,                        
			id: "grade",
			name: "grade",           
			class: 'fullside', 
			placeHolder:"Selected Grade",          
			onChange: function() {  
				//make_id = dijit.byId('grade').get('value');
				paymentTerm();
			 
			}
		}, "grade");
		dijit.byId('dept').attr('value','<?php echo $this->degree_row['degree'];?>');
		
		setReadonlyPageEdit();
		
		
	});	
	
	
	var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_dept = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-grade')); ?>';
	function getallModel(dept_id,a){
			dojo.xhrPost({
				url:url_dept,
				content:{
					'dept_id':dept_id
					},
				handleAs:"json",
				load: function(data) {
					grade_store  = getDataStorefromJSON('id','name', data);
				    dijit.byId('grade').set('store',grade_store);  
				    dijit.byId('grade').attr('value','<?php echo $this->degree_row['grade']?>');
				    if(a!=""){
				    	dijit.byId('grade').attr('value',a);
			        } 
				},
				error: function(err) {
					//alert(err);
				}
			});
	}
	var url_getstuno = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-stu-no')); ?>';
	function getStudentNo(dept_id){
		if(dept_id==''){
			return false;
			}
		dojo.xhrPost({
				url:url_getstuno,
				content:{
					'dept_id':dept_id
					},
				handleAs:"json",
				load: function(data) {
					  dijit.byId('stu_id').attr('value',data);   

				},
				error: function(err) {
					alert(err);
				}
			});
	}
	function paymentTerm(){
		old_grade='<?php echo $this->degree_row['grade'];?>';
    	old_payterm='<?php echo $this->degree_row['payment_term'];?>';
    	grade=dijit.byId('grade').get('value');
    	payterm=dijit.byId('payment_term').get('value');
    	if(old_grade==grade && old_payterm==payterm){
    		defaultPayment();
	    }else{
	    	generat=dijit.byId('study_year').get('value');
			payment_term=dijit.byId('payment_term').get('value');
			grade=dijit.byId('grade').get('value');
			//time=dijit.byId('time').get('value');
			session=dijit.byId('session').get('value');
			if(generat!='' && payment_term !='' && grade !='' && session !=''){
				getPaymentTerms(generat,payment_term,grade,session);
			}
			dijit.byId('discount').attr('value','0');
	    	dijit.byId('books').attr('value','0');
	    	dijit.byId('addmin_fee').attr('value','0');
	    	dijit.byId('remaining').attr('value','0');
	    	dijit.byId('remark').attr('value','0');
	    //	dijit.byId('char_price').attr('value','0');
	    	dijit.byId('not').attr('value',''); 
		}
	}
	function paymentTerms(){
		generat=dijit.byId('study_year').get('value');
		payment_term=dijit.byId('payment_term').get('value');
		grade=dijit.byId('grade').get('value');
		//time=dijit.byId('time').get('value');
		session=dijit.byId('session').get('value');
		if(generat!='' && payment_term !='' && grade !='' && session !=''){
			getPaymentTerms(generat,payment_term,grade,session);
		}
	}
	
	var payment_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_getpaymentterm = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-payment-term')); ?>';
	function getPaymentTerms(generat,pay,grade,session){
			dojo.xhrPost({
				url:url_getpaymentterm,
				content:{
					'generat_id':generat,
					'pay_id':pay,
					'grade_id':grade,
					//'time':time,
					'session':session
					},
				handleAs:"json",
				load: function(data) {
				      if(data){
				    	  dijit.byId('tuitionfee').attr('value',data.tuition_fee);
					      dijit.byId('total').attr('value',data.tuition_fee);
					      dijit.byId('books').attr('value',data.tuition_fee);
				      }else {
				    	
				      }
				 
				},
				error: function(err) {
					//alert(err);
				}
			});
	}
	
	function setReadonlyPageEdit(){
		dijit.byId("student_type").set('readOnly',true);
		dijit.byId("old_stu_name").set('readOnly',true);
		dijit.byId("old_studens").set('readOnly',true);
		dijit.byId("en_name").set('readOnly',true);
		dijit.byId("kh_name").set('readOnly',true);
		dijit.byId("sex").set('readOnly',true);
		dijit.byId("dob").set('readOnly',true);
		dijit.byId("phone").set('readOnly',true);
		dijit.byId("address").set('readOnly',true);
		dijit.byId("study_year").set('readOnly',true);
		dijit.byId("room").set('readOnly',true);
		dijit.byId("dept").set('readOnly',true);
		dijit.byId("grade").set('readOnly',true);
		dijit.byId("tuitionfee").set('readOnly',true);
		dijit.byId("session").set('readOnly',true);
		dijit.byId("study_hour").set('readOnly',true);
		dijit.byId("payment_term").set('readOnly',true);
		dijit.byId("discount").set('readOnly',true);
		dijit.byId("remark").set('readOnly',true);
		dijit.byId("addmin_fee").set('readOnly',true);
		dijit.byId("books").set('readOnly',true);
		dijit.byId("not").set('readOnly',true);
		dijit.byId("start_date").set('readOnly',true);
		dijit.byId("end_date").set('readOnly',true);
		dijit.byId("remaining").set('readOnly',true);
		
	}
	
	function defaultPayment(){
		
		dijit.byId('tuitionfee').attr('value','<?php echo $this->degree_row['tuition_fee'];?>');
    	dijit.byId('total').attr('value','<?php echo $this->degree_row['total'];?>');
    	dijit.byId('discount').attr('value','<?php echo $this->degree_row['discount_percent'];?>');
    	dijit.byId('books').attr('value','<?php echo $this->degree_row['paid_amount'];?>');
    	dijit.byId('addmin_fee').attr('value','<?php echo $this->degree_row['admin_fee'];?>');
    	dijit.byId('remaining').attr('value','<?php echo $this->degree_row['balance_due'];?>');
    	dijit.byId('remark').attr('value','<?php echo $this->degree_row['other_fee'];?>');
    	dijit.byId('not').attr('value','<?php echo $this->degree_row['note'];?>');
    	dijit.byId('study_hour').attr('value','<?php echo $this->degree_row['time'];?>');
		dijit.byId('price_per_section').attr('value','<?php echo $this->degree_row['price_per_sec'];?>');
		
		netTotal();
	}
	
	function netTotal() {
		var netTotal=0;
		var netPaidAmount=0;
		var rowId = $('#identity').val();
		var rowIDArray = rowId.split(',');
		
		tuition_fee = dijit.byId('tuitionfee').get('value');
		paid_amount = dijit.byId('books').get('value');
		total_payment = dijit.byId('total').get('value');
		
		if(document.getElementById('buy_product').checked){
			for(var n = 0; n < rowIDArray.length; n++) {
				netTotal += dijit.byId('subtotal_'+rowIDArray[n]).get('value');
				netPaidAmount += dijit.byId('subtotal_'+rowIDArray[n]).get('value');
			}
		}
		
		grand_total_payment = parseFloat(netTotal) + parseFloat(total_payment) ;
		grand_total_paid = parseFloat(netPaidAmount) + parseFloat(paid_amount) ;
				
		ex_rate = dijit.byId('ex_rate').get('value');
		
		dijit.byId('grand_total').attr('value',grand_total_payment);
		dijit.byId('convert_to_riels').attr('value',grand_total_payment * ex_rate);
		dijit.byId('total_received').attr('value',grand_total_paid);
		
		dijit.byId('total_balance').attr('value',grand_total_payment - grand_total_paid);
		
		//calculatBalanceAndReturn();
	}
	
	//get price balance 
	function getBalanceOldStudent(){
		old_studens=old_studens=dijit.byId('old_studens').get('value');
		if(old_studens != -1){
			//alert(old_studens);
			getBalancePrice(1,old_studens);
		}
	}
	//get price balance
	var url_balance = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-banlance-price')); ?>';
	function getBalancePrice(servce_id,student_id){
			dojo.xhrPost({
				url:url_balance,
				content:{
					'servce_id':servce_id,
					'student_id':student_id,
					},
				handleAs:"json",
				load: function(data) {
					 
				      if(data){
				    	  dijit.byId('tuitionfee').attr('value',data.price_fee);
				    	  dijit.byId('ids').attr('value',data.id);
				     	  dijit.byId('total').attr('value',data.price_fee);
				    	  dijit.byId('books').attr('value',data.price_fee);
				    	  dijit.byId('not').attr('value',data.sms);
				    	  dijit.byId('remaining').attr('value','0');
				     }else {
				    	 dijit.byId('ids').attr('value','');
				    	 dijit.byId('not').attr('value','');
				    	 paymentTerms();
				 
				      }
				},
				error: function(err) {
					alert(err);
				}
			});
	}
	//set value totale 
	function getTotale(){
		//old % totale
		tuitionfee=dijit.byId('tuitionfee').get('value');
		tuitionfee=isNaN(tuitionfee)?0:tuitionfee;
		discount=dijit.byId('discount').get('value');
		pc=discount/100;
		ds=tuitionfee*pc;
		old_totale=tuitionfee - ds;
		//alert('hello');
		remark=dijit.byId('remark').get('value');
		remark=isNaN(remark)?0:remark;
		addmin_fee=dijit.byId('addmin_fee').get('value');
		addmin_fee=isNaN(addmin_fee)?0:addmin_fee;
		totals=parseFloat(old_totale)+parseFloat(remark)+parseFloat(addmin_fee);
		  dijit.byId('total').attr('value',totals.toFixed(2));
		  dijit.byId('books').attr('value',totals.toFixed(2));
		  getRemaining();
	}
	//set value remaining
	function getRemaining(){
		  total=dijit.byId('total').get('value');
		  total=isNaN(total)?0:total;
		  books=dijit.byId('books').get('value');
		  books=isNaN(books)?0:books;
		  remaining=parseFloat(total) - parseFloat(books);
		  if(total<books){
			 alert('Deposit must be smaller than the total money!');
			 dijit.byId('books').attr('value',total);
			 dijit.byId('remaining').attr('value','0');
		  }else{
		     dijit.byId('remaining').attr('value',remaining.toFixed(2));
		  }
		  CheckAmount();
	}
	function getDisccount(){
		books=dijit.byId('books').get('value');
		books=isNaN(books)?0:books;
	
		tuitionfee=dijit.byId('tuitionfee').get('value');
		tuitionfee=isNaN(tuitionfee)?0:tuitionfee;
		discount=dijit.byId('discount').get('value');
		pc=discount/100;
		ds=tuitionfee*pc;
		totale=tuitionfee - ds;
		if(discount<=100){
			   dijit.byId('total').attr('value',totale.toFixed(2));
			//   dijit.byId('remaining').attr('value','0');
			}else{ 
				alert('No more than a hundred of disccount!');
				dijit.byId('discount').attr('value','100');
				//getTotale();
			  //  dijit.byId('remaining').attr('value','0');
			}
	}
	
	
	var url_getstu_info = '<?php echo $this->url(array('module'=>'global','controller'=>'globals','action'=>'get-studentinfo')); ?>';
	function getStudentBYId(){
		   student_id = dijit.byId("stu_id").get('value');
		   if(student_id==''){
			   return false;
			   }
				dojo.xhrPost({
				   content : {'student_card':  student_id},
				    url: url_getstu_info,			    
					handleAs:"json",
				    load: function(response) {	
					    dijit.byId("kh_name").attr('value',response.stu_khname);
					    dijit.byId("en_name").attr('value',response.stu_enname);
					    dijit.byId('sex').set('value', response.sex);
					    dijit.byId("phone").attr('value',response.phone);
					    dijit.byId("metion").attr('value',response.mention);
					    dijit.byId('year').attr('value',response.year);
					    dijit.byId('degree').set('value', response.degree);
					    dijit.byId('batch').set('value',response.batch);
					    dijit.byId('dept').set('value',response.faculty_id);
					    dijit.byId('session').set('value',response.session);
				    },
				    error: function(e) {
					    alert(e);
				    }
				});
	}
	
	
	//calculator date by select term_payment
	function getDateTerm() {
		payment_term=dijit.byId('payment_term').get('value');
		start_date=dijit.byId('start_date').get('value');
		var a = new Date(start_date);
		if(payment_term==2){
			//mm = a.getMonth()+2+1;
			a.setDate(a.getDate() + (75)); 
			var mm = a.getMonth() + 1;
		}else if(payment_term==3){
			mm = a.getMonth()+5+1;
		}else if(payment_term==4){
			mm = a.getMonth()+10+1;
		}
		var dd = a.getDate();
		 if(dd<10){
			 dd = "0"+dd;
		}
		 if(mm<10){
			 mm = "0"+mm;
		}
		var y = a.getFullYear();
		var epx_date = y + '-'+ mm + '-'+dd ;
		dijit.byId('end_date').attr('value',epx_date);	
	}
	
</script>
<style>
select{ width:100%;}
fieldset{  background:none;}
.red{ color: red; padding-left:5px;}
</style>
<?php $register = $this->frm_register;?>
<form id='office_receipt' action="<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">   
   if(this.validate()) {
    year = dijit.byId('study_year').get('value');
    if(year==-1){
         dijit.byId("study_year").focus();
         return false;
    }
    return true;
   }else {
    return false;
   }
</script>
<table  cellspacing="10" style="margin: 0 auto; width: 100%;">
		<tr>
			<td>
			<fieldset>
				<legend align="center"><strong><?php echo $tr->translate("OFFICIAL_RECEIPT");?></strong></legend>
				<table style="margin: 0 auto; width: 100%;padding: 0px 10px 10px 10px;" cellspacing="5" >
					
					<tr>
						<td>
							<input type="checkbox" value="1" <?php if($this->degree_row['buy_product']==1){echo "checked";}?> onclick="return false;" name="buy_product" id="buy_product" dojoType="dijit.form.CheckBox"  /> Buy Product
						</td>
					</tr>
					
					<tr>
						<td colspan="4"​ style="border-bottom:1px solid #ccc;"><strong><?php echo $tr->translate("STUDENT_INFO");?></strong></td>
					</tr>
					
					<tr>
						<td style="width: 160px"><?php echo $tr->translate("STUDENT_TYPE");?></td>
						<td><?php  echo $register->getElement('student_type');?>
							<?php echo $register->getElement('ids'); ?>
						</td>
						
						<td><?php echo $tr->translate("RECEIPT_NO");?></td>
						<td><?php echo $register->getElement('reciept_no');?>
							<?php echo $register->getElement('id');?><?php echo $register->getElement('parent_id');?>
						</td>
						
						
					</tr>
					<tr>
						<td><?php echo $tr->translate("STUDENT_ID");?></td>
						<td><div id="student_old"><?php echo $register->getElement('old_studens');?></div><div id="id_stu"><?php echo $register->getElement('stu_id');?></div></td>
						
						<td style="width: 160px"><?php echo $tr->translate("STUDENT_NAME");?></td>
						<td>
							<div id="student_old_name"><?php echo $register->getElement('old_stu_name');?></div>
							<div id="name_stu"><?php echo $register->getElement('stu_name');?></div>
							<?php //echo $register->getElement('old_stu_name'); ?>
							<?php //$register->getElement('stu_name');?>
						</td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("NAME_EN");?></td>
						<td><?php echo $register->getElement('en_name');?></td>
						<td><?php echo $tr->translate("NAME_KH");?></td>
						<td><?php echo $register->getElement('kh_name');?></td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("SEX");?></td>
						<td><?php echo $register->getElement('sex');?></td>
						
						<td><?php echo $tr->translate("DOB");?></td>
					<td><input type="text"  class="fullside" name="dob" id="dob" value="<?php echo $this->degree_row['dob'];?>" constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" /></td>
					</tr>
					
					<tr>
						<td><?php echo $tr->translate("ADDRESS");?></td>
						<td><input type="text"  class="fullside" name="address" id="address" value="<?php echo $this->degree_row['address'];?>" dojoType="dijit.form.TextBox" /></td>
						
						<td><?php echo $tr->translate("PHONE");?></td>
						<td><input type="text" name="phone" id="phone" value="<?php echo $this->degree_row['tel'];?>" class="fullside" dojoType="dijit.form.TextBox" /></td>
					</tr>
					
					<tr>
						<td colspan="4"​ style="border-bottom:1px solid #ccc;"><strong><?php echo $tr->translate("STUDY_INFO");?></strong></td>
					</tr>
					
					<tr>
						<td style="width: 160px"><?php echo $tr->translate("YEARS");?></td>
						<td><?php echo $register->getElement('study_year');?></td>
						
						<td><?php echo $tr->translate("ROOM_NAME");?><label class="red">*</label></td>
						<td>
							<select name="room" id="room" dojoType="dijit.form.FilteringSelect" class="fullside" >
								<option value="-1">----- select room -----</option>
								<?php if(!empty($this->room)){foreach ($this->room as $room){?>
									<option value="<?php echo $room['id']?>" <?php if($room['id']==$this->degree_row['room_id']){echo "selected='selected'";}?>><?php echo $room['name']?></option>
								<?php }}?>
							</select>
						</td>
					</tr>
					
					<tr>
						<td><?php echo $tr->translate("DEGREE");?><label class="red">*</label></td>
						<td><input id="dept" /><?php //echo $register->getElement('dept');?></td>
						<td><?php echo $tr->translate("CLASS");?><label class="red">*</label></td>
						<td><input id="grade" /><?php //echo $register->getElement('metion');?></td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("SESSION");?></td>
						<td><?php echo $register->getElement('session');?></td>
						<td style="white-space: nowrap;"><?php echo $tr->translate("TIME");?></td>
						<td>
							<input dojoType="dijit.form.TextBox"  class="fullside" id="study_hour" name="study_hour"  type="text">
						<!--  <select dojoType="dijit.form.FilteringSelect" required="true" class="fullside"  id="time" name="time" type="text" onchange="paymentTerm()">								
									<option value="2"  <?php //if($this->degree_row['time']== 2)  { echo ' selected="selected"'; } ?> ><?php //echo $tr->translate("FULL_TIME");?></option>
									<option value="1" <?php //if($this->degree_row['time']== 1) { echo ' selected="selected"'; } ?> ><?php //echo $tr->translate("PART_TIME");?></option>
							</select>
						-->	
						</td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("PAYMENT_TERM");?><label class="red">*</label></td>
						<td><?php echo $register->getElement('payment_term');?></td>
						<td><?php echo $tr->translate("TUITION_FEE");?></td>
						<td><?php echo $register->getElement('tuitionfee');?></td>
					</tr>
					
					<input type="hidden" name="price_per_section" id="price_per_section" value="<?php echo $this->degree_row['price_per_sec'];?>" dojoType="dijit.form.TextBox" >
					<tr>
						<td>
							<div id="label_amount">
								<?php echo $tr->translate("AMOUNT_SECTION");?>
							</div>
						</td>
						<td>
							<div id="amount_section">
								<input name="amount_section" id="amount_section" onkeyup="getTotale();" dojoType="dijit.form.TextBox" value="<?php if(!empty($this->degree_row['amount_sec'])){echo $this->degree_row['amount_sec'];}else{echo 1;}?>" class="fullside" type="text"/>
							</div>
						</td>
					</tr>
					
					<tr>
						<td colspan="4"​ style="border-bottom:1px solid #ccc;"><strong><?php echo $tr->translate("PAYMENT_INFO");?></strong></td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("DISCOUND");?></td>
						<td title='Ex: 20 or 10%'><?php echo $register->getElement('discount');?></td>
						<td><?php echo $tr->translate("OTHERS_PRICE");?></td>
						<td><?php echo $register->getElement('remark');;?></td>
					</tr>
					<tr>	
						<td><?php echo $tr->translate("ADMIN_FEE");?></td>
						<td title='Ex: 20 or 10%'><?php echo $register->getElement('addmin_fee');?></td>	
						<td><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
						<td title='Ex: 20 or 10%'><?php echo $register->getElement('total');?></td>
					</tr>
					<tr>	
						<td><?php echo $tr->translate("PAID_AMOUNT");?></td>
						<td><?php echo $register->getElement('books');;?></td>
						<td><?php echo $tr->translate("BALANCE");?></td>
						<td><?php echo $register->getElement('remaining');;?></td>
					</tr>
					<tr>	
						<td><?php echo $tr->translate("NOT");?></td>
						<td title='Ex: 20 or 10%' ><?php echo $register->getElement('not');?></td>	
						<td><?php echo $tr->translate("START_DATE");?></td>
						<td><?php echo $register->getElement('start_date');?></td>
					</tr>
					<tr>
						<td><?php //echo $tr->translate("CHAR_PRICE");?></td>
						<td title='Ex: 20 or 10%' ><?php //echo $register->getElement('char_price');?></td>
						<td><?php echo $tr->translate("END_DATE");?></td>
						<td><?php echo $register->getElement('end_date');?></td>
					</tr>
					<input type="hidden" name="ex_rate" id="ex_rate" value="<?php echo $this->exchange_rate ;?>" dojoType="dijit.form.TextBox" />
					<input type="hidden" id="identity" name="identity" />
					
					<tr>
						<td colspan="4" align="left">
							&nbsp;
						</td>
					</tr>
					<tr>
						<td colspan="4">
							<table width="100%" border="1" id="table_row" style="border-collapse: collapse; border:1px solid #ccc;white-space: nowrap;">
									<tr id="head-title" class="head-td" align="right"></tr>
							</table>
						</td>
					</tr>
					
					<tr>
						<td colspan="6" align="right">
							<table style="width:400px;border-collapse: collapse;white-space:nowrap;" cellpadding="10" cellspacing="10" >
								<tr>
									<td ><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
									<td align="right"><input type="text" readonly="readonly" onkeyup="calculatBalanceAndReturn();"  name="grand_total" id="grand_total" dojoType="dijit.form.NumberTextBox" /></td>
								</tr>
								<tr>	
									<td><?php echo $tr->translate("CONVERT_TO_RIELS");?> (៛)</td>
									<td align="right"><input  type="text" readonly="readonly"  name="convert_to_riels" id="convert_to_riels" dojoType="dijit.form.NumberTextBox" /></td>
								</tr>
								<tr>	
									<td><?php echo $tr->translate("RECEIVED_AMOUNT");?></td>
									<td align="right"><input  type="text" readonly="readonly" onkeyup="calculatBalanceAndReturn();" required="true"  name="total_received" id="total_received" dojoType="dijit.form.NumberTextBox" /></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("BALANCE");?></td>
									<td align="right"><input type="text"  readonly="readonly" name="total_balance" value="<?php echo 0?>" id="total_balance" dojoType="dijit.form.NumberTextBox" /></td>
								</tr>
							</table>
						</td>
					</tr>
					
					<tr>
						<td colspan="4" align="center">
							<input type="submit" name="save_new" id="save_new" value="រក្សាទុក" label="<?php echo $tr->translate("GO_EDIT");?>"  dojoType="dijit.form.Button" 
							 iconClass="dijitEditorIcon dijitEditorIconSave" />
						</td>
					</tr>
					
				</table>	
			</fieldset>		
			</td>
		</tr>
	</table>
</form>
<script type="text/javascript">

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	var template = '';
	var service = '';
	var col = 0;
	var no = 0;
	var title = 0;
	tmp = '';
	temp='';
	date_format = '"dd/MM/yyyy"';

	function Initialize() {
		
		<?php if(!empty($this->row_product)){ //echo '111111';exit();
			foreach($this->row_product as $row){ 
		?>
		
			col++;no++;
			template='';
			if(title!=1){
				temp+='<th ><?php echo $tr->translate("DEL");?></th>';
				temp+='<th ><?php echo $tr->translate("N_O");?></th>';
				temp+='<th ><?php echo $tr->translate("PRODUCT");?></th>';
				temp+='<th  ><?php echo $tr->translate("PRICE");?></th>';
				temp+='<th  ><?php echo $tr->translate("AMOUNT");?></th>';
				temp+='<th  ><?php echo $tr->translate("DISCOUNT");?> %</th>';
				temp+='<th  ><?php echo $tr->translate("SUBTOTAL");?></th>';
				temp+='<th><?php echo $tr->translate("REMARK");?></th>';
				dojo.query("#head-title").append(temp);
				title=1;
			}
			template+='<td align="center"  style="width:3%"><img onclick="" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td align="center" style="width:3%;">'+no+'</td>';
			
			template+='<td style="width:30%"><input type="hidden" dojoType="dijit.form.TextBox" name="id_balance_record_'+col+'" id="id_balance_record_'+col+'"/>';
			template+='<select style="width:100%"  onchange="" readOnly dojoType="dijit.form.FilteringSelect" id="product_'+col+'" name="product_'+col+'">';
			template+='<option value="">Select </option>';
			<?php if(!empty($this->all_product)){foreach($this->all_product as $product){?>
			template+='<option value="'+<?php echo $product['id']?>+'"><?php echo $product['name'];?></option>';
			<?php }}?>
			template+='</select></td>';	
			
			
			column = 0;
			template+='<td style="width:10%"> <input class="fullside"  type="text" readOnly onkeyup="" name="price_'+col+'" id="price_'+col+'" dojoType="dijit.form.NumberTextBox" " /><label id="subsub"></label></td>';	
			template+='<td style="width:10%"> <input class="fullside" type="text" readOnly onkeyup="" name="qty_'+col+'" id="qty_'+col+'" value="1" dojoType="dijit.form.NumberTextBox" /><label id="qty"></label></td>';			
			
			template+='<td style="width:10%"> <input class="fullside"  type="text" readOnly onkeyup="" name="discount_'+col+'" value="<?php echo 0;?>" id="discount_'+col+'" dojoType="dijit.form.NumberTextBox" /><label id="subsub"></label></td>';
			template+='<td style="width:10%"> <input class="fullside" value="0" type="text"  readonly="readonly" name="subtotal_'+col+'" id="subtotal_'+col+'" dojoType="dijit.form.NumberTextBox"/><label id="qty"></label></td>';
			template+='<td style="width:24%"> <input class="fullside"  type="text" readOnly name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ" /><label id="subsub"></label></td>';

			//constraints="{datePattern:'dd/MM/yyyy'}"
			
			tmp='<tr id="row'+col+'">';
			tmp+="</tr>";
			dojo.query("#table_row").append(tmp);
			
			if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
			} else {$("#identity").val(col);}
			dojo.html.set(dojo.byId("row"+col),template , {
			parseContent: true,
			});
			//getValidate(col);
			
		dijit.byId('product_'+col).attr('value',<?php echo $row['service_id'];?>);
		dijit.byId('price_'+col).attr('value',<?php echo $row['fee'];?>);
		dijit.byId('qty_'+col).attr('value',<?php echo $row['qty'];?>);
		dijit.byId('discount_'+col).attr('value',<?php echo $row['discount_percent'];?>);
		dijit.byId('subtotal_'+col).attr('value',<?php echo $row['subtotal'];?>);
		dijit.byId('remark'+col).attr('value',<?php echo $row['note'];?>);
		
		<?php }}?>
	}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	function displayAmountSection(){
		payment_term = dijit.byId('payment_term').get('value');
		if(payment_term==5){
			document.getElementById('amount_section').style.display="block";
			document.getElementById('label_amount').style.display="block";
			
		}else{
			document.getElementById('amount_section').style.display="none";
			document.getElementById('label_amount').style.display="none";
			//alert(222);
		}
		
	}


	//set hour defuale
	function setHourDefaul(){
		dept=dijit.byId('dept').get('value');
		session=dijit.byId('session').get('value');
		if(dept==1 && session==1){
			dijit.byId('study_hour').attr('value','7:30AM - 10:50AM');
		}else if(dept==1 && session==2){
			dijit.byId('study_hour').attr('value','1:30PM - 4:50PM');
		}else if(session==1){
			dijit.byId('study_hour').attr('value','7:00AM - 11:00AM');
		}else if(session==2){
			dijit.byId('study_hour').attr('value','1:00PM - 5:00PM');
		}else if(session==5){
			dijit.byId('study_hour').attr('value','7:30AM - 4:30PM');
		}else{
			dijit.byId('study_hour').attr('value','');
		}
	}


	function changControll(){
		student_type=dijit.byId('student_type').get('value');
		 if(student_type==3){
			 document.getElementById('student_old').style.display="block";
			 document.getElementById('student_old_name').style.display="block";
			 document.getElementById('id_stu').style.display="none";
			 document.getElementById('name_stu').style.display="none";
			 //clearControll();
		}else{
			 document.getElementById('student_old').style.display="none";
			 document.getElementById('student_old_name').style.display="none";
			 document.getElementById('id_stu').style.display="block";
			 document.getElementById('name_stu').style.display="block";
			 //clearControll();
		} 
	}

	function setID(){
		stu_id = dijit.byId('old_stu_name').get('value');
		//alert(stu_id);
		dijit.byId('old_studens').attr('value',stu_id);
	}

	//
	function clearControll(){
		dijit.byId('kh_name').attr('value','');
		dijit.byId('en_name').attr('value','');
	}
	///get Gerneral old student
	function getGeneralOldStudentById(){
		var url_getalldstudent = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-general-old-student')); ?>';
		student_id=dijit.byId('old_studens').get('value');
		dijit.byId('old_stu_name').attr('value',student_id);
			dojo.xhrPost({
				url:url_getalldstudent,
				content:{
					'student_id':student_id,
					},
				handleAs:"json",
				load: function(data) {
					   if(data){
						dijit.byId('kh_name').attr('value',data.stu_khname);
						dijit.byId('en_name').attr('value',data.stu_enname);
						dijit.byId('sex').attr('value',data.sex);
						dijit.byId('dept').attr('value',data.degree);
						getallModel(data.degree,data.grade);
						 //dijit.byId('grade').attr('value',data.grade);
					  }else {
						alert('Student Id not found!');
						dijit.byId('kh_name').attr('value','');
						dijit.byId('en_name').attr('value','');
						dijit.byId('sex').attr('value','');
						dijit.byId('dept').attr('value','');
						dijit.byId('grade').attr('value','');
					  } 
				},
				error: function(err) {
					//alert(err);
				}
			});
	}
</script>