<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('Product Payment')); 
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>	
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/convertion.js"></script>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require('dojox.form.BusyButton');
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dojo.store.Memory");
	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.form.Textarea");
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.CheckBox");
	dojo.ready(function(){ 
		addRow();
		getNewReceiptNo("");

		new dijit.form.FilteringSelect({
		    autoComplete: true,                        
		    id: "student_name",
		    name: "student_name",           
		    class: 'fullside',  
		    required: true,
		    placeHolder:"----- select student name -----",          
		    onChange: function() {  
		    	getStudentInfo();
		    }
		}, "student_name");
		
	});	


	var student_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_get_student = '<?php echo $this->url(array('module'=>'accounting','controller'=>'productpayment','action'=>'get-student-by-branch')); ?>';
	function getStudentByBranch(){
		
		dijit.byId('student_name').attr('value','');
		branch_id = dijit.byId('branch').get('value');
		if(branch_id>0){
			dojo.xhrPost({
				url:url_get_student,
				content:{
					'branch_id':branch_id
					},
				handleAs:"json",
				load: function(data) {
					//alert(data);
					student_store  = getDataStorefromJSON('id','name', data);
					dijit.byId('student_name').set('store',student_store);   
				},
				error: function(err) {
					alert(err);
				}
			});
		}
	}
	
</script>

<?php 
	$register = $this->frm_unifrom_and_book;
?>

<form id='office_receipt' action="<?php echo $this->url(array('module'=>'accounting','controller'=>'productpayment','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">   
	if(this.validate()) {
		if(dijit.byId('branch').get('value')==-1){
			alert("You must select branch ! ");
			dijit.byId('branch').focus();
			return false;
		}

		var rowId = $('#identity').val();
		//alert(rowId);
		if(rowId!=''){
			var rowIDArray = rowId.split(',');
			for(var n = 0; n < rowIDArray.length; n++) {
				service_id = dijit.byId('service_'+rowIDArray[n]).get('value');
				if(service_id==0){
					alert("Please select product !!! ");
					return false;
				}
			}
		}else{
			return false;
		}

		return true;
    }else {
    	return false;
    }

</script>
<table id="head_tbl"  cellspacing="10" style="margin: 0 auto; width: 100%;">
	<tr>
		<td>
			<fieldset>
					<legend align="center"><strong​ style="font-size: 18px;"><?php echo $tr->translate("ADD_STUDENT_SERVICE_PAYMENT");?></strong></legend>
					<table style="margin: 0 auto; width: 100%;padding:10px;" cellspacing="7" cellpadding="10px" >
						<tr>
							<td width="12%"><?php echo $tr->translate("BRANCH");?></td>
							<td>
								<select name="branch" id="branch" dojoType="dijit.form.FilteringSelect" class="fullside" onchange="getStudentByBranch();getNewReceiptNo('');" >
									<option value="-1">select branch</option>
									<?php if(!empty($this->branch)){foreach ($this->branch as $branch){?>
										<option value="<?php echo $branch['id']?>"><?php echo $branch['name']?></option>
									<?php }}?>
								</select>
							</td>
						</tr>
						
						<tr>
							<td width="12%"><?php echo $tr->translate("STUDENT_NAME");?></td>
							<td width="37%">
								
								<input id="student_name" />
								
							</td>
							
							<td align="right" style="width: 12%"><?php echo $tr->translate("RECEIPT_NO");?></td>
							<td align="center" style="width: 37%"><input type="text" name="receipt_no" style="color:red;" id="receipt_no" readOnly="readOnly" class="fullside" dojoType="dijit.form.TextBox" > </td>
						</tr>
						<tr>
							
						</tr>
						<tr>
							<td ><?php echo $tr->translate("NAME_KH");?></td>
							<td ><?php echo $register->getElement('kh_name');?></td>
							<td align="right"><?php echo $tr->translate("NAME_EN");?></td>
							<td align="center"><?php echo $register->getElement('en_name');?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("SEX");?></td>
							<td ><?php echo $register->getElement('sex');?></td>
						    <td align="right"><?php echo $tr->translate("PHONE");?></td>
							<td align="center"><input type="text" name="phone" id="phone" class="fullside" readonly dojoType="dijit.form.TextBox" /></td>	
						</tr>
						<tr>
							<td colspan="4" align="left">
									<input type="button" label="<?php echo $tr->translate('ADD_ROW');?>" dojoType="dijit.form.Button" 
								 		iconClass="dijitIconEditProperty" onclick="addRow();" />
							</td>
						</tr>
						<tr>
							<td colspan="4">
								<table id="table_row" style="border-collapse: collapse; border:1px solid #ccc;">
										<tr id="head-title" class="head-td" align="right"></tr>
								</table>
							</td>
						</tr>
						<tr>
							<td colspan="2">
								<input type="hidden" name="ex_rate" id="ex_rate" value="<?php echo $this->exchange_rate ;?>" dojoType="dijit.form.TextBox" />
								<input type="hidden" id="identity" name="identity" />
								<input type="text" class="fullside" name="readmoney" readonly="readonly" id="readmoney" dojoType="dijit.form.TextBox" />
							</td>
							<td colspan="2" align="right">
								<table style="width:80%;border-collapse: collapse;white-space:nowrap;" cellpadding="10" cellspacing="10" >
									<tr>
										<td ><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
										<td align="right"><input class="fullside" type="text" readonly="readonly" onkeyup="calculatBalanceAndReturn();"  name="grand_total" id="grand_total" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
									<tr>	
										<td><?php echo $tr->translate("CONVERT_TO_RIELS");?> (៛)</td>
										<td align="right"><input  type="text" class="fullside"  readonly="readonly"  name="convert_to_riels" id="convert_to_riels" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
								</table>
							</td>
						</tr>
						<tr>
							<td colspan="4" align="center">
								
								<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
								
								<input type="submit" name="save_close" id="save_close" value="រក្សាទុក" label="<?php echo $tr->translate('SAVE_CLOSE');?>"  dojoType="dijit.form.Button" 
								 iconClass="dijitEditorIcon dijitEditorIconSave" />
								 
								<input type="submit" name="save_new" id="save_new" value="រក្សាទុក" label="<?php echo $tr->translate('SAVE_NEW');?>"  dojoType="dijit.form.Button" 
								 iconClass="dijitEditorIcon dijitEditorIconSave" />
							</td>
						</tr>
					</table>	
			<style>
				.h{ margin-top: -8px;/*margin-left:4px;*/}
			</style>	
			</fieldset>		
		</td>
	</tr>
</table>	
</form>

<script type="text/javascript">




var url_getreceiptno = '<?php echo $this->url(array('module'=>'registrar','controller'=>'coursestudy','action'=>'get-receipt-no')); ?>';
	function getNewReceiptNo(condition){
		branch_id = dijit.byId('branch').get('value');
		dojo.xhrPost({
			url:url_getreceiptno,
			content:{
				'type':5, // product payment
				'branch_id':branch_id,
				},
			handleAs:"json",
			load: function(data) {
				
				dijit.byId('receipt_no').attr('value',data);   
				if(condition==1){ 
					printSave(data);
				}
				
			},
			error: function(err) {
				alert(err);
			}
		});
			
	}

function setID(type){
	if(type==1){
		dijit.byId('stu_name').attr('value',dijit.byId('studentid').get('value')); 
	}else{
		dijit.byId('studentid').attr('value',dijit.byId('stu_name').get('value')); 
	}
}
function clearControll(){
	dijit.byId('en_name').attr('value','');
	dijit.byId('studentid').attr('value','');
	dijit.byId('kh_name').attr('value','');
	dijit.byId('sex').attr('value','');
}
function calculatePrice() {
	var total = $('#tuitionfee').val();
	var ds = $('#discount').val();
	if(ds.length!=0){
		if(ds.indexOf("%")!==-1){
			var pds=ds.split("%");
			if(!isNaN(pds[0])){
				var discount=(total*parseFloat(pds[0]))/100;
				after_discount = total - discount;
				return after_discount;

			}else{
				after_discount = total - ds;
				return after_discount;
			}
		}else{
			if(!isNaN(ds)&&ds!=0){
				discount = parseFloat(ds).toFixed(2);
				after_discount = total - discount;
				return after_discount;
			}else{
				//batch
				after_discount = total;
				return after_discount;
			}
		}
	}
}

</script>

<script type="text/javascript">

var template = '';
var service = '<?php echo $this->all_service; ?>';

var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
function addRow() {
	try{
		col++;no++;
		template='';
		if(title!=1){
			temp+='<th><?php echo $tr->translate("DEL");?></th>';
			temp+='<th><?php echo $tr->translate("N_O");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("SERVICES");?></th>';
			temp+='<th><?php echo $tr->translate("DESCRIPTION");?></th>';
			temp+='<th id="lbl_titlemetion" width="250px"><?php echo $tr->translate("AMOUNT");?></th>';
			temp+='<th id="lbl_titlemetion" width="250px"><?php echo $tr->translate("PRICE");?></th>';
			temp+='<th id="lbl_titlemetion" width="250px"><?php echo $tr->translate("DISCOUNT");?> %</th>';
			temp+='<th id="lbl_titlemetion" width="250px"><?php echo $tr->translate("SUBTOTAL");?></th>';
			
			dojo.query("#head-title").append(temp);
			title=1;
		}
			template+='<td width="50px" align="center"><img onclick="deleteRecord('+col+');calculateDiscount('+col+');" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td width="50px" align="center">'+no+'</td>';
			template+='<td width="300px"><select class="fullside" dojoType="dijit.form.FilteringSelect" onchange="getprice('+col+');" id="service_'+col+'" name="service_'+col+'">'+service+'</select></td>';			
			template+='<td width="600px"> <input type="text" style="width: 100%;" class="fullside" name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ" style="width:160px;" /><label id="subsub"></label></td>';
			column = 0;
			template+='<td width="250px"> <input type="text" style="width: 100%;" class="fullside"  onkeyup="calculateDiscount('+col+');" name="qty_'+col+'" id="qty_'+col+'" value="1" dojoType="dijit.form.NumberTextBox" /><label id="qty"></label></td>';
			template+='<td width="250px"> <input type="text" style="width: 100%;" class="fullside" required="true" onkeyup="calculateDiscount('+col+');" name="price_'+col+'" id="price_'+col+'" dojoType="dijit.form.NumberTextBox" /><label id="subsub"></label></td>';
			template+='<td width="250px"> <input type="text" style="width: 100%;" class="fullside" onkeyup="calculateDiscount('+col+');" name="discount_'+col+'" value="<?php echo 0;?>" id="discount_'+col+'" dojoType="dijit.form.NumberTextBox" /><label id="subsub"></label></td>';
			template+='<td width="250px"> <input type="text" style="width: 100%;" class="fullside"  readonly="readonly" name="subtotal_'+col+'" id="subtotal_'+col+'" dojoType="dijit.form.NumberTextBox"/><label id="qty"></label></td>';
			

		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);
		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
	}catch(e){
		alert('An error has occurred: '+e.message);
	}
 }
function calculateDiscount(index){
	price = dijit.byId('price_'+index).get('value');
	//alert(price);
	qty = dijit.byId('qty_'+index).get('value');
	qty=isNaN(qty)?1:qty;
	if(qty==1){dijit.byId('qty_'+index).attr('value',qty);}
	total = price*qty;
	
	discount = dijit.byId('discount_'+index).get('value');
	discount = isNaN(discount)?0:discount;
	dijit.byId('subtotal_'+index).attr('value',total-(total*discount/100));
	netTotal();
}

function netTotal() {
	var netTotal=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	for(var n = 0; n < rowIDArray.length; n++) {
		//netTotal += Number($('#subtotal_'+rowIDArray[n]).val());
		netTotal += dijit.byId('subtotal_'+rowIDArray[n]).get('value');
	}
	dijit.byId('grand_total').attr('value',netTotal);
	
	ex_rate = dijit.byId('ex_rate').get('value');
	dijit.byId('convert_to_riels').attr('value',netTotal * ex_rate);
	
	readMoneyInKhmer(netTotal.toFixed(2));
}

function readMoneyInKhmer(netTotal){
	//alert(netTotal);
	var str = netTotal.toString();
	str_cent = 'សេន';
	first_decimal = str.substr(-2);
	last_decimal = str.substr(-1);
	if(first_decimal>0){string='និង';}else{string="";str_cent=""}
	if(first_decimal!='00' && first_decimal<10 ){str_zero = "សូន្យ";}else{str_zero='';}
	first_money_decimal = read_in_khmer_from_10_to_99(first_decimal);
	last_money_decimal = read_in_khmer_from_0_to_9(last_decimal)
	money_khmer=read_money_in_khmer(netTotal);

	if(first_decimal>0){string_en='និង';}else{string_en="";str_cent_en=""}
	if(first_decimal!='00' && first_decimal<10 ){str_zero_en = "Zero";}else{str_zero_en='';}
	first_money_decimal_en = read_in_english_from_10_to_99(first_decimal);
	last_money_decimal_en = read_in_english_from_0_to_9(last_decimal)
	money_english=read_money_in_english(netTotal);
	read_eng = money_english.trim()+string+ first_money_decimal+str_zero+last_money_decimal+'ដុល្លាគត់'

	read_eng = '( '+money_english.trim()+string_en+ first_money_decimal_en+str_zero_en+last_money_decimal_en+' Dollar Only )'
	
	dijit.byId('readmoney').attr('value',money_khmer.trim()+string+ first_money_decimal+str_zero+last_money_decimal+'ដុល្លាគត់');
}

var url_price = "<?php echo $this->url(array('module'=>'registrar','controller'=>'uniformandbook','action'=>'get-price'));?>";
function getprice(index){
	service_price = dijit.byId('service_'+index).get('value');
	//alert(service_price);
	dojo.xhrPost({
		url:url_price,
		content:{
			'service_price':service_price,
			},
		handleAs:"json",
		load: function(data) {
			//alert(data);
			dijit.byId("price_"+index).attr("value",data);
			calculateDiscount(index);
		},
		error: function(err) {
			alert(err);
		}
	});
}


var url_student_info = "<?php echo $this->url(array('module'=>'registrar','controller'=>'studentservicepayment','action'=>'get-student')); ?>";
function getStudentInfo(){
			studentid = dijit.byId('student_name').get('value');
			//alert(studentid);
			dojo.xhrPost({
				url:url_student_info,
				content:{
					'studentid':studentid
					},
				handleAs:"json",
				load: function(data) {
					//alert(data);
					//alert(data.sex);
					dijit.byId("kh_name").attr("value",data.stu_khname);
					dijit.byId("en_name").attr("value",data.stu_enname);
					dijit.byId("sex").attr("value",data.sex);
					dijit.byId("phone").attr("value",data.tel);
					//alert(data);
					//dijit.byId("price_"+key).attr("value",data.price_fee);
				},
				error: function(err) {
					//alert(err);
				}
			});
}

function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
	}
</script>


