<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_STUDENT_PRODUCT_PAYMENT')); 
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>	
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/convertion.js"></script>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require('dojox.form.BusyButton');
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dojo.store.Memory");
	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.form.Textarea");
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.CheckBox");
	dojo.ready(function(){ 
		addRow();
		getNewReceiptNo("");
	});	
	
</script>

<?php 
	$register = $this->frm_unifrom_and_book;
?>

<form id='office_receipt' action="<?php echo $this->url(array('module'=>'registrar','controller'=>'uniformandbook','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">   
	if(dijit.byId('study_year').get('value')==-1){
		alert("You must select Year ! ");
		dijit.byId('study_year').focus();
		return false;
	}
    else if(this.validate()) {
    	return true;
    }else {
    	return false;
    }

</script>
<table id="head_tbl"  cellspacing="10" style="margin: 0 auto; width: 100%;">
	<tr>
		<td>
			<fieldset>
					<legend align="center"><strong​ style="font-size: 18px;"><?php echo $tr->translate("ADD_STUDENT_PRODUCT_PAYMENT");?></strong></legend>
					<table style="margin: 0 auto; width: 100%;padding:10px;" cellspacing="7" cellpadding="10px" >
						<tr>
							<td width="12%"><?php echo $tr->translate("STUDENT_NAME");?></td>
							<td width="37%">
								<select type="text" style="" class="fullside" dojoType="dijit.form.FilteringSelect" autoComplete="false" queryExpr="*${0}*" name="stu_name" id="stu_name" onChange="getStudentInfo();" >
									<option value="-1">Select Student Name</option>
									<?php if(!empty($this->row)){foreach ($this->row as $row){?>
									<option value="<?php echo $row['id']?>"><?php echo $row['name']?></option>
									<?php }}?>
								</select>
							</td>
							
							<td align="right" style="width: 12%"><?php echo $tr->translate("RECEIPT_NO");?></td>
							<td align="center" style="width: 37%"><input type="text" name="receipt_no" style="color:red;" id="receipt_no" class="fullside" dojoType="dijit.form.TextBox" > </td>
						</tr>
						<tr>
							
						</tr>
						<tr>
							<td ><?php echo $tr->translate("NAME_KH");?></td>
							<td ><?php echo $register->getElement('kh_name');?></td>
							<td align="right"><?php echo $tr->translate("NAME_EN");?></td>
							<td align="center"><?php echo $register->getElement('en_name');?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("SEX");?></td>
							<td ><?php echo $register->getElement('sex');?></td>
						    <td align="right"><?php echo $tr->translate("PHONE");?></td>
							<td align="center"><input type="text" name="phone" id="phone" class="fullside" readonly dojoType="dijit.form.TextBox" /></td>	
						</tr>
						<tr>
							<td colspan="4" align="left">
									<input type="button" label="<?php echo $tr->translate('ADD_ROW');?>" dojoType="dijit.form.Button" 
								 		iconClass="dijitIconEditProperty" onclick="addRow();" />
							</td>
						</tr>
						<tr>
							<td colspan="4">
								<table border="1" id="table_row" style="border-collapse: collapse; border:1px solid #ccc;">
										<tr id="head-title" class="head-td" align="right"></tr>
								</table>
							</td>
						</tr>
						<tr>
							<td colspan="2">
								<input type="hidden" id="identity" name="identity" />
								<input type="text" class="fullside" name="readmoney" id="readmoney" readonly dojoType="dijit.form.TextBox" />
							</td>
							<td colspan="2" align="right">
								<table style="width:400px;border-collapse: collapse;white-space:nowrap;" cellpadding="10" cellspacing="10" >
									<tr>
										<td ><?php echo $tr->translate("EXCHANGE_RATE")." (៛)";?></td>
										<td align="right">
											<input type="text" name="ex_rate" id="ex_rate" class="fullside" readonly value="<?php echo $this->exchange_rate ;?>" dojoType="dijit.form.NumberTextBox" />
										</td>
									</tr>
									<tr>
										<td ><?php echo $tr->translate("TOTAL");?></td>
										<td align="right"><input class="fullside" type="text" readonly="readonly" onkeyup="calculatBalanceAndReturn();"  name="grand_total" id="grand_total" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
									<tr>	
										<td><?php echo $tr->translate("CONVERT_TO_RIELS");?> (៛)</td>
										<td align="right"><input  type="text" class="fullside" readonly="readonly"  name="convert_to_riels" id="convert_to_riels" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
								</table>
							</td>
						</tr>
						<tr>
							<td colspan="4" align="center">
								<input type="button" name="save_close" id="save_close" onclick="submitDataClose();" value="រក្សាទុក" label="<?php echo $tr->translate('SAVE_CLOSE');?>"  dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconSave" />
								 
								<input type="button" name="save_new" id="save_new" onclick="submitDataAddNew();" value="រក្សាទុក" label="<?php echo $tr->translate('SAVE_NEW');?>"  dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconSave" />
								
								<input type="button" value="បោះពុម្ព" label="<?php echo $tr->translate('PRINT');?>" id="print" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="printSave('');"/> 
							</td>
						</tr>
					</table>	
			<style>
				.h{ margin-top: -8px;/*margin-left:4px;*/}
			</style>	
			</fieldset>		
		</td>
	</tr>
</table>	
</form>

<script type="text/javascript">


function submitDataClose(){
	
	condition = checkValidateAddRow();
	if(condition==false){
		alert("Please select service or product !!! ");
		return false;
	}
		
	if(dijit.byId('office_receipt').validate()) {
		
		dijit.byId('save_new').set('disabled',true);
		dijit.byId('save_close').set('disabled',true);
	
		var url_submit = '<?php echo $this->url(array('module'=>'registrar','controller'=>'uniformandbook','action'=>'add')); ?>';
		loading();
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("office_receipt"),		    
			load: function(data) {
				document.getElementsByClassName("overlay")[0].style.display="none";	
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/registrar/uniformandbook";
			},
			error: function(e) {
			}
		});
	}
}

function submitDataAddNew(){
	
	condition = checkValidateAddRow();
	if(condition==false){
		alert("Please select service or product !!! ");
		return false;
	}
	
	if(dijit.byId('office_receipt').validate()) {
	
		dijit.byId('save_new').set('disabled',true);
		dijit.byId('save_close').set('disabled',true);
		
		var url_submit = '<?php echo $this->url(array('module'=>'registrar','controller'=>'uniformandbook','action'=>'add')); ?>';
		loading();
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("office_receipt"),		    
			load: function(data) {
				document.getElementsByClassName("overlay")[0].style.display="none";		
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/registrar/uniformandbook/add";
			},
			error: function(e) {
			}
		});
	}
}

function checkValidateAddRow(){
	var rowId = $('#identity').val();
	//alert(rowId);
	if(rowId!=''){
		var rowIDArray = rowId.split(',');
		for(var n = 0; n < rowIDArray.length; n++) {
			product_id = dijit.byId('service_'+rowIDArray[n]).get('value');
			if(product_id==0){
				return false;
			}
		}
	}
	return true;
}


function loading(){
    document.getElementsByClassName("overlay")[0].style.display="block";
}


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

function printSave(new_receipt_no){		

	if(dijit.byId('office_receipt').validate()) {
		
		condition = checkValidateAddRow();
		if(condition==false){
			alert("Please select service or product !!! ");
			return false;
		}
		
		dojo.byId("lb_kh_name").innerHTML = dijit.byId("kh_name").get('value');
		dojo.byId("lb_en_name").innerHTML = dijit.byId("en_name").get('value');
		dojo.byId("lb_sex").innerHTML = dijit.byId("sex").attr('displayedValue');
		dojo.byId("lb_phone").innerHTML = dijit.byId("phone").attr('displayedValue');
		
		// if(new_receipt_no==''){
			// getNewReceiptNo(1);
		// }else{
			// dojo.byId("lb_receipt_no").innerHTML = new_receipt_no;
		// }
		
		dojo.byId("lb_receipt_no").innerHTML = dijit.byId("receipt_no").get('value');
		
		dojo.byId("lb_stu_type").innerHTML = "សិស្សចាស់/Old Student";
		dojo.byId("lb_receipt_type").innerHTML = "Material";
		
		var total = dijit.byId("grand_total").get('value');
		dojo.byId("lb_grand_total").innerHTML = " $ "+total;
		dojo.byId("lb_total_balance").innerHTML = " $ 0";
		dojo.byId("lb_total_paid").innerHTML = " $ "+total;
		dojo.byId("lb_read_money").innerHTML = dijit.byId('readmoney').get('value');
		
		
		checked =  "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/checked.png'?>'>";
		uncheck = "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/uncheck.png'?>'>";
		
		dojo.byId("check_book").innerHTML = uncheck;
		dojo.byId("check_uniform").innerHTML = uncheck;
		dojo.byId("check_material").innerHTML = uncheck;
		dojo.byId("check_other").innerHTML = uncheck;
		
		dojo.byId("lb_description_book").innerHTML = "&nbsp;";
		dojo.byId("lb_description_uniform").innerHTML = "&nbsp;";
		dojo.byId("lb_description_material").innerHTML = "&nbsp;";
		dojo.byId("lb_description_other").innerHTML = "&nbsp;";
		
		
		var rowId = $('#identity').val();
		if(rowId==""){
			return false;
		}
		var rowIDArray = rowId.split(',');
		for(var n = 0; n < rowIDArray.length; n++) {
			pro1 = dijit.byId('service_'+rowIDArray[n]).get('value');
			
			if(pro1==1){
				dojo.byId("check_uniform").innerHTML = checked;		
				dojo.byId("lb_description_uniform").innerHTML = dijit.byId('remark'+rowIDArray[n]).get('value') + " = $"+ dijit.byId('subtotal_'+rowIDArray[n]).get('value');
			}
			
			if(pro1==82){
				dojo.byId("check_book").innerHTML = checked;		
				dojo.byId("lb_description_book").innerHTML = dijit.byId('remark'+rowIDArray[n]).get('value') + " = $"+ dijit.byId('subtotal_'+rowIDArray[n]).get('value');
			}
			
			if(pro1==83){
				dojo.byId("check_material").innerHTML = checked;		
				dojo.byId("lb_description_material").innerHTML = dijit.byId('remark'+rowIDArray[n]).get('value') + " = $"+ dijit.byId('subtotal_'+rowIDArray[n]).get('value');
			}
			
			if(pro1==84){
				dojo.byId("check_other").innerHTML = checked;		
				dojo.byId("lb_description_other").innerHTML = dijit.byId('remark'+rowIDArray[n]).get('value') + " = $"+ dijit.byId('subtotal_'+rowIDArray[n]).get('value');
			}
		}
		dijit.byId("popup_invoice").show();	
	}
	
	
}



var url_getreceiptno = '<?php echo $this->url(array('module'=>'registrar','controller'=>'coursestudy','action'=>'get-receipt-no')); ?>';
	function getNewReceiptNo(condition){
		
		dojo.xhrPost({
			url:url_getreceiptno,
			content:{
				'type':5, // product payment
				'branch_id':0,
				},
			handleAs:"json",
			load: function(data) {
				
				dijit.byId('receipt_no').attr('value',data);   
				if(condition==1){ 
					printSave(data);
				}
				
			},
			error: function(err) {
				alert(err);
			}
		});
			
	}

</script>

<div class="dijitHidden" style="width: 26cm !important; height: 11cm ; padding: 0px; margin: 0px;">
<?php $keycode = $this->keycode;?>
	<div data-dojo-type="dijit.Dialog" style="width:26cm;" align="center" data-dojo-props="title:'<?php echo $tr->translate("");?>'" id="popup_invoice" >
		
		<div id="divPrint" style="width: 24cm !important; height: 13cm ; padding: 0px; margin: 0px;">
			<style>
				.fontbig{
					font-size: 15px;	
				}
				.fonttel{
					font-size: 18px;	
				}
				.pleft{
					width: 110px;	
				}
				.label{ font-weight: bold;font-size: 22px;}
				.value{ font:bold 12px 'Khmer OS Battambang';border: 1px solid rgba(14, 0, 107, 1); height: 25px; padding: 0 2px;width: 98%; display: block;
						margin-top: -25px; line-height: 25px;
					    text-align: center;
						}
				.values{ border: 1px solid rgba(14, 0, 107, 1);; height: 25px; padding: 0 10px;display: block;
						line-height: 25px;}
				.h{ margin-top: -8px;/*margin-left:4px;*/}
​​               .print td{ font:bold 12px 'Khmer OS Battambang';}
			   .khmerbold{font:bold 12px 'Khmer OS Battambang';}
			   .khmer{font:12px 'Khmer OS Battambang';}
			   .one{white-space:nowrap;}
			   
				.underline{margin-top: -19px;text-align:center;}
				.underline1{margin-top: -19px;text-align:left;}
				.data{font-size:13px;font-weight:bold;}
				.data1{font-size:14px;}
				.receiptno{font-size:15px;font-weight:bold;}
				.tab_row{ margin-top: -8px;}
				.fonteng{font-size:12px;}
				
			</style>	
			<table border="0" width="100%" class="print" cellspacing="0"  cellpadding="0" style="white-space: nowrap;font-size:12px;font-family:'Khmer OS Battambang';line-height: 23px;">
				<tr>
				    <td colspan="8"  align="center" style="">
						<table width="100%" border="0" style="white-space:nowrap; font-family:Khmer OS Battambang;margin-top:-15px;font-weight:bold;line-height: 20px;">
							<tr>
								<td width="25%" align="left" style="font-size:11px;">
									<div style="font-size:15px;"><?php if (!empty($this->branch_info['branch_namekh'])){ echo $this->branch_info['branch_namekh'];}?></div><?php echo date('l , jS / m / Y , H:i:s ',strtotime(Zend_Date::now()));?>
								</td>
								<td width="50%" align="center">
									<img style="width: 20%;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br >
								</td>
								<td width="25%" align="center" style="font-size:17px;color:red;"><label id="lb_receipt_type" style="color:#000;font-size:16px;"> </label><div style="margin-top:-5px;">N<sup>o</sup> : <label id="lb_receipt_no" class="receiptno" ></div></label></td>
							</tr>
						</table>
				    </td>
				</tr>
				
				<tr>
					<td width="15%"></td>
					<td width="20%"></td>
					<td width="15%"></td>
					<td width="20%"></td>
					<td width="5%"></td>
					<td width="10%"></td>
					<td width="5%"></td>
					<td width="10%"></td>
				</tr>
			
				<tr >
					<td colspan="8">
						<table width="100%" style="white-space:nowrap; font-size:12px;font-family:'Khmer OS Battambang';line-height: 21px;margin-top: -25px;">
							<tr>
								<td width="40%"><img style="width: 100%;height:4px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/double_underline.png'?>"></td>
								<td width="20%" align="center" style="font-size:16px;">បង្កាន់ដៃទទួលប្រាក់ RECEIPT</td>
								<td width="40%"><img style="width: 100%;height:4px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/double_underline.png'?>"></td>
							</tr>
						</table>
					</td>
				</tr>
			
				<tr>
					<td>ឈ្មោះភាសាខ្មែរ/Name in Khmer</td>
					<td>
						&nbsp;:&nbsp; <label id="lb_kh_name"  class="data" ></label>
						<div class="underline">...............................................</div>
					</td>
					<td align="center"> អក្សរឡាតាំង/Latin&nbsp;</td>
					<td>
						:&nbsp; <label id="lb_en_name" class="data" ></label>
						<div class="underline">...............................................</div>
					</td>
					<td align="center">ភេទ/Sex</td>
					<td>
						&nbsp;:&nbsp; <label id="lb_sex" class="data" ></label>
						<div class="underline">..................</div>
					</td>
					
					<td align="center">&nbsp;អត្តលេខ/ID&nbsp;</td>
					<td>
						:&nbsp; <label id="" class="data" >&nbsp;</label>
						<div class="underline">....................</div>
					</td>
				</tr>
				
				
				<tr>
					<td colspan="8">
						<table width="100%" style="white-space: nowrap;font-size:12px;font-family:'Khmer OS Battambang';line-height: 21px;">
							<tr>
								<td width="15%">លេខទូរស័ព្ទ/Phone Number</td>
								<td width="50%">
									&nbsp;:&nbsp; <label id="lb_phone" class="data" ></label>
									<div class="underline">
										....................................................................................................................................
									</div>
								</td>
								<td width="15%">
									ប្រភេទសិស្ស/Student Type
								</td>
								<td width="20%">
									&nbsp;:&nbsp; <label id="lb_stu_type" class="data" ></label>
									<div class="underline">
										&nbsp;&nbsp;................................................
									</div>
								</td>
							</tr>
						</table>
					</td>
				</tr>
					
				<tr>
					<td colspan="8" style="border:1px solid #000;">
						<table width="100%" border="0" class="data2" style="white-space:nowrap; font-family:Khmer OS Battambang,Times New Roman;font-size:11px;line-height: 21px;">
							<tr>
								<td width="8%"></td>
								<td width="3%"></td>
								<td width="4%"></td>
								<td width="7%"></td>
								<td width="7%"></td>
								<td width="7%"></td>
								<td width="8%"></td>
								<td width="7%"></td>
								<td width="8%"></td>
								<td width="6%"></td>
								<td width="10%"></td>
								<td width="6%"></td>
							</tr>
							<tr>
								<td colspan="12">
									សម្រាប់សេវា/Services
								</td>
								
							</tr>
							
							<tr>
								<td colspan="12">
									<table width="100%" style="margin-top:-5px; white-space:nowrap; font-family:Khmer OS Battambang,Times New Roman;font-size:11px;line-height: 21px;">
										<tr>
											<td width="10%" >
												<label id="check_book"></label> ថ្លៃសៀវភៅពុម្ភ/Book Fee :
											</td>
											<td width="90%">
												<label id="lb_description_book" class="data1">&nbsp;</label> 
												<div class="underline1">...............................................................................................................................................................................................................................................</div>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							
							<tr>
								<td colspan="12">
									<table width="100%" style="margin-top:-5px;white-space:nowrap; font-family:Khmer OS Battambang,Times New Roman;font-size:11px;line-height: 21px;">
										<tr>
											<td width="14%" >
												<label id="check_uniform"></label> ថ្លៃឯកសណ្ឋាន/Uniform Fee :
											</td>
											<td width="86%">
												<label id="lb_description_uniform" class="data1">&nbsp;</label> 
												<div class="underline1">...........................................................................................................................................................................................................................................</div>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							
							<tr>
								<td colspan="12">
									<table width="100%" style="margin-top:-5px;white-space:nowrap; font-family:Khmer OS Battambang,Times New Roman;font-size:11px;line-height: 21px;">
										<tr>
											<td width="18%" >
												<label id="check_material"></label> ថ្លៃសម្ភារៈសិក្សា/Study Material Fee :
											</td>
											<td width="82%">
												<label id="lb_description_material" class="data1">&nbsp;</label> 
												<div class="underline1">................................................................................................................................................................................................................................</div>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							
							<tr>
								<td colspan="12">
									<table width="100%" style="margin-top:-5px; white-space:nowrap; font-family:Khmer OS Battambang,Times New Roman;font-size:11px;line-height: 21px;">
										<tr>
											<td width="8%" >
												<label id="check_other"></label> ផ្សេងៗ/Others :
											</td>
											<td width="92%">
												<label id="lb_description_other" class="data1">&nbsp;</label> 
												<div class="underline1">..............................................................................................................................................................................................................................................................</div>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							
							<tr>
								<td colspan="12">
									<table width="100%" border="0" style="margin-top: -5px;white-space:nowrap; font-family:Khmer OS Battambang,Times New Roman;font-size:11px;line-height: 21px;">
										<tr>
											<td width="15%">ទឹកប្រាក់សរុប/Total Amount : </td>
											<td width="15%" align="center">
												<label id="lb_grand_total" class="data1" >&nbsp;</label>
												<div class="underline">.......................................</div>
											</td>
											
											<td width="12%" align="center">ទឹកប្រាក់ជំពាក់/Credit : </td>
											<td width="15%" align="center">
												<label id="lb_total_balance" class="data1" >&nbsp;</label>
												<div class="underline">........................................</div>
											</td>
											
											<td width="25%">ទឹកប្រាក់ទទួលបានសរុប/Total Received Amount</td>
											<td width="18%" style="border:1px solid #000;" align="center">
												<label id="lb_total_paid" class="data1" ></label>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							
							<tr>
								<td colspan="12">
									<table width="100%" border="0" style="margin-top: -5px;white-space:nowrap; font-family:Khmer OS Battambang,Times New Roman;font-size:11px;line-height: 21px;">
										<tr>
											<td width="18%">ទឹកប្រាក់ទទួលបានជាអក្សរ/In Words : </td>
											<td width="82%" align="left">
												&nbsp;<label id="lb_read_money" class="data1" ></label>
												<div class="underline1">.....................................................................................................................................................................................................................................</div>
											</td>
										</tr>
									</table>
								</td>	
							</tr>
							
						</table>
					</td>
				</tr>
				
				<tr>
					<td colspan="12">
						<table width="100%" style="white-space:nowrap; font-size:12px;font-family:Khmer OS Battambang, Times New Roman;">
							<tr>
								<td width="70%">&nbsp;</td>
								<td width="30%"align="right" >រាជធានីភ្នំពេញ.ថ្ងៃទី <?php echo date('d');?> / <?php echo date('m');?> / <?php echo date('Y');?></td>
							</tr>
						</table>
					</td>
				</tr>
				
				<tr>
					<td colspan="12">
						<table width="100%" style="white-space:nowrap; font-size:12px;font-family:Khmer OS Muol;font-weight:bold;">
							<tr style="line-height:18px;">
								<td width="" align="center">ប្រធានគណនេយ្យ<br />Accounting Manager</td>
								<td width="" align="center">ស្តុក(សាខា)<br />Stock</td>
								<td width="" align="center">គណនេយ្យស្តុក(HO)<br />Stock</td>
								<td width="" align="center">គណនេយ្យចំណូល<br />Accountant</td>
								<td width="" align="center">អ្នកបង់ប្រាក់<br />Payer</td>
								<td width="" align="center">បេឡា<br />Cashier</td>
								<td width="" align="center">អ្នកផ្តល់ពត៌មាន​<br />Receiptionist</td>
							</tr>
							
							<tr>
								<td colspan="7" align="center">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="5" ></td>
								<td align="center">
									<div style=" font-size: 12px;"> 
										<?php 
										   $session_user=new Zend_Session_Namespace('auth');
										   $last_name=$session_user->last_name;
										   $username = $session_user->first_name;
										   echo $last_name." ".$username;
										?>
									</div>
								</td>
								<td align="center"></td>
							</tr>
							
							<tr>
								<td colspan="7" align="center" style="border-top: 1px solid #000;">&nbsp;</td>
							</tr>

						</table>
					</td>
				</tr>	
				<tr>
					<td colspan="12" >
						<table width="100%" style="margin-top:-20px; font-family:Khmer OS Battambang, Times New Roman; font-size:10px;white-space:nowrap;line-height: 15px;">
							<tr>
								<td colspan="2" valign="top" style="font-family:Khmer OS Muol;"><u>បញ្ជាក់ៈ Note</u></td>
							</tr>
							
							<tr>
								<td width="70%">
									<table width="100%" style="white-space:nowrap; font-size:10px;font-family:Khmer OS Battambang,Times New Roman;line-height: 14px;">
										<tr>
											<td colspan="2" style="white-space: pre;"><?php if (!empty($this->keycode['note_student_material_service'])){echo $this->keycode['note_student_material_service'];}?></td>
										</tr>
									</table>
								</td>
								<td width="30%" valign="top" align="center"> 
									លេខទូរស័ព្ទ/Tel: ការិយាល័យផ្តល់ពត៌មាន/Information office <br />
									- 092 36 36 42 <br />
									- 087 53 99 99 <br />
									- 023 99 99 98 <br />
								</td>
								
							</tr>
						</table>
					</td>
				</tr>		
			</table>
		</div>
		<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>	
		<button dojoType="dijit.form.Button" label="Cancel" iconClass="dijitEditorIcon dijitEditorIconCancel"
				showLabel="true" type="button" onclick="hideDialog();">Cancel</button>
		<button dojoType="dijit.form.Button" label="Print" iconClass="dijitEditorIcon dijitEditorIconPrint"
				showLabel="true" type="button" onclick="printSubmit();">Print</button>
	</div>
</div>
<script>

function setID(type){
	if(type==1){
		dijit.byId('stu_name').attr('value',dijit.byId('studentid').get('value')); 
	}else{
		dijit.byId('studentid').attr('value',dijit.byId('stu_name').get('value')); 
	}
}
function clearControll(){
	dijit.byId('en_name').attr('value','');
	dijit.byId('studentid').attr('value','');
	dijit.byId('kh_name').attr('value','');
	dijit.byId('sex').attr('value','');
}
//save daata when sub button print 
function printSubmit(){
	$('#office_receipt').submit();
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
}
function calculatePrice() {
	var total = $('#tuitionfee').val();
	var ds = $('#discount').val();
	if(ds.length!=0){
		if(ds.indexOf("%")!==-1){
			var pds=ds.split("%");
			if(!isNaN(pds[0])){
				var discount=(total*parseFloat(pds[0]))/100;
				after_discount = total - discount;
				return after_discount;

			}else{
				after_discount = total - ds;
				return after_discount;
			}
		}else{
			if(!isNaN(ds)&&ds!=0){
				discount = parseFloat(ds).toFixed(2);
				after_discount = total - discount;
				return after_discount;
			}else{
				//batch
				after_discount = total;
				return after_discount;
			}
		}
	}
}
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    dijit.byId("terms").hide();	//hideDialog();
}

</script>

<script type="text/javascript">
function showPopupDept() {
	if(dijit.byId('faculty').value==-1){
		dijit.byId("popup_dept").show();
	}
}
function hideDialog() {		
	dijit.byId("popup_invoice").hide();
}

var template = '';
var service = '<?php echo $this->all_service; ?>';

var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
function addRow() {
	try{
		col++;no++;
		template='';
		if(title!=1){
			temp+='<th><?php echo $tr->translate("DEL");?></th>';
			temp+='<th><?php echo $tr->translate("N_O");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("SERVICES");?></th>';
			temp+='<th><?php echo $tr->translate("DESCRIPTION");?></th>';
			temp+='<th id="lbl_titlemetion" width="250px"><?php echo $tr->translate("AMOUNT");?></th>';
			temp+='<th id="lbl_titlemetion" width="250px"><?php echo $tr->translate("PRICE");?></th>';
			temp+='<th id="lbl_titlemetion" width="250px"><?php echo $tr->translate("DISCOUNT");?> %</th>';
			temp+='<th id="lbl_titlemetion" width="250px"><?php echo $tr->translate("SUBTOTAL");?></th>';
			
			dojo.query("#head-title").append(temp);
			title=1;
		}
			template+='<td width="50px" align="center"><img onclick="deleteRecord('+col+');calculateDiscount('+col+');" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td width="50px" align="center">'+no+'</td>';
			template+='<td width="300px"><select class="fullside" dojoType="dijit.form.FilteringSelect" onchange="getprice('+col+');" id="service_'+col+'" name="service_'+col+'">'+service+'</select></td>';			
			template+='<td width="600px"> <input type="text" style="width: 100%;" class="fullside" name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ" style="width:160px;" /><label id="subsub"></label></td>';
			column = 0;
			template+='<td width="250px"> <input type="text" style="width: 100%;" class="fullside"  onkeyup="calculateDiscount('+col+');" name="qty_'+col+'" id="qty_'+col+'" value="1" dojoType="dijit.form.NumberTextBox" /><label id="qty"></label></td>';
			template+='<td width="250px"> <input type="text" style="width: 100%;" class="fullside" required="true" onkeyup="calculateDiscount('+col+');" name="price_'+col+'" id="price_'+col+'" dojoType="dijit.form.NumberTextBox" /><label id="subsub"></label></td>';
			template+='<td width="250px"> <input type="text" style="width: 100%;" class="fullside" onkeyup="calculateDiscount('+col+');" name="discount_'+col+'" value="<?php echo 0;?>" id="discount_'+col+'" dojoType="dijit.form.NumberTextBox" /><label id="subsub"></label></td>';
			template+='<td width="250px"> <input type="text" style="width: 100%;" class="fullside"  readonly="readonly" name="subtotal_'+col+'" id="subtotal_'+col+'" dojoType="dijit.form.NumberTextBox"/><label id="qty"></label></td>';
			

		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);
		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
	}catch(e){
		alert('An error has occurred: '+e.message);
	}
 }
function calculateDiscount(index){
	price = dijit.byId('price_'+index).get('value');
	//alert(price);
	qty = dijit.byId('qty_'+index).get('value');
	qty=isNaN(qty)?1:qty;
	if(qty==1){dijit.byId('qty_'+index).attr('value',qty);}
	total = price*qty;
	
	discount = dijit.byId('discount_'+index).get('value');
	discount = isNaN(discount)?0:discount;
	dijit.byId('subtotal_'+index).attr('value',total-(total*discount/100));
	netTotal();
}

function netTotal() {
	var netTotal=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	for(var n = 0; n < rowIDArray.length; n++) {
		//netTotal += Number($('#subtotal_'+rowIDArray[n]).val());
		netTotal += dijit.byId('subtotal_'+rowIDArray[n]).get('value');
	}
	dijit.byId('grand_total').attr('value',netTotal);
	
	ex_rate = dijit.byId('ex_rate').get('value');
	dijit.byId('convert_to_riels').attr('value',netTotal * ex_rate);
	
	readMoneyInKhmer(netTotal.toFixed(2));
}

function readMoneyInKhmer(netTotal){
	var str = netTotal.toString();
	str_cent = 'សេន';
	first_decimal = str.substr(-2);
	last_decimal = str.substr(-1);
	
	if(first_decimal>0){string='ដុល្លា និង ';last_string="សេន"}else{string="";str_cent="";last_string="ដុល្លាគត់";}
	if(first_decimal!='00' && first_decimal<10 ){str_zero = "សូន្យ";}else{str_zero='';}
	first_money_decimal = read_in_khmer_from_10_to_99(first_decimal);
	last_money_decimal = read_in_khmer_from_0_to_9(last_decimal);
	money_khmer=read_money_in_khmer(netTotal);

	if(first_decimal>0){string_en='dot';}else{string_en="";str_cent_en=""}
	if(first_decimal!='00' && first_decimal<10 ){str_zero_en = "Zero";}else{str_zero_en='';}
	first_money_decimal_en = read_in_english_from_10_to_99(first_decimal);
	last_money_decimal_en = read_in_english_from_0_to_9(last_decimal);
	money_english=read_money_in_english(netTotal);
	
	//read_eng = money_english.trim()+string+ first_money_decimal+str_zero+last_money_decimal+last_string;
	//read_eng = '( '+money_english.trim()+string_en+ first_money_decimal_en+str_zero_en+last_money_decimal_en+' Dollar Only )';
	
	dijit.byId('readmoney').attr('value',money_khmer.trim()+string+ first_money_decimal+str_zero+last_money_decimal+last_string);
}

var url_price = "<?php echo $this->url(array('module'=>'registrar','controller'=>'uniformandbook','action'=>'get-price'));?>";
function getprice(index){
	service_price = dijit.byId('service_'+index).get('value');
	//alert(service_price);
	dojo.xhrPost({
		url:url_price,
		content:{
			'service_price':service_price,
			},
		handleAs:"json",
		load: function(data) {
			//alert(data);
			dijit.byId("price_"+index).attr("value",data);
			calculateDiscount(index);
		},
		error: function(err) {
			alert(err);
		}
	});
}


var url_student_info = "<?php echo $this->url(array('module'=>'registrar','controller'=>'studentservicepayment','action'=>'get-student')); ?>";
function getStudentInfo(){
			studentid = dijit.byId('stu_name').get('value');
			//alert(studentid);
			dojo.xhrPost({
				url:url_student_info,
				content:{
					'studentid':studentid
					},
				handleAs:"json",
				load: function(data) {
					//alert(data);
					//alert(data.sex);
					dijit.byId("kh_name").attr("value",data.stu_khname);
					dijit.byId("en_name").attr("value",data.stu_enname);
					dijit.byId("sex").attr("value",data.sex);
					dijit.byId("phone").attr("value",data.tel);
					//alert(data);
					//dijit.byId("price_"+key).attr("value",data.price_fee);
				},
				error: function(err) {
					//alert(err);
				}
			});
}

function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
	}
</script>

<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>	
<style>
.overlay {display: none;position: absolute;width: 100%;height: 150%;top: 0px;left: 0px;background: #FCFCFC;z-index: 1001;opacity: .5;}
.overlay-load {width: 350px;height: 100px;margin: auto;top: 0px;bottom: 0px;position: absolute;left: 0px;right: 0px;
           text-align: center;
           background: #fff url("<?php echo $this->baseUrl()?>/images/loading.gif") 50% 25%;
           background-repeat: no-repeat;          
}
.overlay-msg{margin-bottom: 10px;bottom: 0px;position: absolute;font-style: italic;color: rgb(19, 19, 19);} 
</style>


