<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('Edit Student buy product')); 
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>	
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/convertion.js"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require('dojox.form.BusyButton');
	dojo.require("dojo.NodeList-manipulate");
	
dojo.ready(function(){
    	 dijitValue();
    	 getStudentInfo();
    	 initailize();
		 netTotal();
});

function dijitValue(){
	 dijit.byId('reciept_no').attr('value','<?php echo $this->row['receipt_number']?>');
	 dijit.byId('grand_total').attr('value','<?php echo $this->row['total_payment']?>');
	 dijit.byId("phone").set('readOnly',true);
	 dijit.byId("stu_name").set('readOnly',true);
}
</script>

<style>
select{ width:100%;}
fieldset{  background:none;}
.red{ color: red; padding-left:5px;}
</style>
<?php $register = $this->frm_register;
//print_r($register);
?>
<form id='office_receipt' action="<?php echo $this->url(array('module'=>'registrar','controller'=>'uniformandbook','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">   
   if(this.validate()) {
    return true;
   }else {
    return false;
   }
</script>
<table  cellspacing="10" style="margin: 0 auto; width: 100%;">
	<tr>
		<td>
		<fieldset>
					<legend align="center"><strong style="font-size: 18px;"><?php echo $tr->translate("EDIT_STUDENT_SERVICE_PAYMENT");?></strong></legend>
					<table style="margin: 0 auto; width: 100%;padding:10px;" cellspacing="7" >
						<tr>
							<td style="width: 12%" align="left"><?php echo $tr->translate("STUDENT_NAME");?></td>
							<td style="width: 37%" align="center">
								<select type="text" style="" class="fullside" dojoType="dijit.form.FilteringSelect" name="stu_name" id="stu_name" onChange="" >
									<option value="-1">Select Student Name</option>
									<?php if(!empty($this->row_name)){foreach ($this->row_name as $row){?>
									<option value="<?php echo $row['id']?>" <?php if($row['id']==$this->row['student_id']) echo 'selected="selected"' ?> ><?php echo $row['name']?></option>
									<?php }}?>
								</select>
							</td>
							
							<td align="right" style="width: 12%"><?php echo $tr->translate("RECEIPT_NO");?></td>
							<td style="width: 37%"><?php echo $register->getElement('reciept_no');?></td>
						</tr>
						<tr>
						    <td><?php echo $tr->translate("NAME_KH");?></td>
							<td><?php echo $register->getElement('kh_name');?></td>
							<td align="right"><?php echo $tr->translate("NAME_EN");?></td>
							<td ><?php echo $register->getElement('en_name');?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("SEX");?></td>
							<td><?php echo $register->getElement('sex');?></td>
						    <td align="right"><?php echo $tr->translate("PHONE");?></td>
							<td ><?php echo $register->getElement('phone');?></td>	
						</tr>
						<tr>
							<td colspan="4" align="left">
								&nbsp;
							</td>
						</tr>
						<tr>
							<td colspan="4">
								<table border="1" id="table_row" style="border-collapse: collapse; border:1px solid #ccc;">
										<tr id="head-title" class="head-td" align="right"></tr>
								</table>
							</td>
						</tr>
						<tr>
							<td colspan="2">
								<input type="hidden" name="ex_rate" id="ex_rate" value="<?php echo $this->exchange_rate ;?>" dojoType="dijit.form.TextBox" />
								<input type="hidden" id="identity" name="identity" />
								<input type="text" class="fullside" name="readmoney" id="readmoney" readonly dojoType="dijit.form.TextBox" />
							</td>
							<td colspan="2" align="right">
								<table style="width:250px;border-collapse: collapse;white-space:nowrap;" cellpadding="10" cellspacing="10" >
									<tr>
										<td ><?php echo $tr->translate("TOTAL");?></td>
										<td align="right"><input class="fullside" type="text" readonly="readonly" onkeyup="calculatBalanceAndReturn();"  name="grand_total" id="grand_total" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
									<tr>	
										<td><?php echo $tr->translate("CONVERT_TO_RIELS");?> (៛)</td>
										<td align="right"><input  type="text" readonly="readonly"  name="convert_to_riels" id="convert_to_riels" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
								</table>
							</td>
						</tr>
						<tr>
							<td colspan="4" align="center">
								<input type="button" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
									iconClass="dijitIconUndo" onclick="window.location = '<?php echo $this->url(array('module'=>'registrar','controller'=>"uniformandbook",'action'=>'index'),null,true); ?>';" />
								<input type="submit" name="save_new" id="save_new" value="រក្សាទុក" label="<?php echo $tr->translate('GO_EDIT');?>"  dojoType="dijit.form.Button" 
								 	iconClass="dijitEditorIcon dijitEditorIconSave" />
							</td>
						</tr>
					</table>
				<style>
					.h{ margin-top: -8px;/*margin-left:4px;*/}
				</style>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>

<script type="text/javascript">

	var template = '';
	var metion = '<?php echo $this->all_metion; ?>';
	var payment_term = '<?php echo count($this->payment_term);?>';
	var service = '<?php echo $this->all_service; ?>';
	var col = 0;
	var no = 0;
	var title = 0;
	tmp = '';
	temp='';
	function addRow() {
			col++;no++;
			template='';
			if(title!=1){
				temp+='<th><?php echo $tr->translate("DEL");?></th>';
				temp+='<th><?php echo $tr->translate("N_O");?></th>';
				temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("SERVICES");?></th>';
				temp+='<th><?php echo $tr->translate("REMARK");?></th>';
				temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("AMOUNT");?></th>';
				temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("PRICE");?></th>';
				temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("DISCOUNT");?></th>';
				temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("SUBTOTAL");?></th>';
				
				dojo.query("#head-title").append(temp);
				title=1;
			}
				template+='<td width="50px" align="center"><img onclick="deleteRecord('+col+');calculateDiscount('+col+');" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
				template+='<td width="50px" align="center">'+no+'</td>';
				template+='<td width="300px"><select class="fullside" onchange="getprice('+col+');"  dojoType="dijit.form.FilteringSelect" id="service_'+col+'" name="service_'+col+'">'+service+'</select></td>';			
				template+='<td width="600px"> <input type="text" class="fullside" name="remark'+col+'" value="" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ"  /><label id="subsub"></label></td>';
				column = 0;
				template+='<td width="250px"> <input class="fullside" type="text" onkeyup="calculateDiscount('+col+');getValidate('+col+');" name="qty_'+col+'" value="1" id="qty_'+col+'" dojoType="dijit.form.NumberTextBox" /><label id="qty"></label></td>';
				template+='<td width="250px"> <input class="fullside" type="text" required="true" onkeyup="calculateDiscount('+col+');" name="price_'+col+'" value="" id="price_'+col+'" dojoType="dijit.form.NumberTextBox" /><label id="subsub"></label></td>';
				template+='<td width="250px"> <input class="fullside" type="text"  onkeyup="calculateDiscount('+col+');" value="<?php echo 0;?>"  name="discount_'+col+'" id="discount_'+col+'" dojoType="dijit.form.NumberTextBox" /><label id="subsub"></label></td>';
				template+='<td width="250px"> <input class="fullside" type="text" readonly="readonly" name="subtotal_'+col+'" value="" id="subtotal_'+col+'" dojoType="dijit.form.NumberTextBox" /><label id="qty"></label></td>';
				
			tmp='<tr id="row'+col+'">';
			tmp+="</tr>";
			dojo.query("#table_row").append(tmp);
			if($("#identity").val()!="") {
				var identity = $("#identity").val();
				$("#identity").val(identity+','+col);
			} else {$("#identity").val(col);}
			dojo.html.set(dojo.byId("row"+col),template , {
				 parseContent: true,
			});
	 }
	 
	function calculateDiscount(index){
			price = dijit.byId('price_'+index).get('value');
			qty = dijit.byId('qty_'+index).get('value');
			qty=isNaN(qty)?1:qty;
			if(qty==1){dijit.byId('qty_'+index).attr('value',qty);}
			total = price*qty;
			
			discount = dijit.byId('discount_'+index).get('value');
			discount=isNaN(discount)?0:discount;
			dijit.byId('subtotal_'+index).attr('value',total-(total*discount/100));
			//dijit.byId('paidamount_'+index).attr('value',total-(total*discount/100));
			netTotal();
	}
	
	function netTotal() {
		var netTotal=0;
		var rowId = $('#identity').val();
		var rowIDArray = rowId.split(',');
		for(var n = 0; n < rowIDArray.length; n++) {
			netTotal += dijit.byId('subtotal_'+rowIDArray[n]).get('value');
		}
		dijit.byId('grand_total').attr('value',netTotal);
		ex_rate = dijit.byId('ex_rate').get('value');
		dijit.byId('convert_to_riels').attr('value',netTotal * ex_rate);
		
		readMoneyInKhmer(netTotal.toFixed(2));
	}
	
	
	function readMoneyInKhmer(netTotal){
		//alert(netTotal);
		var str = netTotal.toString();
		str_cent = 'សេន';
		first_decimal = str.substr(-2);
		last_decimal = str.substr(-1);
		if(first_decimal>0){string='និង';}else{string="";str_cent=""}
		if(first_decimal!='00' && first_decimal<10 ){str_zero = "សូន្យ";}else{str_zero='';}
		first_money_decimal = read_in_khmer_from_10_to_99(first_decimal);
		last_money_decimal = read_in_khmer_from_0_to_9(last_decimal)
		money_khmer=read_money_in_khmer(netTotal);

		if(first_decimal>0){string_en='និង';}else{string_en="";str_cent_en=""}
		if(first_decimal!='00' && first_decimal<10 ){str_zero_en = "Zero";}else{str_zero_en='';}
		first_money_decimal_en = read_in_english_from_10_to_99(first_decimal);
		last_money_decimal_en = read_in_english_from_0_to_9(last_decimal)
		money_english=read_money_in_english(netTotal);
		read_eng = money_english.trim()+string+ first_money_decimal+str_zero+last_money_decimal+'ដុល្លាគត់'

		read_eng = '( '+money_english.trim()+string_en+ first_money_decimal_en+str_zero_en+last_money_decimal_en+' Dollar Only )'
		
		dijit.byId('readmoney').attr('value',money_khmer.trim()+string+ first_money_decimal+str_zero+last_money_decimal+'ដុល្លាគត់');
	}

	var url_price = "<?php echo $this->url(array('module'=>'registrar','controller'=>'uniformandbook','action'=>'get-price'));?>";
	function getprice(index){
		service_price = dijit.byId('service_'+index).get('value');
		//alert(service_price);
		dojo.xhrPost({
			url:url_price,
			content:{
				'service_price':service_price,
				},
			handleAs:"json",
			load: function(data) {
				//alert(data);
				dijit.byId("price_"+index).attr("value",data);
				calculateDiscount(index);
			},
			error: function(err) {
				alert(err);
			}
		});
	}

	var url_student_info = "<?php echo $this->url(array('module'=>'registrar','controller'=>'uniformandbook','action'=>'get-student')); ?>";
	function getStudentInfo(){
				studentid = dijit.byId('stu_name').get('value');
				dojo.xhrPost({
					url:url_student_info,
					content:{
						'studentid':studentid
						},
					handleAs:"json",
					load: function(data) {
						//alert(data);
						//alert(data.sex);
						dijit.byId("kh_name").attr("value",data.stu_khname);
						dijit.byId("en_name").attr("value",data.stu_enname);
						dijit.byId("sex").attr("value",data.sex);
						dijit.byId("phone").attr("value",data.tel);
						//alert(data);
						//dijit.byId("price_"+key).attr("value",data.price_fee);
					},
					error: function(err) {
						alert(err);
					}
				});
	}
	function setID(type){
		if(type==1){
			dijit.byId('stu_name').attr('value',dijit.byId('studentid').get('value')); 
		}else{
			dijit.byId('studentid').attr('value',dijit.byId('stu_name').get('value')); 
		}
	}
	function initailize(){
		<?php if(!empty($this->rows)){
			foreach($this->rows as $row){
		?>
		col++;no++;
		template='';
		if(title!=1){
			temp+='<th><?php echo $tr->translate("DEL");?></th>';
			temp+='<th><?php echo $tr->translate("N_O");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("SERVICES");?></th>';
			temp+='<th><?php echo $tr->translate("REMARK");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("AMOUNT");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("PRICE");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("DISCOUNT");?></th>';
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("SUBTOTAL");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
			template+='<td width="50px" align="center"><img onclick="" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td width="50px" align="center">'+no+'</td>';
			template+='<td width="300px"><select onchange="" readOnly class="fullside" dojoType="dijit.form.FilteringSelect" id="service_'+col+'" name="service_'+col+'">'+service+'</select></td>';	
			template+='<td width="600px"> <input type="text" readOnly class="fullside" name="remark'+col+'" value="" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ" /><label id="subsub"></label></td>';		
			column = 0;
			template+='<td width="250px"> <input type="text" readOnly style="width: 100%;" class="fullside" onkeyup="calculateDiscount('+col+',1);getValidate('+col+');" name="qty_'+col+'" value="" id="qty_'+col+'" dojoType="dijit.form.NumberTextBox" /><label id="qty"></label></td>';
			template+='<td width="250px"> <input type="text" readOnly style="width: 100%;" class="fullside" required="true" onkeyup="calculateDiscount('+col+',1);" name="price_'+col+'" value="" id="price_'+col+'" dojoType="dijit.form.NumberTextBox" /><label id="subsub"></label></td>';
			template+='<td width="250px"> <input type="text" readOnly style="width: 100%;" class="fullside" onkeyup="calculateDiscount('+col+',1);" value=""  name="discount_'+col+'" id="discount_'+col+'" dojoType="dijit.form.NumberTextBox" /><label id="subsub"></label></td>';
			template+='<td width="250px"> <input type="text" style="width: 100%;" class="fullside" readonly="readonly" name="subtotal_'+col+'" value="" id="subtotal_'+col+'" dojoType="dijit.form.NumberTextBox"/><label id="qty"></label></td>';
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);
		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
			 parseContent: true,
		});
		
		dijit.byId('service_'+col).attr('value','<?php echo $row['service_id']?>');
		dijit.byId('price_'+col).attr('value','<?php echo $row['fee']?>');
		dijit.byId('qty_'+col).attr('value','<?php echo $row['qty']?>');
		dijit.byId('discount_'+col).attr('value','<?php echo $row['discount_percent']?>');
		dijit.byId('remark'+col).attr('value','<?php echo $row['note']?>');
		dijit.byId('subtotal_'+col).attr('value','<?php echo $row['subtotal']?>');
		<?php } }?>
	}

	function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
	}
</script>
	
	