<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('របាយការណ៏ សិស្ស'); 
	echo $this->headTitle(''); 
	$frm =  $this->form_search;
// 	$degree=$this->rs['degree'];
// 	echo $degree;exit();
?>	
<div style="width: 30cm;margin: 0 auto;">
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'allstudent','action'=>'rpt-all-student')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		
		<table width="80%">
	       <tr>
	           <td><?php echo $frm->getElement("title");?></td>
	           <td> <?php echo $frm->getElement("study_year");?></td>
	           <td> <?php echo $frm->getElement("grade_all");?></td>
			   <td> <?php echo $frm->getElement("session");?></td>
			   <td>
					<select name="stu_type" id="stu_type" type="text" class="fullside" dojoType="dijit.form.FilteringSelect" >
						<option value="-1" <?php if($this->search['stu_type']==-1){echo 'selected="selected"';}?>> All Students </option>
						<option value="0" <?php if($this->search['stu_type']==0){echo 'selected="selected"';}?>> Old Students </option>
						<option value="1" <?php if($this->search['stu_type']==1){echo 'selected="selected"';}?>> New Students </option>
						<option value="2" <?php if($this->search['stu_type']==2){echo 'selected="selected"';}?>> Drop Students </option>
						<option value="3" <?php if($this->search['stu_type']==3){echo 'selected="selected"';}?>> Comeback Students </option>
					</select>
				</td>
			</tr>
			<tr>
				<td><input dojoType="dijit.form.DateTextBox" class="fullside"  id="start_date" name="start_date" placeholder="Search....." value="<?php echo $this->search['start_date'];?>" type="text"></td>
				<td><input dojoType="dijit.form.DateTextBox" class="fullside"  id="end_date" name="end_date"  value="<?php echo $this->search['end_date'];?>" type="text"></td>
				<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button></td>

		 	</tr>
		</table>		
</form>
</div>
	<div style="border: 1px dotted #000;background: #fff;width:29cm;margin: 0 auto;min-height: 27cm;padding: 0.5cm;">
		<div id="divPrint">
			<table border="0" style="background:#fff; margin: 0 auto; width: 100%; ">
				<tr>
					<td width="28%" >
						<img style="width: 155px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br />
					</td>
					<td width="44%" align="center">
						<strong​​ style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 14px;font-family:'Khmer MEF2';"><?php echo $tr->translate("ALL_STUDENT_REPORT");?></strong>
					</td>
					<td width="28%" align="right">
						<strong>&nbsp;</strong>
					</td>
				</tr>
				<tr>
					<td width="28%" >
						&nbsp;
					</td>
					<td width="44%" align="center">
						<strong​​ style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">From  <?php echo date('d-M-Y',strtotime($this->search['start_date']));?>  To   <?php echo $this->search['end_date'];?> </strong><br />
					</td>
					<td width="28%" align="right">
						<strong>&nbsp;</strong>
					</td>
				</tr>
				
			<style>
				table tr th{
					border: 1px solid #000;	
				}
				
			</style>
			
				<tr>
					<td colspan="3">
					<div id="exportExcel">
						<table cellpadding="4"​ style="font-family:'Khmer OS Battambang' ; margin:0 auto;width:100%;border:1px solid #000; border-collapse: collapse;white-space: nowrap;"  border="1" >
							<tr style="font-size:11px; height: 20px;" align="center" >
								<td rowspan="2">No.</td>
								<td rowspan="2">Student Code</td>
								<td rowspan="2">Name</td>
								<td rowspan="2">Sex</td>
								<td rowspan="2">Nationality</td>
								<td rowspan="2">Tel</td>
								<td rowspan="2">Email</td>
								<td colspan="5">Study Info</td>
							</tr>
							<tr style="font-size:11px; height: 20px;" align="center" >
								<td >AcademicYear</td>
								<td >Degree</td>
								<td >Grade</td>
								<td >Session</td>
								<td >Status</td>
							</tr>
						<?php $i=0;$degree=0; foreach ($this->rs AS $row) { $i++;$degree=$row['degree'];?>
							
							<tr style="font-size:11px; height: 23px;" align="center" >
								<td ><?php echo $i;?></td>
								<td ><?php echo $row['stu_code'];?></td>
								<td align="left">&nbsp;<?php echo $row['name'];?>&nbsp;</td>
								<td ><?php echo $row['sex'];?></td>	
								<td ><?php echo $row['nationality'];?></td>
								<td ><?php echo $row['tel'];?></td>
								<td align="left">&nbsp;<?php echo $row['email'];?></td>
								
								
								<td ><?php echo $row['academic_year'];?></td>
								<td ><?php echo $row['degree'];?></td>
								<td align="left">&nbsp;<?php echo $row['grade'];?></td>
								<td ><?php echo $row['session'];?></td>	
								<td style="color: red;"><?php echo $row['status'];?></td>	
								
							</tr>
						<?php }?>	
						</table>	
					</div>	
					</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr >
					<td colspan="3">
						<table width="100%">
							<tr>
								<td align="center" width="25%">
									<span style="font-size: 14px;"><?php echo $tr->translate("APPROVED_BY"); ?></span>
								</td>
								<td align="center" width="25%">
									<span style="font-size: 14px;"><?php echo $tr->translate("VERIFIED_BY"); ?></span>
								</td>
								<td align="center" width="25%">
									<span style="font-size: 14px;"><?php echo $tr->translate("CHECKED_BY"); ?></span>
								</td>
								<td align="center"  width="25%">
									<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate("PREPARED_BY"); ?></span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</div>
	</div>
	
	
	
	
	
	