<!DOCTYPE html>
<head>
   <meta charset="utf-8" />
   <title>Enrollment Management System</title>
   <meta content="width=device-width, initial-scale=1.0" name="viewport" />
   <meta content="" name="description" />
   <meta content="" name="author" />
   <link href="<?php echo $this->baseUrl()?>/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/assets/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/assets/bootstrap/css/bootstrap-fileupload.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/css/style.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/css/style-responsive.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/css/style-default.css" rel="stylesheet" id="style_color" />
   <link rel="shortcut icon" href="<?php echo $this->baseUrl()?>/images/icon.ico" type="image/x-icon"/>
<style>

ul, ol {
    padding: 0;
     margin: 0px !important;}
.container-fluid {
    padding-right: 15px;
    padding-left: 15px;
}
</style>
<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$register=$this->url(array('module'=>'registrar','controller'=>'register','action'=>'add'), null, true);
$shortcoursereg=$this->url(array('module'=>'registrar','controller'=>'coursestudy','action'=>'add'), null, true);
$servicepayment=$this->url(array('module'=>'registrar','controller'=>'studentservicepayment','action'=>'add'), null, true);
$studentlunchpayment=$this->url(array('module'=>'registrar','controller'=>'studentlunchpayment','action'=>'add'), null, true);
$studentproductpayment=$this->url(array('module'=>'registrar','controller'=>'uniformandbook','action'=>'add'), null, true);

$studnetpaymentreport=$this->url(array('module'=>'registrar','controller'=>'allreports','action'=>'index'), null, true);
$nearlypaymentalert=$this->url(array('module'=>'registrar','controller'=>'studentnearlyendservice','action'=>'index'), null, true);
$paymentlate=$this->url(array('module'=>'registrar','controller'=>'studentpaymentlate','action'=>'index'), null, true);

$student_register=$this->url(array('module'=>'foundation','controller'=>'register','action'=>'add'), null, true);
$tuition_fee=$this->url(array('module'=>'accounting','controller'=>'fee','action'=>'index'), null, true);
$service_fee=$this->url(array('module'=>'accounting','controller'=>'servicecharge','action'=>'index'), null, true);
$service_name=$this->url(array('module'=>'accounting','controller'=>'service','action'=>'index'), null, true);
$stopservice=$this->url(array('module'=>'accounting','controller'=>'suspendservice','action'=>'index'), null, true);

$rpt_dailypayment=$this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-studentpayment'), null, true);
$rpt_paymentdetail=$this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-studentpaymentdetail'), null, true);

$rpt_servicefee=$this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-service-charge'), null, true);
$rpt_service_fee=$this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-fee'), null, true);
$rpt_paymentdetailby=$this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-paymentdetailbytype'), null, true);

$rpt_suspend =$this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-suspendservice'), null, true);
$rpt_studentbalance=$this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rptstudentbalance'), null, true);
$rpt_expectincome=$this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rptexpectincome'), null, true);

$rpt_nearly=$this->url(array('module'=>'allreport','controller'=>'loan','action'=>'rptstudentnearlyendservice'), null, true);
$rpt_paymenlate=$this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rptstudentpaymentlate'), null, true);
$rpt_calculate = $this->url(array('module'=>'registrar','controller'=>'calculator','action'=>'index'), null, true);
?>
<style type="text/css">
.metro-nav {
    font-family: 'Kh Battambang','Khmer Battambang' !important;
}
</style>
</head>
<body class="fixed-top" style="font-family:'Kh Battambang','Khmer Battambang' !important;">
   <div id="container" class="row-fluid" style="margin: 0 auto; background: #cfddf5;height: 100%; padding:10px 0px;">
         <div class="container-fluid">
            <!-- BEGIN PAGE CONTENT-->
            <div class="row-fluid">
                <!--BEGIN METRO STATES-->
                <div class="metro-nav metro-fix-view">
                     <div class="metro-nav-block double" style="background:#ec920e;">
                        <a href="<?php echo $register;?>" style="text-align: center;" class="text-center" data-original-title="">
                            <span class="value">
                                <i class="icon-user"></i>
                            </span>
                        </a>
                         <div class="status" align="center"><?php echo $tr->translate('STUDENT_REGISTRATION');?></div>
                    </div>
                    <div class="metro-nav-block double" style="background:#8d3e03;">
                        <a href="<?php echo $shortcoursereg;?>" data-original-title="">
                            <i class="icon-user"></i>
                            <div class="info"></div>
                            <div class="status"><?php echo $tr->translate('STUDENT_COURSE');?></div>
                        </a>
                    </div>
                   <div class="metro-nav-block double" style="background:#ec0e0e;">
                       <a href="<?php echo $servicepayment;?>" data-original-title="">
                           <i class="icon-user"></i>
                           <div class="info"></div>
                           <div class="status"><?php echo $tr->translate('STUDENT_SERVICE_PAYMENT');?></div>
                       </a>
                   </div>
                   <div class="metro-nav-block double" style="background:#0e90ec;">
                       <a href="<?php echo $studentlunchpayment;?>" data-original-title="">
                           <i class="icon-user"></i>
                           <div class="info"></div>
                           <div class="status"><?php echo $tr->translate('STUDENT_LUNCH_PAYMENT');?></div>
                       </a>
                   </div>
                   <div class="metro-nav-block double" style="background:#6d0eec;">
                       <a href="<?php echo $studentproductpayment;?>" data-original-title="">
                           <i class="icon-user"></i>
                           <div class="info"></div>
                           <div class="status"><?php echo $tr->translate('STUDENT_STUDY_MATERIAL_PAYMENT');?></div>
                       </a>
                   </div>
                   
                </div>
                <!--END METRO STATES-->
            </div>
            <!-- END PAGE CONTENT-->
            
            
            <div style="height: 380px;width: 49%;overflow: scroll;background: #f2f2f2;">
		   		<table width="100%" >
	   				<tr>
		   				<td>
		   					<fieldset>
	   							<legend align="center" style="font-size: 15px;margin: 0;"><?php echo $tr->translate("STUDENT_NEARLY_END_SERVICE");?></legend>
	   							<?php if(!empty($this->row)){?>
	   							<table width="100%" border="1" style="border: 1px solid #000;border-collapse: collapse;max-height: 370px;white-space: nowrap;color: #000;">
	   								<tr style="font-size:12px; height: 20px;border: 1px solid #000; background: #ccc; line-height: 30px; font-weight: bold;" align="center" >
										<td>&nbsp;<?php echo $tr->translate("N_O"); ?>&nbsp;</td>
									    <td>&nbsp;<?php echo $tr->translate("STUDENT_ID"); ?>&nbsp;</td>
										<td>&nbsp;<?php echo $tr->translate("STUDENT_NAME"); ?>&nbsp;</td>
										<td style="border: 1px solid #000;">&nbsp;<?php echo $tr->translate("PHONE"); ?>&nbsp;</td>
										<td style="border: 1px solid #000;">&nbsp;<?php echo $tr->translate("GRADE"); ?>&nbsp;</td>
										<td style="border: 1px solid #000;"><?php echo $tr->translate("SERVICE_NAME"); ?></td>
										<td style="border: 1px solid #000;"><?php echo $tr->translate("PAID_DATE"); ?></td>
										<td style="border: 1px solid #000;"><?php echo $tr->translate("VALIDATE"); ?></td>
										<td style="border: 1px solid #000;"><?php echo $tr->translate("AMOUNT_DAY"); ?></td>
									</tr>
	   								<?php $i=0;$stu_name = ""; foreach ($this->row as $rs){
	   								
	   									$i++;
	   									$stu_name=$rs['stu_khname'];
	   									if(empty($stu_name)){
	   										$stu_name = $rs['stu_enname'];
	   									}
	   									
	   									$end_dat=date("Y-m-d");
	   									$total_day=strtotime($end_dat)-strtotime($rs['end']);
	   									$day = $total_day/(60*60*24);
	   									
	   									if($rs['payfor_type']==3){
	   										$stu_code = $rs['transport_code'];
	   									}else if($rs['payfor_type']==4){
	   										$stu_code = $rs['lunch_code'];
	   									}else{
	   										$stu_code = $rs['stu_code'];
	   									}
	   								?>
	   								<tr style="font-size:11px; height: 20px;border: 1px solid #000;" align="center" class="hover" >
										<td style="border: 1px solid #000;"><?php echo $i;?></td>
										<td style="border: 1px solid #000;">&nbsp;<?php echo $stu_code;?>&nbsp;</td>
										<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $stu_name;?></td>	
										<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $rs['tel'];?></td>
										<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $rs['grade'];?></td>
										<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $rs['service'];?></td>
										<td style="border: 1px solid #000;">&nbsp;<?php echo date("d-M-Y",strtotime($rs['start']));?>&nbsp;</td>
										<td style="border: 1px solid #000;color: red;">&nbsp;<?php echo date("d-M-Y",strtotime($rs['end']));?>&nbsp;</td>
										<?php if($day>=0){
											$daylate ="Late ".abs($day);
										}else{
											$daylate ="Remain ".abs($day);
										}?>
										<td align="center" style="border: 1px solid #000;color: red;font-weight: bold;">&nbsp;<?php echo ($daylate);?> days</td>
			 						</tr>
	   								<?php }}?>
	   							</table>
	   							
		   					</fieldset>
		   				</td>
		   			</tr>
		   		</table>
		    </div>
		    
		    
		    
         </div>
         <!-- END PAGE CONTAINER-->
         
     	
	   
      <!-- END PAGE -->  
   </div>
   <!-- END CONTAINER -->
   <!-- BEGIN JAVASCRIPTS -->
   <!-- Load javascripts at bottom, this will reduce page load time -->
   
   
   <script src="<?php echo $this->baseUrl()?>/js/jquery-1.8.3.min.js"></script>
   <script src="<?php echo $this->baseUrl()?>/js/jquery.nicescroll.js" type="text/javascript"></script>
   <script src="<?php echo $this->baseUrl()?>/assets/bootstrap/js/bootstrap.min.js"></script>
   <script src="<?php echo $this->baseUrl()?>/js/common-scripts.js"></script>
</body>
<!-- END BODY -->
</html>