<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle('Other Income'); 
	
?>	
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'submitdailyincome','action'=>'other-income')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table width="100%" style="margin: 0 auto;">
			<tr>
				<td>
				</td>
			</tr>
		</table>			
</form>