<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("ADD_RENTAL_PAYMENT"));
	//print_r($this->reil);
?>	
<style>
 
</style>
<script type="text/javascript" src="js/dojo/dojo.js" djConfig="isDebug: true, parseOnLoad: true"></script>
<script type="text/javascript">
    dojo.require("dojo.NodeList-manipulate");
    dojo.require("dojo.parser");
    dojo.require("dijit.form.Textarea");
    dojo.require("dijit.form.CheckBox");
    dojo.require("dojox.form.BusyButton");
</script>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
dojo.require("dojo.data.ItemFileWriteStore");
</script>
<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>
<form  id='frm_rent_payment' action="" dojoType="dijit.form.Form" method="post"  enctype="multipart/form-data" >
<script type="dojo/method" event="onSubmit" enctype="multipart/form-data">			
	if(this.validate()) {
               dijit.byId('save_new').set('disabled',true);
			   dijit.byId('save_close').set('disabled',true);
			   return true;
			} else {
				return false;
			}
</script>
<table cellspacing="2" width="100%" style="margin: 0 auto; ">
	<tr>
		<td width="33%;" valign="top">
			<fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("CUSTOMER_INFO")?></strong></legend>
				<table style="margin: 0 auto; width: 100%;text-align: right;" cellspacing="2"  >
				        <tr>
							<td><?php echo $tr->translate("OLD_CUS");?></td>
							<td align="left" style="height: 0px;"> <input type="checkbox" name="is_new_cu" id="is_new_cu" value="1" onClick="hidendOldCus();" ></td> 
						</tr>
						<tr>
							<td><?php echo $tr->translate("CUS_ID");?></td>
							<td><input type="text" name="cus_id" class="fullside" id="cus_id"  style="color:red;" dojoType="dijit.form.ValidationTextBox" required="required" value="<?php echo $this->cus_id;?>"/> </td> 
						</tr>
						<tr>
							<td><?php echo $tr->translate("CUS_NAME");?></td>
							<td>
							  <div id="cus_name_div">
								<input type="text" name="cus_name" class="fullside" id="cus_name"   dojoType="dijit.form.ValidationTextBox" required="required"/> 
							  </div>
							    <!-- old Customer  -->
							    <div id="old_cus_div">
									<select dojoType='dijit.form.FilteringSelect' id="old_cus" name="old_cus"   class="fullside"  ​​ onChange="getOldCustomerInfo();setCusName();" placeholder=" ">
							   			<option value="0"><?php echo $tr->translate("SELECT_CUSTOMER_NAME");?></option>
							   			<?php if(!empty($this->cus)) foreach ($this->cus as $c){?>
							   			<option value="<?php echo $c['id']?>" ><?php echo $c['cus_name']?> </option>
							   			<?php }?>
						   			</select>
						   		</div>
					   			<!-- /end old Customer  -->
							</td>
						</tr>
						<tr>
						    <td><?php echo $tr->translate("SEX");?></td>
							<td>
								<select dojoType='dijit.form.FilteringSelect' id="sex" name="sex"   class="fullside"  ​​  placeholder=" ">
						   			<option value="1"><?php echo $tr->translate("MALE");?></option>
						   			<option value="2"><?php echo $tr->translate("FEMALE");?> </option>
					   			</select>
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("PHONE");?></td>
							<td><input type="text" name="phone" class="fullside" id="phone"   dojoType="dijit.form.TextBox" /> </td>
					    </tr>
					    <tr>
							<td><?php echo $tr->translate("START_DATE");?></td>
							<td><input type="text" name="start_date" class="fullside" id="start_date"   dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now"/> </td>
					    </tr>
					    <tr>
							<td><?php echo $tr->translate("END_DATE");?></td>
							<td><input type="text" name="end_date" class="fullside" id="end_date"   dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now"/> </td>
					    </tr>
					    <tr>
							<td><?php echo $tr->translate("EMAIL");?></td>
							<td><input type="text" name="email" class="fullside" id="email"   dojoType="dijit.form.TextBox" /> </td>
					    </tr>
					    <tr>
							<td><?php echo $tr->translate("ADDRESS");?></td>
							 <td><textarea class="fullside"  style=" height: 30px !important;" tabindex="20" dojoType=""  id="address" name="address"  ></textarea> </td>  
					    </tr>
				</table>	
			</fieldset>	
		</td>
		<td width="33%;" valign="top">
			<fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("WATER_INFO")?></strong></legend>
				<table style="margin: 0 auto; width: 100%;text-align: right;" cellspacing="2"  >
						<tr>
							<td><?php echo $tr->translate("OLd_CONGTOR");?></td>
							<td><input type="text" name="water_old_congtor" class="fullside" id="water_old_congtor"   dojoType="dijit.form.NumberTextBox" required="required" onkeyup="getQtyPariceWater();"/> </td> 
						</tr>
						<tr>
							<td><?php echo $tr->translate("NEW_CONGTOR");?></td>
							<td><input type="text" name="water_new_congtor" class="fullside" id="water_new_congtor"   dojoType="dijit.form.NumberTextBox" required="required" onChange="getQtyPariceWater();"/> </td>
						</tr>
						<tr>
						    <td><?php echo $tr->translate("QUANTITY");?>(M<sup>3</sup>)</td>
							<td><input type="text" name="water_qty" class="fullside" id="water_qty"   dojoType="dijit.form.NumberTextBox" readonly="true" /> </td> 
						</tr>
						<tr>
							<td><?php echo $tr->translate("COST");?>(៛)</td>
							<td><input type="text" name="water_cost" class="fullside" id="water_cost"   dojoType="dijit.form.NumberTextBox" onKeyup="getQtyPariceWater();"/> </td>
					    </tr>
					    <tr>
							<td><?php echo $tr->translate("TOTAL");?>(៛)</td>
							<td><input type="text" name="water_total" class="fullside" id="water_total"   dojoType="dijit.form.NumberTextBox" readOnly="true" /> </td>
					    </tr>
					    <tr>
							<td><?php echo $tr->translate("START_DATE");?></td>
							<td><input type="text" name="water_start_date" class="fullside" id="water_start_date"   dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now"/> </td>
					    </tr>
					    <tr>
							<td><?php echo $tr->translate("END_DATE");?></td>
							<td><input type="text" name="water_end_date" class="fullside" id="water_end_date"   dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now"/> </td>
					    </tr>
					    <tr>
					        <td><?php echo $tr->translate("EXC_RATE");?>($)</td>
					        <td><input type="text" name="water_exc_rate" class="fullside" id="water_exc_rate"   dojoType="dijit.form.NumberTextBox" onKeyup="getQtyPariceWater();" placeholder="" readOnly="true"/></td>
					    </tr>
				</table>
					
			</fieldset>	
		</td>
		<td width="33%;" valign="top">
			<fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("FIRE_INFO")?></strong></legend>
				<table style="margin: 0 auto; width: 100%;text-align: right;" cellspacing="2"  >
						<tr>
							<td><?php echo $tr->translate("OLd_CONGTOR");?></td>
							<td><input type="text" name="fire_old_congtor" class="fullside" id="fire_old_congtor"   dojoType="dijit.form.NumberTextBox" required="required" onKeyup="getQtyPariceFire();"/> </td> 
						</tr>
						<tr>
							<td><?php echo $tr->translate("NEW_CONGTOR");?></td>
							<td><input type="text" name="fire_new_congtor" class="fullside" id="fire_new_congtor"   dojoType="dijit.form.NumberTextBox" required="required" onChange="getQtyPariceFire();"/> </td>
						</tr>
						<tr>
						    <td><?php echo $tr->translate("QUANTITY");?>(M<sup>3</sup>)</td>
							<td><input type="text" name="fire_qty" class="fullside" id="fire_qty"   dojoType="dijit.form.NumberTextBox" readonly="true" /> </td> 
						</tr>
						<tr>
							<td><?php echo $tr->translate("COST");?>(៛)</td>
							<td><input type="text" name="fire_cost" class="fullside" id="fire_cost"   dojoType="dijit.form.NumberTextBox" onKeyup="getQtyPariceFire();"/> </td>
					    </tr>
					    <tr>
							<td><?php echo $tr->translate("TOTAL");?>(៛)</td>
							<td><input type="text" name="fire_total" class="fullside" id="fire_total"   dojoType="dijit.form.NumberTextBox" readOnly="true"/> </td>
					    </tr>
					    <tr>
							<td><?php echo $tr->translate("START_DATE");?></td>
							<td><input type="text" name="fire_start_date" class="fullside" id="fire_start_date"   dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now"/> </td>
					    </tr>
					    <tr>
							<td><?php echo $tr->translate("END_DATE");?></td>
							<td><input type="text" name="fire_end_date" class="fullside" id="fire_end_date"   dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now"/> </td>
					    </tr>
					    <tr>
					         <td><?php echo $tr->translate("EXC_RATE");?>($) </td>
					         <td><input type="text" name="fire_exc_rate" class="fullside" id="fire_exc_rate"   dojoType="dijit.form.NumberTextBox" onKeyup="getQtyPariceWater();" readOnly="true"/>    </td>
					    </tr>
				</table>	
			</fieldset>	
		</td>
	</tr>
	<tr>
		<td width="33%;" valign="top">
			<fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("​ទូទាត់សេវាជួលតូប")?></strong></legend>
				<table style="margin: 0 auto; width: 100%;text-align: right;" cellspacing="2"  >
						<tr>
							<td><?php echo $tr->translate("ថ្ងៃបង់ប្រាក់");?></td>
							<td><input type="text" name="rent_date" class="fullside" id="rent_date"   dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now" /> </td> 
						</tr>
						<tr>
							<td><?php echo $tr->translate("លេខបង្កាន់ដៃ");?></td>
							<td><input type="text" name="receipt_no" class="fullside" id="receipt_no" style="color:red;"  dojoType="dijit.form.ValidationTextBox" required="required" value="<?php echo $this->receipt_no;?>"/> </td>
						</tr>
						<tr>
						    <td><?php echo $tr->translate("ទឹកប្រាក់");?>($)</td>
							<td><input type="text" name="rent_paid" class="fullside" id="rent_paid" value="0"  dojoType="dijit.form.NumberTextBox"  onKeyup="getTotal();"/> </td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ថ្ងៃចាប់ផ្តើម");?></td>
							<td><input type="text" name="rent_start_date" class="fullside" id="rent_start_date"   dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now"/> </td>
					    </tr>
					    <tr>
							<td><?php echo $tr->translate("ថ្ងៃផុតកំណត់");?></td>
							<td><input type="text" name="rent_end_date" class="fullside" id="rent_end_date"   dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now"/> </td>
					    </tr>
				</table>	
			</fieldset>	
		</td>
		<td width="33%;" valign="top">
			<fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("ទូទាត់សេវាអនាម័យ")?></strong></legend>
				<table style="margin: 0 auto; width: 100%;text-align: right;" cellspacing="2"  >
						<tr>
							<td><?php echo $tr->translate("តម្លៃ");?>($)</td>
							<td><input type="text" name="hygiene_price" class="fullside" id="hygiene_price"  value="0" dojoType="dijit.form.NumberTextBox" onKeyup="getTotal();"/> </td> 
						</tr>
						<tr>
							<td><?php echo $tr->translate("ថ្ងៃចាប់ផ្តើម");?></td>
							<td><input type="text" name="hygiene_start_date" class="fullside" id="hygiene_start_date"   dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now"/> </td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ថ្ងៃផុតកំណត់");?></td>
							<td><input type="text" name="hygiene_end_date" class="fullside" id="hygiene_end_date"   dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now" /> </td>
					    </tr>
					    <tr>
							<td><?php echo $tr->translate("NOTE");?></td>
							<td><input type="text" name="hygiene_note" class="fullside" id="hygiene_note"   dojoType="dijit.form.TextBox" /> </td> 
						</tr>
				</table>	
			</fieldset>	
		</td>
	
		<td width="33%;" valign="top">
			<fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("OTHERS")?></strong></legend>
				<table style="margin: 0 auto; width: 100%;text-align: right;" cellspacing="2"  >
						<tr>
							<td><?php echo $tr->translate("តម្លៃ");?>($)</td>
							<td><input type="text" name="other_price" class="fullside" id="other_price" value="0"  dojoType="dijit.form.NumberTextBox" onKeyup="getTotal();"/> </td> 
						</tr>
						<tr>
							<td><?php echo $tr->translate("ថ្ងៃចាប់ផ្តើម");?></td>
							<td><input type="text" name="other_start_date" class="fullside" id="other_start_date"   dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now"/> </td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("ថ្ងៃផុតកំណត់");?></td>
							<td><input type="text" name="other_end_date" class="fullside" id="other_end_date"   dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now" /> </td>
					    </tr>
						<tr>
							<td><?php echo $tr->translate("NOTE");?></td>
							<td><input type="text" name="other_note" class="fullside" id="other_note"   dojoType="dijit.form.TextBox" /> </td> 
						</tr>
				</table>	
			</fieldset>
		</td>
	</tr>
	<tr>
		<td width="33%;" valign="top">
			<fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("PAID_AMOUN")?></strong></legend>
				<table style="margin: 0 auto; width: 100%;text-align: right;" cellspacing="2"  >
						<tr>
						    <td><?php echo $tr->translate("ទឹកប្រាក់សរុប");?>($)​</td>
							<td><input type="text" name="all_total_amount" class="fullside" id="all_total_amount"  value="0" dojoType="dijit.form.NumberTextBox" readOnly="true"/> </td> 
						</tr>
						<tr>
							<td><?php echo $tr->translate("ប្រាក់បានបង់");?>($)</td>
							<td><input type="text" name="paid" class="fullside" id="paid" value="0"  dojoType="dijit.form.NumberTextBox" required="true" onKeyup="getTotal()"/> </td>
					    </tr>
					    <tr>
							<td><?php echo $tr->translate("ប្រាក់ជំពាក់");?>($)</td>
							<td><input type="text" name="balance" class="fullside" id="balance" value="0"  dojoType="dijit.form.NumberTextBox" readOnly="true"/> </td>
					    </tr>
					    
					    <tr>
							<td><?php echo $tr->translate("NOTE");?></td>
							<td><input type="text" name="note" class="fullside" id="note"   dojoType="dijit.form.TextBox" /> </td> 
						</tr>
					    
					    <tr>
						    <td><?php echo $tr->translate("STATUS");?></td>
							<td>
								<select dojoType='dijit.form.FilteringSelect' id="status" name="status"   class="fullside"  ​​  placeholder=" ">
						   			<option value="1"><?php echo $tr->translate("ACTIVE");?></option>
						   			<option  value="0"><?php echo $tr->translate("DEACTIVE");?> </option>
					   			</select>
							</td>
						</tr>
					    
				</table>	
			</fieldset>	
		</td>
		
		<td colspan="2">
			<table width="70%">
				<tr>
					<td>
						<input name="readmoney" id="readmoney" type="text" readOnly class="fullside" dojoType="dijit.form.TextBox" />
					</td>
				</tr>
			</table>
		</td>
		
	</tr>
	
	<tr>
		<td colspan="4" align="center" style="padding-left:40px;">
			<input iconClass="dijitIconClear" type="reset" value="clear" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
			<input type="submit" value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" 
				iconClass="dijitEditorIcon dijitEditorIconSave" />
			<input type="submit" value="save_new" name="save_new"  id="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" 
				 iconClass="dijitEditorIcon dijitEditorIconSave" />
				 
			<input type="button" value="បោះពុម្ព" label="<?php echo $tr->translate('PRINT');?>" id="print" dojoType="dijit.form.Button" 
				iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="printSave();"/> 
		</td>
    </tr>
</table>	
</form>
<script>
var reil_exc="<?php echo $this->reil['reil']?>";
$(document).ready(function() {
	hidendOldCus();
});

function hidendOldCus(){
	if($('#is_new_cu').is(':checked')){
		$('#old_cus_div').show();
		$("#cus_name_div").hide();
		dijit.byId("old_cus").attr("value",'0');
	}else {
		$("#cus_name_div").show();
		$('#old_cus_div').hide();
		clearCusOld();
	}
}

function clearCusOld(){
	dijit.byId("water_old_congtor").attr("value","");
	dijit.byId("water_new_congtor").attr("value","");
	dijit.byId("fire_old_congtor").attr("value","");
	dijit.byId("fire_new_congtor").attr("value","");
	dijit.byId("cus_id").attr('value','<?php echo $this->cus_id;?>');
	dijit.byId("cus_name").attr("value","");
	dijit.byId("phone").attr("value","");
	dijit.byId("email").attr("value","");
	$("#address").val("");
}

function setCusName(){
	 dijit.byId("cus_name").attr('value',dijit.byId("old_cus").attr('displayedValue'));
}

//functon water info
function getQtyPariceWater(){
	var old_c=dijit.byId("water_old_congtor").get("value");
	var new_c=dijit.byId("water_new_congtor").get("value");
	dijit.byId("water_qty").attr("value",parseFloat(new_c-old_c));
	if(new_c <= old_c){
		alert("value new number can't smaller then old number! ");
		dijit.byId("water_new_congtor").attr("value",parseFloat(old_c+1));
		new_c=dijit.byId("water_new_congtor").get("value");
		old_c=dijit.byId("water_old_congtor").get("value");
		dijit.byId("water_qty").attr("value",parseFloat(new_c-old_c));
	}

	 if(!isNaN(dijit.byId("water_cost").get("value"))){
		  var qty=dijit.byId("water_qty").get("value");
		  var cost=dijit.byId("water_cost").get("value");
		  dijit.byId("water_total").attr("value",parseFloat(qty*cost));
		  //convert reil to dollar 
		  var reil_total=dijit.byId("water_total").get("value");
		  dijit.byId("water_exc_rate").attr("value",parseFloat(reil_total/reil_exc));
	 }else{
		 dijit.byId("water_total").attr("value",0);
		 dijit.byId("water_exc_rate").attr("value",0);
	 }
	 getTotal();
}

//functon fire info
function getQtyPariceFire(){
	var old_c=dijit.byId("fire_old_congtor").get("value");
	var new_c=dijit.byId("fire_new_congtor").get("value");
	dijit.byId("fire_qty").attr("value",parseFloat(new_c-old_c));
	if(new_c <= old_c){
		alert("value new number can't smaller then old number! ");
		dijit.byId("fire_new_congtor").attr("value",parseFloat(old_c+1));
		new_c=dijit.byId("fire_new_congtor").get("value");
		old_c=dijit.byId("fire_old_congtor").get("value");
		dijit.byId("fire_qty").attr("value",parseFloat(new_c-old_c));
	}

	 if(!isNaN(dijit.byId("fire_cost").get("value"))){
		  var qty=dijit.byId("fire_qty").get("value");
		  var cost=dijit.byId("fire_cost").get("value");
		  dijit.byId("fire_total").attr("value",parseFloat(qty*cost));
		  //convert reil to dollar 
		  var reil_total=dijit.byId("fire_total").get("value");
		  dijit.byId("fire_exc_rate").attr("value",parseFloat(reil_total/reil_exc));
	 }else{
		 dijit.byId("fire_exc_rate").attr("value",0);
		 dijit.byId("fire_total").attr("value",0);
	 }
	 getTotal();
}

//functon get sum money All total
function getTotal(){
	var total=0;
	var water=dijit.byId("water_exc_rate").get("value");
	var fire=dijit.byId("fire_exc_rate").get("value");
	var rent_paid=dijit.byId("rent_paid").get("value");
	var hygiene_price=dijit.byId("hygiene_price").get("value");
	var other_price=dijit.byId("other_price").get("value");
	if(isNaN(water)){
		water=0;
	}
	if(isNaN(fire)){
		fire=0;
	}
	if(isNaN(rent_paid)){
		rent_paid=0;
	}
	if(isNaN(hygiene_price)){
		hygiene_price=0;
	}
	if(isNaN(other_price)){
		other_price=0;
	}
	total=parseFloat(water+fire+rent_paid+hygiene_price+other_price);
	
	dijit.byId("all_total_amount").attr("value",total.toFixed(2));
	
	readMoneyInKhmer(total.toFixed(2));
	
	dijit.byId("paid").attr("value",total.toFixed(2));

	if(!isNaN(dijit.byId("paid").get("value"))){
		var amount=dijit.byId("all_total_amount").get("value");
		var paid=dijit.byId("paid").get("value");
		dijit.byId("balance").attr("value",parseFloat(amount-paid));
		if(amount<paid){
			alert("Paid can't bigger than amount!!!");
			dijit.byId("paid").attr("value",amount.toFixed(2));
			dijit.byId("balance").attr("value",0);
		}
	}else{
		dijit.byId("balance").attr("value",0);
	}
}

function readMoneyInKhmer(netTotal){
	//alert(netTotal);
	var str = netTotal.toString();
	str_cent = 'សេន';
	first_decimal = str.substr(-2);
	last_decimal = str.substr(-1);
	
	if(first_decimal>0){string='ដុល្លា និង ';last_string="សេន"}else{string="";str_cent="";last_string="ដុល្លាគត់";}
	if(first_decimal!='00' && first_decimal<10 ){str_zero = "សូន្យ";}else{str_zero='';}
	first_money_decimal = read_in_khmer_from_10_to_99(first_decimal);
	last_money_decimal = read_in_khmer_from_0_to_9(last_decimal);
	money_khmer=read_money_in_khmer(netTotal);

	if(first_decimal>0){string_en='dot';}else{string_en="";str_cent_en=""}
	if(first_decimal!='00' && first_decimal<10 ){str_zero_en = "Zero";}else{str_zero_en='';}
	first_money_decimal_en = read_in_english_from_10_to_99(first_decimal);
	last_money_decimal_en = read_in_english_from_0_to_9(last_decimal);
	money_english=read_money_in_english(netTotal);
	
	dijit.byId('readmoney').attr('value',money_khmer.trim()+string+ first_money_decimal+str_zero+last_money_decimal+last_string);
}


//get old customer info 
var url_getcusinfo = '<?php echo $this->url(array('module'=>'registrar','controller'=>'customerpayment','action'=>'get-customer-info')); ?>';
function getOldCustomerInfo(){
	var old_cus = dijit.byId("old_cus").get('value');
	if(old_cus==0 || old_cus==''){
		return  false;
	}
	dojo.xhrPost({
		url:url_getcusinfo,
		content:{
			'cus_id':old_cus
			},
		handleAs:"json",
		load: function(data) {
			 //set customer 
			dijit.byId("cus_id").attr("value",data.customer_code); 
			dijit.byId("cus_name").attr("value",data.first_name);	
			dijit.byId("sex").attr("value",data.sex);
			dijit.byId("phone").attr("value",data.phone);
			//dijit.byId("start_date").attr("value",data.start_date);
			//dijit.byId("end_date").attr("value",data.end_date);
			dijit.byId("email").attr("value",data.email);
			$("#address").val(data.address);

			//set water old congtor 
			dijit.byId("water_old_congtor").attr("value",data.water_new_congtor); 
			dijit.byId("water_cost").attr("value",data.water_cost);
			
			//set water old congtor 
			dijit.byId("fire_old_congtor").attr("value",data.fire_new_congtor);
			dijit.byId("fire_cost").attr("value",data.fire_cost);
			
		},
		error: function(err) {
			alert(err);
		}
	});
}
function getMonthByNumber(m){
	var monthName=[
		"Jan",
		 "Feb",
		 "Mar",
		 "Apr",
		 "May",
		 "Jun",
		 "Jul",
		 "Aug",
		 "Sep",
		 "Oct",
		 "Nov",
		 "Dec",
		];
		return (monthName[m-1]);
}

//save daata when sub button print 
function printSubmit(){
	$('#frm_rent_payment').submit();
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
}

function printSave(new_stu_id,new_receipt_no){		
	if(dijit.byId('frm_rent_payment').validate()) {
		 
		 
		 dojo.byId("lb_receipt_no").innerHTML = dijit.byId("receipt_no").get('value');
		 
		 if(document.getElementById('is_new_cu').checked){
			cus_name = dijit.byId("old_cus").attr('displayedValue');
		 }else{
			cus_name = dijit.byId("cus_name").get('value');
		 }
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////		
		
		 dojo.byId("lb_cus_name").innerHTML = cus_name;
		 dojo.byId("lb_sex").innerHTML = dijit.byId("sex").attr('displayedValue');
		 dojo.byId("lb_phone").innerHTML = dijit.byId("phone").attr('displayedValue');
		 
		 dojo.byId("lb_readmoney").innerHTML = dijit.byId("readmoney").attr('displayedValue');
		 
		 dojo.byId("lb_total_payment").innerHTML = " $ "+dijit.byId("all_total_amount").attr('displayedValue');
		 /*
		 var b = new Date(dijit.byId("rent_start_date").get('value'));
			mm = b.getMonth()+1;
			var dd = b.getDate();
			if(dd<10){
				dd = "0"+dd;
			}
			var mon = getMonthByNumber(mm);
			if(mm<10){
				mm = "0"+mm;
			}
			var y = b.getFullYear();
			var start_date = dd + '-' + mon + '-' + y ;
			
		 dojo.byId("lb_start_date").innerHTML = start_date;	
		
		 var a = new Date(dijit.byId("rent_end_date").get('value'));
			mm = a.getMonth()+1;
			var dd = a.getDate();
			if(dd<10){
				dd = "0"+dd;
			}
			var months = getMonthByNumber(mm);
			if(mm<10){
				mm = "0"+mm;
			}
			var y = a.getFullYear();
			var epx_date = dd + '-' +months + '-' + y ;
			
		 dojo.byId("lb_epx_date").innerHTML = epx_date;
		 */
		 //dojo.byId("lb_read_money").innerHTML = dijit.byId('readmoney').get('value');
		 
		 rent_payment = dijit.byId('rent_paid').get('value');
		 if(rent_payment>0){
			dojo.byId("lb_rent_payment").innerHTML = " $ "+rent_payment;
			dojo.byId("checkbox_rent").innerHTML = "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/checked.png'?>'>";
		 
			var date = new Date(dijit.byId("rent_start_date").get('value'));
			mm = date.getMonth()+1;
			var dd = date.getDate();
			if(dd<10){
				dd = "0"+dd;
			}
			var mon = getMonthByNumber(mm);
			if(mm<10){
				mm = "0"+mm;
			}
			var y = date.getFullYear();
			var start_date = dd + '/' + mon + '/' + y ;
			
			dojo.byId("lb_rent_start_date").innerHTML = start_date;
			
			var date = new Date(dijit.byId("rent_end_date").get('value'));
			mm = date.getMonth()+1;
			var dd = date.getDate();
			if(dd<10){
				dd = "0"+dd;
			}
			var mon = getMonthByNumber(mm);
			if(mm<10){
				mm = "0"+mm;
			}
			var y = date.getFullYear();
			var end_date = dd + '/' + mon + '/' + y ;
			
			dojo.byId("lb_rent_end_date").innerHTML = end_date;
		 }else{
			dojo.byId("lb_rent_payment").innerHTML = "";
			dojo.byId("checkbox_rent").innerHTML = "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/uncheck.png'?>'>";
		 
			dojo.byId("lb_rent_start_date").innerHTML = "";
			dojo.byId("lb_rent_end_date").innerHTML = "";
		 }
		 
		 
		 water_payment = dijit.byId('water_exc_rate').get('value');
		 if(water_payment>0){
			dojo.byId("lb_water_payment").innerHTML = " $ "+water_payment;
			dojo.byId("checkbox_water").innerHTML = "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/checked.png'?>'>";
		 
			water_new_congtor = dijit.byId('water_new_congtor').get('value');
			if(water_new_congtor>0){
				
			}else{
				water_new_congtor = "";
			}
			dojo.byId("lb_water_new_congtor").innerHTML = water_new_congtor;
			
			water_old_congtor = dijit.byId('water_old_congtor').get('value');
			if(water_old_congtor>0){
				
			}else{
				water_old_congtor = "";
			}
			dojo.byId("lb_water_old_congtor").innerHTML = water_old_congtor;
			
			water_qty = dijit.byId('water_qty').get('value');
			if(water_qty>0){
				
			}else{
				water_qty = "";
			}
			dojo.byId("lb_water_qty").innerHTML = water_qty;
			
			water_cost = dijit.byId('water_cost').get('value');
			if(water_cost>0){
				water_cost = dijit.byId('water_cost').get('value')+" ៛";
			}else{
				water_cost = "";
			}
			dojo.byId("lb_water_cost").innerHTML = water_cost;
			
			var date = new Date(dijit.byId("water_start_date").get('value'));
			mm = date.getMonth()+1;
			var dd = date.getDate();
			if(dd<10){
				dd = "0"+dd;
			}
			var mon = getMonthByNumber(mm);
			if(mm<10){
				mm = "0"+mm;
			}
			var y = date.getFullYear();
			var start_date = dd + '/' + mon + '/' + y ;
			
			dojo.byId("lb_water_start_date").innerHTML = start_date;
			
			
			var date = new Date(dijit.byId("water_end_date").get('value'));
			mm = date.getMonth()+1;
			var dd = date.getDate();
			if(dd<10){
				dd = "0"+dd;
			}
			var mon = getMonthByNumber(mm);
			if(mm<10){
				mm = "0"+mm;
			}
			var y = date.getFullYear();
			var end_date = dd + '/' + mon + '/' + y ;
			
			dojo.byId("lb_water_end_date").innerHTML = end_date;
		 
		 }else{
			dojo.byId("lb_water_payment").innerHTML = "";
			dojo.byId("checkbox_water").innerHTML = "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/uncheck.png'?>'>";
		 
			dojo.byId("lb_water_new_congtor").innerHTML = "";
			dojo.byId("lb_water_old_congtor").innerHTML = "";
			dojo.byId("lb_water_cost").innerHTML = "";
			dojo.byId("lb_water_start_date").innerHTML = "";
			dojo.byId("lb_water_end_date").innerHTML = "";
		 }
		 
		 fire_payment = dijit.byId('fire_exc_rate').get('value');
		 if(fire_payment>0){
			dojo.byId("lb_fire_payment").innerHTML = " $ "+fire_payment; 
			dojo.byId("checkbox_fire").innerHTML = "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/checked.png'?>'>";
		 
			
			fire_new_congtor = dijit.byId('fire_new_congtor').get('value');
			if(fire_new_congtor>0){
				
			}else{
				fire_new_congtor = "";
			}
			dojo.byId("lb_fire_new_congtor").innerHTML = fire_new_congtor;
			
			fire_old_congtor = dijit.byId('fire_old_congtor').get('value');
			if(fire_old_congtor>0){
				
			}else{
				fire_old_congtor = "";
			}
			dojo.byId("lb_fire_old_congtor").innerHTML = fire_old_congtor;
			
			fire_qty = dijit.byId('fire_qty').get('value');
			if(fire_qty>0){
				
			}else{
				fire_qty = "";
			}
			dojo.byId("lb_fire_qty").innerHTML = fire_qty;
			
			fire_cost = dijit.byId('fire_cost').get('value');
			if(fire_cost>0){
				fire_cost = dijit.byId('fire_cost').get('value')+" ៛";
			}else{
				fire_cost = "";
			}
			dojo.byId("lb_fire_cost").innerHTML = fire_cost;
			
			var date = new Date(dijit.byId("fire_start_date").get('value'));
			mm = date.getMonth()+1;
			var dd = date.getDate();
			if(dd<10){
				dd = "0"+dd;
			}
			var mon = getMonthByNumber(mm);
			if(mm<10){
				mm = "0"+mm;
			}
			var y = date.getFullYear();
			var start_date = dd + '/' + mon + '/' + y ;
			
			dojo.byId("lb_fire_start_date").innerHTML = start_date;
			
			
			var date = new Date(dijit.byId("fire_end_date").get('value'));
			mm = date.getMonth()+1;
			var dd = date.getDate();
			if(dd<10){
				dd = "0"+dd;
			}
			var mon = getMonthByNumber(mm);
			if(mm<10){
				mm = "0"+mm;
			}
			var y = date.getFullYear();
			var end_date = dd + '/' + mon + '/' + y ;
			
			dojo.byId("lb_fire_end_date").innerHTML = end_date;
			
		 }else{
			dojo.byId("lb_fire_payment").innerHTML = " ";
			dojo.byId("checkbox_fire").innerHTML = "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/uncheck.png'?>'>";
			
			dojo.byId("lb_fire_new_congtor").innerHTML = "";
			dojo.byId("lb_fire_old_congtor").innerHTML = "";
			dojo.byId("lb_fire_cost").innerHTML = "";
			dojo.byId("lb_fire_start_date").innerHTML = "";
			dojo.byId("lb_fire_end_date").innerHTML = "";
		 }
		 
		 cleaner = dijit.byId('hygiene_price').get('value');
		 if(cleaner>0){
			dojo.byId("lb_cleaner").innerHTML = " $ "+cleaner;  
			dojo.byId("checkbox_cleaner").innerHTML = "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/checked.png'?>'>";
		 
			var date = new Date(dijit.byId("hygiene_start_date").get('value'));
			mm = date.getMonth()+1;
			var dd = date.getDate();
			if(dd<10){
				dd = "0"+dd;
			}
			var mon = getMonthByNumber(mm);
			if(mm<10){
				mm = "0"+mm;
			}
			var y = date.getFullYear();
			var start_date = dd + '/' + mon + '/' + y ;
			
			dojo.byId("lb_hygiene_start_date").innerHTML = start_date;
			
			
			var date = new Date(dijit.byId("hygiene_end_date").get('value'));
			mm = date.getMonth()+1;
			var dd = date.getDate();
			if(dd<10){
				dd = "0"+dd;
			}
			var mon = getMonthByNumber(mm);
			if(mm<10){
				mm = "0"+mm;
			}
			var y = date.getFullYear();
			var end_date = dd + '/' + mon + '/' + y ;
			
			dojo.byId("lb_hygiene_end_date").innerHTML = end_date;
		 }else{
			dojo.byId("lb_cleaner").innerHTML = " ";  
			dojo.byId("checkbox_cleaner").innerHTML = "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/uncheck.png'?>'>";
		 
			dojo.byId("lb_hygiene_start_date").innerHTML = "";
			dojo.byId("lb_hygiene_end_date").innerHTML = "";
		 }
		 
		 other_price = dijit.byId('other_price').get('value');
		 if(other_price>0){
			dojo.byId("lb_other_price").innerHTML = " $ "+other_price; 
			dojo.byId("checkbox_other").innerHTML = "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/checked.png'?>'>";
		 }else{
			dojo.byId("lb_other_price").innerHTML = "";  
			dojo.byId("checkbox_other").innerHTML = "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/uncheck.png'?>'>";
		 }
		 
		 dojo.byId("checkbox_broken_material").innerHTML = "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/uncheck.png'?>'>";
		 dojo.byId("checkbox_bicycle").innerHTML = "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/uncheck.png'?>'>";
		 dojo.byId("checkbox_moto").innerHTML = "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/uncheck.png'?>'>";
		 
		 
		dijit.byId("terms").show();	
	}
	
}

function hideDialog() {		
	dijit.byId("terms").hide();
}
</script>

<div class="dijitHidden" style="width: 25cm !important; height: 15cm ; padding: 0px; margin: 0px;">
	
	<div data-dojo-type="dijit.Dialog" style="width:30cm !important;height: 17cm ;" align="center" data-dojo-props="title:'<?php echo $tr->translate("");?>'" id="terms" >
		<style>
			.data2{font-size:10px !important;}
		</style>
		
		<div id="divPrint" style="width: 25cm !important; height: 13cm ; padding: 0px; margin: 0px;">
			<style>
				.fontbig{
					font-size: 15px;	
				}
				.fonttel{
					font-size: 18px;	
				}
				.pleft{
					width: 110px;	
				}
				.label{ font-weight: bold;font-size: 22px;}
				.value{ font:bold 12px 'Khmer OS Battambang';border: 1px solid rgba(14, 0, 107, 1); height: 25px; padding: 0 2px;width: 98%; display: block;
						margin-top: -25px; line-height: 25px;
					    text-align: center;
						}
				.values{ border: 1px solid rgba(14, 0, 107, 1); height: 25px; padding: 0 10px;display: block;
						line-height: 25px;}
				.h{ margin-top: -8px;/*margin-left:4px;*/}
​​               .print td{ font:bold 12px 'Khmer OS Battambang';}
			   .khmerbold{font:bold 12px 'Khmer OS Battambang';}
			   .khmer{font:12px 'Khmer OS Battambang';}
			   .one{white-space:nowrap;}
			   
				.underline{margin-top: -18px;text-align:center;}
				.underline_top{margin-top: -15px;text-align:center;}
				.data{font-size:14px;font-weight:bold;}
				.data1{font-size:14px;font-weight:bold;}
				
				.receiptno{font-size:22px;font-weight:bold;}
				.tab_row{ margin-top: -8px;}
				.fonteng{font-size:12px;}
				.table_print{
					white-space:nowrap;
					font-size:14px;
					font-family:'Khmer OS Battambang';
					line-height:20px;
				}
			</style>	
			<table border="0" width="100%" class="print" cellspacing="0"  cellpadding="0" style="white-space:nowrap; font-size:14px;font-family:'Khmer OS Battambang';line-height: 17px;margin-top:-5px;">
				<tr>
				    <td colspan="6"  align="center" style="">
						<table width="100%" border="0" style="white-space:nowrap; font-family:Khmer OS Battambang;margin-top:-10px;font-weight:bold;">
							<tr>
								<td width="35%" align="left" style="font-size:14px;">
									<div style="font-size:17px;"><?php if (!empty($this->branch_info['branch_namekh'])){ echo $this->branch_info['branch_namekh'];}?></div><?php echo date('l , jS / m / Y , H:i:s ',strtotime(Zend_Date::now()));?>
								</td>
								<td width="30%" align="center">
									<img style="width: 35%;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br >
								</td>
								<td width="35%" align="center" style="font-size:22px;color:red;"><div style="margin-top:-5px;">N<sup>o</sup> : <label id="lb_receipt_no" class="receiptno" ></div></label></td>
							</tr>
						</table>
				    </td>
				</tr>
				
				<tr >
					<td colspan="6">
						<table width="100%" style="white-space:nowrap; font-size:12px;font-family:'Khmer OS Battambang';line-height: 21px;margin-top: -25px;">
							<tr>
								<td width="40%"><img style="width: 100%;height:4px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/double_underline.png'?>"></td>
								<td width="20%" align="center" style="font-size:16px;">បង្កាន់ដៃទទួលប្រាក់ RECEIPT</td>
								<td width="40%"><img style="width: 100%;height:4px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/double_underline.png'?>"></td>
							</tr>
						</table>
					</td>
				</tr>

				<tr>
					<td colspan="6">
						&nbsp;
					</td>
				</tr>
				
				<tr>
					<td width="10%">ឈ្មោះអ្នកបង់ប្រាក់</td>
					<td width="38%">
						&nbsp;:&nbsp;<label id="lb_cus_name"  class="data" ></label>
						<div class="underline_top">&nbsp;...............................................................................................</div>
					</td>
					<td width="4%" align="center"> ភេទ</td>
					<td width="5%">
						:&nbsp;<label id="lb_sex" class="data" ></label>
						<div class="underline_top">..........</div>
					</td>
					<td width="8%" align="center"> លេខទូរសព្ទ</td>
					<td width="35%">
						:&nbsp;<label id="lb_phone" class="data" ></label>
						<div class="underline_top">&nbsp;.........................................................................................</div>
					</td>
				</tr>
				
				<tr>
					<td colspan="6">
						&nbsp;
					</td>
				</tr>
				
				
				<tr>
					<td colspan="6" style="border:2px solid #000;">
						<table width="100%" style="white-space:nowrap;font-size:14px;font-family:'Khmer OS Battambang';line-height:22px;margin:5px;">
							<tr>
								<td colspan="2">
									<table width="100%" class="table_print">
										<tr>
											<td width="12%">
												<label id="checkbox_book_rental"></label>
												 ថ្លៃកក់ជួលតូប
											</td>
											<td width="88%">
												:&nbsp;<label id="" class="data" ></label>
												<div class="underline">................................................................................................................................................................................................................................</div>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="2">
									<table border="0" width="100%" class="table_print">
										<tr>
											<td width="12%">
												<label id="checkbox_rent"></label>
												 ថ្លៃជួលតូប
											</td>
											<td width="22%">
												:&nbsp;<label id="lb_rent_payment" class="data" ></label>
												<div class="underline">...................................................</div>
											</td>
											
											<td width="13%">
												 មានសុពលភាព ចំនួន
											</td>
											<td width="8%">
												:&nbsp;<label id="" class="data" ></label>
												<div class="underline">................</div>
											</td>
											
											<td width="8%">
												 ខែ ចាប់ពីថ្ងៃទី
											</td>
											<td width="15%">
												:&nbsp;<label id="lb_rent_start_date" class="data" ></label>
												<div class="underline">..................................</div>
											</td>
											
											<td width="7%">
												 ដល់ថ្ងៃទី
											</td>
											<td width="15%">
												:&nbsp;<label id="lb_rent_end_date" class="data" ></label>
												<div class="underline">................................</div>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							
							<tr>
								<td colspan="2">
									<table width="100%" border="0" class="table_print">
										<tr>
											<td width="5%">
												<label id="checkbox_fire"></label>
												 ថ្លៃភ្លើង
											</td>
											
											<td width="6%">
												:&nbsp;<label id="lb_fire_payment" class="data" ></label>
												<div class="underline">..............</div>
											</td>
											
											<td width="5%">
												កុងទ័រថ្មី
											</td>
											<td width="6%">
												:&nbsp;<label id="lb_fire_new_congtor" class="data" ></label>
												<div class="underline">..............</div>
											</td>
											
											<td width="6%">
												កុងទ័រចាស់
											</td>
											<td width="6%">
												:&nbsp;<label id="lb_fire_old_congtor" class="data" ></label>
												<div class="underline">..............</div>
											</td>
											
											<td width="9%">
												កុងទ័រប្រើប្រាស់
											</td>
											<td width="6%">
												:&nbsp;<label id="lb_fire_qty" class="data" ></label>
												<div class="underline">..............</div>
											</td>
											
											<td width="3%">
												Kw X
											</td>
											<td width="6%">
												&nbsp;<label id="lb_fire_cost" class="data" ></label>
												<div class="underline">..............</div>
											</td>
											
											<td width="8%">
												/1Kw ចាប់ពីថ្ងៃទី
											</td>
											<td width="9%">
												:&nbsp;<label id="lb_fire_start_date" class="data" ></label>
												<div class="underline">.......................</div>
											</td>
											
											<td width="5%">
												ដល់ថ្ងៃទី
											</td>
											<td width="9%">
												:&nbsp;<label id="lb_fire_end_date" class="data" ></label>
												<div class="underline">.....................</div>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							
							<tr>
								<td colspan="2">
									<table width="100%" class="table_print">
										<tr>
											<td width="5%">
												<label id="checkbox_water"></label>
												 ថ្លៃទឹក
											</td>
											<td width="6%">
												:&nbsp;<label id="lb_water_payment" class="data" ></label>
												<div class="underline">..............</div>
											</td>
											
											<td width="5%">
												កុងទ័រថ្មី
											</td>
											<td width="6%">
												:&nbsp;<label id="lb_water_new_congtor" class="data" ></label>
												<div class="underline">..............</div>
											</td>
											
											<td width="6%">
												កុងទ័រចាស់
											</td>
											<td width="6%">
												:&nbsp;<label id="lb_water_old_congtor" class="data" ></label>
												<div class="underline">..............</div>
											</td>
											
											<td width="9%">
												កុងទ័រប្រើប្រាស់
											</td>
											<td width="6%">
												:&nbsp;<label id="lb_water_qty" class="data" ></label>
												<div class="underline">..............</div>
											</td>
											
											<td width="3%">
												Kw X
											</td>
											<td width="6%">
												&nbsp;<label id="lb_water_cost" class="data" ></label>
												<div class="underline">..............</div>
											</td>
											
											<td width="8%">
												/1Kw ចាប់ពីថ្ងៃទី
											</td>
											<td width="9%">
												:&nbsp;<label id="lb_water_start_date" class="data" ></label>
												<div class="underline">.......................</div>
											</td>
											
											<td width="5%">
												ដល់ថ្ងៃទី
											</td>
											<td width="9%">
												:&nbsp;<label id="lb_water_end_date" class="data" ></label>
												<div class="underline">.....................</div>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							
							<tr>
								<td colspan="2">
									<table width="100%" class="table_print">
										<tr>
											<td width="12%">
												<label id="checkbox_cleaner"></label>
												 ថ្លៃសម្រាម
											</td>
											<td width="56%">
												:&nbsp;<label id="lb_cleaner" class="data" ></label>
												<div class="underline">............................................................................................................................................</div>
											</td>
											
											<td width="6%">
												ចាប់ពីថ្ងៃទី
											</td>
											<td width="11%">
												:&nbsp;<label id="lb_hygiene_start_date" class="data" ></label>
												<div class="underline">.......................</div>
											</td>
											
											<td width="5%">
												ដល់ថ្ងៃទី
											</td>
											<td width="10%">
												:&nbsp;<label id="lb_hygiene_end_date" class="data" ></label>
												<div class="underline">.....................</div>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							
							<tr>
								<td colspan="2">
									<table width="100%" class="table_print">
										<tr>
											<td width="12%">
												<label id="checkbox_moto"></label>
												 ថ្លៃកិបសំបុត្រម៉ូតូ
											</td>
											<td width="8%">
												:&nbsp;<label id="" class="data" ></label>
												<div class="underline">.................</div>
											</td>
											
											<td width="9%">
												លេខសំបុត្រពី
											</td>
											<td width="8%">
												:&nbsp;<label id="" class="data" ></label>
												<div class="underline">.................</div>
											</td>
											
											<td width="6%">
												ដល់លេខ
											</td>
											<td width="8%">
												:&nbsp;<label id="" class="data" ></label>
												<div class="underline">.................</div>
											</td>
											
											<td width="9%">
												សរុបប្រើប្រាស់
											</td>
											<td width="5%">
												:&nbsp;<label id="" class="data" ></label>
												<div class="underline">..........</div>
											</td>
											
											<td width="1%">
												X
											</td>
											<td width="5%">
												&nbsp;<label id="" class="data" ></label>
												<div class="underline">............</div>
											</td>
											
											<td width="9%">
												/1សំបុត្រ បិទវេនទី
											</td>
											<td width="4%">
												:&nbsp;<label id="" class="data" ></label>
												<div class="underline">........</div>
											</td>
											
											<td width="6%">
												សំរាប់ថ្ងៃទី
											</td>
											<td width="10%">
												:&nbsp;<label id="" class="data" ></label>
												<div class="underline">....................</div>
											</td>
										</tr>
									</table>
								</td>
								
							</tr>
							
							<tr>
								<td colspan="2">
									<table width="100%" border="0" class="table_print">
										<tr>
											<td width="12%">
												<label id="checkbox_bicycle"></label>
												 ថ្លៃកិបសំបុត្រកង់
											</td>
											<td width="8%">
												:&nbsp;<label id="" class="data" ></label>
												<div class="underline">.................</div>
											</td>
											
											<td width="9%">
												លេខសំបុត្រពី
											</td>
											<td width="8%">
												:&nbsp;<label id="" class="data" ></label>
												<div class="underline">.................</div>
											</td>
											
											<td width="6%">
												ដល់លេខ
											</td>
											<td width="8%">
												:&nbsp;<label id="" class="data" ></label>
												<div class="underline">.................</div>
											</td>
											
											<td width="9%">
												សរុបប្រើប្រាស់
											</td>
											<td width="5%">
												:&nbsp;<label id="" class="data" ></label>
												<div class="underline">..........</div>
											</td>
											
											<td width="1%">
												X
											</td>
											<td width="5%">
												&nbsp;<label id="" class="data" ></label>
												<div class="underline">............</div>
											</td>
											
											<td width="9%">
												/1សំបុត្រ បិទវេនទី
											</td>
											<td width="4%">
												:&nbsp;<label id="" class="data" ></label>
												<div class="underline">........</div>
											</td>
											
											<td width="6%">
												សំរាប់ថ្ងៃទី
											</td>
											<td width="10%">
												:&nbsp;<label id="" class="data" ></label>
												<div class="underline">....................</div>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							
							<tr>
								<td colspan="2">
									<table width="100%" class="table_print">
										<tr>
											<td width="12%">
												<label id="checkbox_broken_material"></label>
												 ថ្លៃលក់អេតចាយ
											</td>
											<td width="88%">
												:&nbsp;<label id="" class="data" ></label>
												<div class="underline">................................................................................................................................................................................................................................</div>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							
							<tr>
								<td colspan="2">
									<table width="100%" class="table_print" >
										<tr>
											<td width="12%">
												<label id="checkbox_other"></label>
												 ផ្សេងៗ
											</td>
											<td width="88%">
												:&nbsp;<label id="lb_other_price" class="data" ></label>
												<div class="underline">................................................................................................................................................................................................................................</div>
											</td>
										</tr>
									</table>
								</td>			
							</tr>
							
							<tr>
								<td colspan="2">
									<table width="100%" class="table_print" >
										<tr>
											<td width="15%">ទឹកប្រាក់ទទួលបានសរុប</td>
											<td width="25%">
												:&nbsp;<label id="lb_total_payment" class="data" ></label>
												<div class="underline">............................................................</div>
											</td>
											<td width="5%">ជាអក្សរ</td>
											<td width="55%">
												:&nbsp;<label id="lb_readmoney" class="data" ></label>
												<div class="underline">.........................................................................................................................................</div>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							
						</table>
					</td>
				</tr>
				
				
				
				<tr>
					<td colspan="6">
						<table width="100%" style="white-space:nowrap; font-size:13px;font-family:Khmer OS Battambang, Times New Roman;">
							<tr>
								<td width="55%">&nbsp;</td>
								<td width="45%"align="right" >រាជធានីភ្នំពេញ.ថ្ងៃទី <?php echo date('d');?> / <?php echo date('m');?> / <?php echo date('Y');?></td>
							</tr>
						</table>
					</td>
				</tr>
				
				<tr>
					<td colspan="6">
						<table width="100%" style="white-space:nowrap; font-size:14px;font-family:Khmer OS Battambang, Times New Roman;margin-bottom:8px;">
							<tr align="center">
								<td width="33%"><span style="font-family:'khmer os muol light';font-size:12px;">ប្រធានគណនេយ្យ</span></td>
								<td width="33%"><span style="font-family:'khmer os muol light';font-size:12px;">អ្នកបង់ប្រាក់</span></td>
								<td width="33%"><span style="font-family:'khmer os muol light';font-size:12px;">បេឡា</span></td>
							</tr>
							<tr align="center">
								<td colspan="3">&nbsp;</td>
							</tr>
							<tr align="center">
								<td colspan="3">&nbsp;</td>
							</tr>
							<tr>
								<td align="left">
									&nbsp;
								</td>
								<td align="left">
									&nbsp;
								</td>
								<td align="center">
									<?php 
									   $session_user=new Zend_Session_Namespace('auth');
									   $last_name=$session_user->last_name;
									   $username = $session_user->first_name;
									   echo $last_name." ".$username;
									?>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				
				<tr >
					<td colspan="6" style="border:2px solid #000;">
						
					</td>
				</tr>
				<tr >
					<td colspan="6" >
						&nbsp;
					</td>
				</tr>
				<tr>
					<td colspan="6" >
						<strong>បញ្ចាក់:&nbsp;&nbsp;</strong>-&nbsp;ប្រាក់ដែលបានបង់ហើយមិនអាចដកវីញបានឡើយ ៕ <strong>Notice:</strong> Your Payment is non-returnable.
					</td>
				</tr>
							
			</table>
		</div>
		
		<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>	
		<button dojoType="dijit.form.Button" label="Cancel" iconClass="dijitEditorIcon dijitEditorIconCancel"
			showLabel="true" type="button" onclick="hideDialog();">Cancel</button>
		<button dojoType="dijit.form.Button" label="Print" showLabel="true" iconClass="dijitEditorIcon dijitEditorIconPrint"
			 type="button" onclick="printSubmit();">Print</button>
	</div>
</div>

