<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_expense;
?>
<title><?php echo $tr->translate("ADD_OTHER_EXPENSE")?></title>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
</style>
 <script>
		require(["dijit/form/DateTextBox","dijit/form/NumberTextBox"]);
 </script>
<form id='frm_add_tran' action="" 
				dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
               if(dijit.byId("branch_id").get("value")==''){
					alert("Please Select Branch Name!!!");
                    dijit.byId("branch_id").focus();
					return false;
				}
				if(dijit.byId("cate_expense").get("value")==0){
					alert("Please Select Category Expense!!!");
                    dijit.byId("cate_expense").focus();
					return false;
				}
                dijit.byId("saveclose").attr("disabled",true);
				return true;
			}else {
				return false;
			}
</script>
<table cellspacing="10" class='fullside' >
	<tr>
		<td>
			<fieldset>
				<legend><strong><?php echo $tr->translate("ADD_OTHER_EXPENSE")?></strong></legend>
				<table cellspacing="10"  width="100%" style="white-space: nowrap;">
					<tr>
						<td width="33%;" valign="top">
							 <fieldset>
								<legend align="center" ><strong><?php echo $tr->translate("BRANCH_INFO")?></strong></legend>
								 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
										<tr>
											<td><?php echo $tr->translate("BRANCH_ID")?></td>
											<td><?php echo $frm->getElement('branch_id');?></td>
										</tr>
										<tr>
											<td><?php echo $tr->translate("CATEGORY_EXPENSE")?></td>
											<td><input id="cate_expense" /></td>
										</tr>
										<tr>
										    <td><?php echo $tr->translate("CURRENCY_TYPE")?></td>
											<td><?php echo $frm->getElement('currency_type');//echo $frm->getElement('for_date');?></td>
										</tr>
										<tr>
											<td><?php echo $tr->translate("DATE")?></td>
											<td><?php echo $frm->getElement('Date');?></td>
										</tr>
										<tr>
											<td><?php echo $tr->translate("NOTE")?></td>
											<td><?php echo $frm->getElement('Description');?></td>
										</tr>
																
								</table>
							</fieldset>	
						</td>
						<td width="33%;" valign="top">
							 <fieldset>
								<legend align="center" ><strong><?php echo $tr->translate("EXPENSE_INFO")?></strong></legend>
								 <table style="margin: 0 auto; width: 100%;text-align: left;" cellspacing="2"  >
									   <tr>
											<td><?php echo $tr->translate("FIXED_ASSET")?></td>
											<td><?php echo $frm->getElement('fixed_id');?>
												 <input type="hidden" name="hid_fixed_id" id="hid_fixed_id"  value="" />
												 <input type="hidden" name="old_fixed_id" id="old_fixed_id"  value="<?php echo $this->row['fixedetail_id']?>" />
												 <input type="hidden" name="old_total_paid" id="old_total_paid"  value="<?php echo $this->row['total_amount']?>" />
											</td>
										</tr>
										<tr>
											<td><?php echo $tr->translate("RECEIPT_NO")?></td>
											<td><?php echo $frm->getElement('invoice');?></td>
										</tr>
										<tr>
											<td><?php echo $tr->translate("TOTAL_EXPENSE")?></td>
											<td><?php echo $frm->getElement('total_amount');?></td>
										</tr>
										<tr>
											<td><?php echo $tr->translate("EXPENSE_TITLE")?></td>
											<td><?php echo $frm->getElement('title');?></td>
										</tr>
										<tr>
											<td><?php echo $tr->translate("STATUS")?></td>
											<td><?php echo $frm->getElement('Stutas');?></td>
										</tr>
								</table>
							</fieldset>	
						</td>
					</tr>
					<tr>
						<td align="center" colspan="4">
						<input type="reset" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button"
								 iconClass="dijitIconClear"/>
							<input type="submit"   label="<?php echo $tr->translate("SAVE_CLOSE");?>" name='saveclose' id='saveclose' value='saveclose' dojoType="dijit.form.Button"
								 iconClass="dijitIconDelete"/>
						</td>
					</tr>
				</table>
			</fieldset>
		</td>
	</tr>		
		
</table>
</form>

<script type="text/javascript">

	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dojo.store.Memory");
	dojo.require("dijit.form.Textarea");

	var cate_expense_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->cate_expense));?> );
	
	dojo.ready(function(){
		new dijit.form.FilteringSelect({
			store: cate_expense_store,
			autoComplete: true,                        
			required: true,                      
		    id: "cate_expense",
		    name: "cate_expense",  
		    tabindex: "1",  
		    value:0,       
		    class: 'fullside',  
		    placeHolder:"Selecte Category", 
		    onChange: function() {          
			   	service_id = dijit.byId('cate_expense').get('value');
			    if(service_id==-1){
			   		dijit.byId("popup_cate").show();
			    }
		   }
		}, "cate_expense");
	});

	var url_add_cate_expense = '<?php echo $this->url(array("module"=>"registrar","controller"=>"income","action"=>"add-cate-income")); ?>';
	function addCateExpense(){
		if(dijit.byId('frm_add_cate_expense').validate()) {
			dojo.xhrPost({
				url:url_add_cate_expense,
				form: dojo.byId("frm_add_cate_expense"),
				handleAs:"json",
				load: function(data) {
					//alert(data); 
					var Itemmake = { 
							id: data,
							name: dijit.byId('cate_title').get('value')
						};
					addDataToSelectbox(dijit.byId('cate_expense'), cate_expense_store, Itemmake, data);
					dijit.byId('frm_add_cate_expense').reset();
					hidePopup();
					
				},
				error: function(err) {
					alert(err);
				}
			});
		}
	}
	
	function hidePopup(){		
		dijit.byId("popup_cate").hide();
	}
	
</script>

<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:30%;" id="popup_cate" >
		<form style="background-color: buttonface;" id='frm_add_cate_expense' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
			<tr>
				<td>
					<fieldset style="background-color: buttonface;">
					<table style="margin: 0 auto; width: 95%;" cellspacing="5">
						<tr>
							<td style="width:100px"><?php echo $tr->translate("TITLE")?></td>
							<td><input class="fullside" tabindex="1" value="" dojoType="dijit.form.ValidationTextBox" name="cate_title" id="cate_title" type="text" required="true" /></td>
						</tr>
						<tr>
							<td style="width:100px"><?php echo $tr->translate("TYPE")?></td>
							<td>
								<select class="fullside"  tabindex="3" name="type" id="type" dojoType="dijit.form.FilteringSelect" >
									    <option value="0"><?php echo $tr->translate("EXPENSE")?></option>
								</select>
							</td>
						</tr>
						<tr>
							<td colspan="2" align="center">
								<input iconClass="dijitIconUndo" type="button" label="<?php echo $tr->translate("CANCEL")?>" name="close" id="close" value="close" label="Close" dojoType="dijit.form.Button" onclick="hidePopup();" />
								<input type="button" value="save" name="save" label="<?php echo $tr->translate("SAVE_CLOSE")?>" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addCateExpense();"/>
							</td>
						</tr>
					</table>
				</fieldset>
				</td>
			</tr>
		</table>

		</form>
	</div>
</div>

<script>
$( document ).ready(function() {
    dijit.byId("cate_expense").attr("value",'<?php echo $this->row['cat_id']?>');
     
});

var url_fixedasset = '<?php echo $this->url(array("module"=>"registrar","controller"=>"expense","action"=>"get-totalasset")); ?>';
function getFixedAssetTotalPaid(){
	dijit.byId("total_amount").set('readonly', true);
	fixed_id=dijit.byId("fixed_id").get("value");
	if(fixed_id==''){
		dijit.byId("total_amount").attr("value",'');
		dijit.byId("total_amount").attr("readonly",false);
		return false;
	}
		dojo.xhrPost({
			url:url_fixedasset,	
			content:{ 
			    'fixed_id':fixed_id,
			},		    
			handleAs:"json",
			load: function(data) {
				if(data){
					dijit.byId("total_amount").attr("value",data.total_depre);
					$("#hid_fixed_id").val(data.id);
					 
				}else{
					dijit.byId("total_amount").attr("value",'');
					$("#hid_fixed_id").val('');
				}
			},
			error: function(err) {
				alert(err);
			}
		});
	
}
 
</script>
