<?php 
	$frm = $this->frm_search;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("OTHER_EXPENSE")?></title>
<script>
	dojo.require('dijit.form.Button');
	dojo.require("dijit.form.DateTextBox");
</script>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'registrar','controller'=>'expense','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
  <table width="100%">
   <tr>  
        <td><?php echo $frm->getElement("adv_search");?></td>
        <td><?php echo $frm->getElement('branch');?></td>
   		<td><?php echo $frm->getElement('currency_type');?></td>
   		<td><?php echo $frm->getElement('cat_expend');?></td>
   		<td>
			<select name="asset_id" id="asset_id" dojoType="dijit.form.FilteringSelect" class="fullside"  >
				<option value=""><?php echo $tr->translate('FIXED_ASSET')?></option>
				<?php if(!empty($this->fix_asset)){foreach ($this->fix_asset as $category){?>
					<option value="<?php echo $category['id']?>" <?php if($category['id']==$this->search['asset_id']){echo "selected='selected'";}?>><?php echo $category['name']?></option>	
				<?php }}?>
			</select>
		</td>
   </tr>
   <tr>
   		
   		<td><?php echo $frm->getElement('start_date');?></td>
   		<td><?php echo $frm->getElement('end_date');?></td>
   		<td><?php echo $frm->getElement('status');?></td>
   		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
   </tr>
</table>
</form>
 <?php echo $this->list;?>
