<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm =  $this->form_search;
	//print_r($this->rs[0]);
?>	
<title><?php echo $tr->translate('Daily Income Student Test');?></title>



<form  id='foundation_class' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table width="100%">
	    <tr>
	    	<td><?php echo $frm->getElement('branch');?></td>
	    	<td>
			 	<select name="shift"  id="shift" dojoType="dijit.form.FilteringSelect" class="fullside" >
			 		<option value="0" <?php if($this->search['shift']==0){echo 'selected="selected"';}?>>Shift</option>
			 		<option value="1" <?php if($this->search['shift']==1){echo 'selected="selected"';}?>>10:00am</option>
			 		<option value="2" <?php if($this->search['shift']==2){echo 'selected="selected"';}?>>04:00pm</option>
			 		<option value="3" <?php if($this->search['shift']==3){echo 'selected="selected"';}?>>06:30pm</option>
			 	</select>
			</td>
			<td><?php echo $frm->getElement('user');?></td>
		</tr>
		<tr>	
	    	<td>
				<select name="degree" id="degree" class="fullside" dojoType="dijit.form.FilteringSelect"  >
					<option value="0"><?php echo $tr->translate("DEGREE")?></option>
					<?php if(!empty($this->degree)){foreach($this->degree as $rs){?>
						<option value="<?php echo $rs['id'];?>"><?php echo $rs['name'];?></option>
					<?php }}?>
				</select>
			</td>
			<td><?php echo $frm->getElement('start_date');?></td>
			<td><?php echo $frm->getElement('end_date');?></td>
			<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button> </td>
	    </tr>
	</table>
</form>	

<style>
.hover:hover{background: #ddd;}
tr.row_control {
    display: table-row !important;
}
</style>

<div style="border: 1px dotted #000;background: #fff; margin: 0 auto;min-height: 27cm; padding: 0.5cm;">
	<form  action="<?php echo $this->url(array('module'=>'allreport','controller'=>'submitdailyincome','action'=>'rpt-submit-daily-income')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<div id="divPrint">
	<style>
		.bor{
			border-right: 1px solid #000;	
			border-bottom: 1px solid #000;
			font-size:13px;
		}
		.bor_r{
			border-right: 1px solid #000;	
			font-size:13px;
		}
		.padd{
			padding: 0 3px;	
		}
		#row{ font-size:12px; line-height: 20px;border: 1px solid #000;font-family:'Khmer OS Battambang';  }
		
		table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
	  th{padding: 5px;}
	  
	  table { page-break-inside:auto }
	    tr{ page-break-inside:avoid; page-break-after:auto; }
	</style>

	<?php 
		$shift = array(1=>"10:00am",2=>"04:00pm",3=>"06:30pm");
	?>

		<table style="background:#fff;width:90%; margin: 0 auto;width: 100%;font-family:'Khmer OS Battambang';">
			<tr>
				
				<td width="15%" align="center">
					<img style="width:70%;" src="<?php echo $this->baseUrl().'/images/logo.png'?>">
				</td>
				<td align="center" width="70%" style="font-family: Khmer OS Battambang,Times New Roman;color:#000; font-size: 14px;">
					<strong  style="font-weight:bold;color:#000; font-size: 17px;font-family: Khmer OS Battambang,Times New Roman;​"><?php echo $tr->translate("Daily Income Report(Student Test)");?></strong><br />
					<strong style="font-family: Khmer OS Battambang,Times New Roman;color:#000; font-size: 13px;">For Date <?php echo date("d-M-Y",strtotime($this->search["start_date"]))?> to <?php echo date("d-M-Y",strtotime($this->search["end_date"]));?></strong> <br />   
					<?php //if($this->search['shift']>0){echo "Time : ".$shift[$this->search['shift']]." , "."Shift : ".$this->search['shift'];}?>
				</td>
				<td width="15%" >
					<?php if($this->search['branch']>0 && !empty($this->row)){echo "Branch : ".$this->row[0]['branch_name']."</br>";}?>
					<?php if($this->search['user']>0 && !empty($this->row)){echo "User : ".$this->row[0]['user'];}?>
				</td>
				
			</tr>
			<tr>
				<td colspan="3" id="exportExcel">
					<table cellpadding="8"​ style=" border: solid 1px #000; margin:0 auto; width:100%; border-collapse: collapse; white-space: nowrap;font-family:'Khmer OS Battambang';"  border="1" >
	 					 <thead>
		 					 <tr align="center" style="background: #c1d0f3;font-size: 13px; line-height: 20px;font-weight: bold;">
								<td class="padd">N<sup>o</sup></td>
								<td class="padd">Branch</td>
								<td class="padd">For Date</td>
								<td class="padd">Type</td>
								<td class="padd">Shift</td>
								<td class="padd">User</td>
								
								<td class="padd">Total Amount</td>
								<td class="padd">Amount in Dollars</td>
								<td class="padd">Amount in Riels</td>
		 					 </tr>
	 					 </thead>
	 					 <?php $i=0; $grand_total = 0;$grand_total_in_dollar=0;$grand_total_in_riel=0;$shift="";$payfor_type=""; if (!empty($this->row)) foreach ($this->row as $rs){ $i++;?>
	 					 
	 					 <?php 
	 					 	if($rs['shift'] == 1){
	 					 		$shift = "វេនទី ".$rs['shift']."(10:00am)";
	 					 	}else if($rs['shift'] == 2){
	 					 		$shift = "វេនទី ".$rs['shift']."(04:00pm)";
	 					 	}else if($rs['shift'] == 3){
	 					 		$shift = "វេនទី ".$rs['shift']."(06:30pm)";
	 					 	}
	 					 	
	 					 	if($rs['payfor_type'] == 1 ){
	 					 		$payfor_type = "ខ្មែរពេញម៉ោង";
	 					 	}else if($rs['payfor_type'] == 2 ){
	 					 		$payfor_type = "Englist Parttime and Other";
	 					 	}else if($rs['payfor_type'] == 3 ){
	 					 		$payfor_type = "Transportation";
	 					 	}else if($rs['payfor_type'] == 4 ){
	 					 		$payfor_type = "Food and Stay";
	 					 	}else if($rs['payfor_type'] == 5 ){
	 					 		$payfor_type = "Product";
	 					 	}else if($rs['payfor_type'] == 6 ){
	 					 		$payfor_type = "Englist Fulltime";
	 					 	}else if($rs['payfor_type'] == 7 ){
	 					 		$payfor_type = "ជួលតូប";
	 					 	}else if($rs['payfor_type'] == 8 ){
	 					 		$payfor_type = "ផ្ញើរកង់ ម៉ូតូ និង អេតចាយ";
	 					 	}else if($rs['payfor_type'] == 9 ){
	 					 		$payfor_type = "ចំណូលផ្សេងៗ";
	 					 	}else if($rs['payfor_type'] == 10 ){
	 					 		$payfor_type = "សិស្សធ្វើតេស្ត";
	 					 	}
	 					 	
	 					 	
	 					 ?>
	 					 
	 					 <tr id="row" align="center" class="hover">
	 					 	<td class="padd">&nbsp;<?php echo $i;?>&nbsp;</td>
	 					 	<td class="padd">&nbsp;<?php echo $rs['branch_name'];?>&nbsp;</td>
							<td class="padd">&nbsp;<?php echo $rs['for_date'];?>&nbsp;</td>
							<td class="padd">&nbsp;<?php echo $payfor_type;?>&nbsp;</td>
							<td class="padd">&nbsp;<?php echo $shift;?>&nbsp;</td>
							<td class="padd">&nbsp;<?php echo $rs['user_name'];?>&nbsp;</td>
							
							<td class="padd">&nbsp;<?php echo "$ ".number_format($rs['total_amount'],2);?>&nbsp;</td>
							<td class="padd">&nbsp;<?php echo "$ ".number_format($rs['amount_usd'],2);?>&nbsp;</td>
							<td class="padd">&nbsp;<?php echo number_format($rs['amount_riel'],2)." ៛";?>&nbsp;</td>
	 					 </tr>
	 					 <?php 
	 					 $grand_total = $grand_total + $rs['total_amount'];
	 					 $grand_total_in_dollar = $grand_total_in_dollar + $rs['amount_usd'];
	 					 $grand_total_in_riel = $grand_total_in_riel + $rs['amount_riel'];
					}
	 					 
	 					 ?>
	 					 
	 					 <tr align="center" style="background: #e8e8e8;font-size: 16px;font-family: Khmer OS Battmabng,Times New Roman;">
	 					 	<td colspan="6">Grand Total</td>
	 					 	<td ><?php echo "$ ".number_format($grand_total,2);?></td>
	 					 	<td ><?php echo "$ ".number_format($grand_total_in_dollar,2);?></td>
	 					 	<td ><?php echo number_format($grand_total_in_riel,2)." ៛";?></td>
	 					 </tr>
	 					 
	 				</table>
	 				
				</td>
			</tr>	
			
			<tr>
				<td colspan="3">&nbsp;</td>
			</tr>
			
			<tr>
				<td colspan="3">
					<table width="100%" border="0" style="white-space: nowrap;font-size: 13px;">
						<tr>
							<td align="center" width="25%">
								<span style="font-size: 14px;"><?php echo $tr->translate("APPROVED_BY"); ?></span>
							</td>
							<td align="center" width="25%">
								<span style="font-size: 14px;"><?php echo $tr->translate("VERIFIED_BY"); ?></span>
							</td>
							<td align="center" width="25%">
								<span style="font-size: 14px;"><?php echo $tr->translate("CHECKED_BY"); ?></span>
							</td>
							<td align="center"  width="25%">
								<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate("PREPARED_BY"); ?></span>
							</td>
						</tr>
					</table>							
				</td>
			</tr>
		</table>
	</div>
	</form>	
</div>
<script type="text/javascript">

dojo.ready(function(){
	document.getElementById('hide_amount_usd').style.display="none";
	calculateRemainReil();
});
					
function calculateRemainReil(){
	total_amount = '<?php echo $grand_total;?>';
	amount_usd = dijit.byId("amount_usd").get('value');
	exchange_rate = '<?php echo $this->rate?>';
	total_reil = ((total_amount - amount_usd)*exchange_rate).toFixed(2);
	//alert(total_reil);

	var result = 100 * Math.ceil(total_reil / 100);
	
	//alert(rounded);
	var total_reil = result.toFixed(2).replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1,");

	dijit.byId('amount_riel').attr('value',result);
	
	dojo.byId("lb_amount_usd").innerHTML = " $ " + amount_usd;
	dojo.byId("lb_amount_reil").innerHTML = " ៛ " + total_reil;
	
}



function doPrint() {
	//alert(1);
	
	document.getElementById('hide_amount_usd').style.display="block";
	document.getElementById('amount_usd').style.display="none";
	
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    //hideDialog();
    //alert(1);
    document.getElementById('amount_usd').style.display="block";
    document.getElementById('hide_amount_usd').style.display="none";
}
function preview()
{ 
  var disp_setting="toolbar=no,status=no,resizable=no,location=no,directories=yes,menubar=no,"; 
      disp_setting+="scrollbars=no,width=1200, height=700, left=100, top=25"; 
  var content_vlue = document.getElementById("divPrint").innerHTML; 
  
  var docprint=window.open("","",disp_setting); 
   docprint.document.open(); 
   docprint.document.write('<html><head>'); 
   docprint.document.write('</head><div style=" font-size:16px !important; margin:0px; font-family:Verdana;"><style>table th {font-size:14px !important;} table td{font-size:12px !important;}</style><center>');          
   docprint.document.write(content_vlue);          
   docprint.document.write('</center></div></html>'); 
   docprint.document.close(); 
   docprint.focus(); 
}
function exportExcel(){
	$('#exportExcel').tableExport({type:'excel',escape:'false'});
}
</script>
 