<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('PARKING_PAYMENT_REPORT')); 
	$frm =  $this->form_search;
?>	
<?php
	$array_month = array(
			"1"=>"January",
			"2"=>"February",
			"3"=>"March",
			"4"=>"April",
			"5"=>"May",
			"6"=>"June",
			"7"=>"July",
			"8"=>"August",
			"9"=>"September",
			"10"=>"October",
			"11"=>"November",
			"12"=>"December",
	);
?>
<div style="width: 28cm;margin: 0 auto;">
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-parking-payment')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table>	
		<tr>
			<td>
				<input dojoType="dijit.form.TextBox" class="fullside" id="txtsearch" name="txtsearch" placeholder="Search....." value="<?php echo $this->search['txtsearch'];?>" type="text">
			</td>
			<td>
				<?php echo $frm->getElement("branch");?>
			</td>
			<td>
				<?php echo $frm->getElement("start_date");?>
			</td>
			<td>
				<?php echo $frm->getElement("end_date");?>
			</td>
			<td>
				<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
			</td>
		</tr>
	</table>
</form>	
</div>
<div style="border: 1px dotted #000;background: #fff;width: 27cm;margin: 0 auto;min-height: 27cm; padding: 0.5cm;">
	<div id="divPrint">
		<div id="exportExcel">
			<table style="background:#fff;width:90%; margin: 0 auto;width: 100%;">
				
				<tr>
					<td width="20%" align="left">
						<img style="width:70%;" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br />
					</td>
					<td align="center" width="60%">
						<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate("PARKING_PAYMENT_REPORT")?></strong><br />
						<strong style="font-family: Khmer OS Battambang,Times New Roman;color:#000; font-size: 13px;">For Date <?php echo date("d-M-Y",strtotime($this->search["start_date"]))?> to <?php echo date("d-M-Y",strtotime($this->search["end_date"]));?></strong>
					</td>
					<td width="20%" align="right">
						<?php if($this->search['branch']>0 && !empty($this->row)){echo "Branch : ".$this->row[0]['branch_name'];}?>
					</td>
				</tr>
				<tr>
					<td colspan="3">
						<table cellpadding="5"​ style="margin:0 auto;border: 1px solid #000;width:100%; border-collapse: collapse;white-space: nowrap;font-family: Khmer OS Battambang , Times New Roman; "  border="1" >
							<tr style="font-size:13px; height: 20px;border: 1px solid #000;background: #ccc;font-weight: bold;" align="center" >
								<td style="border: 1px solid #000;"><?php echo $tr->translate("N_O");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("RECEIPT_NO");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("CUS_ID");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("NAME");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("PHONE");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("EMAIL");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("ថ្លៃកិបសំបុត្រម៉ូតូ");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("ថ្លៃកិបសំបុត្រកង់");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("លក់អេតចាយ");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("TOTAL");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("NOTE");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("USER");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("CREATE_DATE");?></td>
							</tr>
						<?php $i=0;$grand_total=0; if(!empty($this->row)){foreach ($this->row AS $row) { $i++;
							?>
							<tr class="hover" style="font-size:12px; height: 20px;border: 1px solid #000;" align="center" >
								<td style="border: 1px solid #000;"><?php echo $i;?></td>
								<td style="border: 1px solid #000;"><?php echo $row['receipt_no'];?></td>
								<td style="border: 1px solid #000;">&nbsp;<?php echo $row['customer_code'];?>&nbsp;</td>
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['name'];?></td>	
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['phone'];?></td>
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['email'];?></td>
								<td align="center" style="border: 1px solid #000;">&nbsp;<?php if($row['parking_moto_fee']>0){echo " $ ".$row['parking_moto_fee'];}?></td>
								<td align="center" style="border: 1px solid #000;">&nbsp;<?php if($row['parking_bike_fee']>0){echo " $ ".$row['parking_bike_fee'];}?></td>
								<td align="center" style="border: 1px solid #000;">&nbsp;<?php if($row['broken_thing_fee']>0){echo " $ ".$row['broken_thing_fee'];}?></td>
								<td align="center" style="border: 1px solid #000;">&nbsp;<?php echo " $ ".$row['total_fee'];?></td>
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['note'];?></td>
								<td align="center" style="border: 1px solid #000;">&nbsp;<?php echo $row['user_name'];?></td>
								<td align="center" style="border: 1px solid #000;">&nbsp;<?php echo date("d-M-Y",strtotime($row['create_date']));?></td>
 							</tr>
							<?php 
								$grand_total = $grand_total + $row['total_fee'];
								}}
							?>	 
							<tr style="background: #c7ffc6;">
								<td colspan="11" align="center">
									<?php echo $tr->translate("GRAND_TOTAL");?>&nbsp;&nbsp;&nbsp;
								</td>
								<td colspan="11" align="center">
									<?php echo "$ ".number_format($grand_total,2);?>
								</td>
							</tr>
						</table>	
					</td>
				</tr>
				
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr >
					<td colspan="3" align="center" >
						<table width="100%" style="font-family: Khmer OS Battambang , Times New Roman;">
							<tr>
								<td align="center" width="25%">
									<span style="font-size: 14px;"><?php echo $tr->translate("APPROVED_BY"); ?></span>
								</td>
								<td align="center" width="25%">
									<span style="font-size: 14px;"><?php echo $tr->translate("VERIFIED_BY"); ?></span>
								</td>
								<td align="center" width="25%">
									<span style="font-size: 14px;"><?php echo $tr->translate("CHECKED_BY"); ?></span>
								</td>
								<td align="center"  width="25%">
									<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate("PREPARED_BY"); ?></span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</div>			
	</div>		
</div>





