<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Report Student Nearly End Service'); 
	echo $this->headTitle(''); 
	$frm =  $this->form_search;
?>	
<?php
	$array_month = array(
			"1"=>"January",
			"2"=>"February",
			"3"=>"March",
			"4"=>"April",
			"5"=>"May",
			"6"=>"June",
			"7"=>"July",
			"8"=>"August",
			"9"=>"September",
			"10"=>"October",
			"11"=>"November",
			"12"=>"December",
	);
?>
<div style="width: 28cm;margin: 0 auto;">
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-invoice-parttime')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table>	
		<tr>
			<td>
				<input dojoType="dijit.form.TextBox" class="fullside" id="txtsearch" name="txtsearch" placeholder="Search....." value="<?php echo $this->search['txtsearch'];?>" type="text">
			</td>
			<td>
				<?php echo $frm->getElement("branch");?>
			</td>
			<td>
				<?php echo $frm->getElement("degree_gep");?>
			</td>
			<td>
				<?php echo $frm->getElement("grade_gep");?>
			</td>
			<td>
				<?php echo $frm->getElement("start_date");?>
			</td>
			<td>
				<?php echo $frm->getElement("end_date");?>
			</td>
			<td>
				<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
			</td>
		</tr>
	</table>
</form>	
</div>
<div style="border: 1px dotted #000;background: #fff;width: 27cm;margin: 0 auto;min-height: 27cm; padding: 0.5cm;">
	<div id="divPrint">
		<div id="exportExcel">
			<table style="background:#fff;width:90%; margin: 0 auto;width: 100%;">
				
				<tr>
					<td width="20%" align="left">
						<img style="width:70%;" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br />
					</td>
					<td align="center" width="60%">
						<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate("INVOICE_PARTTIME_REPORT")?></strong><br />
						<strong style="font-family: Khmer OS Battambang,Times New Roman;color:#000; font-size: 13px;">For Date <?php echo date("d-M-Y",strtotime($this->search["start_date"]))?> to <?php echo date("d-M-Y",strtotime($this->search["end_date"]));?></strong>
					</td>
					<td width="20%" align="right">
						<?php if($this->search['branch']>0 && !empty($this->row)){echo "Branch : ".$this->row[0]['branch_name'];}?>
					</td>
				</tr>
				<tr>
					<td colspan="3">
						<table cellpadding="5"​ style="margin:0 auto;border: 1px solid #000;width:100%; border-collapse: collapse;white-space: nowrap;"  border="1" >
							<tr style="font-size:13px; height: 20px;border: 1px solid #000;background: #ccc;" align="center" >
								<td style="border: 1px solid #000;"><?php echo $tr->translate("N_O");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("INVOICE_NO");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("STUDENT_ID");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("STUDENT_NAME");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("GRADE");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("SESSION");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("ROOM");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("PAYMENT_TERM");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("TUITION_FEE");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("DISCOUNT");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("OTHER_FEE");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("NOTE");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("USER");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("CREATE_DATE");?></td>
							</tr>
						<?php $i=0;$totalpaid=0;$totalbalance=0; if(!empty($this->row)){foreach ($this->row AS $row) { $i++;
							  $stu_name = $row['stu_enname'];
							  if(empty($stu_name)){$stu_name = $row['stu_khname'];}		

							  if($row['discount_percent']>0 && $row['discount_fix']>0){
							  	$discount = $row['discount_percent']." % + "." $ ".$row['discount_fix'];
							  }else if($row['discount_percent']>0){
							  	$discount = $row['discount_percent']."%";
							  }else if($row['discount_fix']>0){
							  	$discount = "$ ".$row['discount_fix'];
							  }else{
							  	$discount="";
							  }
							?>
							<tr class="hover" style="font-size:12px; height: 20px;border: 1px solid #000;" align="center" >
								<td style="border: 1px solid #000;"><?php echo $i;?></td>
								<td style="border: 1px solid #000;"><?php echo $row['invoice_no'];?></td>
								<td style="border: 1px solid #000;">&nbsp;<?php echo $row['stu_code'];?>&nbsp;</td>
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $stu_name;?></td>	
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['grade_name'];?></td>
								<td align="center" style="border: 1px solid #000;">&nbsp;<?php echo $row['session_name'];?></td>
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['room_name'];?></td>
								<td align="center" style="border: 1px solid #000;">&nbsp;<?php echo $row['payment_term'];?></td>
								<td align="center" style="border: 1px solid #000;">&nbsp;<?php echo " $ ".$row['tuition_fee'];?></td>
								<td align="center" style="border: 1px solid #000;">&nbsp;<?php echo $discount;?></td>
								<td align="center" style="border: 1px solid #000;">&nbsp;<?php echo " $ ".$row['other_fee'];?></td>
								<td align="center" style="border: 1px solid #000;">&nbsp;<?php echo " $ ".$row['total_payment'];?></td>
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['note'];?></td>
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['user'];?></td>
								<td align="center" style="border: 1px solid #000;">&nbsp;<?php echo date("d-M-Y",strtotime($row['create_date']));?></td>
 							</tr>
							<?php }}?>	 
						</table>	
					</td>
				</tr>
				
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr >
					<td colspan="3" align="center" >
						<table width="100%">
							<tr>
								<td align="center" width="25%">
									<span style="font-size: 14px;"><?php echo $tr->translate("APPROVED_BY"); ?></span>
								</td>
								<td align="center" width="25%">
									<span style="font-size: 14px;"><?php echo $tr->translate("VERIFIED_BY"); ?></span>
								</td>
								<td align="center" width="25%">
									<span style="font-size: 14px;"><?php echo $tr->translate("CHECKED_BY"); ?></span>
								</td>
								<td align="center"  width="25%">
									<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate("PREPARED_BY"); ?></span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</div>			
	</div>		
</div>





