<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('PARKING_PAYMENT_REPORT')); 
	$frm =  $this->form_search;
?>	
<?php
	$array_month = array(
			"1"=>"January",
			"2"=>"February",
			"3"=>"March",
			"4"=>"April",
			"5"=>"May",
			"6"=>"June",
			"7"=>"July",
			"8"=>"August",
			"9"=>"September",
			"10"=>"October",
			"11"=>"November",
			"12"=>"December",
	);
?>
<div style="width: 28cm;margin: 0 auto;">
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-parking-payment')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table>	
		<tr>
			<td>
				<input dojoType="dijit.form.TextBox" class="fullside" id="txtsearch" name="txtsearch" placeholder="Search....." value="<?php echo $this->search['txtsearch'];?>" type="text">
			</td>
			<td>
				<?php echo $frm->getElement("branch");?>
			</td>
			<td>
				<?php echo $frm->getElement("user");?>
			</td>
			<td>
			 	<select name="shift"  id="shift" dojoType="dijit.form.FilteringSelect" class="fullside" >
			 		<option value="0" <?php if($this->search['shift']==0){echo 'selected="selected"';}?>>Shift</option>
			 		<option value="1" <?php if($this->search['shift']==1){echo 'selected="selected"';}?>>10:00am</option>
			 		<option value="2" <?php if($this->search['shift']==2){echo 'selected="selected"';}?>>04:00pm</option>
			 		<option value="3" <?php if($this->search['shift']==3){echo 'selected="selected"';}?>>06:30pm</option>
			 	</select>
			</td>
			<td>
				<?php echo $frm->getElement("start_date");?>
			</td>
			<td>
				<?php echo $frm->getElement("end_date");?>
			</td>
			<td>
				<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
			</td>
		</tr>
	</table>
	
</form>	
</div>
<div style="border: 1px dotted #000;background: #fff;width: 27cm;margin: 0 auto;min-height: 27cm; padding: 0.5cm;">
	<form  action="<?php echo $this->url(array('module'=>'allreport','controller'=>'submitdailyincome','action'=>'parking')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<div id="divPrint">
		<style>
			table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
			th{padding: 5px;}
			  
			table { page-break-inside:auto }
			tr{ page-break-inside:avoid; page-break-after:auto; }
		</style>
		<div id="exportExcel">
			<table style="background:#fff;width:90%; margin: 0 auto;width: 100%;">
				
				<tr>
					<td width="20%" align="left">
						<img style="width:70%;" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br />
					</td>
					<td align="center" width="60%">
						<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate("PARKING_PAYMENT_REPORT")?></strong><br />
						<strong style="font-family: Khmer OS Battambang,Times New Roman;color:#000; font-size: 13px;">For Date <?php echo date("d-M-Y",strtotime($this->search["start_date"]))?> to <?php echo date("d-M-Y",strtotime($this->search["end_date"]));?></strong>
					</td>
					<td width="20%" align="right">
						<?php if($this->search['branch']>0 && !empty($this->row)){echo "Branch : ".$this->row[0]['branch_name'];}?>
					</td>
				</tr>
				<tr>
					<td colspan="3">
						<table cellpadding="5"​ style="margin:0 auto;border: 1px solid #000;width:100%; border-collapse: collapse;white-space: nowrap;font-family: Khmer OS Battambang , Times New Roman; "  border="1" >
							<thead>
								<tr style="font-size:13px; height: 20px;border: 1px solid #000;background: #c1d0f3;font-weight: bold;" align="center" >
									<td style="border: 1px solid #000;"><?php echo $tr->translate("N_O");?></td>
									<td style="border: 1px solid #000;"><?php echo $tr->translate("RECEIPT_NO");?></td>
									<td style="border: 1px solid #000;"><?php echo $tr->translate("CUS_ID");?></td>
									<td style="border: 1px solid #000;"><?php echo $tr->translate("NAME");?></td>
									<td style="border: 1px solid #000;"><?php echo $tr->translate("PHONE");?></td>
									<td style="border: 1px solid #000;"><?php echo $tr->translate("EMAIL");?></td>
									<td style="border: 1px solid #000;"><?php echo $tr->translate("ថ្លៃកិបសំបុត្រម៉ូតូ");?></td>
									<td style="border: 1px solid #000;"><?php echo $tr->translate("ថ្លៃកិបសំបុត្រកង់");?></td>
									<td style="border: 1px solid #000;"><?php echo $tr->translate("លក់អេតចាយ");?></td>
									<td style="border: 1px solid #000;"><?php echo $tr->translate("TOTAL");?></td>
									<td style="border: 1px solid #000;"><?php echo $tr->translate("NOTE");?></td>
									<td style="border: 1px solid #000;"><?php echo $tr->translate("USER");?></td>
									<td style="border: 1px solid #000;"><?php echo $tr->translate("CREATE_DATE");?></td>
								</tr>
							</thead>
						<?php $i=0;$grand_total=0; if(!empty($this->row)){foreach ($this->row AS $row) { $i++;
							?>
							<tr class="hover" style="font-size:12px; height: 20px;border: 1px solid #000;" align="center" >
								<td style="border: 1px solid #000;"><?php echo $i;?></td>
								<td style="border: 1px solid #000;"><?php echo $row['receipt_no'];?></td>
								<td style="border: 1px solid #000;">&nbsp;<?php echo $row['customer_code'];?>&nbsp;</td>
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['name'];?></td>	
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['phone'];?></td>
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['email'];?></td>
								<td align="center" style="border: 1px solid #000;">&nbsp;<?php if($row['parking_moto_fee']>0){echo " $ ".$row['parking_moto_fee'];}?></td>
								<td align="center" style="border: 1px solid #000;">&nbsp;<?php if($row['parking_bike_fee']>0){echo " $ ".$row['parking_bike_fee'];}?></td>
								<td align="center" style="border: 1px solid #000;">&nbsp;<?php if($row['broken_thing_fee']>0){echo " $ ".$row['broken_thing_fee'];}?></td>
								<td align="center" style="border: 1px solid #000;">&nbsp;<?php echo " $ ".$row['total_fee'];?></td>
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['note'];?></td>
								<td align="center" style="border: 1px solid #000;">&nbsp;<?php echo $row['user_name'];?></td>
								<td align="center" style="border: 1px solid #000;">&nbsp;<?php echo date("d-M-Y",strtotime($row['create_date']));?></td>
 							</tr>
							<?php 
								$grand_total = $grand_total + $row['total_fee'];
								}}
							?>	 
						</table>
						
					<?php if(!empty($grand_total)){?>
						<table width="60%" border="1" style="white-space: nowrap;margin: 0 auto; text-align: center;margin-top: 20px;border-collapse: collapse;border: 1px solid #000;">
							<tr style="background: #c1d0f3;">
								<td align="center">
									<?php echo $tr->translate("GRAND_TOTAL");?>&nbsp;&nbsp;&nbsp;
								</td>
								<td width="25%">
									Rate
								</td>
								<td width="25%">
									Amount in USD
								</td>
								<td width="25%">
									Amount in Riel
									
									<input type="hidden" name="total_amount" id="total_amount" value="<?php echo number_format($grand_total,2);?>" dojoType="dijit.form.TextBox" />
									<input type="hidden" name="amount_riel" id="amount_riel" dojoType="dijit.form.TextBox" />
									<input type="hidden" name="shift_id" id="shift_id" value="<?php echo $this->search['shift'];?>" dojoType="dijit.form.TextBox" />
									<input type="hidden" name="branch_id" id="branch_id" value="<?php echo $this->search['branch'];?>" dojoType="dijit.form.TextBox" />
									<input type="hidden" name="user_id" id="user_id" value="<?php echo $this->search['user'];?>" dojoType="dijit.form.TextBox" />
								</td>
								
							</tr>
							<tr>
								<td style="border: 1px solid #000;">
									<?php echo "&nbsp;$ ".number_format($grand_total,2)?>
								</td>
								
								<td>
									<?php echo $this->rate." ៛";?>
								</td>
								
								<td style="border: 1px solid #000;">
									<div id="input_usd">
										<input type="text" name="amount_usd" id="amount_usd" value="0" class="fullside" onkeyup="calculateRemainReil();" dojoType="dijit.form.TextBox" />
									</div>
									<div id="hide_amount_usd">
										<label id="lb_amount_usd"></label>
									</div>
								</td>
								
								<td style="border: 1px solid #000;">
									<label id="lb_amount_reil"></label>
								</td>
							</tr>
						</table>
					<?php }?>
							
					</td>
				</tr>
				
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr >
					<td colspan="3" align="center" >
						<table width="100%" style="font-family: Khmer OS Battambang , Times New Roman;">
							<tr>
								<td align="center" width="25%">
									<span style="font-size: 14px;"><?php echo $tr->translate("APPROVED_BY"); ?></span>
								</td>
								<td align="center" width="25%">
									<span style="font-size: 14px;"><?php echo $tr->translate("VERIFIED_BY"); ?></span>
								</td>
								<td align="center" width="25%">
									<span style="font-size: 14px;"><?php echo $tr->translate("CHECKED_BY"); ?></span>
								</td>
								<td align="center"  width="25%">
									<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate("PREPARED_BY"); ?></span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</div>			
	</div>	
		<table width="100%">
			<tr>
				<td align="center">
					<input type="submit" name="save_close" id="save_close"  value="រក្សាទុក" label="<?php echo $tr->translate('SAVE_CLOSE');?>"  dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />	
						
					<input type="text" name="for_date" id="for_date" dojoType="dijit.form.DateTextBox" value="now" constraints="{datePattern:'dd/MM/yyyy'}"/>	
						
				</td>
			</tr>
		</table>	
	</form>
</div>

<script type="text/javascript">

	dojo.ready(function(){
		document.getElementById('hide_amount_usd').style.display="none";
		calculateRemainReil();
	});
							
	function calculateRemainReil(){
		total_amount = <?php echo $grand_total;?>;
		
		amount_usd = dijit.byId("amount_usd").get('value');
	
		exchange_rate = <?php echo $this->rate?>;
		
		dollar_to_convert = (total_amount - amount_usd).toFixed(2);
		//alert(dollar_to_convert);
		
		total_reil = dollar_to_convert*exchange_rate;
		
		//alert("total="+total_amount+",usd="+amount_usd+",exchange_rate="+exchange_rate+",riel="+total_reil);
	
		var result = 100 * Math.ceil(total_reil / 100);
		
		//alert(rounded);
		var total_reil = result.toFixed(2).replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1,");
	
		dijit.byId('amount_riel').attr('value',result);
		
		dojo.byId("lb_amount_usd").innerHTML = " $ " + amount_usd;
		dojo.byId("lb_amount_reil").innerHTML = " ៛ " + total_reil;
		
	}

	function doPrint() {
		//alert(1);
		
		document.getElementById('hide_amount_usd').style.display="block";
		document.getElementById('amount_usd').style.display="none";
		
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    //hideDialog();
	    //alert(1);
	    document.getElementById('amount_usd').style.display="block";
	    document.getElementById('hide_amount_usd').style.display="none";
	}

	function preview()
	{ 
	  var disp_setting="toolbar=no,status=no,resizable=no,location=no,directories=yes,menubar=no,"; 
	      disp_setting+="scrollbars=no,width=1200, height=700, left=100, top=25"; 
	  var content_vlue = document.getElementById("divPrint").innerHTML; 
	  
	  var docprint=window.open("","",disp_setting); 
	   docprint.document.open(); 
	   docprint.document.write('<html><head>'); 
	   docprint.document.write('</head><div style=" font-size:16px !important; margin:0px; font-family:Verdana;"><style>table th {font-size:14px !important;} table td{font-size:12px !important;}</style><center>');          
	   docprint.document.write(content_vlue);          
	   docprint.document.write('</center></div></html>'); 
	   docprint.document.close(); 
	   docprint.focus(); 
	}
	function exportExcel(){
		$('#exportExcel').tableExport({type:'excel',escape:'false'});
	}
	
</script>



