<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Report Student Nearly End Service'); 
	echo $this->headTitle(''); 
	$frm =  $this->form_search;
?>	
<?php
	$array_month = array(
			"01"=>"January",
			"02"=>"February",
			"03"=>"March",
			"04"=>"April",
			"05"=>"May",
			"06"=>"June",
			"07"=>"July",
			"08"=>"August",
			"09"=>"September",
			"10"=>"October",
			"11"=>"November",
			"12"=>"December",
			"12"=>"December",
			
			"1"=>"January",
			"2"=>"February",
			"3"=>"March",
			"4"=>"April",
			"5"=>"May",
			"6"=>"June",
			"7"=>"July",
			"8"=>"August",
			"9"=>"September",
			"10"=>"October",
			"11"=>"November",
			"12"=>"December",
	);
?>
<div style="width: 28cm;margin: 0 auto;">
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-payable-nextmonth-transport')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table>	
		<tr>
			<td>
				<input dojoType="dijit.form.TextBox" id="txtsearch" name="txtsearch" class="fullside" placeholder="Search....." value="<?php echo $this->search['txtsearch'];?>" type="text">
			</td>
			<td>
				<?php echo $frm->getElement("branch");?>
			</td>
			<td>
				<?php echo $frm->getElement("transport_service");?>
			</td>
			<td>
	    		<select name="for_month" id="for_month" dojoType="dijit.form.FilteringSelect" class="fullside" >
	    			<option value="0"> select month </option>
	    			<?php if(!empty($this->all_month)){foreach ($this->all_month as $month){?>
	    				<option value="<?php echo $month['id']?>" <?php if($month['id']==$this->search['for_month']){echo "selected='selected'";}?>> <?php echo $month['name']?> </option>
	    			<?php }}?>
	    		</select>
	    	</td>
	    	<td>
	    		<select name="for_year" id="for_year" dojoType="dijit.form.FilteringSelect" class="fullside" >
	    			<?php for($i=2016;$i<=date("Y")+1;$i++){?>
	    				<option value="<?php echo $i;?>" <?php if($i==$this->search['for_year']){echo "selected='selected'";}?>> <?php echo $i;?> </option>
	    			<?php }?>
	    		</select>
	    	</td>
			
			<td>
				<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
			</td>
		</tr>
	</table>
</form>	
</div>
<div style="border: 1px dotted #000;background: #fff;width: 27cm;margin: 0 auto;min-height: 27cm; padding: 0.5cm;">
	<div id="divPrint">
		<div id="exportExcel">
			<table style="background:#fff;width:90%; margin: 0 auto;width: 100%;">
				
				<tr>
					<td width="20%" align="left">
						<img style="width:70%;" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br />
					</td>
					<td align="center" width="60%">
						<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate("TRANSPORT_PAYMENT_PAYABLE_REPORT")?></strong><br />
						<?php if(!empty($this->search['for_month'])){echo "For ".$array_month[$this->search['for_month']]." ".$this->search['for_year'];}?>
					</td>
					<td width="20%" align="right">
						<?php if($this->search['branch']>0 && !empty($this->row)){echo "Branch : ".$this->row[0]['branch_name'];}?>
					</td>
				</tr>
				<tr>
					<td colspan="3">
						<table cellpadding="5"​ style="margin:0 auto;border: 1px solid #000;width:100%; border-collapse: collapse;white-space: nowrap;"  border="1" >
							<tr style="font-size:13px; height: 20px;border: 1px solid #000;background: #ccc;" align="center" >
								<td style="border: 1px solid #000;">&nbsp;N.o&nbsp;</td>
								<td style="border: 1px solid #000;">&nbsp;Receipt No&nbsp;</td>
								<td style="border: 1px solid #000;">Code</td>
								<td style="border: 1px solid #000;">&nbsp;Student Name&nbsp;</td>
								<td style="border: 1px solid #000;">&nbsp;Sex&nbsp;</td>
								<td style="border: 1px solid #000;">&nbsp;Grade&nbsp;</td>
								<td style="border: 1px solid #000;">Service Name</td>
								<td style="border: 1px solid #000;">Paid Date</td>
								<td style="border: 1px solid #000;">Validate</td>
							</tr>
						<?php $i=0;$totalpaid=0;$totalbalance=0; if(!empty($this->row)){foreach ($this->row AS $row) { $i++;
												
							?>
							<tr class="hover" style="font-size:12px; height: 20px;border: 1px solid #000;" align="center" >
								<td style="border: 1px solid #000;"><?php echo $i;?></td>
								<td style="border: 1px solid #000;"><?php echo $row['receipt'];?></td>
								<td style="border: 1px solid #000;">&nbsp;<?php echo $row['transport_code'];?>&nbsp;</td>
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['name'];?></td>	
								<td align="center" style="border: 1px solid #000;">&nbsp;<?php echo $row['sex'];?></td>
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['grade'];?></td>
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['service'];?></td>
								<td style="border: 1px solid #000;">&nbsp;<?php echo date("d-M-Y",strtotime($row['start']));?>&nbsp;</td>
								<td style="border: 1px solid #000;color: red;">&nbsp;<?php echo date("d-M-Y",strtotime($row['end']));?>&nbsp;</td>
 							</tr>
							<?php }}?>	 
						</table>	
					</td>
				</tr>
				
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr >
					<td colspan="3" align="center" >
						<table width="100%">
							<tr>
								<td align="center" width="25%">
									<span style="font-size: 14px;"><?php echo $tr->translate("APPROVED_BY"); ?></span>
								</td>
								<td align="center" width="25%">
									<span style="font-size: 14px;"><?php echo $tr->translate("VERIFIED_BY"); ?></span>
								</td>
								<td align="center" width="25%">
									<span style="font-size: 14px;"><?php echo $tr->translate("CHECKED_BY"); ?></span>
								</td>
								<td align="center"  width="25%">
									<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate("PREPARED_BY"); ?></span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</div>			
	</div>		
</div>





