<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm =  $this->form_search;
	//print_r($this->rs[0]);
?>	
<title><?php echo $tr->translate('Daily Income English Fulltime Fee');?></title>



<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-daily-income-english-fulltime')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table width="100%">
	    <tr>
	    	<td><input type="text" name="txtsearch" id="txtsearch" class="fullside" value="<?php echo $this->search['txtsearch'];?>" dojoType="dijit.form.TextBox" /> </td>
	    	<td><?php echo $frm->getElement('branch');?></td>
	    	<td><?php echo $frm->getElement('degree_en_ft');?></td>
	    	<td><?php echo $frm->getElement('grade_en_ft');?></td>
	    	<td><?php echo $frm->getElement('room');?></td>
	    	<td><?php echo $frm->getElement('user');?></td>
	    </tr>
	    <tr>	
	    	<td>
			 	<select name="shift"  id="shift" dojoType="dijit.form.FilteringSelect" class="fullside" >
			 		<option value="0" <?php if($this->search['shift']==0){echo 'selected="selected"';}?>>Shift</option>
			 		<option value="1" <?php if($this->search['shift']==1){echo 'selected="selected"';}?>>10:00am</option>
			 		<option value="2" <?php if($this->search['shift']==2){echo 'selected="selected"';}?>>04:00pm</option>
			 		<option value="3" <?php if($this->search['shift']==3){echo 'selected="selected"';}?>>06:30pm</option>
			 	</select>
			</td>
	    	<td> <?php echo $frm->getElement("start_date");?></td>
	   	  	<td> <?php echo $frm->getElement("end_date");?></td>
	   	  	<td> <?php echo $frm->getElement("from_receipt");?></td>
	   	  	<td> <?php echo $frm->getElement("to_receipt");?></td>
	    	
	    	<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button> </td>
	    </tr>
	</table>
</form>	

<style>
.hover:hover{background: #ddd;}
tr.row_control {
    display: table-row !important;
}
</style>

<div style="border: 1px dotted #000;background: #fff; margin: 0 auto;min-height: 27cm; padding: 0.5cm;">
<form  action="<?php echo $this->url(array('module'=>'allreport','controller'=>'submitdailyincome','action'=>'english-fulltime')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<div id="divPrint">
<style>
/* 	table{ page-break-inside:auto } */
/*     tr{ page-break-inside:avoid; page-break-after:auto } */
/* 	#header { */
/* 		display: table-header-group; */
/* 		page-break-inside:avoid; page-break-after:auto; */
/* 	} */
	.bor{
		border-right: 1px solid #000;	
		border-bottom: 1px solid #000;
		font-size:13px;
	}
	.bor_r{
		border-right: 1px solid #000;	
		font-size:13px;
	}
	.padd{
		padding: 0 3px;	
	}
	#row{ font-size:12px; line-height: 17px;border: 1px solid #000;font-family:'Khmer OS Battambang';  }
	
	table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
  th{padding: 5px;}
  
  table { page-break-inside:auto }
    tr{ page-break-inside:avoid; page-break-after:auto; }
</style>

	<?php 
		$shift = array(1=>"10:00am",2=>"04:00pm",3=>"06:30pm");
	?>

	<table style="background:#fff;width:90%; margin: 0 auto;width: 100%;font-family:'Khmer OS Battambang';">
		<tr>
			
			<td width="15%" align="center">
				<img style="width:70%;" src="<?php echo $this->baseUrl().'/images/logo.png'?>">
			</td>
			<td align="center" width="70%" style="font-family: Khmer OS Battambang,Times New Roman;color:#000; font-size: 14px;">
				<strong  style="font-weight:bold;color:#000; font-size: 17px;font-family: Khmer OS Battambang,Times New Roman;​"><?php echo $tr->translate("Daily Income Report(Study English Fulltime Fee)");?></strong><br />
				<strong style="font-family: Khmer OS Battambang,Times New Roman;color:#000; font-size: 13px;">For Date <?php echo date("d-M-Y",strtotime($this->search["start_date"]))?> to <?php echo date("d-M-Y",strtotime($this->search["end_date"]));?></strong> <br />   
				<?php if($this->search['shift']>0){echo "Time : ".$shift[$this->search['shift']]." , "."Shift : ".$this->search['shift'];}?>
			</td>
			<td width="15%" >
				<?php if($this->search['branch']>0 && !empty($this->rs)){echo "Branch : ".$this->rs[0]['branch_name']."</br>";}?>
				<?php if($this->search['user']>0 && !empty($this->rs)){echo "User : ".$this->rs[0]['user_name'];}?>
			</td>
			
		</tr>
		<tr>
			<td colspan="3" id="exportExcel">
				<table cellpadding="8"​ style=" border: solid 1px #000; margin:0 auto; width:100%; border-collapse: collapse; white-space: nowrap;font-family:'Khmer OS Battambang';"  border="1" >
 					 <thead>
	 					 <tr align="center" style="background: #c1d0f3;font-size: 13px; line-height: 16px;">
							<td rowspan="2" class="padd">N<sup>o</sup></td>
							<td rowspan="2" class="padd">Receipt No.</td>
							<td rowspan="2" class="padd">Student ID</td>
							<td rowspan="2" class="padd">Student Name</td>
							<td rowspan="2" class="padd">Sex</td>
							<td rowspan="2" class="padd">Level/Grade</td>
							<td rowspan="2" class="padd">Time</td>
							<td colspan="3" class="padd">Study Fee Income</td>
							<td rowspan="2" class="padd">Admin<br/>Fee</td>
							<td rowspan="2" class="padd">Material<br/>fee</td>
							<td rowspan="2" class="padd">Other<br/>Fee</td>
							<td rowspan="2" class="padd">Credit</td>
							<td rowspan="2" class="padd">Total in<br/>USD</td>
							<td rowspan="2" class="padd">Remark</td>
							<td rowspan="2" class="padd">Create Date</td>
	 					 </tr>
						 <tr align="center" style="background: #c1d0f3;font-size: 12px; line-height: 14px;">
							<td rowspan="2" class="padd">Full Price</td>
							<td rowspan="2" class="padd">Discount</td>
							<td rowspan="2" class="padd">Amount</td>
	 					 </tr>
 					 </thead>
			
			<?php ////////////////////////////////// value //////////////////////////////////////////////////////////////////////////////////?>
			
				<?php 
					$i=0;
					$amont_new_student=0;
					$amont_old_student=0; 
					$total_study_fee=0;
					$total_admin_fee=0;
					$total_study_material_fee=0;
					$total_other_fee=0;
					$total_balance=0;
					$grand_total=0;
					$stu_id=0;
					$stu_name="";
				?>		
						
				<?php if(!empty($this->rs)){foreach ($this->rs as $rs){$i++;
						$stu_name = $rs['stu_enname'];
						if($stu_name == ""){
							$stu_name = $rs['stu_khname'];
						}
						//$study_material = $rs['grand_total_payment'] - ($rs['total_payment'] + $rs['admin_fee'] + $rs['other_fee']);
				?>
						
 					<tr id="row" align="center" class="hover" <?php if($rs['is_void']==1){echo "style='color:red;'";}?>>
 					
						<td class="padd"><?php echo $i;?></td>
						<td class="padd"><?php echo $rs['receipt_number'];?></td>
						<td class="padd"><?php echo $rs['stu_code'];?></td>
						<td class="padd"><?php echo $stu_name;?></td>
						<td class="padd"><?php echo $rs['sex'];?></td>
						<td class="padd"><?php echo $rs['grade'];?></td>
						<td class="padd"><?php echo $rs['time'];?></td>						
						
					<?php /*?>	
						
						<td class="padd"><?php if($rs['is_new']==1 AND $stu_id!=$rs['student_id']){echo "Yes";$amont_new_student = $amont_new_student + 1;}?></td>
						<td class="padd"><?php if($rs['is_new']==0 AND $stu_id!=$rs['student_id']){echo "Yes";$amont_old_student = $amont_old_student + 1;}?></td>
					<?php */?>	
						
						<td align="right" class="padd"><?php echo "$ ".$rs['tuition_fee'];?></td>
						<td class="padd">
							<?php if($rs['discount_percent']>0 && $rs['discount_fix']>0){
										echo $rs['discount_percent']." %"." + $".$rs['discount_fix'];
									}else if($rs['discount_percent']>0){
										echo $rs['discount_percent']." %";
									}else if($rs['discount_fix']>0){
										echo "$ ".$rs['discount_fix'];
									}
							?>
							
						</td>
						<td align="right" class="padd"><?php echo "$ ".$rs['tuition_fee_after_discount'];?></td>
						
						
						<td align="right" class="padd"><?php if($rs['admin_fee']>0){echo "$ ".$rs['admin_fee'];}?></td>
						
						
						<td align="right" class="padd"><?php if($rs['material_fee']>0){echo "$ ".$rs['material_fee'];}?></td>
						
						<td align="right" class="padd"><?php if($rs['other_fee']>0){echo "$ ".$rs['other_fee'];}?></td>
						
						<td align="right" class="padd"><?php if($rs['grand_total_balance']>0){echo "$ ".$rs['grand_total_balance'];}?></td>
						<td align="right" class="padd"><?php echo "$ ".$rs['grand_total_paid_amount'];?></td>
						
						<td class="padd"><?php echo $rs['note'];?></td>
						<td class="padd"><?php echo date("d-M-Y",strtotime($rs['create_date']));?></td>
 					</tr>
 					
					<?php 
						if($rs['is_void']==0){
							$stu_id=$rs['student_id'];
						
							$total_study_fee = $total_study_fee + $rs['tuition_fee_after_discount'];
							
							$total_admin_fee = $total_admin_fee + $rs['admin_fee'];
							
							$total_study_material_fee = $total_study_material_fee + $rs['material_fee'];
							
							$total_other_fee = $total_other_fee + $rs['other_fee'];
							
							
							if($rs['is_complete']==0){
								$total_balance = $total_balance + $rs['grand_total_balance'];
							}
						}
					?> 					
 					
 				<?php }}
 				
 						$grand_total = $total_study_fee + $total_admin_fee + $total_study_material_fee + $total_other_fee - $total_balance;
 				?>
 				
				</table>	
				
				<?php if(!empty($grand_total)){?>
					<table border="0" width="100%" >
						<tr>
							<td colspan="2">&nbsp;</td>
						</tr>
						<tr>
							<td width="70%" style="border: 1px solid #000;">
								&nbsp;<u>Summary Report:</u>
								<table width="100%" style="font-size: 14px;line-height: 24px;" cellspacing="1">
									<tr class="hover">
										<td>
											&nbsp;I. Income from English program fee(English full time)
										</td>
										<td>
											
										</td>
									</tr>
								<?php /*?>	
									<tr class="hover">
										<td>
											 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1. Total of new student
										</td>
										<td>
											<?php echo $amont_new_student;?> student(s)
										</td>
									</tr>
									<tr class="hover">
										<td>
											 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2. Total of old student
										</td>
										<td>
											<?php echo $amont_old_student;?> student(s)
										</td>
									</tr>
								<?php */?>		
									<tr class="hover">
										<td>
											 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1. Total Amount of study fee
										</td>
										<td>
											<?php echo "$ ".number_format($total_study_fee,2);?>
										</td>
									</tr>
									<tr class="hover">
										<td>
											&nbsp;II. Total amount of admin fee
										</td>
										<td>
											<?php echo "$ ".number_format($total_admin_fee,2);?>
										</td>
									</tr>
									<tr class="hover">
										<td>
											&nbsp;III. Total amount of study material fee
										</td>
										<td>
											<?php echo "$ ".number_format($total_study_material_fee,2);?>
										</td>
									</tr>
									<tr class="hover">
										<td>
											&nbsp;IV. Total amount of other fee
										</td>
										<td>
											<?php echo "$ ".number_format($total_other_fee,2);?>
										</td>
									</tr>
									<tr class="hover">
										<td>
											&nbsp;V. Total amount of student credit
										</td>
										<td>
											<?php echo "$ ".number_format($total_balance,2);?>
										</td>
									</tr>
									
									<tr class="hover">
										<td style="border-top:2px solid #000;">
											&nbsp; Total
										</td>
										
										<td style="border-top:2px solid #000;">
											<?php echo "$ ".number_format($grand_total,2);?>
										</td>
									</tr>
								</table>
							</td>
							<td width="30%" valign="top">
								<table width="100%" style="white-space: nowrap; font-size: 14px;">
									<tr>
										<td width="40%">
											&nbsp;
										</td>
										<td width="60%">
											&nbsp;Rate = <?php echo number_format($this->rate);?>
										</td>
									</tr>
									<tr>
										<td >
											&nbsp;Grand Total 
										</td>
										<td style="border: 1px solid #000;">
											<?php echo "$ ".number_format($grand_total,2)?>
										</td>
									</tr>
									<tr>
										<td>
											&nbsp;Amount in USD
										</td>
										<td style="border: 1px solid #000;">
											<div id="input_usd">
												<input type="text" name="amount_usd" id="amount_usd" value="0" onkeyup="calculateRemainReil();" dojoType="dijit.form.TextBox" />
											</div>
											<div id="hide_amount_usd">
												<label id="lb_amount_usd"></label>
											</div>
										</td>
									</tr>
									<tr>
										<td>
											&nbsp;Amount in Riel
											<input type="hidden" name="total_amount" id="total_amount" value="<?php echo number_format($grand_total,2);?>" dojoType="dijit.form.TextBox" />
											<input type="hidden" name="amount_riel" id="amount_riel" dojoType="dijit.form.TextBox" />
											<input type="hidden" name="shift_id" id="shift_id" value="<?php echo $this->search['shift'];?>" dojoType="dijit.form.TextBox" />
											<input type="hidden" name="branch_id" id="branch_id" value="<?php echo $this->search['branch'];?>" dojoType="dijit.form.TextBox" />
											<input type="hidden" name="user_id" id="user_id" value="<?php echo $this->search['user'];?>" dojoType="dijit.form.TextBox" />
										</td>
										<td style="border: 1px solid #000;">
											<label id="lb_amount_reil"></label>
										</td>
									</tr>
									<tr class="row_control" style="display: none;">
										<td>
											For Date
										</td>
										<td>
											<input type="text" name="for_date" id="for_date" dojoType="dijit.form.DateTextBox" value="now" constraints="{datePattern:'dd/MM/yyyy'}"/>
										</td>
									</tr>
									<tr class="row_control" style="display: none;">
										<td>
										</td>
										<td>
											<input type="submit" name="save_close" id="save_close"  value="រក្សាទុក" label="<?php echo $tr->translate('SAVE_CLOSE');?>"  dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconSave" />
										</td>
									</tr>
								</table>							
							</td>
						</tr>
						
						<tr>
							<td colspan="2">&nbsp;</td>
						</tr>
						
						<tr>
							<td colspan="2">
								<table width="100%" border="0" style="white-space: nowrap;font-size: 13px;">
									<tr align="center">
										<td width="15%">Auditor</td>
										<td width="18%">Senior Accountant</td>
										<td width="18%">Accountant Income</td>
										<td width="16%">Madam</td>
										<td width="18%">School Principal</td>
										<td width="15%">Cashier</td>
									</tr>
									<tr>
										<td colspan="6">&nbsp;</td>
									</tr>
									<tr align="center">
										<td>
											<div style="font-size: 13px;line-height: 20px;">
												Name:..............................<br />
												Date:........../........../..........
											</div>
										</td>
										<td>
											<div style="font-size: 13px;line-height: 20px;">
												Name:..............................<br />
												Date:........../........../..........
											</div>
										</td>
										<td>
											<div style="font-size: 13px;line-height: 20px;">
												Name:..............................<br />
												Date:........../........../..........
											</div>
										</td>
										<td>
											<div style="font-size: 13px;line-height: 20px;">
												Name:..............................<br />
												Date:........../........../..........
											</div>
										</td>
										<td>
											<div style="font-size: 13px;line-height: 20px;">
												Name:..............................<br />
												Date:........../........../..........
											</div>
										</td>
										<td>
											<div style="font-size: 13px;line-height: 20px;">
												Name:..............................<br />
												Date:........../........../..........
											</div>
										</td>
									</tr>
								</table>							
							</td>
						</tr>
						
					</table>
				<?php }?>
				</td>
			</tr>
		</table>
	
	</div>
	<table width="100%">
		<tr>
			<td align="center">
					
					
					
					
			</td>
		</tr>
	</table>
	</form>	
</div>
<script type="text/javascript">

dojo.ready(function(){
	document.getElementById('hide_amount_usd').style.display="none";
	calculateRemainReil();
});
					
function calculateRemainReil(){
	total_amount = '<?php echo $grand_total;?>';
	amount_usd = dijit.byId("amount_usd").get('value');
	exchange_rate = '<?php echo $this->rate?>';
	total_reil = ((total_amount - amount_usd)*exchange_rate).toFixed(2);
	//alert(total_reil);

	var result = 100 * Math.ceil(total_reil / 100);
	
	//alert(rounded);
	var total_reil = result.toFixed(2).replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1,");

	dijit.byId('amount_riel').attr('value',result);
	
	dojo.byId("lb_amount_usd").innerHTML = " $ " + amount_usd;
	dojo.byId("lb_amount_reil").innerHTML = " ៛ " + total_reil;
	
}



function doPrint() {
	//alert(1);
	
	document.getElementById('hide_amount_usd').style.display="block";
	document.getElementById('amount_usd').style.display="none";
	
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    //hideDialog();
    //alert(1);
    document.getElementById('amount_usd').style.display="block";
    document.getElementById('hide_amount_usd').style.display="none";
}
function preview()
{ 
  var disp_setting="toolbar=no,status=no,resizable=no,location=no,directories=yes,menubar=no,"; 
      disp_setting+="scrollbars=no,width=1200, height=700, left=100, top=25"; 
  var content_vlue = document.getElementById("divPrint").innerHTML; 
  
  var docprint=window.open("","",disp_setting); 
   docprint.document.open(); 
   docprint.document.write('<html><head>'); 
   docprint.document.write('</head><div style=" font-size:16px !important; margin:0px; font-family:Verdana;"><style>table th {font-size:14px !important;} table td{font-size:12px !important;}</style><center>');          
   docprint.document.write(content_vlue);          
   docprint.document.write('</center></div></html>'); 
   docprint.document.close(); 
   docprint.focus(); 
}
function exportExcel(){
	$('#exportExcel').tableExport({type:'excel',escape:'false'});
}
</script>
 