<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Report Student Drop Lunch and Stay'); 
	echo $this->headTitle(''); 
	$frm =  $this->form_search;
?>	
<div style="width: 28cm;margin: 0 auto;">
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-student-drop-lunch-and-stay')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		
		<table width="100%">
	       <tr>
	           <td><?php echo $frm->getElement("title");?></td>
			   <td> <?php echo $frm->getElement("branch");?></td>
			   
			   <td>
			   		<select name="service" id="service" dojoType="dijit.form.FilteringSelect" class="fullside"  >
			   			<option value="0"> select service </option>
			   			<?php if(!empty($this->service)){foreach ($this->service as $transport){?>
			   				<option value="<?php echo $transport['id']?>" <?php if($transport['id'] == $this->search['service']){echo "selected='selected'";}?>><?php echo $transport['name']?></option>
			   			<?php }}?>
			   		</select>
			   </td>
			   <td> <?php echo $frm->getElement("user");?></td>
			</tr>
			<tr>   
			   <td> <?php echo $frm->getElement("start_date");?></td>
	   	  	   <td> <?php echo $frm->getElement("end_date");?></td>
			   <td>
			   		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
	       	   </td>
	       </tr>
		</table>
		
		
</form>		
</div>
	<div style="border: 1px dotted #000;background: #fff;width: 27cm;margin: 0 auto;min-height: 27cm;padding: 0.5cm;">	
		<div id="divPrint">
			<table style="background:#fff; margin: 0 auto;width: 100%">
				<tr>
					<td width="20%" align="left">
						<img style="width: 60%;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br />
					</td>
					<td  align="center" width="60%">
						<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 17px;font-family:'Khmer MEF2';"><?php echo $tr->translate("STUDENT_DROP_LUNCH_AND_STAY_REPORT");?></strong><br />
						<strong  style="font-weight:bold;color:#000; font-size: 13px;font-family:'Khmer OS Muol';​">From <?php echo date('d-m-Y',strtotime($this->search['start_date']));?> &nbsp;To&nbsp; <?php echo date('d-m-Y',strtotime($this->search['end_date']));?></strong>
					</td>
					<td width="20%" align="right">
					</td>
				</tr>
				
					<style>
						table tr th{
							border: 1px solid #000;	
						}
						.hover:hover{background: #ccc;}
					</style>
			
				<tr>
					<td colspan="3">
						<table cellpadding="5"​ style="margin:0 auto;width:100%; border-collapse: collapse;white-space: nowrap;font-family: Khmer OS Battambang , Times New Roman;"  border="1" >
							<tr style="font-size:13px; height: 20px; background: #ccc;" align="center" >
								<td >No.</td>
								<td >Branch</td>
								<td >Student ID</td>
								<td >Student Name</td>
								<td >Gender</td>
								<td >Phone</td>
								<td >Service</td>
								<td >Type</td>
								<td >Reason</td>
								<td >Date Stop</td>
							</tr>
						<?php $i=0;if(!empty($this->rs)){ foreach ($this->rs AS $row) { $i++;?>
							<tr class="hover" style="font-size:12px; height: 20px;" align="center" >
								<td ><?php echo $i;?></td>
								<td ><?php echo $row['branch_name'];?></td>
								<td ><?php echo $row['stu_code'];?></td>
								<td align="left">&nbsp;&nbsp;<?php echo $row['name'];?></td>
								<td ><?php echo $row['sex'];?></td>
								<td ><?php echo $row['tel'];?></td>
								<td ><?php echo $row['service_name'];?></td>
								<td ><?php echo $row['type'];?></td>
								<td ><?php echo $row['reason'];?></td>
								<td ><?php echo date("d-M-Y",strtotime($row['date']));?></td>
							</tr>
						<?php }}?>	
						</table>	
					</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr >
					<td colspan="3">
						<table width="100%">
							<tr>
								<td align="center" width="25%">
									<span style="font-weight: bold;font-size: 14px;">Approved by</span>
								</td>
								<td align="center" width="25%">
									<span style="font-weight: bold;font-size: 14px;">Verified by</span>
								</td>
								<td align="center" width="25%">
									<span style="font-weight: bold;font-size: 14px;">Checked by</span>
								</td>
								<td align="center"  width="25%">
									<span style="font-weight: bold;font-size: 14px;">Prepared by</span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</div>		
	</div>
