<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Report Student Drop'); 
	echo $this->headTitle(''); 
	$frm =  $this->form_search;
?>	
<div style="width: 28cm;margin: 0 auto;">
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-student-drop')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		
		<table width="98%">
	       <tr>
	           <td><?php echo $frm->getElement("title");?></td>
	           <td> <?php echo $frm->getElement("branch");?></td>
	           <td> <?php echo $frm->getElement("study_year");?></td>
	           <td> <?php echo $frm->getElement("degree_all");?></td>
	           <td> <?php echo $frm->getElement("grade_all");?></td>
			   <td> <?php echo $frm->getElement("session");?></td>
			</tr>
			<tr>   
			   <td><input type="text" name="start_date" id="start_date" class="fullside" value="<?php echo $this->search['start_date'];?>" dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}"/></td>
		    	<td><input type="text" name="end_date" id="end_date" class="fullside" value="<?php echo $this->search['end_date'];?>" dojoType="dijit.form.DateTextBox"  constraints="{datePattern:'dd/MM/yyyy'}"/></td>
			   <td> <?php echo $frm->getElement("user");?></td>
			   <td>
			   		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
	       	   </td>
	       </tr>
		</table>
		
		
</form>		
</div>
	<div style="border: 1px dotted #000;background: #fff;width: 27cm;margin: 0 auto;min-height: 27cm;padding: 0.5cm;">	
		<div id="divPrint">
			<table style="background:#fff; margin: 0 auto;width: 100%">
				<tr>
					<td width="20%" align="left">
						<img style="width: 60%;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br />
					</td>
					<td  align="center" width="60%">
						<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate("RPT_STUDENT_DROP");?></strong><br />
						<strong  style="font-weight:bold;color:#000; font-size: 13px;font-family:'Khmer OS Muol';​">From <?php echo date('d-m-Y',strtotime($this->search['start_date']));?> &nbsp;To&nbsp; <?php echo date('d-m-Y',strtotime($this->search['end_date']));?></strong>
					</td>
					<td width="20%" align="right">
					</td>
				</tr>
				
					<style>
						table tr th{
							border: 1px solid #000;	
						}
						.hover:hover{background: #ccc;}
					</style>
			
				<tr>
					<td colspan="3">
						<table cellpadding="5"​ style="margin:0 auto;width:100%; border-collapse: collapse;white-space: nowrap;font-family: Khmer OS Battambang , Times New Roman;"  border="1" >
							<tr style="font-size:13px; height: 20px; background: #ccc;" align="center" >
								<td >No.</td>
								<td >Branch</td>
								<td >Student ID</td>
								<td >Student Name</td>
								<td >Gender</td>
								<td >AcademicYear</td>
								<td >Degree</td>
								<td >Grade</td>
								<td >Session</td>
								<td >Type</td>
								<td >Date Stop</td>
								<td >Reason</td>
							</tr>
						<?php $i=0; foreach ($this->rs AS $row) { $i++;?>
							<tr class="hover" style="font-size:12px; height: 20px;" align="center" >
								<td ><?php echo $i;?></td>
								<td ><?php echo $row['branch_name'];?></td>
								<td ><?php echo $row['stu_id'];?></td>
								<td align="left">&nbsp;&nbsp;<?php echo $row['name'];?></td>
								<td ><?php echo $row['sex'];?></td>
								<td ><?php echo $row['academic_year'];?></td>
								<td ><?php echo $row['degree'];?></td>
								<td ><?php echo $row['grade'];?></td>
								<td ><?php echo $row['session'];?></td>
								<td ><?php echo $row['type'];?></td>
								<td ><?php echo $row['date'];?></td>
								<td ><?php echo $row['note'];?></td>
							</tr>
						<?php }?>	
						</table>	
					</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr >
					<td colspan="3">
						<table width="100%">
							<tr>
								<td align="center" width="25%">
									<span style="font-weight: bold;font-size: 14px;">Approved by</span>
								</td>
								<td align="center" width="25%">
									<span style="font-weight: bold;font-size: 14px;">Verified by</span>
								</td>
								<td align="center" width="25%">
									<span style="font-weight: bold;font-size: 14px;">Checked by</span>
								</td>
								<td align="center"  width="25%">
									<span style="font-weight: bold;font-size: 14px;">Prepared by</span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</div>		
	</div>
