<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Rpt Att Study'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$frm = $this->form_search;
?>
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-att-study')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table width=80%" align="left">
		<tr>
			<td>
				<input  dojoType="dijit.form.TextBox"  class="fullside"  id="txtsearch" name="txtsearch" placeholder="Advance Search....." value="<?php echo $this->search['txtsearch'];?>" type="text">
			</td>
			<td>
				<?php echo $frm->getElement('branch');?>
			</td>
			<td>
				<select name="grade" id="grade" class="fullside" dojoType="dijit.form.FilteringSelect" >
					<option value="0">----- select grade -----</option>
					<?php if(!empty($this->grade)){foreach ($this->grade as $grade){?>
						<option value="<?php echo $grade['id']?>" <?php if($grade['id']==$this->search['grade']){echo 'selected="selected"';}?>><?php echo $grade['name']?></option>
					<?php }}?>
				</select>
			</td>
			
			<td>
				<select name="session" id="session" class="fullside" dojoType="dijit.form.FilteringSelect" >
					<option value="0">----- select session -----</option>
					<?php if(!empty($this->session)){foreach ($this->session as $session){?>
						<option value="<?php echo $session['id']?>" <?php if($session['id']==$this->search['session']){echo 'selected="selected"';}?>><?php echo $session['name']?></option>
					<?php }}?>
				</select>
			</td>
			
			<td>
				<select name="room" id="room" class="fullside" dojoType="dijit.form.FilteringSelect" >
					<option value="0">----- select room -----</option>
					<?php if(!empty($this->room)){foreach ($this->room as $room){?>
						<option value="<?php echo $room['id']?>" <?php if($room['id']==$this->search['room']){echo 'selected="selected"';}?>><?php echo $room['name']?></option>
					<?php }}?>
				</select>
			</td>
			
			<td>
				<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
			</td>
		</tr>
	</table>	
</form>
<style>
#footer{display: none;}
</style>	
<div style="border: 1px dotted #000;background: #fff; margin: 0 auto;min-height: 27cm;">
	<div id="divPrint">
	<div></div>
		<table style="background:#fff; margin: 0 auto; width: 100%; padding: 1cm; ">
			<tr>
				<td width="15%" align="center">
					<img style="width: 70%;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br />
				</td>
				<td align="center" width="70%">
					<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 15px;font-family:'Khmer MEF2';"><?php echo $tr->translate('Student Attendance List');?></strong><br >
				</td>
				<td align="right" width="15%">&nbsp;</td>
			</tr>
			<tr> 
				<td colspan="3"  id="exportExcel" >
					<style> th,td{ padding:0 1px;}</style>
						<style type="text/css">
							body{font-family: "Times New Roman",Arial; }
							table{ border-collapse:collapse; margin:0 auto;
							border-color:#000; }
							.padd tr td{  text-align:center}
							.padd tr th{  background-color: #ccc; }
							.hover:hover{background-color: #ccc;}
							
						</style>

					<table class="padd" width="99%" border="1" align="center" style="font-size:11px;white-space:nowrap;font-family: 'Khmer OS Battambang';">
						 <?php $i=0;$grade='';$session='';$room='';if(!empty($this->rs)){foreach($this->rs as $key => $rs){$i++;?>
						 		
						 	<?php if($grade != $rs['grade'] || $session != $rs['session'] || $room != $rs['room']){
// 						 		echo 'grade='.$grade.' , session='.$session.' , room='.$room;
						 			if($key>0){	
						 	?>
						  		  <tr>
								  		<td colspan="15" align="center">Class Patron's Signature</td>
								  </tr>
								  <tr>
								  		<td colspan="15" align="center">English Program Assistan's Signature</td>
								  </tr>
								  <tr>
								  		<td colspan="15" align="center">School Principle or Vice Principle's Signature</td>
								  </tr>
				 	 			</table>
								<table class="padd" width="99%" border="1" align="center" style="white-space:nowrap;font-family: Khmer OS Battambang;font-size: 11px;margin-top: 50px;">
				 	 		<?php }$i=1;?>
						  
						  <tr  style="font-size:10px;text-align:center; color:#000; height: 23px; border-left:1px solid #fff; border-right:1px solid #fff; border-top: 1px solid #fff;"​ align="center">
							    <td colspan="2" style="">
							    	<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 11px;font-family:'Khmer MEF2';" ><?php echo $tr->translate('Room').' : '.$rs['room_name']; ?></strong>
							    </td>
							    <td colspan="3" style="">
							    	<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 11px;font-family:'Khmer MEF2';" ><?php echo $tr->translate('Grade').' : '.$rs['grade_name']; ?></strong>
							    </td>
							    <td colspan="3" style="">
							    	<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 11px;font-family:'Khmer MEF2';" ><?php echo $tr->translate('Session').' : '.$rs['session_name']; ?></strong>
							    </td>
						  </tr>
						  <tr style="font-size:12px; height: 30px;background-color: #ccc;line-height: 20px;font-weight: bold;" align="center">
							    <td>&nbsp;<?php echo $tr->translate('N_O');?>&nbsp;</td>
							    <td>&nbsp;<?php echo $tr->translate('អត្តលេខ');?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate('ឈ្មោះ');?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate('ភេទ ');?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate('លេខទូរស័ព្ទ');?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate('ថ្ងៃចាប់ផ្តើម');?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate('ថ្ងៃផុតកំណត់');?>&nbsp;</td>
						  </tr>
						  
						  <?php 
						 		}
						 		$grade = $rs['grade'];
						 		$session = $rs['session'];
						 		$room = $rs['room'];
						  ?>
						 
						  <tr class="hover" style="font-size:11px; height: 18px;"​ align="center">
							    <td><?php echo $i;?></td>
							    <td><?php echo $rs['stu_code']; ?></td>
							    <td><?php echo $rs['name']; ?></td>
							    <td><?php echo $rs['sex'];?></td>
							    <td><?php echo $rs['stu_phone'];?></td>
							   	<td><?php echo date('d-m-Y',strtotime($rs['start_date'])); ?></td>
							    <td><?php echo date('d-m-Y',strtotime($rs['validate']));?></td>
						  </tr>
						  <?php }}?>
						  
						  <tr>
						  		<td colspan="15" align="center">Class Patron's Signature</td>
						  </tr>
						  <tr>
						  		<td colspan="15" align="center">English Program Assistan's Signature</td>
						  </tr>
						  <tr>
						  		<td colspan="15" align="center">School Principle or Vice Principle's Signature</td>
						  </tr>
						</table>
					
					</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr >
					<td colspan="3">
						<table width="100%" style="font-family: Khmer OS Battambang;font-size: 11px;">
							<tr>
								<td align="center" width="25%">
									<span style=" font-size: 14px;"><?php echo $tr->translate('VERIFIED_BY');?></span>
								</td>
								<td  width="50%">
									&nbsp;
								</td>
								<td align="center"  width="25%">
									<span style=" font-size: 14px;text-align: right;"><?php echo $tr->translate('PREPARE_BY');?></span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
	</div>	
</div>

