<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Report Student Balance'); 
	echo $this->headTitle(''); 
	$frm=$this->form_search;
	
	$payfor_type=array(
				1=>"Khmer Fulltime",
				6=>"English Fulltime",
				2=>"English Parttime",
				3=>"Transport",
				4=>"Lunch and Stay",
			);
?>	
<div style="width: 28cm;margin: 0 auto;">
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rptstudentbalance')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table>	
		<tr>
			<td>
				<input dojoType="dijit.form.TextBox" class="fullside" id="txtsearch" name="txtsearch" placeholder="Search....." value="<?php echo $this->search['txtsearch'];?>" type="text">
			</td>
			<td>
				<?php echo $frm->getElement('service');?>
			</td>
			<td>
				<select name="status" id="status" dojoType="dijit.form.FilteringSelect" class="fullside"  >
					<option value="" <?php if($this->search['status']==""){echo "selected='selected'";}?>>select status</option>
					<option value="1" <?php if($this->search['status']==1){echo "selected='selected'";}?>>បង់រួច</option>
					<option value="0" <?php if($this->search['status']==0){echo "selected='selected'";}?>>មិនទាន់បង់</option>
				</select>
			</td>
			<td>
				<select name="payfor_type" id="payfor_type" dojoType="dijit.form.FilteringSelect" class="fullside"  >
					<option value="" <?php if($this->search['payfor_type']==""){echo "selected='selected'";}?>>select type</option>
					<option value="1" <?php if($this->search['payfor_type']==1){echo "selected='selected'";}?>>Khmer Fulltime</option>
					<option value="6" <?php if($this->search['payfor_type']==6){echo "selected='selected'";}?>>English Fulltime</option>
					<option value="2" <?php if($this->search['payfor_type']==2){echo "selected='selected'";}?>>English Parttime</option>
					<option value="3" <?php if($this->search['payfor_type']==3){echo "selected='selected'";}?>>Transport</option>
					<option value="4" <?php if($this->search['payfor_type']==4){echo "selected='selected'";}?>>Lunch and Stay</option>
				</select>
			</td>
			<td> <?php echo $frm->getElement("start_date");?></td>
	   	  	<td> <?php echo $frm->getElement("end_date");?></td>
			<td>
				<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
			</td>
		</tr>
	</table>
</form>	
</div>
<div style="border: 1px dotted #000;background: #fff;width: 27cm;margin: 0 auto;min-height: 27cm;padding: 0.5cm;">
	<div id="divPrint">
		<div id="exportExcel" >
			<table  style="background:#fff; margin: 0 auto;width: 100%;">
				<tr>
					<td width="28%" align="left">
						<img style="width:50%;" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br />
					</td>
					<td align="center" width="44%">
						<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate("REPORT_STUDENT_BALANCE")?></strong><br />
						<span style="font-weight: bold;font-size: 14px;">From &nbsp;<?php echo date("d-M-Y",strtotime($this->search['start_date']));?> &nbsp;To&nbsp; <?php echo date("d-M-Y",strtotime($this->search['end_date']));?></span><br />
						<?php if(!empty($this->search['payfor_type'])){?>
						<span style="font-weight: bold;font-size: 14px;"><?php echo $payfor_type[$this->search['payfor_type']];?></span>
						<?php }?>
					</td>
					<td width="28%" align="right">
					</td>
				</tr>
				<tr>
					<td colspan="3">
						<table cellpadding="5"​ style="margin:0 auto;border: 1px solid #000;width:100%; border-collapse: collapse;white-space: nowrap;font-family: Khmer OS Battambang,Times New Roman;"  border="1" >
							<tr style="font-size:13px; height: 20px;border: 1px solid #000;background-color: #ccc;line-height: 30px;font-weight: bold;" align="center" >
								<td style="border: 1px solid #000;"><?php echo $tr->translate("N_O");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("RECEIPT_NO");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("STUDENT_ID");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("STUDENT_NAME");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("SEX");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("SERVICE_NAME");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("PRICE");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("DISCOUNT");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("PAID_AMOUNT");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("BALANCE");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("PAID_DATE");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("VALIDATE");?></td>
								<td style="border: 1px solid #000;"><?php echo $tr->translate("NOTE");?></td>
							</tr>
						<?php $i=0;$totalpaid=0;$totalbalance=0;if(!empty($this->rs)){ foreach ($this->rs AS $row) { 
							$i++;
							
							if($row['payfor_type']==3){
								$stu_code = $row['transport_code'];
							}else if($row['payfor_type']==4){
								$stu_code = $row['lunch_code'];
							}else{
								$stu_code = $row['code'];
							}
						?>
							<tr style="font-size:12px; height: 20px;border: 1px solid #000;" align="center" >
								<td style="border: 1px solid #000;"><?php echo $i;?></td>
								<td style="border: 1px solid #000;"><?php echo $row['receipt'];?></td>
								<td style="border: 1px solid #000;">&nbsp;<?php echo $stu_code;?>&nbsp;</td>
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['name'];?></td>	
								<td style="border: 1px solid #000;"><?php echo $row['sex'];?></td>
								<td align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['service'];?></td>
								<td style="border: 1px solid #000;">&nbsp;<?php echo "$ ".$row['fee'];?>&nbsp;</td>
								<td style="border: 1px solid #000;"><?php echo $row['discount']." %";?></td>
								<td style="border: 1px solid #000;"><?php echo "$ ".$row['payment'];?></td>
								<td style="border: 1px solid #000;"><?php echo "$ ".$row['paid'];?></td>
								<?php if($row['complete']==0){ ?>
									<td style="border: 1px solid #000;color:red;"><?php echo "$ ".$row['balance'];?></td>
									<?php $totalbalance=$totalbalance + $row['balance'];?>
								<?php }else{?>
									<td style="border: 1px solid #000;"><?php echo "$ ".$row['balance'];?></td>
									<?php $totalpaid=$totalpaid+$row['balance'];?>
								<?php }?>
								<td style="border: 1px solid #000;">&nbsp;<?php echo date("d-M-Y",strtotime($row['paid_date']));?>&nbsp;</td>
								<td style="border: 1px solid #000;">&nbsp;<?php echo date("d-M-Y",strtotime($row['validate']));?>&nbsp;</td>
								<?php if($row['complete']!=0){ ?>
									<td style="border: 1px solid #000;">&nbsp;<?php echo $row['comment'];?>&nbsp;</td>
								<?php }else{?>
									<td style="border: 1px solid #000;color:red;">&nbsp;<?php echo $row['comment'];?>&nbsp;</td>
								<?php }}?>
							</tr>
						<?php }?>	
						</table>	
					</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="2"></td>
					<td>
						<table border="1" align="right" style="width:50%; margin-right:0.5%; white-space:nowrap;border-collapse: collapse;border: 1px #000 solid;">
							<tr style="font-size:13px; background:#ccc; height: 20px;width: 400px;" align="center">
								<th>&nbsp;Total Balance Remain&nbsp;</th>
							</tr>
							<tr align="center" style=" height:18px; font-size:13px; padding: 1px;font-weight: bold;" >
								<td style="color: red;">$ <?php echo number_format($totalbalance,2);?></td>
							</tr>
						  </table>
					</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr >
					<td colspan="3" align="center" >
						<table width="100%" style="font-family: Khmer OS Battambang,Times New Roman;">
							<tr>
								<td align="center" width="25%">
									<span style="font-size: 14px;"><?php echo $tr->translate("APPROVED_BY"); ?></span>
								</td>
								<td align="center" width="25%">
									<span style="font-size: 14px;"><?php echo $tr->translate("VERIFIED_BY"); ?></span>
								</td>
								<td align="center" width="25%">
									<span style="font-size: 14px;"><?php echo $tr->translate("CHECKED_BY"); ?></span>
								</td>
								<td align="center"  width="25%">
									<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate("PREPARED_BY"); ?></span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</div> 				
	</div>		
</div>





