<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Report Student Payment Late'); 
	echo $this->headTitle(''); 
	$frm =  $this->form_search;
?>	
<?php
// 			$date1=date_create("2013-03-15");
// 			$date2=date_create("2013-04-15");
// 			$diff=date_diff($date1,$date2);
// 			echo $diff->format("%R%a days");exit();
?>
<div style="width: 28cm;margin: 0 auto;">
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rptstudentpaymentlate')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table width="100%">	
		<tr>
			<td>
				<input dojoType="dijit.form.TextBox" id="txtsearch" class="fullside" name="txtsearch" placeholder="Search....." value="<?php echo $this->search['txtsearch'];?>" type="text">
			</td>
			<td> <?php echo $frm->getElement("branch");?></td>
			<td > <?php echo $frm->getElement("degree_all");?></td>
			<td > <?php echo $frm->getElement("grade_all");?></td>
			<td> <?php echo $frm->getElement("service");?></td>
			<td>
				<input class="fullside" name="to_date" id="to_date" constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" placeholder="to date" value="<?php echo $this->search['end_date'];?>" type="text">
			</td>
			<td>
				<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
			</td>
		</tr>
	</table>
</form>	
</div>
<div style="border: 1px dotted #000;background: #fff;width: 27cm;margin: 0 auto;min-height: 27cm; padding: 0.5cm;">
	<div id="divPrint">
			<table style="background:#fff;width:90%; margin: 0 auto;white-space: nowrap;width: 100%;">
				
				<tr>
					<td width="20%" align="left">
						<img style="width:70%;" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br />
					</td>
					<td align="center" width="60%">
						<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';">របាយការណ៏​​ សិស្សបង់យឺត</strong><br />
						<span style="font-weight: bold;font-size: 11px;">&nbsp;ON&nbsp; <?php echo date("d-M-Y",strtotime($this->search['end_date']));?></span><br />
					</td>
					<td width="20%" align="right">
						
					</td>
				</tr>
				<tr>
					<td colspan="3">
						<table cellpadding="5"​ style="margin:0 auto;border: 1px solid #000;width:100%; border-collapse: collapse;white-space: nowrap;"  border="1" >
							<tr style="font-size:12px; font-weight:bold; border: 1px solid #000; background: #ccc; line-height: 30px;" align="center" >
								<td>&nbsp;<?php echo $tr->translate("N_O"); ?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("BRANCH"); ?>&nbsp;</td>
				                <td>&nbsp;<?php echo $tr->translate("STUDENT_ID"); ?>&nbsp;</td>
				     			<td>&nbsp;<?php echo $tr->translate("STUDENT_NAME"); ?>&nbsp;</td>
							    <td>&nbsp;<?php echo $tr->translate("SEX"); ?>&nbsp;</td>
							    <td>&nbsp;<?php echo $tr->translate("PHONE"); ?>&nbsp;</td>
							    <td>&nbsp;<?php echo $tr->translate("DEGREE"); ?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("GRADE"); ?>&nbsp;</td>
				                <td>&nbsp;<?php echo $tr->translate("RECEIPT"); ?>&nbsp;</td>
				                <td>&nbsp;<?php echo $tr->translate("SERVICE_NAME"); ?>&nbsp;</td>
				                <td>&nbsp;<?php echo $tr->translate("PAID_DATE"); ?>&nbsp;</td>
				                <td>&nbsp;<?php echo $tr->translate("VALIDATE"); ?>&nbsp;</td>
				                <td>&nbsp;<?php echo $tr->translate("AMOUNT_LATE"); ?>&nbsp;</td>
							</tr>
							<?php $i=0;$totalpaid=0;$totalbalance=0; if(!empty($this->row)){foreach ($this->row AS $row) { $i++;
												
								$end_dat=date($row['end']);
								$total_day=strtotime($end_dat)-strtotime($this->search['end_date']);
								$day=$total_day/(60*60*24);
								
								if($row['payfor_type']==3){
									$stu_code = $row['transport_code'];
								}else if($row['payfor_type']==4){
									$stu_code = $row['lunch_code'];
								}else{
									$stu_code = $row['stu_code'];
								}
							?>
							<tr style="font-size:11px; height: 20px;border: 1px solid #000;" align="center" class="hover" >
								<td style=""><?php echo $i;?></td>
								<td align="left" style="">&nbsp;<?php echo $row['branch_name'];?></td>	
								<td style="">&nbsp;<?php echo $stu_code;?>&nbsp;</td>
								<td align="left" style="">&nbsp;<?php echo $row['name'];?></td>	
								<td align="left" style="">&nbsp;<?php echo $row['sex'];?></td>
								<td align="left" style="">&nbsp;<?php echo $row['tel'];?></td>
								<td align="left" style="">&nbsp;<?php echo $row['degree'];?></td>
								<td align="left" style="">&nbsp;<?php echo $row['grade'];?></td>
								<td style=""><?php echo $row['receipt'];?></td>
								<td align="left" style="">&nbsp;<?php echo $row['service'];?></td>
								<td style="">&nbsp;<?php echo date("d-M-Y",strtotime($row['start']));?>&nbsp;</td>
								<td style="color: red;">&nbsp;<?php echo date("d-M-Y",strtotime($row['end']));?>&nbsp;</td>
								<td align="center" style="color: red;font-weight: bold;">&nbsp;<?php echo abs($day);?> days</td>
	 						</tr>
							<?php }}?>	 
						</table>	
					</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr >
					<td colspan="3" align="center" >
						<table width="100%">
							<tr>
								<td align="center" width="25%">
									<span style="font-size: 14px;"><?php echo $tr->translate("APPROVED_BY"); ?></span>
								</td>
								<td align="center" width="25%">
									<span style="font-size: 14px;"><?php echo $tr->translate("VERIFIED_BY"); ?></span>
								</td>
								<td align="center" width="25%">
									<span style="font-size: 14px;"><?php echo $tr->translate("CHECKED_BY"); ?></span>
								</td>
								<td align="center"  width="25%">
									<span style="font-size: 14px;text-align: right;"><?php echo $tr->translate("PREPARED_BY"); ?></span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				
			</table>
						
		</div>		
</div>





