<?php 
	  $tr=Application_Form_FrmLanguages::getCurrentlanguage();
	
	  $home=$this->url(array('module'=>'home','controller'=>'index','action'=>'index'), null, true);
	  $registrar=$this->url(array('module'=>'registrar','controller'=>'register','action'=>'index'), null, true);
	  $foundation=$this->url(array('module'=>'foundation','controller'=>'register','action'=>'index'), null, true);
	  $gep=$this->url(array('module'=>'gep','controller'=>'studentstudy','action'=>'index'), null, true);
	  $accounting=$this->url(array('module'=>'accounting','controller'=>'fee','action'=>'index'), null, true);
	 // $gep=$this->url(array('module'=>'gep','controller'=>'studentstudy','action'=>'index'), null, true);
	  //$gep=$this->url(array('module'=>'gep','controller'=>'gep','action'=>'index'), null, true);
	  $report=$this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'index'), null, true);
	  $global=$this->url(array('module'=>'global','controller'=>'branch','action'=>'index'), null, true);
	  $kidergarten=$this->url(array('module'=>'kindergarten','controller'=>'kindergarten','action'=>'index'), null, true);
	  $reference_path=$this->url(array('module'=>'analysis','controller'=>'query','action'=>'index'), null, true);
	  $backup=$this->url(array('module'=>'backup','controller'=>'index','action'=>'index'), null, true);
      $user=$this->url(array('module'=>'user','controller'=>'index','action'=>'index'), null, true);
      $acl=$this->url(array('module'=>'rsvacl','controller'=>'user','action'=>'index'), null, true);
      $setting=$this->url(array('module'=>'setting','controller'=>'index','action'=>'index'), null, true);
       
      $module=Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
	  
      //$url_logo = $this->baseUrl()."/images/cam-app-logo.png";
      
	  $item_arr=array(
	  	'index'=>'<li>
					<a><img src="/psst/trunk/public/images/cam-app-logo.png" style="max-height:45px"></a>
				</li>',
	  		
	   'home'=>'<li class="link">
					<a title="ទំព័រដើម" href="'.$home.'">
						<span class="icon_menu"><i class="fa fa-home" aria-hidden="true"></i></span><br />'.$tr->translate("HOME_PAGE").'
					</a>
				</li>',	  
	  'registrar'=>'<li class="link">
						<a title="ការិ.ចុះឈ្មោះ" href="'.$registrar.'">
							<span class="icon_menu"><i class="fa fa-graduation-cap" aria-hidden="true"></i></span><br />'.$tr->translate("REGISTRATION").'
						</a>
				  </li>',
	  'global'=>'<li class="link">
			  		<a title="ព័ត៏មានផ្សេងៗ" href="'.$global.'">
			  			<span class="icon_menu"><i class="fa fa-users" aria-hidden="true"></i></span><br />'.$tr->translate("OTHER_INFOMATION").'
			  		</a>
	  			</li>',
	  'foundation'=>'<li class="link">
				  		<a title="ការិយាល័យរដ្ឋបាល" href="'.$foundation.'">
				  			<span class="icon_menu"><i class="fa fa-university" aria-hidden="true"></i></span><br />'.$tr->translate("ADMINISTRATION").'
				  		</a>
				  	</li>',
	 /* 'kindergarten'=>'<li class="link">
	  		<a href="'.$kidergarten.'">
	  			<span>'.$tr->translate("Kindergarten").'</span>
	  		</a>
	  	</li>',
	 	'gep'=>'<li class="link">
							<a title="ការិយាល័យរដ្ឋបាល" href="'.$gep.'">
								<span>'.$tr->translate("GEP").'</span>
							</a>
						</li>',
	  
	  */
	  	'accounting'=>'<li class="link">
						<a title="ការិយាល័យគណនេយ្យ" href="'.$accounting.'">
							<span class="icon_menu"><i class="fa fa-money" aria-hidden="true"></i></span><br />'.$tr->translate("ACCOUNTING").'
						</a>
					</li>',
	     
	    'allreport'=>'<li class="link">
							<a title="របាយការណ៏" href="'.$report.'">
								<span class="icon_menu"><i class="fa  fa-file-text" aria-hidden="true"></i></span><br />'.$tr->translate("REPORT").'
							</a>
					   </li>',
	  	'rsvacl'=>'<li class="link">
				  		<a title="acl" href="'.$acl.'">
				  			<span class="icon_menu"><i class="fa  fa-cog" aria-hidden="true"></i></span><br />'.$tr->translate("ACL").'
				  		</a>
				   </li>',
	  	'setting'=>'<li class="link">
					  	<a title="ការកំណត់ផ្សេងៗ" href="'.$setting.'">
					  		<span class="icon_menu"><i class="fa  fa-cogs" aria-hidden="true"></i></span><br />'.$tr->translate("SRMS_SETTING").'
					  	</a>
					</li>',
	 
	  );
?>  
<div id="menu">
	<ul>
		<?php
			foreach($item_arr as $key=>$value){
				if($module==$key){
					echo str_replace('class="link"', 'class="current"', $value);
				}
				else{
					echo $value;
				}
			} 
		?>
		<li style="float: right;">
			<a href="" class="langiconen" onclick="changeLange(2);"></a>
		</li>
		<li style="float: right;  border-left: 1px solid #fff; border-right: 1px solid #fff;">
		<a href="" class="langiconkh" onclick="changeLange(1);"></a>
		</li>
	</ul>
</div>

<script>	
var url_changelang = '<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'changelange'));?> ';
function changeLange(lang){
	dojo.xhrPost({
		url: url_changelang,
	    content :{ 
			    'lange':lang,
		},	
		handleAs:"json",
		load: function(data) {
			location.reload();
		},
		error: function(err) {
			
		}
	});
}
	</script>