<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('TIME')); 
?>	

<?php  $classname= $this->frm_classname;?>
<form  id='add_room' action="<?php echo $this->url(array('module'=>'global','controller'=>'time','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			}else {
				return false;
			}
</script>
<table cellspacing="10" width="40%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset style="background-color:menu;">
					<legend align="center" ><strong><?php echo $tr->translate("TIME");?></strong></legend>
					<table style="margin: 0 auto; width: 95%;" cellspacing="10">
						<tr>
							<td style="width: 100px"><?php echo $tr->translate("FROM_TIME")?></td>
							<td><input type="text" name="from_time" id="from_time" dojoType="dijit.form.TextBox" class="fullside" /></td>
						</tr>
						<tr>
							<td ><?php echo $tr->translate("TO_TIME")?></td>
							<td><input type="text" name="to_time" id="to_time" dojoType="dijit.form.TextBox" class="fullside" /></td>
						</tr>
						<tr>
							<td colspan="2" align="center">
								<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconSave" />
								<input type="submit" value="save_new" name="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconSave" />
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
