<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('SRMS_WUREGISTER')); 
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>	
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/convertion.js"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.store.Memory");
	dojo.require('dojox.form.BusyButton');
	dojo.require("dojo.NodeList-manipulate");
	var dept_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->all_dept));?> );

	dojo.ready(function(){ 
		addRow();
		displayNoneAddRow();
		changControll();
		getStudentNo(7,'');
		setStudyTime();
		displayAmountSection();
		
		new dijit.form.FilteringSelect({
		    store: dept_store,
		    autoComplete: true,                        
		    required: true,
		    id: "dept",
		    name: "dept",           
		    class: 'fullside',  
		    placeHolder:"Selected Class",          
		    onChange: function() {  
		    	dept_id = dijit.byId('dept').get('value');
		    	dijit.byId('grade').attr('value','');
		    	getallModel(dept_id,a=''); 
		    	getStudentNo(dept_id,'');
				
				oldStudentChangeDegree();
				
		    }
		}, "dept");
	    
		new dijit.form.FilteringSelect({
		    //store: dept_store,
		    autoComplete: true,                        
		    id: "grade",
		    name: "grade",           
		    class: 'fullside',  
		    placeHolder:"Selected Grade",          
		    onChange: function() {  
		    	make_id = dijit.byId('grade').get('value');
		    	paymentTerm();
		    }
		}, "grade");

		new dijit.form.FilteringSelect({
		    autoComplete: true,                        
		    id: "study_year",
		    name: "study_year",           
		    class: 'fullside',  
		    placeHolder:"Selected year",          
		    onChange: function() {  
		    	paymentTerm();
		    }
		}, "study_year");

		getDateTerm();

		new dijit.form.FilteringSelect({
		    autoComplete: true,                        
		    id: "old_studens",
		    name: "old_studens",           
		    class: 'fullside',  
			required : false,
		    placeHolder:"----- select student id -----",          
		    onChange: function() {  
		    	getGepOldStudentById();
		    	paymentTerm();
		    	getStartDate();
		    }
		}, "old_studens");

		new dijit.form.FilteringSelect({
		    autoComplete: true,                        
		    id: "old_stu_name",
		    name: "old_stu_name",           
		    class: 'fullside',  
			required : false,
		    placeHolder:"----- select student name -----",          
		    onChange: function() {  
		    	setID(1);
		    }
		}, "old_stu_name");

		new dijit.form.FilteringSelect({
		    autoComplete: true,                        
		    id: "drop_studens",
		    name: "drop_studens", 
		    required: false,         
		    class: 'fullside',  
		    placeHolder:"----- select student id -----",          
		    onChange: function() {  
		    	getGepOldStudentById();
		    	paymentTerm();
		    	getStartDate();
		    }
		}, "drop_studens");

		new dijit.form.FilteringSelect({
		    autoComplete: true,                        
		    id: "drop_student_name",
		    name: "drop_student_name",
		    required: false,           
		    class: 'fullside',  
		    placeHolder:"----- select student name -----",          
		    onChange: function() {  
		    	setID(2);
		    }
		}, "drop_student_name");
		
		
	});	


	var year_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_year = '<?php echo $this->url(array('module'=>'accounting','controller'=>'coursestudy','action'=>'get-year-by-branch')); ?>';
	function getYearByBranch(){
		branch_id = dijit.byId('branch').get('value');
			dojo.xhrPost({
				url:url_year,
				content:{
					'branch_id':branch_id
					},
				handleAs:"json",
				load: function(data) {
					//alert(data);
					year_store  = getDataStorefromJSON('id','name', data);
				    dijit.byId('study_year').set('store',year_store);   
				},
				error: function(err) {
					//alert(err);
				}
			});
	}
	
	var old_stu_id_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var old_stu_name_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	
	var url_old_stu_id = '<?php echo $this->url(array('module'=>'accounting','controller'=>'coursestudy','action'=>'get-old-stu-id-by-branch')); ?>';
	function getOldStuIdByBranch(){
		
		dijit.byId('old_studens').attr('value','');
		dijit.byId('old_stu_name').attr('value','');
		
		branch_id = dijit.byId('branch').get('value');
		
			dojo.xhrPost({
				url:url_old_stu_id,
				content:{
					'branch_id':branch_id
					},
				handleAs:"json",
				load: function(data) {
					//alert(data);
					old_stu_id_store  = getDataStorefromJSON('id','name', data[0]);
					dijit.byId('old_studens').set('store',old_stu_id_store);   

					old_stu_name_store  = getDataStorefromJSON('id','name', data[1]);
					dijit.byId('old_stu_name').set('store',old_stu_name_store);
				},
				error: function(err) {
					//alert(err);
				}
			});
	}

	var drop_stu_id_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var drop_stu_name_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	
	var url_drop_stu_id = '<?php echo $this->url(array('module'=>'accounting','controller'=>'coursestudy','action'=>'get-drop-stu-id-by-branch')); ?>';
	function getDropStuIdByBranch(){
		
		dijit.byId('drop_studens').attr('value','');
		dijit.byId('drop_student_name').attr('value','');
		
		branch_id = dijit.byId('branch').get('value');
		if(branch_id>0){
			dojo.xhrPost({
				url:url_drop_stu_id,
				content:{
					'branch_id':branch_id
					},
				handleAs:"json",
				load: function(data) {
					//alert(data);
					drop_stu_id_store  = getDataStorefromJSON('id','name', data[0]);
					dijit.byId('drop_studens').set('store',drop_stu_id_store);   

					drop_stu_name_store  = getDataStorefromJSON('id','name', data[1]);
					dijit.byId('drop_student_name').set('store',drop_stu_name_store);
				},
				error: function(err) {
					//alert(err);
				}
			});
		}
	}
	

	
	var grade_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_dept = '<?php echo $this->url(array('module'=>'registrar','controller'=>'coursestudy','action'=>'get-grade')); ?>';
	function getallModel(dept_id,a){
			dojo.xhrPost({
				url:url_dept,
				content:{
					'dept_id':dept_id
					},
				handleAs:"json",
				load: function(data) {
					//alert(data);
					grade_store  = getDataStorefromJSON('id','name', data);
				    dijit.byId('grade').set('store',grade_store);   
				    if(a!=""){
				    	dijit.byId('grade').attr('value',a);
			        } 
				},
				error: function(err) {
					//alert(err);
				}
			});
	}
	
	var url_getstuno = '<?php echo $this->url(array('module'=>'registrar','controller'=>'coursestudy','action'=>'get-stu-no')); ?>';
	function getStudentNo(dept_id,condition){
		branch_id = dijit.byId('branch').get('value'); 
		if(dept_id>0 && branch_id>0){
			dojo.xhrPost({
				url:url_getstuno,
				content:{
					'dept_id':dept_id,
					'branch_id':branch_id,
					},
				handleAs:"json",
				load: function(data) {
					//alert(data);
					 dijit.byId('stu_id').attr('value',data);   
					if(condition!=''){
						//printSave(data,'');
						getNewReceiptNo(data);
					}
				},
				error: function(err) {
					alert(err);
				}
			});
		}
	}
	var url_getreceiptno = '<?php echo $this->url(array('module'=>'registrar','controller'=>'coursestudy','action'=>'get-receipt-no')); ?>';
	function getNewReceiptNo(new_stu_id){
		
		type = 2; // parttime payment
		branch_id = dijit.byId('branch').get('value');
		
		dojo.xhrPost({
				url:url_getreceiptno,
				content:{
					'type':type,
					'branch_id':branch_id,
					},
				handleAs:"json",
				load: function(data) {
					//alert(data);
					//url_getstuno  = getDataStorefromJSON('id','name', data);
					 dijit.byId('reciept_no').attr('value',data);   
					if(new_stu_id!=''){
						printSave(new_stu_id,data);
					}
				},
				error: function(err) {
					alert(err);
				}
			});
			
	}
	function paymentTerm(){
		study_year=dijit.byId('study_year').get('value');
		payment_term=dijit.byId('payment_term').get('value');
		levele=dijit.byId('grade').get('value');
		if(study_year!='' && payment_term !='' && levele !='' ){
			getPaymentTerms(study_year,levele,payment_term);
		}
		getDateTerm();
	}
///get price balance where complete=0
	function getPriceBalance(){
		student_type=dijit.byId('student_type').get('value');
		old_studens=dijit.byId('old_studens').get('value');
		if(student_type==3){
			if(old_studens != -1){
				getBalancePrice(4,old_studens); // 4 is register service
			}
		}
	}
	//get price balance
	var url_balance = '<?php echo $this->url(array('module'=>'registrar','controller'=>'coursestudy','action'=>'get-banlance-price')); ?>';
	function getBalancePrice(servce_id,student_id){
			type=2; // 2 is GEP register
			dojo.xhrPost({
				url:url_balance,
				content:{
					'servce_id':servce_id,
					'student_id':student_id,
					'type':type,
					},
				handleAs:"json",
				load: function(data) {
				      if(data){
				    	  dijit.byId('not').attr('value',data.sms);
				    	  dijit.byId('study_year').attr('value',data.year);
				    	  dijit.byId('session').attr('value',data.session);
				    	  dijit.byId('payment_term').attr('value',data.payment_term);
				    	  dijit.byId('start_date').attr('value',data.start_date);
				    	  dijit.byId('end_date').attr('value',data.validate);
				    	  dijit.byId('tuitionfee').attr('value',data.balance);
				    	  //dijit.byId('id_balance_record').attr('value',data.id);
				     	  dijit.byId('total').attr('value',data.balance);
				    	  dijit.byId('books').attr('value',data.balance);
				     }else {
				    	 dijit.byId('ids').attr('value','');
				    	// paymentTerms();
				    	 dijit.byId('tuitionfee').attr('value','0'); 
				    	 dijit.byId('total').attr('value','0'); 
				    	 dijit.byId('discount').attr('value','0');
				    	 dijit.byId('books').attr('value','0');
					     dijit.byId('addmin_fee').attr('value','0');
					     dijit.byId('remaining').attr('value','0');
					     dijit.byId('remark').attr('value','0');
					    // dijit.byId('char_price').attr('value','0');
					     dijit.byId('not').attr('value','');
				      }
				},
				error: function(err) {
					//alert(err);
				}
			});
	}
	var payment_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_getpaymentterm = '<?php echo $this->url(array('module'=>'accounting','controller'=>'coursestudy','action'=>'get-payment-gep')); ?>';
	function getPaymentTerms(study_year,levele,payment_term){
		dijit.byId('tuitionfee').attr('value',0);
    	dijit.byId('total').attr('value',0);
    	dijit.byId('books').attr('value',0);
    	dijit.byId('discount').attr('value',0);
    	dijit.byId('addmin_fee').attr('value',0);
    	dijit.byId('remaining').attr('value',0);
    	dijit.byId('remark').attr('value',0);
    	//dijit.byId('char_price').attr('value',0);

    	if(payment_term==5){ // if pay by section => show amount of section 
			document.getElementById('amount_section').style.display="block";
			document.getElementById('label_amount').style.display="block";
			
		}else{ // pay by other => hide amount of section
			document.getElementById('amount_section').style.display="none";
			document.getElementById('label_amount').style.display="none";
		}
			dojo.xhrPost({
				url:url_getpaymentterm,
				content:{
					'study_year':study_year,
					'levele':levele,
					'payment_term':payment_term,
					},
				handleAs:"json",
				load: function(data) {
				      if(data){
				    	dijit.byId('tuitionfee').attr('value',data.tuition_fee);
				    	dijit.byId('total').attr('value',data.tuition_fee);
				    	dijit.byId('books').attr('value',data.tuition_fee);
				    	dijit.byId('price_per_section').attr('value',data.tuition_fee);
				    	//dijit.byId('discount').attr('value','0');
				    	//dijit.byId('addmin_fee').attr('value','0');
				    	//dijit.byId('remaining').attr('value','0');
				    	//dijit.byId('remark').attr('value','0');
				      }else {

					  }

				      netTotal();
				      
				},
				error: function(err) {
					alert(err);
				}
			});
	}
	//set value totale 
	function getTotale(){
		//old % totale
		
		payment_term = dijit.byId('payment_term').get('value');
		if(payment_term==5){
			tuitionfee = dijit.byId('tuitionfee').get('value');
			amount_section = dijit.byId('amount_section').get('value');
			
			tuitionfee = tuitionfee * amount_section;
		}else{
			tuitionfee=dijit.byId('tuitionfee').get('value');
		}
		tuitionfee=isNaN(tuitionfee)?0:tuitionfee;
		
		discount=dijit.byId('discount').get('value');
		pc=discount/100;
		ds=tuitionfee*pc;
		old_totale=tuitionfee - ds;
		//alert('hello');
		
		remark=dijit.byId('remark').get('value');
		remark=isNaN(remark)?0:remark;
		
		addmin_fee=dijit.byId('addmin_fee').get('value');
		addmin_fee=isNaN(addmin_fee)?0:addmin_fee;
		
		totals=parseFloat(old_totale)+parseFloat(remark)+parseFloat(addmin_fee);
		  dijit.byId('total').attr('value',totals.toFixed(2));
		  dijit.byId('books').attr('value',totals.toFixed(2));
		  getRemaining();netTotal();
	}
	//set value remaining
	function getRemaining(){
		  total=dijit.byId('total').get('value');
		  total=isNaN(total)?0:total;
		  books=dijit.byId('books').get('value');
		  books=isNaN(books)?0:books;
		  remaining=parseFloat(total) - parseFloat(books);
		  if(total<books){
			 alert('Deposit must be smaller than the total money!');
			 dijit.byId('books').attr('value',total);
			 dijit.byId('remaining').attr('value','0');
		  }else{
		     dijit.byId('remaining').attr('value',remaining.toFixed(2));
		  }
		  CheckAmount();
	}
	function getDisccount(){
		tuitionfee=dijit.byId('tuitionfee').get('value');
		discount=dijit.byId('discount').get('value');
		pc=discount/100;
		ds=tuitionfee*pc;
		totale=tuitionfee - ds;
		if(discount<=100){
			   dijit.byId('total').attr('value',totale.toFixed(2));
			//   dijit.byId('remaining').attr('value','0');
			}else{ 
				alert('No more than a hundred of disccount!');
				dijit.byId('discount').attr('value','100');
				//getTotale();
			  //  dijit.byId('remaining').attr('value','0');
			}
	}
	var major_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
	var stucard_store = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->student_card));?> );

	function setValueTo(){
		if(dijit.byId('kh_name').item != null){
		//alert(items.name);
		dijit.byId("sender_code_no").attr('value', dijit.byId('sender_name').item.code_no);
		}
	}
	//calculator date by select term_payment
	function getDateTerm() {
		
		payment_term=dijit.byId('payment_term').get('value');
		start_date=dijit.byId('start_date').get('value');
		
		amount_section = dijit.byId('amount_section').get('value');
		
		if(payment_term==1){
			 var a = new Date(start_date);
			  mm = a.getMonth()+(1)+1;

			 var dd = a.getDate();
			  if(dd<10){
			   dd = "0"+dd;
			 }
			  if(mm<10){
			   mm = "0"+mm;
			 }
			 var y = a.getFullYear();
			 
			 var epx_date = y + '-' + mm + '-' + dd ;

			 //alert(epx_date);
			 dijit.byId('end_date').attr('value',epx_date);
		 }
		 else if(payment_term==2){
			 var a = new Date(start_date);
			  mm = a.getMonth()+(3)+1;

			 var dd = a.getDate();
			  if(dd<10){
			   dd = "0"+dd;
			 }
			  if(mm<10){
			   mm = "0"+mm;
			 }
			 var y = a.getFullYear();
			 var epx_date = y + '-' + mm + '-' + dd ;

			 //alert(epx_date);
			 dijit.byId('end_date').attr('value',epx_date);
		 }
		 else if(payment_term==3){
			 var a = new Date(start_date);
			  mm = a.getMonth()+(6)+1;

			 var dd = a.getDate();
			  if(dd<10){
			   dd = "0"+dd;
			 }
			  if(mm<10){
			   mm = "0"+mm;
			 }
			 var y = a.getFullYear();
			 var epx_date = y + '-' + mm + '-' + dd ;

			 //alert(epx_date);
			 dijit.byId('end_date').attr('value',epx_date);
		 }
		 else if(payment_term==4){
			 var a = new Date(start_date);
			  mm = a.getMonth()+(12)+1;

			 var dd = a.getDate();
			  if(dd<10){
			   dd = "0"+dd;
			 }
			  if(mm<10){
			   mm = "0"+mm;
			 }
			 var y = a.getFullYear();
			 
			 var epx_date = y + '-' + mm + '-' + dd ;

			 //alert(epx_date);
			 dijit.byId('end_date').attr('value',epx_date);
		 }else if(payment_term==5){
			var a = new Date(start_date);
			dd = a.getDate()+parseInt(amount_section); 
			 
			 if(dd<10){
			   dd = "0"+dd;
			 }
			 mm = a.getMonth()+1;
			 if(mm<10){
			   mm = "0"+mm;
			 }
			 var y = a.getFullYear(); 
			 var epx_date = y + '-' + mm + '-' + dd ;
			 
			 dijit.byId('end_date').attr('value',epx_date);
		 }
	}

	var url_get_start_date = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-start-date-register')); ?>';
	function getStartDate(){
		stu_type=dijit.byId('student_type').get('value');
		if(stu_type!=1){
			if(stu_type==3){
				stu_id = dijit.byId('old_studens').get('value');
			}else{
				stu_id = dijit.byId('drop_studens').get('value');
			}

			service_id=4;  // 4 => get validate only student register
			if(stu_id>0){
				dojo.xhrPost({
					url:url_get_start_date,
					content:{
						'service_id':service_id,
						'stu_id':stu_id
						},
					handleAs:"json",
					load: function(data) {
						if(data){
							dijit.byId('start_date').attr('value',data);
						}else{
							dijit.byId('start_date').attr('value','<?php echo date('Y-m-d');?>');
						}	
					},
					error: function(err) {
						alert(err);
					}
				});
			}
		}
	}
	
</script>
<style>
select{ width:100%;}
fieldset{  background:none;}
.red{ color: red; padding-left:5px;}
</style>
<?php $register = $this->frm_register;?>
<form id='office_receipt' action="<?php echo $this->url(array('module'=>'accounting','controller'=>'coursestudy','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">   
   if(this.validate()) {
    year = dijit.byId('study_year').get('value');
    branch = dijit.byId('branch').get('value');
    if(year==-1){
         dijit.byId("study_year").focus();
         return false;
    }
    if(branch==-1){
         dijit.byId("branch").focus();
         return false;
    }
    return true;
   }else {
    return false;
   }
</script>
<table  cellspacing="10" style="margin: 0 auto; width: 100%;">
	<tr>
		<td>
			<fieldset>
			<legend align="center"><strong><?php echo $tr->translate("OFFICIAL_RECEIPT");?></strong></legend>
				<table style="margin: 0 auto; width: 100%;padding:0px 10px 10px 10px;" cellspacing="7" >
					<tr>
						<td colspan="4"​ style="border-bottom:1px solid #ccc;"><strong><?php echo $tr->translate("STUDENT_INFO");?></strong></td>
					</tr>
					
					<tr>
						<td style="width: 160px"><?php echo $tr->translate("BRANCH");?></td>
						<td>
							<select name="branch" id="branch" class="fullside" onchange="getYearByBranch();getOldStuIdByBranch();getDropStuIdByBranch();getStudentNo(7,'');getNewReceiptNo('');" dojoType="dijit.form.FilteringSelect" type="text" >
								<option value="-1">-------- select branch ------</option>
								<?php if(!empty($this->branch)){foreach ($this->branch as $branch){?>
								<option value="<?php echo $branch['id'];?>"><?php echo $branch['name'];?></option>
								<?php }}?>
							</select>
						</td>
						<td></td>
						<td>
							<input type="checkbox" value="1" onchange="displayNoneAddRow();netTotal();" name="buy_product" id="buy_product" dojoType="dijit.form.CheckBox"  /> Buy Product
						</td>
					</tr>
					
					<tr>
						<td style="width: 160px"><?php echo $tr->translate("STUDENT_TYPE");?>
							  <?php echo $register->getElement('ids');?>
						</td>
						<td><?php echo $register->getElement('student_type');?></td>
						<td><?php echo $tr->translate("RECEIPT_NO");?></td>
						<td><?php echo $register->getElement('reciept_no');?></td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("STUDENT_ID");?></td>
						<td>
							<div id="student_id"><?php echo $register->getElement('stu_id');?></div>
							<div id="student_ids"><input id="old_studens" /></div>
							
							<div id="drop_stu_code"><input id="drop_studens" /></div>
						</td>
						<td style="width: 160px"><?php echo $tr->translate("STUDENT_NAME");?></td>
						<td>
							<div id="student_old_name"><input id="old_stu_name" /></div>
							<div id="name_stu"><?php echo $register->getElement('stu_name');?></div>
							
							<div id="drop_stu_name"><input id="drop_student_name" /></div>
						</td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("NAME_EN");?></td>
						<td><?php echo $register->getElement('en_name');?></td>
						<td><?php echo $tr->translate("NAME_KH");?></td>
						<td><?php echo $register->getElement('kh_name');?></td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("SEX");?></td>
						<td><?php echo $register->getElement('sex');?></td>
						<td><?php echo $tr->translate("DOB");?></td>
						<td><input type="text"  class="fullside" name="dob" id="dob" value="now" constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" /></td>
					</tr>
					
					<tr>
						<td><?php echo $tr->translate("ADDRESS");?></td>
						<td><input type="text"  class="fullside" name="address" id="address" dojoType="dijit.form.TextBox" /></td>
						
						<td><?php echo $tr->translate("PHONE");?></td>
						<td><input type="text" name="phone" id="phone" class="fullside" dojoType="dijit.form.TextBox" /></td>
					</tr>
					
					<tr>
						<td colspan="4"​ style="border-bottom:1px solid #ccc;"><strong><?php echo $tr->translate("STUDY_INFO");?></strong></td>
					</tr>
					
					<tr>
						<td style="width: 160px"><?php echo $tr->translate("ACADEMIC_YEAR");?></td>
						<td><input id="study_year" /></td>
						
						<td><?php echo $tr->translate("ROOM_NAME");?><label class="red">*</label></td>
						<td>
							<select name="room" id="room" dojoType="dijit.form.FilteringSelect" class="fullside" >
								<option value="-1">----- select room -----</option>
								<?php if(!empty($this->room)){foreach ($this->room as $room){?>
									<option value="<?php echo $room['id']?>"><?php echo $room['name']?></option>
								<?php }}?>
							</select>
						</td>
					</tr>
					<tr>
						<input type="hidden" name="old_stu_code" id="old_stu_code" dojoType="dijit.form.TextBox" />
						<input type="hidden" name="old_degree" id="old_degree" dojoType="dijit.form.TextBox" />
						<input type="hidden" name="old_grade" id="old_grade" dojoType="dijit.form.TextBox" />
					
						<td><?php echo $tr->translate("DEGREE");?><label class="red">*</label></td>
						<td><input id="dept" /><?php //echo $register->getElement('dept');?></td>
						
						<td><?php echo $tr->translate("CLASS");?><label class="red">*</label></td>
						<td><input id="grade" /><?php //echo $register->getElement('metion');?></td>
					</tr>
					<tr>
						<td title="ចាប់ពីម៉ោង"><?php echo $tr->translate("SESSION");?>*</td>
						<td>
							<select class="fullside"  tabindex="24" name="session" id="session" onchange="setStudyTime();" dojoType="dijit.form.FilteringSelect" >
								<option value='1'><?php echo $tr->translate('MORNING')?></option>
								<option value='2'><?php echo $tr->translate('AFTERNOON')?></option>
								<option value='3'><?php echo $tr->translate('EVERNING')?></option>
							</select>
						</td>
						
						<td><?php echo $tr->translate("TIME");?>*</td>
						<td>
							<input type="text" class="fullside" dojoType="dijit.form.TextBox" name="study_time" id="study_time" /> 
						</td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("PAYMENT_TERM");?><label class="red">*</label></td>
						<td><?php echo $register->getElement('payment_term');?></td>
						<td><?php echo $tr->translate("TUITION_FEE");?></td>
						<td><?php echo $register->getElement('tuitionfee');?></td>
					</tr>
					<input type="hidden" name="ex_rate" id="ex_rate" value="<?php echo $this->exchange_rate ;?>" dojoType="dijit.form.TextBox" />
					<input type="hidden" name="price_per_section" id="price_per_section" dojoType="dijit.form.TextBox" >
					<tr>
						<td>
							<div id="label_amount">
								<?php echo $tr->translate("AMOUNT_SECTION");?>
							</div>
						</td>
						<td>
							<div id="amount_section">
								<input name="amount_section" id="amount_section" onkeyup="calculateTotalFee();getDateTerm();" dojoType="dijit.form.TextBox" value="1" class="fullside" type="text"/>
							</div>
						</td>
					</tr>
					
					<tr>
						<td colspan="4"​ style="border-bottom:1px solid #ccc;"><strong><?php echo $tr->translate("PAYMENT_INFO");?></strong></td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("DISCOUND");?></td>
						<td title='Ex: 20 or 10%'><?php echo $register->getElement('discount');?></td>
						<td><?php echo $tr->translate("OTHERS_PRICE");?></td>
						<td><?php echo $register->getElement('remark');;?></td>
					</tr>
					<tr>	
						<td><?php echo $tr->translate("ADMIN_FEE");?></td>
						<td title='Ex: 20 or 10%'><?php echo $register->getElement('addmin_fee');?></td>	
						<td><?php echo $tr->translate("TOTALE");?></td>
						<td title='Ex: 20 or 10%'><?php echo $register->getElement('total');?></td>
					</tr>
					<tr>	
						<td><?php echo $tr->translate("BOOKS");?></td>
						<td><?php echo $register->getElement('books');;?></td>
						<td><?php echo $tr->translate("BALANCE");?></td>
						<td><?php echo $register->getElement('remaining');;?></td>
					</tr>
					<tr>	
						<td><?php echo $tr->translate("NOT");?></td>
						<td title='Ex: 20 or 10%' ><?php echo $register->getElement('not');?></td>	
						<td><?php echo $tr->translate("START_DATE");?></td>
						<td><?php echo $register->getElement('start_date');?></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td><?php echo $tr->translate("END_DATE");?></td>
						<td><?php echo $register->getElement('end_date');?></td>
					</tr>
					
					<input type="hidden" id="identity" name="identity" />
					<tr>
						<td colspan="4" align="left">
							<input type="button" label="<?php echo $tr->translate('ADD_ROW');?>" dojoType="dijit.form.Button" 
								iconClass="dijitIconEditProperty" onclick="addRow();" />
						</td>
					</tr>
					<tr>
						<td colspan="4">
							<table width="100%" border="1" id="table_row" style="border-collapse: collapse; border:1px solid #ccc;white-space: nowrap;">
									<tr id="head-title" class="head-td" align="right"></tr>
							</table>
						</td>
					</tr>
					
					<tr>
						<td colspan="6" align="right">
							<table style="width:400px;border-collapse: collapse;white-space:nowrap;" cellpadding="10" cellspacing="10" >
								<tr>
									<td ><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
									<td align="right"><input type="text" readonly="readonly" onkeyup="calculatBalanceAndReturn();"  name="grand_total" id="grand_total" dojoType="dijit.form.NumberTextBox" /></td>
								</tr>
								<tr>	
									<td><?php echo $tr->translate("CONVERT_TO_RIELS");?> (៛)</td>
									<td align="right"><input  type="text" readonly="readonly"  name="convert_to_riels" id="convert_to_riels" dojoType="dijit.form.NumberTextBox" /></td>
								</tr>
								<tr>	
									<td><?php echo $tr->translate("RECEIVED_AMOUNT");?></td>
									<td align="right"><input  type="text" readonly="readonly" onkeyup="calculatBalanceAndReturn();" required="true"  name="total_received" id="total_received" dojoType="dijit.form.NumberTextBox" /></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("BALANCE");?></td>
									<td align="right"><input type="text"  readonly="readonly" name="total_balance" value="<?php echo 0?>" id="total_balance" dojoType="dijit.form.NumberTextBox" /></td>
								</tr>
							</table>
						</td>
					</tr>
					
					<tr>
						<td colspan="4" align="center">
							<input type="button" name="save_close" id="save_close"  onclick="submitDataClose();" value="រក្សាទុក &ចាកចេញ" label="<?php echo $tr->translate('SAVE_CLOSE');?>"  dojoType="dijit.form.Button" 
							 iconClass="dijitEditorIcon dijitEditorIconSave" />
							<input type="button" name="save_new" id="save_new" onclick="submitDataAddNew();" value="រក្សាទុក" label="<?php echo $tr->translate('SAVE_NEW');?>"  dojoType="dijit.form.Button" 
							 iconClass="dijitEditorIcon dijitEditorIconSave" />
						</td>
					</tr>
				</table>	
			</fieldset>		
		</td>
	</tr>
</table>	
</form>
<script type="text/javascript">


function submitDataClose(){
	
	if(document.getElementById('buy_product').checked){
		condition = checkValidateAddRow();
		if(condition==false){
			alert("Please select service or product !!! ");
			return false;
		}
	}
		
	if(dijit.byId('office_receipt').validate()) {
		
		dijit.byId('save_new').set('disabled',true);
		dijit.byId('save_close').set('disabled',true);
	
		var url_submit = '<?php echo $this->url(array('module'=>'accounting','controller'=>'coursestudy','action'=>'add')); ?>';
		loading();
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("office_receipt"),		    
			load: function(data) {
				document.getElementsByClassName("overlay")[0].style.display="none";	
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/accounting/coursestudy";
			},
			error: function(e) {
			}
		});
	}
}

function submitDataAddNew(){
	
	if(document.getElementById('buy_product').checked){
		condition = checkValidateAddRow();
		if(condition==false){
			alert("Please select service or product !!! ");
			return false;
		}
	}
	
	if(dijit.byId('office_receipt').validate()) {
	
		dijit.byId('save_new').set('disabled',true);
		dijit.byId('save_close').set('disabled',true);
		
		var url_submit = '<?php echo $this->url(array('module'=>'accounting','controller'=>'coursestudy','action'=>'add')); ?>';
		loading();
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("office_receipt"),		    
			load: function(data) {
				document.getElementsByClassName("overlay")[0].style.display="none";		
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/accounting/coursestudy/add";
			},
			error: function(e) {
			}
		});
	}
}

function checkValidateAddRow(){
	var rowId = $('#identity').val();
	//alert(rowId);
	if(rowId!=''){
		var rowIDArray = rowId.split(',');
		for(var n = 0; n < rowIDArray.length; n++) {
			product_id = dijit.byId('product_'+rowIDArray[n]).get('value');
			if(product_id==''){
				return false;
			}
		}
	}
	return true;
}


function loading(){
    document.getElementsByClassName("overlay")[0].style.display="block";
}


///////////////////////////////////////////////////////////// Add Row /////////////////////////////////////////////////////////

var template = '';
var service = '';
var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
date_format = '"dd/MM/yyyy"';

function addRow() {
	col++;no++;
	template='';
	if(title!=1){
	temp+='<th ><?php echo $tr->translate("DEL");?></th>';
	temp+='<th ><?php echo $tr->translate("N_O");?></th>';
	temp+='<th ><?php echo $tr->translate("PRODUCT");?></th>';
	temp+='<th  ><?php echo $tr->translate("PRICE");?></th>';
	temp+='<th  ><?php echo $tr->translate("AMOUNT");?></th>';
	temp+='<th  ><?php echo $tr->translate("DISCOUNT");?> %</th>';
	temp+='<th  ><?php echo $tr->translate("SUBTOTAL");?></th>';
	temp+='<th><?php echo $tr->translate("REMARK");?></th>';
	dojo.query("#head-title").append(temp);
	title=1;
	}
	template+='<td align="center"  style="width:3%"><img onclick="deleteRecord('+col+');calculateTotal('+col+');" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
	template+='<td align="center" style="width:3%;">'+no+'</td>';
	
	template+='<td style="width:30%"><input type="hidden" dojoType="dijit.form.TextBox" name="id_balance_record_'+col+'" id="id_balance_record_'+col+'"/>';
	template+='<select style="width:100%"  onchange="getProductPrice('+col+');" dojoType="dijit.form.FilteringSelect" id="product_'+col+'" name="product_'+col+'">';
	template+='<option value="">Select </option>';
	<?php if(!empty($this->all_product)){foreach($this->all_product as $product){?>
	template+='<option value="'+<?php echo $product['id']?>+'"><?php echo $product['name'];?></option>';
	<?php }}?>
	template+='</select></td>';	
	
	
	column = 0;
	template+='<td style="width:10%"> <input class="fullside"  type="text"  onkeyup="calculateTotal('+col+');" name="price_'+col+'" id="price_'+col+'" dojoType="dijit.form.NumberTextBox" " /><label id="subsub"></label></td>';	
	template+='<td style="width:10%"> <input class="fullside" type="text"  onkeyup="calculateTotal('+col+');" name="qty_'+col+'" id="qty_'+col+'" value="1" dojoType="dijit.form.NumberTextBox" /><label id="qty"></label></td>';			
	
	template+='<td style="width:10%"> <input class="fullside"  type="text" onkeyup="calculateTotal('+col+');" name="discount_'+col+'" value="<?php echo 0;?>" id="discount_'+col+'" dojoType="dijit.form.NumberTextBox" /><label id="subsub"></label></td>';
	template+='<td style="width:10%"> <input class="fullside"  type="text"  readonly="readonly" name="subtotal_'+col+'" id="subtotal_'+col+'" dojoType="dijit.form.NumberTextBox"/><label id="qty"></label></td>';
	template+='<td style="width:24%"> <input class="fullside"  type="text" name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ" /><label id="subsub"></label></td>';
	
	//constraints="{datePattern:'dd/MM/yyyy'}"
	
	tmp='<tr id="row'+col+'">';
	tmp+="</tr>";
	dojo.query("#table_row").append(tmp);
	
	if($("#identity").val()!="") {
	var identity = $("#identity").val();
	$("#identity").val(identity+','+col);
	} else {$("#identity").val(col);}
	dojo.html.set(dojo.byId("row"+col),template , {
	parseContent: true,
	});
	//getValidate(col);
	}
	function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
	if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
}



///////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////








function displayAmountSection(){
	payment_term = dijit.byId('payment_term').get('value');
	if(payment_term==5){
		document.getElementById('amount_section').style.display="block";
		document.getElementById('label_amount').style.display="block";
		
	}else{
		document.getElementById('amount_section').style.display="none";
		document.getElementById('label_amount').style.display="none";
		//alert(222);
	}
	
}

function calculateTotalFee(){
	// price_per_sec = dijit.byId('price_per_section').get('value');
	// amount_sec = dijit.byId('amount_section').get('value');

	// total_fee = price_per_sec * amount_sec;
	// dijit.byId('tuitionfee').attr('value',total_fee);
	getDisccount();getTotale();
}

function setStudyTime(){
	session = dijit.byId('session').get('value');
	if(session==1){
		dijit.byId('study_time').attr('value','8:00AM - 10:30AM ');
	}else if(session==2){
		dijit.byId('study_time').attr('value','2:00PM - 4:30PM ');
	}else if(session==3){
		dijit.byId('study_time').attr('value','5:30PM - 6:30PM ');
	}else{
		dijit.byId('study_time').attr('value','');
	}
}



function SubmitRegister(){
	if(dijit.byId('office_receipt').validate()){
		if(dijit.byId('tuitionfee').get('value') < dijit.byId('discount').get('value')){
			alert("Discount cannot greather than fee value!");
			return false;
		}
		dijit.byId('office_receipt').submit();
	}
}
function printSave(new_stu_id,new_receipt_no){		
		if(dijit.byId('office_receipt').validate() ) {
			if(dijit.byId('study_year').get('value')==-1){
               dijit.byId("study_year").focus();
               return false;
			}
			dojo.byId("lb_term").innerHTML = dijit.byId("payment_term").attr('displayedValue');
			
			//	 var d = dojo.byId("start_date").value.split('/');
			//   dojo.byId("lb_term_start").innerHTML = d[1] + "/" + d[0] +"/"+d[2];
				 var d=dijit.byId('start_date').get('value');
				 var day = d.getDate();
				 var x = d.toDateString().substr(4,3);
				 var year = d.getFullYear();
				 dojo.byId("lb_term_start").innerHTML = day+'-'+x+'-'+year;
				// var d = dojo.byId("end_date").value.split('/');
				// dojo.byId("lb_term_end").innerHTML = d[1] + "/" + d[0] +"/"+d[2];
				 var d=dijit.byId('end_date').get('value');
				 var day = d.getDate();
				 var x = d.toDateString().substr(4,3);
				 var year = d.getFullYear();
				 dojo.byId("lb_term_end").innerHTML = day+'-'+x+'-'+year;
			
		 dojo.byId("lb_student").innerHTML =dijit.byId("kh_name").get('value')+" - "+ dijit.byId("en_name").get('value');

		 degree = dijit.byId('dept').get('value');

		 stu_type = dijit.byId('student_type').get('value');
		 if(stu_type==1){
			 if(new_stu_id==''){
				 getStudentNo(degree,1);
			 }else{
				 dojo.byId("lb_student_id").innerHTML = new_stu_id;			
				 dojo.byId("lb_enroll_id").innerHTML = new_receipt_no;
			 }
		 }else{
			 dojo.byId("lb_enroll_id").innerHTML = dijit.byId("reciept_no").get('value');
			 dojo.byId("lb_student_id").innerHTML = dijit.byId("old_studens").attr('displayedValue');
		 }
		 
		 
		 
		 
		 dojo.byId("lb_level").innerHTML = dijit.byId("grade").attr('displayedValue');
		 dojo.byId("lb_session").innerHTML = dijit.byId("session").attr('displayedValue');
		 
		 dojo.byId("lb_study_time").innerHTML =dijit.byId("study_time").get('value');
		// dojo.byId("lb_room").innerHTML = dijit.byId("room").attr('displayedValue');
		 dojo.byId("lb_note").innerHTML = dijit.byId("not").get('value');
		 dojo.byId("lb_course_cost").innerHTML ="$ "+dijit.byId("tuitionfee").get('value').toFixed(2);
		 // សិក្សាបើ discount=0 កុំអោយវាចេញ​​ (blank) , if discount>0 it show discount%
		 var discount = dijit.byId("discount").get('value');
		 if(discount == 0){
			discount = '';
		 }else{
			 discount = discount+" %";
		 }
		 dojo.byId("lb_discount").innerHTML = discount;
		 dojo.byId("lb_total").innerHTML ="$ "+dijit.byId("total").get('value');
		 dojo.byId("lb_adminfee").innerHTML ="$ "+dijit.byId("addmin_fee").get('value');
		 dojo.byId("lb_remark").innerHTML ="$ "+dijit.byId("remark").get('value');
		 dojo.byId("lb_book").innerHTML ="$ "+dijit.byId("books").get('value').toFixed(2);
		 dojo.byId("lb_balance").innerHTML ="$ "+dijit.byId("remaining").get('value');
		 dijit.byId("terms").show();	
		}
}
</script>
<div class="dijitHidden" style="width: 20cm !important; height: 11cm ; padding: 0px; margin: 0px;">
<?php $keycode = $this->keycode;?>
	<div data-dojo-type="dijit.Dialog" style="width:24cm;" align="center" data-dojo-props="title:'<?php echo $tr->translate("STUDENT_PAYMENT_RECEIPT");?>'" id="terms" >
		 <div class="header">
		     <table     bgcolor="fef7e4" cellspacing="0"  cellpadding="0" style="width: 19cm;  font-size:14px; color:rgba(14, 0, 107, 1); padding: 0px; margin: 0px;">
		          <tr>
		              <td colspan="8"  align="center"><strong style="font-family:'Khmer OS Muol';font-size: 20px;color: rgb(47, 70, 149);"> សាលារៀន &nbsp;<font style="color: rgb(246, 86, 74);">អាស៊ាន </font>&nbsp;ហ៊ែរីថេជ</strong>
		              ​​​​​<br/><strong style="font-size: 20px;font-weight:bold;color: rgb(47, 70, 149);">ASEAN <font style="color: rgb(246, 86, 74);">HERITAGE</font> SCHOOL</strong>
		              </td>
		          </tr>
		     </table>
		</div>
		<div id="divPrint" style="width: 19cm !important; height: 12cm ; padding: 0px; margin: 0px;">
			<style>
				.fontbig{
					font-size: 15px;	
				}
				.fonttel{
					font-size: 18px;	
				}
				.pleft{
					width: 110px;	
				}
				.label{ font-weight: bold;font-size: 22px;}
				.value{ font:bold 12px 'Khmer OS Battambang';border: 1px solid rgba(14, 0, 107, 1); height: 25px; padding: 0 2px;width: 98%; display: block;
						line-height: 25px;
					    text-align: center;
						}
				.values{ border: 1px solid rgba(14, 0, 107, 1);; height: 25px; padding: 0 10px;display: block;
						line-height: 25px;}
				.h{}
​​               .print td{ font:bold 12px 'Khmer OS Battambang';}
			   .khmerbold{font:bold 12px 'Khmer OS Battambang';}
			   .khmer{font:12px 'Khmer OS Battambang';}
			   .one{white-space:nowrap;}
			   .h{ margin-top: -10px;/*margin-left:4px;*/}
			</style>	
			<table style="white-space: nowrap;" style="white-space: nowrap;" class="print" bgcolor="fef7e4" cellspacing="0"  cellpadding="0" style="width: 19cm !important;height: 11cm; font-size:12px; color:rgba(14, 0, 107, 1); padding:25px 10px 0px 5px; margin: 0px;">
				<tr>
				    <td colspan="5"  style="font:bold 18px 'Kh Muol';" align="center"><u><b><strong style=" font-family: Arial Black;font-family:'Khmer MEF2';">បង្កាន់ដៃបង់ប្រាក់</strong></b></u>
				        <div style="line-height:5px;"><strong style="font-size: 18px;font-weight:bold">OFFICIAL RECEIPT</strong></div>
				    </td>
				</tr>
				<tr> <td colspan="5" height="10px"></td></tr>
				<tr style="white-space: nowrap;">
				    <td class="one khmerbold" style="width:100px;">អត្តលេខសិស្ស<div class="h">Student ID</div></td>
				    <td width="35%"><strong><label id="lb_student_id" class="value"></label></strong></td>
				    <td style="width:5px;"></td>
				    <td class="one khmerbold" style="width:100px;">លេខបង្កាន់ដៃ<div class="h">Receipt No.</div></td>
				    <td  width="35%"><strong><label id="lb_enroll_id" class="value"></label></strong></td>
				 </tr>
				<tr style="white-space: nowrap;">
				    <td class="one khmerbold">ឈ្មោះ​សិស្ស <div class="h">Student Name</div></td>
				    <td ><strong><label id="lb_student" class="value"></label></strong></td>
				    <td style="width:10px;"></td>
				    <td class="one khmerbold">រយះពេលនៃការបង់<div class="h">Payment Period</div></td>
                    <td><strong><label id="lb_term" class="value"></label></strong></td>
                </tr>
				<tr style="white-space: nowrap;">
				    <td class="one khmerbold">កម្រិត<div class="h">Level</div></td>
				    <td><strong><label id="lb_level" class="value"></label></strong></td>
				    <td style="width:10px;"></td>
				    <td class="one khmerbold">តម្លៃវគ្គសិក្សា<div class="h">Tution Fee</div></td>
				    <td><strong><label id="lb_course_cost" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td class="one khmerbold">វេនសិក្សា<div class="h">Session</div></td>
				    <td><strong><label id="lb_session" class="value"></label></strong></td>
				    <td style="width:10px;" ></td>
					<td class="one khmerbold">បញ្ចុះតម្លៃ<div class="h">Discount</div></td>
					<td><strong><label id="lb_discount" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td class="one khmerbold">ម៉ោងសិក្សា<div class="h">Study Time</div></td>
				    <td ><strong><label id="lb_study_time" class="value"></label></strong></td>
				    <td style="width:10px;" ></td>
					<td class="one khmerbold">តម្លៃរដ្ឋបាល <div class="h">Admin fee</div></td>
					<td><strong><label id="lb_adminfee" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td class="one khmerbold" >ថ្ងៃចាប់ផ្តើម<div class="h">Term Start</div></td>
				    <td style="white-space: nowrap;"><strong style="white-space: nowrap;"><label style="white-space: nowrap;" id="lb_term_start" class="value"></label></strong></td>
				    <td style="width:10px;"></td>
					<td class="one khmerbold">ទឹកប្រាក់ត្រូវបង់សរុប<div class="h">Total​ Amount</div></td>
					<td><strong><label id="lb_total" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td class="one khmerbold">មានសុពលភាពត្រឹម<div class="h">Payment Valid</div></td>
				    <td style="white-space: nowrap;"><strong style="white-space: nowrap;"><label style="white-space: nowrap;" id="lb_term_end" class="value"></label></strong></td>
				    <td style="width:10px;" ></td>
					<td class="one khmerbold">ទឹកប្រាក់បានបង់ <div class="h">Amount Paid</div></td>
					<td><strong><label id="lb_book" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td class="one khmerbold">ផ្សេងៗ <div class="h">Others</div></td>
					<td><strong><label id="lb_remark" class="value"></label></strong></td>
					
					<td style="width:10px;"></td>
					<td class="one khmerbold">ទឹកប្រាក់នៅខ្វះ <div class="h">Balance</div></td>
				    <td><strong><label id="lb_balance" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td class="one khmerbold">សម្គាល់ <div class="h">Note</div></td>
				    <td ><strong><label id="lb_note" class="value"></label></strong></td>
					<td style="width:10px;" ></td>
				    <td class="one khmerbold" >ថ្ងៃបានបង់ប្រាក់<div class="h">Paid Date</div>
				    </td>
				    <td class="one khmerbold" style="white-space: nowrap;"><label style="white-space: nowrap;" class="value"> &nbsp;&nbsp;
				    	<?php  $today = date("F j, Y, g:i a");echo $today; ?></label>
				    </td>
				</tr>
				<tr style="white-space: nowrap;">
				    <td colspan="2" class="khmerbold" style="line-height: 14px;">&nbsp;&nbsp; </td>
				    <td></td>
				    <td colspan="2" align="right" class="khmerbold" style="line-height: 14px;">
				        <h4 style="padding-right: 5px ! important;margin-bottom: -10px  !important;">
				              <?php $session_user=new Zend_Session_Namespace('auth');
						           $last_name=$session_user->last_name;
						           $username = $session_user->first_name;
						           echo " Official's Signature : ".$last_name." ".$username;?>
				        </h4><br/>
				    </td>
				</tr>
				<tr><td style="height: 10px;" colspan="5"></td></tr>
			</table>
		</div>
		<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>	
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
				showLabel="false" type="button" onclick="doPrint();printSubmit();">Print</button>
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel"
				showLabel="false" type="button" onclick="hideDialog();">Cancel</button>
	</div>
</div>

<script>
//save daata when sub button print 
function printSubmit(){
	 $('#office_receipt').submit();
}
function hideDialog(){
	dijit.byId('terms').hide();
}
function calculatePrice() {
	var total = $('#tuitionfee').val();
	var ds = $('#discount').val();
	if(ds.length!=0){
		if(ds.indexOf("%")!==-1){
			var pds=ds.split("%");
			if(!isNaN(pds[0])){
				var discount=(total*parseFloat(pds[0]))/100;
				after_discount = total - discount;
				return after_discount;

			}else{
				after_discount = total - ds;
				return after_discount;
			}
		}else{
			if(!isNaN(ds)&&ds!=0){
				discount = parseFloat(ds).toFixed(2);
				after_discount = total - discount;
				return after_discount;
			}else{
				//batch
				after_discount = total;
				return after_discount;
				}
		}
	}
}
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    dijit.byId("terms").hide();	//hideDialog();
}
function CheckAmount(){
	
	//alert('hello');
	remain=calculatePrice();
	if( 100 < dijit.byId('discount').get('value') ){
		alert("Discount cannot greather than fee value!");
		dijit.byId("discount").focus();
		return false;
	}
	else{
		//remain = dijit.byId('tuitionfee').get('value')-dijit.byId('discount').get('value');
	}
	b=dijit.byId('total').get('value');
	a = dojo.number.format(b);
	money_khmer=read_money_in_khmer(a);
	//dijit.byId('char_price').attr('value',money_khmer.trim()+'ដុល្លាគត់');
}
function getNewStudent(){
	if (dojo.byId("is_new").checked){
		dojo.byId("year").value = dojo.number.format(1);
		dojo.byId("batch").value = dojo.number.format(11);
		//getTuitionFee()
	}else{
		dojo.byId("year").value = "";
		dojo.byId("batch").value = "";
	}
}

var url_major = '<?php echo $this->url(array('module'=>'registrar','controller'=>'index','action'=>'get-majors')); ?>';
function changeMajor(){
	//getTuitionFee();
	/*dept_id = dijit.byId('dept').get('value');
			dojo.xhrPost({
			    url: url_major,			    
			    content : { 
				    'dept_id':  dept_id	    
				},
				handleAs:"json", 
			    load: function(response) {
			    	//major_store  = getDataStorefromJSON('id','name', response);
					//dijit.byId('major').set('store',major_store); 					    		    					    		    	
			    },
			    error: function(err) {
			    	 alert(err);
			        
			    }
			});*/
}
var url_add_sender = '<?php echo $this->url(array('module'=>'transfer','controller'=>'index','action'=>'addnewsender')); ?>';//for get payment date of sender 
function saveSender(){
		 sender_name=dijit.byId('sender_name').get('value');
			 sender_tel=dijit.byId('sender_tel').get('value');
				dojo.xhrPost({
				    url: url_add_sender,	
				    content : { 
					    'sender_name': sender_name,
					    'sender_tel': sender_tel			    
					},		    
					handleAs:"json", 
				    load: function(response) {	
				    	var Newsender = {		
				    			id: sender_name,
								name: sender_name
						};		
						addDataToSelectbox(dijit.byId('sender'), sender_store, Newsender, sender_name);
						dijit.byId("popupsender").hide();
				    },
				    error: function(e) {
					    alert("You can not add new sender !");
				        
				    }
				}); 
}
var url_add_getfee = '<?php echo $this->url(array('module'=>'global','controller'=>'globals','action'=>'get-tuitionfee')); ?>';//for get payment date of sender 
function changControll(){
	student_type=dijit.byId('student_type').get('value');
	 if(student_type==3){
		 document.getElementById('student_id').style.display="none";
		 document.getElementById('student_ids').style.display="block";
		 document.getElementById('student_old_name').style.display="block";
		 document.getElementById('name_stu').style.display="none";
		 document.getElementById('drop_stu_code').style.display="none";
		 document.getElementById('drop_stu_name').style.display="none";
		 clearControll();
	}else if(student_type==1){
		 document.getElementById('student_id').style.display="block";
		 document.getElementById('student_ids').style.display="none";
		 document.getElementById('student_old_name').style.display="none";
		 document.getElementById('name_stu').style.display="block";
		 document.getElementById('drop_stu_code').style.display="none";
		 document.getElementById('drop_stu_name').style.display="none";
		 clearControll();
	}else if(student_type==4){
		 document.getElementById('student_id').style.display="none";
		 document.getElementById('student_ids').style.display="none";
		 document.getElementById('student_old_name').style.display="none";
		 document.getElementById('name_stu').style.display="none";
		 document.getElementById('drop_stu_code').style.display="block";
		 document.getElementById('drop_stu_name').style.display="block";
		 clearControll();
	} 
}
function clearControll(){
	dijit.byId('kh_name').attr('value','');
	dijit.byId('en_name').attr('value','');
}

function setID(type){
	if(type==1){
		stu_id = dijit.byId('old_stu_name').get('value');
		dijit.byId('old_studens').attr('value',stu_id);
	}else{
		stu_id = dijit.byId('drop_student_name').get('value');
		dijit.byId('drop_studens').attr('value',stu_id);
	}
}

///get gep old student
var url_getGepoldstudent = '<?php echo $this->url(array('module'=>'registrar','controller'=>'coursestudy','action'=>'get-gep-old-student')); ?>';
function getGepOldStudentById(){
	dijit.byId('kh_name').attr('value','');
	dijit.byId('en_name').attr('value','');
	dijit.byId('sex').attr('value','');
	dijit.byId('dept').attr('value','');
	dijit.byId('grade').attr('value','');

	dijit.byId('old_degree').attr('value','');
	dijit.byId('old_grade').attr('value','');

	stu_type = dijit.byId('student_type').get('value');
	if(stu_type!=1){
		if(stu_type==3){
			student_id=dijit.byId('old_studens').get('value');
			dijit.byId('old_stu_name').attr('value',student_id);
		}else{
			student_id=dijit.byId('drop_studens').get('value');
			dijit.byId('drop_student_name').attr('value',student_id);
		}
		if(student_id>0){
			dojo.xhrPost({
				url:url_getGepoldstudent,
				content:{
					'student_id':student_id,
					},
				handleAs:"json",
				load: function(data) {
					  if(data){
				    	dijit.byId('kh_name').attr('value',data.stu_khname);
				    	dijit.byId('en_name').attr('value',data.stu_enname);
				    	dijit.byId('sex').attr('value',data.sex);
						dijit.byId('study_year').attr('value',data.academic_year);
				    	dijit.byId('dept').attr('value',data.degree);
						dijit.byId('session').attr('value',data.session);
						
						dijit.byId('old_stu_code').attr('value',data.stu_code);
						dijit.byId('old_degree').attr('value',data.degree);
						dijit.byId('old_grade').attr('value',data.grade);
						
						dijit.byId('dob').attr('value',data.dob);
				    	dijit.byId('phone').attr('value',data.tel);
				    	dijit.byId('address').attr('value',data.address);
						
						
						if(data.room==null){
				    		room=-1;
				    	}else{
							room = data.room;
				    	}
				    	dijit.byId('room').attr('value',room);
						
						
				    	getallModel(data.degree,data.grade);
				    	//dijit.byId('grade').attr('value',data.grade);
				      }else {
				    	alert('Student Id not found!');
				    	dijit.byId('kh_name').attr('value','');
				    	dijit.byId('en_name').attr('value','');
				    	dijit.byId('sex').attr('value','');
				    	dijit.byId('dept').attr('value','');
				    	dijit.byId('grade').attr('value','');
				      } 
				},
				error: function(err) {
					//alert(err);
				}
			});
		}
	}
}
		





var url_getproductprice = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-product-price')); ?>';
function getProductPrice(index){
	
	product = dijit.byId('product_'+index).get('value');
	qty = dijit.byId('qty_'+index).get('value');
	discount = dijit.byId('discount_'+index).get('value');
	
	dojo.xhrPost({
		url:url_getproductprice,
		content:{
			'product':product,
			},
		handleAs:"json",
		load: function(data) {
			if(data){
				//alert(data);
				
				fee_discount = data * qty * (discount/100);
				//alert(fee_discount);
				
				dijit.byId('price_'+index).attr('value',data);
				dijit.byId('subtotal_'+index).attr('value',(data * qty) - fee_discount);
				
				netTotal();
			}
		},
		error: function(err) {
			//alert(err);
		}
	});
}

function calculateTotal(index){
	price = dijit.byId('price_'+index).get('value');
	qty = dijit.byId('qty_'+index).get('value');
	qty=isNaN(qty)?1:qty;
	//if(qty==1){dijit.byId('qty_'+index).attr('value',qty);}
	total = price*qty;
	discount = dijit.byId('discount_'+index).get('value');
	discount = isNaN(discount)?0:discount;
	dijit.byId('subtotal_'+index).attr('value',total-(total*(discount/100)));
	netTotal();
}

function netTotal() {
	// alert(1);
		var netTotal=0;
		var netPaidAmount=0;
		var rowId = $('#identity').val();
		var rowIDArray = rowId.split(',');
		//alert(rowIDArray);
		
		tuition_fee = dijit.byId('tuitionfee').get('value');
		paid_amount = dijit.byId('books').get('value');
		total_payment = dijit.byId('total').get('value');
		
		if(document.getElementById('buy_product').checked){
			for(var n = 0; n < rowIDArray.length; n++) {
				//netTotal += Number($('#subtotal_'+rowIDArray[n]).val());
				netTotal += dijit.byId('subtotal_'+rowIDArray[n]).get('value');
				netPaidAmount += dijit.byId('subtotal_'+rowIDArray[n]).get('value');
			}
		}
		
		grand_total_payment = parseFloat(netTotal) + parseFloat(total_payment) ;
		grand_total_paid = parseFloat(netPaidAmount) + parseFloat(paid_amount) ;
				
		ex_rate = dijit.byId('ex_rate').get('value');
		
		dijit.byId('grand_total').attr('value',grand_total_payment);
		dijit.byId('convert_to_riels').attr('value',grand_total_payment * ex_rate);
		dijit.byId('total_received').attr('value',grand_total_paid);
		
		dijit.byId('total_balance').attr('value',grand_total_payment - grand_total_paid);
		
		//calculatBalanceAndReturn();
}

function displayNoneAddRow(){
	
	if(document.getElementById('buy_product').checked){
		document.getElementById('table_row').style.display="block";
	}else{
		document.getElementById('table_row').style.display="none";
	}
	
}


function oldStudentChangeDegree(){
	
	student_type = dijit.byId('student_type').get('value');
	old_degree = dijit.byId('old_degree').get('value');
	degree = dijit.byId('dept').get('value');
	
	if(student_type==3 ){
		if(old_degree!=degree){
		 document.getElementById('student_ids').style.display="none";
		 //document.getElementById('student_old_name').style.display="none";
		 document.getElementById('student_id').style.display="block";
		 //document.getElementById('name_stu').style.display="block";
		 //clearControll();
		 }
		else{
			 document.getElementById('student_ids').style.display="block";
			 //document.getElementById('student_old_name').style.display="block";
			 document.getElementById('student_id').style.display="none";
			 //document.getElementById('name_stu').style.display="none";
		} 
	}
}


</script>

<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>	
<style>
.overlay {display: none;position: absolute;width: 100%;height: 150%;top: 0px;left: 0px;background: #FCFCFC;z-index: 1001;opacity: .5;}
.overlay-load {width: 350px;height: 100px;margin: auto;top: 0px;bottom: 0px;position: absolute;left: 0px;right: 0px;
           text-align: center;
           background: #fff url("<?php echo $this->baseUrl()?>/images/loading.gif") 50% 25%;
           background-repeat: no-repeat;          
}
.overlay-msg{margin-bottom: 10px;bottom: 0px;position: absolute;font-style: italic;color: rgb(19, 19, 19);} 
</style>



