<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("EDIT_PARKING_PAYMENT"));
	//print_r($this->reil);
?>	
<style>
 
</style>
<script type="text/javascript" src="js/dojo/dojo.js" djConfig="isDebug: true, parseOnLoad: true"></script>
<script type="text/javascript">
    dojo.require("dojo.NodeList-manipulate");
    dojo.require("dojo.parser");
    dojo.require("dijit.form.Textarea");
    dojo.require("dijit.form.CheckBox");
    dojo.require("dojox.form.BusyButton");
</script>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
dojo.require("dojo.data.ItemFileWriteStore");
</script>
<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>
<form  id='frm_parking' action="" dojoType="dijit.form.Form" method="post"  enctype="multipart/form-data" >
<script type="dojo/method" event="onSubmit" enctype="multipart/form-data">			
	if(this.validate()) {
               dijit.byId('save_new').set('disabled',true);
			   dijit.byId('save_close').set('disabled',true);
			   return true;
			} else {
				return false;
			}
</script>
<table cellspacing="2" width="100%" style="margin: 0 auto; ">
	<tr>
		<td width="33%;" valign="top">
			<fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("CUSTOMER_INFO")?></strong></legend>
				<table style="margin: 0 auto; width: 100%;text-align: right;" cellspacing="2"  >
				        <tr>
							<td><?php echo $tr->translate("BRANCH");?></td>
							<td>
								<select dojoType='dijit.form.FilteringSelect' id="branch" name="branch" class="fullside" onChange="getOldCustomerByBranch();getCustomerIDByBranch();getReceiptByBranch();" ​​>
									<option value=""><?php echo $tr->translate("Select Branch");?></option>
									<?php if(!empty($this->branch)){foreach($this->branch as $branch){?>
										<option value="<?php echo $branch['id']?>" ><?php echo $branch['name']?></option>
									<?php }}?>
								</select>
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("OLD_CUS");?></td>
							<td align="left" style="height: 0px;"> <input type="checkbox" name="is_new_cu" id="is_new_cu" value="1" checked onClick="return false;" ></td> 
						</tr>
						<tr>
							<td><?php echo $tr->translate("CUS_ID");?></td>
							<td><input type="text" name="cus_id" class="fullside" id="cus_id"  style="color:red;" dojoType="dijit.form.ValidationTextBox" required="required" /> </td> 
						</tr>
						<tr>
							<td><?php echo $tr->translate("CUS_NAME");?></td>
							<td>
							  <div id="cus_name_div">
								<input type="text" name="cus_name" class="fullside" id="cus_name" dojoType="dijit.form.ValidationTextBox" required="required"/> 
							  </div>
							    <!-- old Customer  -->
							    <div id="old_cus_div">
									<select dojoType='dijit.form.FilteringSelect' id="old_cus" name="old_cus"   class="fullside"  ​​ onChange="getOldCustomerInfo();setCusName();" placeholder=" ">
							   			<option value="0"><?php echo $tr->translate("SELECT_CUSTOMER_NAME");?></option>
							   			<?php if(!empty($this->cus)) foreach ($this->cus as $c){?>
							   			<option value="<?php echo $c['id']?>" ><?php echo $c['name']?> </option>
							   			<?php }?>
						   			</select>
						   		</div>
					   			<!-- /end old Customer  -->
							</td>
						</tr>
						<tr>
						    <td><?php echo $tr->translate("SEX");?></td>
							<td>
								<select dojoType='dijit.form.FilteringSelect' id="sex" name="sex"   class="fullside"  ​​  placeholder=" ">
						   			<option value="1"><?php echo $tr->translate("MALE");?></option>
						   			<option value="2"><?php echo $tr->translate("FEMALE");?> </option>
					   			</select>
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("PHONE");?></td>
							<td><input type="text" name="phone" class="fullside" id="phone"   dojoType="dijit.form.TextBox" /> </td>
					    </tr>
					    <tr>
							<td><?php echo $tr->translate("EMAIL");?></td>
							<td><input type="text" name="email" class="fullside" id="email"   dojoType="dijit.form.TextBox" /> </td>
					    </tr>
					    <tr>
							<td><?php echo $tr->translate("ADDRESS");?></td>
							 <td><textarea class="fullside"  style=" height: 30px !important;" tabindex="20" dojoType=""  id="address" name="address"  ></textarea> </td>  
					    </tr>
				</table>	
			</fieldset>	
		</td>
		<td colspan="2" width="67%" valign="top">
			<table width="100%" >
				<tr>
					<td width="50%;" valign="top">
						<fieldset>
							<legend align="center" ><strong><?php echo $tr->translate("ថ្លៃកិបសំបុត្រម៉ូតូ")?></strong></legend>
								<table style="margin: 0 auto; width: 100%;text-align: right;" cellspacing="2"  >
								    <tr>
										<td><?php echo $tr->translate("TOTAL");?>(៛)</td>
										<td><input type="text" name="moto_total_in_riel" class="fullside" id="moto_total_in_riel" onKeyUp="calculateMotoFee();" dojoType="dijit.form.NumberTextBox" /> </td>
								    </tr>
								    <tr>
										<td><?php echo $tr->translate("FOR_DATE");?></td>
										<td><input type="text" name="moto_for_date" class="fullside" id="moto_for_date" dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now"/> </td>
								    </tr>
								    <tr>
								        <td><?php echo $tr->translate("EXC_RATE");?>($)</td>
								        <td><input type="text" name="moto_total_in_dollar" class="fullside" id="moto_total_in_dollar" dojoType="dijit.form.NumberTextBox" readOnly="true"/></td>
								    </tr>
								</table>
						</fieldset>	
					</td>
					<td width="50%;" valign="top">
						<fieldset>
							<legend align="center" ><strong><?php echo $tr->translate("ថ្លៃកិបសំបុត្រកង់")?></strong></legend>
								<table style="margin: 0 auto; width: 100%;text-align: right;" cellspacing="2"  >
									<tr>
										<td><?php echo $tr->translate("TOTAL");?>(៛)</td>
										<td><input type="text" name="bike_total_in_riel" class="fullside" id="bike_total_in_riel" onKeyUp="calculateBikeFee();" dojoType="dijit.form.NumberTextBox" /> </td>
								    </tr>
								    <tr>
										<td><?php echo $tr->translate("FOR_DATE");?></td>
										<td><input type="text" name="bike_for_date" class="fullside" id="bike_for_date" dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now"/> </td>
								    </tr>
								    <tr>
								        <td><?php echo $tr->translate("EXC_RATE");?>($)</td>
								        <td><input type="text" name="bike_total_in_dollar" class="fullside" id="bike_total_in_dollar" dojoType="dijit.form.NumberTextBox" readOnly="true"/></td>
								    </tr>
								</table>	
						</fieldset>	
					</td>
				</tr>
				
				<tr>
					<td valign="top">
						<fieldset>
							<legend align="center" ><strong><?php echo $tr->translate("លក់អេតចាយ")?></strong></legend>
								<table style="margin: 0 auto; width: 100%;text-align: right;" cellspacing="2"  >
								    <tr>
										<td><?php echo $tr->translate("TOTAL");?>(៛)</td>
										<td><input type="text" name="broken_in_riel" class="fullside" id="broken_in_riel" onKeyUp="calculateBrokenFee();" dojoType="dijit.form.NumberTextBox" /> </td>
								    </tr>
								    <tr>
										<td><?php echo $tr->translate("FOR_DATE");?></td>
										<td><input type="text" name="broken_for_date" class="fullside" id="broken_for_date" dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now"/> </td>
								    </tr>
								    <tr>
								        <td><?php echo $tr->translate("EXC_RATE");?>($)</td>
								        <td><input type="text" name="broken_total_in_dollar" class="fullside" id="broken_total_in_dollar" dojoType="dijit.form.NumberTextBox" readOnly="true"/></td>
								    </tr>
								</table>
						</fieldset>	
					</td>
					<td valign="top">
						<fieldset>
							<legend align="center" ><strong><?php echo $tr->translate("PAID_AMOUN")?></strong></legend>
								<table style="margin: 0 auto; width: 100%;text-align: right;" cellspacing="2"  >
									<tr>
									    <td><?php echo $tr->translate("ទឹកប្រាក់សរុប");?>($)​</td>
										<td><input type="text" name="all_total_amount" class="fullside" id="all_total_amount"  value="0" dojoType="dijit.form.NumberTextBox" readOnly="true"/> </td> 
									</tr>
									<tr>
										<td><?php echo $tr->translate("លេខបង្កាន់ដៃ");?></td>
										<td><input type="text" name="receipt_no" class="fullside" id="receipt_no" style="color:red;"  dojoType="dijit.form.ValidationTextBox" required="required" value="<?php echo $this->receipt_no;?>"/> </td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("CREATE_DATE");?></td>
										<td><input type="text" name="create_date" class="fullside" id="create_date" dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}" value="now"/> </td>
									</tr>
								    <tr>
										<td><?php echo $tr->translate("NOTE");?></td>
										<td><input type="text" name="note" class="fullside" id="note"   dojoType="dijit.form.TextBox" /> </td> 
									</tr>
								</table>	
						</fieldset>	
					</td>
				</tr>
				
			</table>
		</td>
	</tr>
	
	
	<tr>
		<td colspan="4" align="center" style="padding-left:40px;">
			<input type="submit" value="save_new" name="save_new"  id="save_new" label="<?php echo $tr->translate('GO_EDIT');?>" dojoType="dijit.form.Button" 
				 iconClass="dijitEditorIcon dijitEditorIconSave" />
		</td>
    </tr>
</table>	
</form>
<script>
var reil_exc="<?php echo $this->reil['reil']?>";
$(document).ready(function() {
	hidendOldCus();
	dijit.byId('old_cus').attr('value','<?php echo $this->row['parking_id']?>');
	getOldCustomerInfo();
	setValue();
	setReadonlyPageEdit();
});

function setValue(){
	dijit.byId('branch').attr('value','<?php echo $this->row['branch_id']?>');
	
	dijit.byId('moto_total_in_riel').attr('value','<?php echo $this->row['parking_moto_fee_in_riel']?>');
	dijit.byId('moto_for_date').attr('value','<?php echo $this->row['moto_for_date']?>');
	dijit.byId('moto_total_in_dollar').attr('value','<?php echo $this->row['parking_moto_fee']?>');
	
	dijit.byId('bike_total_in_riel').attr('value','<?php echo $this->row['parking_bike_fee_in_riel']?>');
	dijit.byId('bike_for_date').attr('value','<?php echo $this->row['bike_for_date']?>');
	dijit.byId('bike_total_in_dollar').attr('value','<?php echo $this->row['parking_bike_fee']?>');
	
	dijit.byId('broken_in_riel').attr('value','<?php echo $this->row['broken_thing_fee_in_riel']?>');
	dijit.byId('broken_for_date').attr('value','<?php echo $this->row['broken_for_date']?>');
	dijit.byId('broken_total_in_dollar').attr('value','<?php echo $this->row['broken_thing_fee']?>');
	
	dijit.byId('all_total_amount').attr('value','<?php echo $this->row['total_fee']?>');
	dijit.byId('receipt_no').attr('value','<?php echo $this->row['receipt_no']?>');
	dijit.byId('create_date').attr('value','<?php echo date("Y-m-d",strtotime($this->row['create_date']))?>');
	dijit.byId('note').attr('value','<?php echo $this->row['note']?>');
}

function setReadonlyPageEdit(){
	dijit.byId('branch').set('readOnly',true);
	
	dijit.byId("cus_id").set('readOnly',true);
	dijit.byId("old_cus").set('readOnly',true);
	
	dijit.byId("moto_total_in_riel").set('readOnly',true);
	dijit.byId("moto_for_date").set('readOnly',true);
	
	dijit.byId("bike_total_in_riel").set('readOnly',true);
	dijit.byId("bike_for_date").set('readOnly',true);
	
	dijit.byId("broken_in_riel").set('readOnly',true);
	dijit.byId("broken_for_date").set('readOnly',true);
	
	dijit.byId("receipt_no").set('readOnly',true);
	dijit.byId("note").set('readOnly',true);
	dijit.byId('create_date').set('readOnly',true);
}


function hidendOldCus(){
	if($('#is_new_cu').is(':checked')){
		$('#old_cus_div').show();
		$("#cus_name_div").hide();
		dijit.byId("old_cus").attr("value",'0');
	}else {
		$("#cus_name_div").show();
		$('#old_cus_div').hide();
		clearCusOld();
	}
}

function clearCusOld(){
	dijit.byId("cus_id").attr('value','<?php echo $this->cus_id;?>');
	dijit.byId("cus_name").attr("value","");
	dijit.byId("phone").attr("value","");
	dijit.byId("email").attr("value","");
	$("#address").val("");
}

function setCusName(){
	 dijit.byId("cus_name").attr('value',dijit.byId("old_cus").attr('displayedValue'));
}

function calculateMotoFee(){

	  moto_in_riel = dijit.byId("moto_total_in_riel").get("value");
	  if(isNaN(moto_in_riel)){
		moto_in_riel=0;
	  }
	  total_in_dollar = moto_in_riel / reil_exc;
	  dijit.byId("moto_total_in_dollar").attr("value",total_in_dollar.toFixed(2));
	  
	 getTotal();
}
function calculateBikeFee(){

	  bike_in_riel = dijit.byId("bike_total_in_riel").get("value");
	  if(isNaN(bike_in_riel)){
		bike_in_riel=0;
	  }
	  total_in_dollar = bike_in_riel / reil_exc;
	  dijit.byId("bike_total_in_dollar").attr("value",total_in_dollar.toFixed(2));
	  
	 getTotal();
}
function calculateBrokenFee(){

	  broken_in_riel = dijit.byId("broken_in_riel").get("value");
	  if(isNaN(broken_in_riel)){
		broken_in_riel=0;
	  }
	  total_in_dollar = broken_in_riel / reil_exc;
	  dijit.byId("broken_total_in_dollar").attr("value",total_in_dollar.toFixed(2));
	  
	 getTotal();
}

//functon get sum money All total
function getTotal(){
	var total=0;
	var moto=dijit.byId("moto_total_in_dollar").get("value");
	var bike=dijit.byId("bike_total_in_dollar").get("value");
	var broken=dijit.byId("broken_total_in_dollar").get("value");

	if(isNaN(moto)){
		moto=0;
	}
	if(isNaN(bike)){
		bike=0;
	}
	if(isNaN(broken)){
		broken=0;
	}
	total=parseFloat(moto+bike+broken);
	
	dijit.byId("all_total_amount").attr("value",total.toFixed(2));
	
	readMoneyInKhmer(total.toFixed(2));
	
}

function readMoneyInKhmer(netTotal){
	//alert(netTotal);
	var str = netTotal.toString();
	str_cent = 'សេន';
	first_decimal = str.substr(-2);
	last_decimal = str.substr(-1);
	
	if(first_decimal>0 && netTotal>=1){string='ដុល្លា និង ';last_string="សេន"}else{string="";str_cent="";last_string="សេន";}
	if(first_decimal!='00' && first_decimal<10 ){str_zero = "សូន្យ";}else{str_zero='';}
	first_money_decimal = read_in_khmer_from_10_to_99(first_decimal);
	last_money_decimal = read_in_khmer_from_0_to_9(last_decimal);
	money_khmer=read_money_in_khmer(netTotal);

	if(first_decimal>0){string_en='dot';}else{string_en="";str_cent_en=""}
	if(first_decimal!='00' && first_decimal<10 ){str_zero_en = "Zero";}else{str_zero_en='';}
	first_money_decimal_en = read_in_english_from_10_to_99(first_decimal);
	last_money_decimal_en = read_in_english_from_0_to_9(last_decimal);
	money_english=read_money_in_english(netTotal);
	
	dijit.byId('readmoney').attr('value',money_khmer.trim()+string+ first_money_decimal+str_zero+last_money_decimal+last_string);
}


//get old customer info 
var url_getcusinfo = '<?php echo $this->url(array('module'=>'registrar','controller'=>'parkingpayment','action'=>'get-customer-info')); ?>';
function getOldCustomerInfo(){
	var old_cus = dijit.byId("old_cus").get('value');
	if(old_cus==0 || old_cus==''){
		return  false;
	}
	dojo.xhrPost({
		url:url_getcusinfo,
		content:{
			'cus_id':old_cus
			},
		handleAs:"json",
		load: function(data) {
			 //set customer 
			dijit.byId("cus_id").attr("value",data.customer_code); 
			dijit.byId("cus_name").attr("value",data.first_name);	
			dijit.byId("sex").attr("value",data.sex);
			dijit.byId("phone").attr("value",data.phone);
			dijit.byId("email").attr("value",data.email);
			$("#address").val(data.address);
		},
		error: function(err) {
			alert(err);
		}
	});
}
function getMonthByNumber(m){
	var monthName=[
		"Jan",
		 "Feb",
		 "Mar",
		 "Apr",
		 "May",
		 "Jun",
		 "Jul",
		 "Aug",
		 "Sep",
		 "Oct",
		 "Nov",
		 "Dec",
		];
		return (monthName[m-1]);
}

//save daata when sub button print 
function printSubmit(){
	//$('#office_receipt').submit();
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
}

function printSave(new_stu_id,new_receipt_no){		
	if(dijit.byId('frm_parking').validate()) {
		 
		 
		 dojo.byId("lb_receipt_no").innerHTML = dijit.byId("receipt_no").get('value');
		 
		 if(document.getElementById('is_new_cu').checked){
			cus_name = dijit.byId("old_cus").attr('displayedValue');
		 }else{
			cus_name = dijit.byId("cus_name").get('value');
		 }
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////		
		 dojo.byId("lb_cus_name").innerHTML = cus_name;

		 dojo.byId("lb_sex").innerHTML = dijit.byId("sex").attr('displayedValue');
		 dojo.byId("lb_phone").innerHTML = dijit.byId("phone").attr('displayedValue');
		 
		 dojo.byId("lb_readmoney").innerHTML = dijit.byId("readmoney").attr('displayedValue');
		 
		 dojo.byId("lb_total_payment").innerHTML = " $ "+dijit.byId("all_total_amount").attr('displayedValue');
		 
		 
		 moto_payment = dijit.byId('moto_total_in_dollar').get('value');
		 if(moto_payment>0){
			dojo.byId("lb_moto_payment").innerHTML = " $ "+moto_payment;
			dojo.byId("checkbox_moto_payment").innerHTML = "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/checked.png'?>'>";
		 }else{
			dojo.byId("lb_moto_payment").innerHTML = "";
			dojo.byId("checkbox_moto_payment").innerHTML = "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/uncheck.png'?>'>";
		 }
		 
		 bike_payment = dijit.byId('bike_total_in_dollar').get('value');
		 if(bike_payment>0){
			dojo.byId("lb_bike_payment").innerHTML = " $ "+bike_payment; 
			dojo.byId("checkbox_bike_payment").innerHTML = "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/checked.png'?>'>";
		 }else{
			dojo.byId("lb_bike_payment").innerHTML = " ";
			dojo.byId("checkbox_bike_payment").innerHTML = "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/uncheck.png'?>'>";
		 }
		 
		 broken = dijit.byId('broken_total_in_dollar').get('value');
		 if(broken>0){
			dojo.byId("lb_broken").innerHTML = " $ "+broken;  
			dojo.byId("checkbox_broken").innerHTML = "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/checked.png'?>'>";
		 }else{
			dojo.byId("lb_broken").innerHTML = " ";  
			dojo.byId("checkbox_broken").innerHTML = "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/uncheck.png'?>'>";
		 }
		 
		 
		 dojo.byId("checkbox_rent").innerHTML = "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/uncheck.png'?>'>";
		 dojo.byId("checkbox_water").innerHTML = "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/uncheck.png'?>'>";
		 dojo.byId("checkbox_fire").innerHTML = "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/uncheck.png'?>'>";
		 
		 dojo.byId("checkbox_cleaner").innerHTML = "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/uncheck.png'?>'>";
		 dojo.byId("checkbox_other").innerHTML = "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/uncheck.png'?>'>";
		 
		 
		dijit.byId("terms").show();	
	}
	
}

function hideDialog() {		
	dijit.byId("terms").hide();
}
</script>

<div class="dijitHidden" style="width: 148mm !important; height: 175mm ; padding: 0px; margin: 0px;">
<?php $keycode = $this->keycode;?>
	<div data-dojo-type="dijit.Dialog" style="width:148mm !important;height: 175mm ;" align="center" data-dojo-props="title:'<?php echo $tr->translate("");?>'" id="terms" >
		
		<style>
			.data2{font-size:10px !important;}
		</style>
		
		<div id="divPrint" style="width: 148mm !important; height: 175mm ; padding: 0px; margin: 0px;">
			<style>
				.fontbig{
					font-size: 15px;	
				}
				.fonttel{
					font-size: 18px;	
				}
				.pleft{
					width: 110px;	
				}
				.label{ font-weight: bold;font-size: 22px;}
				.value{ font:bold 12px 'Khmer OS Battambang';border: 1px solid rgba(14, 0, 107, 1); height: 25px; padding: 0 2px;width: 98%; display: block;
						margin-top: -25px; line-height: 25px;
					    text-align: center;
						}
				.values{ border: 1px solid rgba(14, 0, 107, 1); height: 25px; padding: 0 10px;display: block;
						line-height: 25px;}
				.h{ margin-top: -8px;/*margin-left:4px;*/}
​​               .print td{ font:bold 12px 'Khmer OS Battambang';}
			   .khmerbold{font:bold 12px 'Khmer OS Battambang';}
			   .khmer{font:12px 'Khmer OS Battambang';}
			   .one{white-space:nowrap;}
			   
				.underline{margin-top: -18px;text-align:center;}
				.data{font-size:12px;font-weight:bold;}
				.data1{font-size:12px;font-weight:bold;}
				
				.receiptno{font-size:17px;font-weight:bold;}
				.tab_row{ margin-top: -8px;}
				.fonteng{font-size:12px;}
				
			</style>	
			<table border="0" width="100%" class="print" cellspacing="0"  cellpadding="0" style="white-space:nowrap; font-size:12px;font-family:'Khmer OS Battambang';line-height: 21px;">
				<tr>
				    <td colspan="6"  align="center" style="">
						<table width="100%" border="0" style="white-space:nowrap; font-family:Khmer OS Battambang;margin-top:-10px;font-weight:bold;">
							<tr>
								<td width="35%" align="left" style="font-size:10px;">
									<div style="font-size:13px;">Branch 6 (ចំការដូង​) </div><?php echo date('l , jS / m / Y , H:i:s ',strtotime(Zend_Date::now()));?>
								</td>
								<td width="30%" align="center">
									<img style="width: 50%;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br >
								</td>
								<td width="35%" align="center" style="font-size:17px;color:red;"><div style="margin-top:-5px;">N<sup>o</sup> : <label id="lb_receipt_no" class="receiptno" ></div></label></td>
							</tr>
						</table>
				    </td>
				</tr>
				
				<tr >
					<td colspan="6">
						<table width="100%" style="white-space:nowrap; font-size:12px;font-family:'Khmer OS Battambang';line-height: 21px;margin-top: -25px;">
							<tr>
								<td width="40%"><img style="width: 100%;height:4px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/double_underline.png'?>"></td>
								<td width="20%" align="center" style="font-size:16px;">បណ្ណបង់ប្រាក់</td>
								<td width="40%"><img style="width: 100%;height:4px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/double_underline.png'?>"></td>
							</tr>
						</table>
					</td>
				</tr>

				<tr>
					<td width="15%">&nbsp;</td>
					<td width="30%"></td>
					<td width="7%"></td>
					<td width="10%"></td>
					<td width="10%"></td>
					<td width="28%"></td>
				</tr>
				
				<tr>
					<td>ឈ្មោះអ្នកបង់ប្រាក់</td>
					<td>
						&nbsp;:&nbsp;<label id="lb_cus_name"  class="data" ></label>
						<div class="underline">&nbsp;.........................................</div>
					</td>
					<td align="center"> ភេទ</td>
					<td>
						:&nbsp;<label id="lb_sex" class="data" ></label>
						<div class="underline">............</div>
					</td>
					<td align="center"> លេខទូរសព្ទ</td>
					<td>
						:&nbsp;<label id="lb_phone" class="data" ></label>
						<div class="underline">......................................</div>
					</td>
				</tr>
				
				<tr>
					<td colspan="6">
						<table width="100%" style="white-space:nowrap;font-size:12px;font-family:'Khmer OS Battambang';">
							<tr>
								<td width="10%">ទឹកប្រាក់</td>
								<td width="25%">
									:&nbsp;<label id="lb_total_payment" class="data" ></label>
									<div class="underline">....................................</div>
								</td>
								<td width="10%">ជាអក្សរ</td>
								<td width="55%">
									:&nbsp;<label id="lb_readmoney" class="data" ></label>
									<div class="underline">.................................................................................</div>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				
				<tr>
					<td colspan="6">
						<table width="100%" style="white-space:nowrap;font-size:12px;font-family:'Khmer OS Battambang';">
							<tr>
								<td width="20%">មានសុពលភាព ពីថ្ងៃទី</td>
								<td width="35%" >
									:&nbsp;<label id="lb_start_date" class="data" ></label>
									<div class="underline">.................................................</div>
								</td>
								<td width="12%" align="center">ដល់ថ្ងៃទី</td>
								<td width="33%" align="left">
									:&nbsp;<label id="lb_epx_date" class="data" ></label>
									<div class="underline">.................................................</div>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				
				<tr>
					<td valign="top" align="center">សម្រាប់ៈ</td>
					<td colspan="5">
						<table width="100%" style="white-space:nowrap;font-size:12px;font-family:'Khmer OS Battambang';">
							<tr>
								<td width="7%">
									<label id="checkbox_rent"></label>
								</td>
								<td width="15%">
									 ថ្លៃជួលតូបៈ 
								</td>
								<td width="78%">
									:&nbsp;<label id="" class="data" ></label>
									<div class="underline">.......................................................................................</div>
								</td>
							</tr>
							
							<tr>
								<td width="7%">
									<label id="checkbox_water"></label>
								</td>
								<td width="15%">
									 ថ្លៃទឹកៈ 
								</td>
								<td width="78%">
									:&nbsp;<label id="" class="data" ></label>
									<div class="underline">.......................................................................................</div>
								</td>
							</tr>
							
							<tr>
								<td width="7%">
									<label id="checkbox_fire"></label>
								</td>
								<td width="15%">
									 ថ្លៃភ្លើងៈ 
								</td>
								<td width="78%">
									:&nbsp;<label id="" class="data" ></label>
									<div class="underline">.......................................................................................</div>
								</td>
							</tr>
							
							<tr>
								<td width="7%">
									<label id="checkbox_cleaner"></label>
								</td>
								<td width="15%">
									 ថ្លៃសម្រាមៈ 
								</td>
								<td width="78%">
									:&nbsp;<label id="" class="data" ></label>
									<div class="underline">.......................................................................................</div>
								</td>
							</tr>
							
							<tr>
								<td width="7%">
									<label id="checkbox_bike_payment"></label>
								</td>
								<td width="15%">
									 ថ្លៃកិបសំបុត្រកង់ៈ 
								</td>
								<td width="78%">
									:&nbsp;<label id="lb_bike_payment" class="data" ></label>
									<div class="underline">.......................................................................................</div>
								</td>
							</tr>
							
							<tr>
								<td width="7%">
									<label id="checkbox_moto_payment"></label>
								</td>
								<td width="15%">
									 ថ្លៃកិបសំបុត្រម៉ូតូៈ 
								</td>
								<td width="78%">
									:&nbsp;<label id="lb_moto_payment" class="data" ></label>
									<div class="underline">.......................................................................................</div>
								</td>
							</tr>
							
							<tr>
								<td width="7%">
									<label id="checkbox_broken"></label>
								</td>
								<td width="15%">
									 ថ្លៃលក់អេតចាយៈ 
								</td>
								<td width="78%">
									:&nbsp;<label id="lb_broken" class="data" ></label>
									<div class="underline">.......................................................................................</div>
								</td>
							</tr>
							
							<tr>
								<td width="7%">
									<label id="checkbox_other"></label>
								</td>
								<td width="15%">
									 ផ្សេងៗ
								</td>
								<td width="78%">
									:&nbsp;<label id="" class="data" ></label>
									<div class="underline">.......................................................................................</div>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				
				<tr>
					<td colspan="6">
						&nbsp;
					</td>
				</tr>
				
				<tr>
					<td colspan="6">
						<table width="100%" style="white-space:nowrap; font-size:12px;font-family:Khmer OS Battambang, Times New Roman;">
							<tr>
								<td width="55%">&nbsp;</td>
								<td width="45%"align="right" >រាជធានីភ្នំពេញ.ថ្ងៃទី <?php echo date('d');?> / <?php echo date('m');?> / <?php echo date('Y');?></td>
							</tr>
						</table>
					</td>
				</tr>
				
				<tr>
					<td colspan="6">
						<table width="100%" style="white-space:nowrap; font-size:12px;font-family:Khmer OS Battambang, Times New Roman;">
							<tr align="center">
								<td width="33%"><span style="font-family:'khmer os muol light';font-size:12px;">ប្រធានសាខា</span><br/>ហត្ថលេខា</td>
								<td width="33%"><span style="font-family:'khmer os muol light';font-size:12px;">អ្នកបង់ប្រាក់</span><br/>ហត្ថលេខា</td>
								<td width="33%"><span style="font-family:'khmer os muol light';font-size:12px;">អ្នកទទួលប្រាក់</span><br/>ហត្ថលេខា</td>
							</tr>
							<tr align="center">
								<td colspan="3">&nbsp;</td>
							</tr>
							<tr align="center">
								<td colspan="3">&nbsp;</td>
							</tr>
							<tr>
								<td align="left">
									<table width="100%" border="0" style="white-space:nowrap; font-size:12px;font-family:Khmer OS Battambang, Times New Roman;">
										<tr>
											<td width="20%" align="center">ឈ្មោះ</td>
											<td width="80%"><div style="margin-top: 2px;">&nbsp;................................</div></td>
										</tr>
									</table>
								</td>
								<td align="left">
									<table width="100%" border="0" style="white-space:nowrap; font-size:12px;font-family:Khmer OS Battambang, Times New Roman;">
										<tr>
											<td width="20%" align="center">ឈ្មោះ</td>
											<td width="80%"><div style="margin-top: 2px;">&nbsp;................................</div></td>
										</tr>
									</table>
								</td>
								<td align="left">
									<table width="100%" border="0" style="white-space:nowrap; font-size:12px;font-family:Khmer OS Battambang, Times New Roman;">
										<tr>
											<td width="20%" align="center">ឈ្មោះ</td>
											<td width="80%" align="center">
												<div style=" font-size: 12px;"> 
													
													<?php 
													   $session_user=new Zend_Session_Namespace('auth');
													   $last_name=$session_user->last_name;
													   $username = $session_user->first_name;
													   echo $last_name." ".$username;
													?>
												</div>
												<div class="underline">&nbsp;................................</div>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							
							<tr>
								<td align="left">
									&nbsp;
								</td>
								<td align="left">
									<table width="100%" border="0" style="white-space:nowrap; font-size:12px;font-family:Khmer OS Battambang, Times New Roman;">
										<tr>
											<td width="20%" align="center">ទូរសព្ទ</td>
											<td width="80%"><div style="margin-top: 2px;">&nbsp;................................</div></td>
										</tr>
									</table>
								</td>
								<td align="left">
									<table width="100%" border="0" style="white-space:nowrap; font-size:12px;font-family:Khmer OS Battambang, Times New Roman;">
										<tr>
											<td width="20%" align="center">ទូរសព្ទ</td>
											<td width="80%" align="center"><div style="margin-top: 2px;">&nbsp;................................</div></td>
										</tr>
									</table>
								</td>
							</tr>
							
						</table>
					</td>
				</tr>
				<tr >
					<td colspan="6" >
						&nbsp;
					</td>
				</tr>
				<tr >
					<td colspan="6" style="border:2px solid #000;">
						
					</td>
				</tr>
				<tr >
					<td colspan="6" >
						&nbsp;
					</td>
				</tr>
				<tr>
					<td colspan="6" >
						<strong>បញ្ចាក់:&nbsp;&nbsp;</strong>-&nbsp;ប្រាក់ដែលបានបង់ហើយមិនអាចដកវីញបានឡើយ ៕ <strong>Notice:</strong> Your Payment is non-returnable.
					</td>
				</tr>
							
			</table>
		</div>
		
		<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>	
		<button dojoType="dijit.form.Button" label="Cancel" iconClass="dijitEditorIcon dijitEditorIconCancel"
			showLabel="true" type="button" onclick="hideDialog();">Cancel</button>
		<button dojoType="dijit.form.Button" label="Print" showLabel="true" iconClass="dijitEditorIcon dijitEditorIconPrint"
			 type="button" onclick="printSubmit();">Print</button>
	</div>
</div>

