
<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('STUDENT_DROP')); 
	$frm =  $this->form_search;
?>

<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'foundation','controller'=>'studentdrop','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table style="width:90%">
	  	<tr> 
			<td> <?php echo $frm->getElement("title");?></td>
			<td> <?php echo $frm->getElement("branch");?></td>
			<td> <?php echo $frm->getElement("study_year");?></td>
			<td> <?php echo $frm->getElement("degree_all");?></td>
			<td> <?php echo $frm->getElement("grade_all");?></td>
			<td> <?php echo $frm->getElement("session");?></td>
		</tr>
		<tr>	
			<td><input type="text" name="start_date" id="start_date" class="fullside" value="<?php echo $this->adv_search['start_date'];?>" dojoType="dijit.form.DateTextBox" constraints="{datePattern:'dd/MM/yyyy'}"/></td>
		    <td><input type="text" name="end_date" id="end_date" class="fullside" value="<?php echo $this->adv_search['end_date'];?>" dojoType="dijit.form.DateTextBox"  constraints="{datePattern:'dd/MM/yyyy'}"/></td>
			
			<td>
				<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
			</td>
	  	</tr>
	 </table>
</form>


<?php echo $this->list;?>