<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("ADD_FACULTY"));
?>	
<?php  $frm_dept= $this->frm_dept;?>
<form  id='edit-dept' action="<?php echo $this->url(array('module'=>'global','controller'=>'faculty','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<table cellspacing="10" width="40%" style="margin: 0 auto;">
	<tr>
		<td>
			<fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("ADD_FACULTY");?></strong></legend>
				<table style="margin: 0 auto; width: 100%;" cellspacing="10">
					<tr>
						<td><?php echo $tr->translate("NAME");?></td>
						<td><?php echo $frm_dept->getElement("en_name");?></td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("TYPE");?></td>
						<td><?php echo $frm_dept->getElement("type");?></td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("SHORTCUT");?></td>
						<td><?php echo $frm_dept->getElement("shortcut");?></td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("STATUS");?></td>
						<td><?php echo $frm_dept->getElement("status");?>
							<?php echo $frm_dept->getElement("dept_id");?>
						</td>
					</tr>
					<tr>
						<td colspan="2" align="center">
							<input type="submit" name="save_new" id="save_new"  label="<?php echo $tr->translate("SAVE_NEW");?>" id="submitButton" 
							dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconSave" />
							
							<input type="submit" name="save_close" id="save_close"  label="<?php echo $tr->translate("SAVE_CLOSE");?>" id="submitButton" 
							dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconSave" />
						</td>
					</tr>
				</table>	
			</fieldset>		
		</td>
	</tr>
</table>	
</form>