<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("ADD_FACULTY"));
?>	
<?php  $frm_dept= $this->frm_dept;?>
<form  id='edit-dept' action="<?php echo $this->url(array('module'=>'global','controller'=>'faculty','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<table cellspacing="10" width="40%" style="margin: 0 auto;">
	<tr>
		<td>
			<fieldset>
				<legend align="center" ><strong><?php echo $tr->translate("ADD_FACULTY");?></strong></legend>
				<table style="margin: 0 auto; width: 100%;" cellspacing="10">
					<tr>
						<td><?php echo $tr->translate("NAME");?></td>
						<td><?php echo $frm_dept->getElement("en_name");?></td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("TYPE");?></td>
						<td><?php echo $frm_dept->getElement("type");?></td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("SHORTCUT");?></td>
						<td><?php echo $frm_dept->getElement("shortcut");?></td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("STATUS");?></td>
						<td><?php echo $frm_dept->getElement("status");?>
							<?php echo $frm_dept->getElement("dept_id");?>
						</td>
					</tr>
					<tr>
						<td colspan="2" align="center">
							<input type="submit" name="save_new" id="save_new"  label="<?php echo $tr->translate("SAVE_NEW");?>" id="submitButton" 
							dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconSave" />
							
							<input type="submit" name="save_close" id="save_close"  label="<?php echo $tr->translate("SAVE_CLOSE");?>" id="submitButton" 
							dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconSave" />
						</td>
					</tr>
				</table>	
			</fieldset>		
		</td>
	</tr>
</table>	
</form>
<script>
var url_add_dept = '<?php echo $this->url(array("module"=>"global","controller"=>"Major","action"=>"add-cat-degree")); ?>';
function addDept(){
	if(dijit.byId('frm_add_dept').validate()) {
		dojo.xhrPost({
				url:url_add_dept,
				form: dojo.byId("frm_add_dept"),
				handleAs:"json",
				load: function(data) {
					//alert(data); 
					var Itemmake = { 
					    	 id: data,
						     name: dijit.byId('fac_enname').get('value')
						   };
			   addDataToSelectbox(dijit.byId('dept'), dept_store, Itemmake, data);
			   dijit.byId('frm_add_dept').reset();
			   dijit.byId("popup_add_dept").hide();
					
				},
				error: function(err) {
					alert(err);
				}
		});
	}
}

function getPopupCat(){
	type = dijit.byId('type').get('value');
	if(type==-1){
		dijit.byId("popup_add_dept").show();
    }
}

function hideDialog(){
	dijit.byId('frm_add_dept').reset();
	dijit.byId("popup_add_dept").hide();
}

</script>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:30%;" id="popup_add_dept" >
		<form style="background-color: buttonface; width:100%;" id='frm_add_dept' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">   
   				if(this.validate()) {
					return true;
   				}else {
					return false;
   				}
			</script>
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
				<tr>
					<td><?php echo $tr->translate("DEGREE");?></td>
					<td>
						<input type="text" class="fullsize" name='fac_enname' required="true" id="fac_enname" dojoType="dijit.form.ValidationTextBox" />
					</td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("SHORTCUT");?></td>
					<td>
						<input type="text" class="fullsize" name='shortcut_fac' required="true" id="shortcut_fac" dojoType="dijit.form.ValidationTextBox" />
					</td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("STATUS");?></td>
					<td>
						<select dojoType="dijit.form.FilteringSelect" id="status_fac" name="status_fac"  class="fullsize" type="text">
							<option value='1'>Active</option>
							<option value='2'>Deactive</option>
						</select>
					</td>
				</tr>
				<tr>
					<td colspan="2" align="center">
						<input type="button"  label="<?php echo $tr->translate("CANCEL");?>" id="cancelButton" 
						dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel" onclick="hideDialog();"/>
						
						<input type="button"  label="<?php echo $tr->translate("SAVE");?>" id="submitButton" 
						dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addDept();"/>
					</td>	
				</tr>
			</table>

		</form>
	</div>
</div>