<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("SRMS_FACULTIES_LIST"));
	$frm = $this->frm_search;
?>	
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'global','controller'=>'faculty','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
	<table width="100%">	
		 <tr>
		 	<td><?php echo $frm->getElement("title");?></td>
		 	<td><?php echo $frm->getElement("type");?></td>
		 	<td><?php echo $frm->getElement('status_search');?></td>
		 	<td><button IconClass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
		</tr>
	</table>
	<?php echo $this->list;?>
</form>
