<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_FEE')); 
	$payment_term = $this->payment_term;
	//print_r($payment_term);exit();
?>	
<script type="text/javascript" src="js/dojo/dojo.js" djConfig="isDebug: true, parseOnLoad: true"></script>
<script type="text/javascript">
    dojo.require("dojo.NodeList-manipulate");
    dojo.require("dojo.parser");
    dojo.require("dojo.data.ItemFileWriteStore");  
</script>
 
<script>
var grade_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->names_grade));?> );
var dept_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->dept));?> );
dojo.ready(function(){
	
	new dijit.form.FilteringSelect({
		store: grade_store,
		autoComplete: true,                        
		id: "grade",
		name: "grade",  
		style:'height:40px !important',         
		class: 'fullside',  
		required:false,
		placeHolder:"Select Grade",          
		onChange: function() {  
			grade   = dijit.byId('grade').get('value');
			if(grade==-1){
			dijit.byId("popup_grate").show();
			}else{
				addRow();
			}
		}
	}, "grade");
	
	new dijit.form.FilteringSelect({
		store: dept_store,
		autoComplete: true,                        
		required: true,
		id: "degree_popup1",
		name: "degree_popup1",           
		class: "fullside", 
		placeHolder:"Select Degree",          
		onChange: function() {  
			degree_id = dijit.byId('degree_popup1').get('value');
			if(degree_id==-1){
				dijit.byId("popup_add_dept").show();
			}else{
			}
		}
	}, "degree_popup1");
	
});
</script>
<style>
select{ width:100%;}
fieldset{  background:none;}
table tr.head-title{ background: none repeat scroll 0% 0% rgba(213, 249, 244, 1); padding:2px;}
table tr td.null-border{ background: #fff; border-left:none !important;}
table .set-style td,table .set-style th{ padding: 2px; border:1px solid #ccc;}
table .set-style tr.st1{ background: none repeat scroll 0% 0% rgba(218, 250, 255, 1);}
</style>
<form id='office_receipt' action="<?php echo $this->url(array('module'=>'accounting','controller'=>'fee','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">   
   if(this.validate()) {
    if( dijit.byId("branch").get("value")==''){
    	alert("Please Select Branch Name!!!");
        dijit.byId("branch").focus();
        return false;
	}
    if($('#identity').val()==''){
        alert("Please Select Grade Name!!!");
		dijit.byId("grade").focus();
		return false;
	}
   dijit.byId('save_close').set('disabled',true);
   dijit.byId('save_new').set('disabled',true);
    return true;
   }else {
    return false;
   }
</script>

<table cellspacing="10" style="margin: 0 auto;width:100%;" >
	<tr>
		<td>
			<fieldset>
				<legend align="center" style="font-size: 20px;"><strong><?php echo $tr->translate("ADD_FEE");?></strong></legend>
				<table style="margin: 0 auto; width: 100%; background:#DFF7FD;" cellspacing="10">
					
					<tr>
						<td style="white-space: nowrap;"><?php echo $tr->translate("YEARS");?></td>
						<td>
							<select dojoType="dijit.form.FilteringSelect" required="true"  class="fullside" id="from_year" name="from_year" type="text">
								<?php for($i=date('Y')-2;$i<=date('Y')+1;$i++){?>
									<option value="<?php echo $i;?>"><?php echo $i; ?></option>
								<?php }?>
							</select>
						</td>
						<td ><?php echo $tr->translate("TO");?></td>
						<td>
							<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside"  id="to_year" name="to_year" type="text">
								<?php for($i=date('Y')-1;$i<=date('Y')+2;$i++){?>
									<option value="<?php echo $i;?>"><?php echo $i; ?></option>
								<?php }?>
							</select>
						</td>
						<td ><?php echo $tr->translate("GENERATION");?></td>
						<td ><input dojoType="dijit.form.ValidationTextBox" class="fullside" id="generation" name="generation"  type="text"></td>
						</tr>
					<tr>
						<td ><?php echo $tr->translate("TIME");?></td>
						<td>
							<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="time" name="time" type="text">								
									<option value="2">ពេញម៉ោង</option>
									<option value="1">ក្រៅម៉ោង</option>
							</select>
						</td>
						<td style="white-space: nowrap;"><?php echo $tr->translate("BRANCH");?></td>
						<td>
							<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" autoComplete="false" queryExpr="*${0}*" id="branch" name="branch" type="text">								
								<option value="">Select Branch</option>
								<?php if(!empty($this->branch)){ foreach ($this->branch as $branch){?>	
									<option value="<?php echo $branch['id'];?>"><?php echo $branch['name'];?></option>
								<?php }}?>
							</select>
						</td>								
						<td   ><?php echo $tr->translate("NOTE");?></td>
						<td  ><input dojoType="dijit.form.TextBox"  class="fullside" id="note" name="note"  type="text"></td>
					</tr>
					
					<tr>
						<td><?php echo $tr->translate("GRADE");?></td>
						<td colspan="3"><input id="grade" name="grade" /></td>
						<td></td>
					</tr>
					
				</table>
				<table class="set-style" border="2px" style="border:1px solid #ccc; border-collapse: collapse;margin: 0 auto; width: 100%; background:#DFF7FD;" >
					<thead>
						 
						 <?php $id=0; for($i = 0;$i < count($payment_term);$i++){ ?>
										<?php $id++;if($i==0){ $term = $id;}else{$term.=','.$id;} ?>
									<?php }?>
								<input type="hidden" name="iden_term" id="iden_term"  value="<?php echo $term;?>" >
								<input type="hidden" name="identity" id="identity"  value="" >
						<tr>
							<td colspan="8">
								<table id="table_row" border="1px" style="border-collapse: collapse; border:1px solid #ccc;">
									<tr id="head-title" class="head-td" align="right"></tr>
								</table>
							</td>
						</tr>
					</thead>
					<tfoot>
						<tr>
							<td colspan="8" align="center">
							 	<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
								<input type="button" onclick="submitDataClose()" value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconSave" />
								<input type="submit" value="save_new" name="save_new"  id="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconSave" />
							</td>
						</tr>
					</tfoot>
				 </table>
			</fieldset>		
		</td>
	</tr>
</table>	
</form>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:40%;" id="popup_grate" >
		<form style="background-color: buttonface;" id='frm_add_grade' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
			<tr>
				<td>
					<fieldset style="background-color: buttonface;">
					<legend align="center" ><?php echo $tr->translate("ADD_GRADE");?></legend>
					<table style="margin: 0 auto; width: 95%;" cellspacing="5">
						<tr>
							<td><?php echo $tr->translate("DEGREE")?></td>
							<td><input id="degree_popup1" /></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NAME")?></td>
							<td> 
								<input dojoType="dijit.form.ValidationTextBox" required="true" class="fullside" id="major_enname" name="major_enname" value="" type="text">
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("SHORTCUT")?></td>
							<td><input dojoType="dijit.form.ValidationTextBox"  class="fullside" id="shortcut" name="shortcut" value="" type="text">
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("STATUS")?></td>
							<td>
								<select name="grade_status" id="grade_status" dojoType="dijit.form.FilteringSelect"  class="fullside">
								    <option value="1" label="ប្រើប្រាស់" selected="selected">ប្រើប្រាស់</option>
								    <option value="0" label="មិនប្រើប្រាស់">មិនប្រើប្រាស់</option>
								</select>
							</td>
						</tr>
							<tr>
								<td colspan="2" align="center">
									<input type="button" value="save" id="savegrade" name="save" label="<?php echo $tr->translate("GO_SAVE");?>" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addGrade();"/>
								</td>
						</tr>
					</table>
				</fieldset>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>
<?php  $frm_dept= $this->frm_dept;?>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:400px;" id="popup_add_dept" >
		<form  id='frm_add_dep' name='frm_add_dep' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
				
				
				<table style="margin: 0 auto; width: 100%;" cellspacing="10">
					<tr>
						<td><?php echo $tr->translate("NAME");?></td>
						<td><?php echo $frm_dept->getElement("en_name");?></td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("TYPE");?></td>
						<td><?php echo $frm_dept->getElement("type");?></td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("SHORTCUT");?></td>
						<td width="35%"><input type="text"  name='shortcut_fac' id="shortcut_fac" dojoType="dijit.form.TextBox" /></td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("STATUS");?></td>
						<td><?php echo $frm_dept->getElement("status");?>
							<?php echo $frm_dept->getElement("dept_id");?>
						</td>
					</tr>
					<tr>
						<td colspan="2" align="center">
							<input type="button"  label="<?php echo $tr->translate("SAVE");?>" id="save_dep" 
							dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconSave" onclick="adddegree();"/>
						</td>
					</tr>
				</table>
		</form>
	</div>
</div>
<script type="text/javascript">

function ResetRecordRecord() {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	if(arrays.length==1){
		deleteRecord(identity);
	}	
	else{
		for(var i=0;i<arrays.length;i++) {
			deleteRecord(arrays[i]);
		}
	}
}
var template = '';
var grade = '<?php echo $this->all_grade; ?>';
var metion = '<?php echo $this->all_metion; ?>';
var payment_term = '<?php echo count($this->payment_term);?>';
var session='<?php echo $this->all_session;?>';

var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
function addRow() { 
		grade=dijit.byId("grade").get("value");
		if(grade==''){return false;}
		label_grade = dijit.byId("grade").attr('displayedValue');
		col++;no++;
		template='';
		if(title!=1){    
			temp+='<th><?php echo $tr->translate("DEL");?></th>';
			temp+='<th><?php echo $tr->translate("N_O");?></th>';
			
			temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("GRADE");?></th>';
			//temp+='<th id="lbl_titlemetion" width="100px"><?php echo $tr->translate("SESSION");?></th>';
			<?php $s=0; ?>
			<?php  foreach ($payment_term as $value){?>
			
			<?php echo"temp+='<th>$value</th>';"; ?>			
			<?php }?>
			temp+='<th><?php echo $tr->translate("REMARK");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
			template+='<td width="47px"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td width="50px" align="center">'+no+'</td>';
			//template+='<td width="17%"><select dojoType="dijit.form.FilteringSelect" autoComplete="false" queryExpr="*${0}*" id="class_'+col+'" name="class_'+col+'">'+grade+'</select></td>';
			template+='<td width="20%">&nbsp;'+label_grade+'<input type="hidden" dojoType="dijit.form.TextBox" required="true" id="class_'+col+'" name="class_'+col+'" value="'+grade+'" /></td>';
			//template+='<td><select dojoType="dijit.form.FilteringSelect" id="session_'+col+'" name="session_'+col+'">'+session+'</select></td>';			
			column = 0;
			for(j=0;j<payment_term;j++){ column++; 
				template+='<td width="9%"><input type="text" id="fee'+col+'_'+column+'" value="0" name="fee'+col+'_'+column+'" dojoType="dijit.form.NumberTextBox" style="width: 100%;" /></td>';
			}
			template+='<td> <input type="text"  name="remark'+col+'" class="fullside" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ"/><label id="subsub"></label></td>';
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);

		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
 }
dojo.ready(function(){
	 var metion = '<?php echo $this->all_metion; ?>';
	 addRow();
	 
});
function showPopupFaculty(r_key){
	faculty_id = dijit.byId('metion'+r_key).value;	
	if(faculty_id==-1){
		r_index = r_key;
		dijit.byId("popup_dept").show();
	}
}
var url_get_faculty ='<?php echo $this->url(array('module'=>'global','controller'=>'globals','action'=>'getfaculty-option')); ?>';
function getAllFucaltyOption(f_id){                                                                      
	dojo.xhrPost({
		url: url_get_faculty,				    
		handleAs:"json", 
		load: function(response){
			//alert(response.option);
			dojo.html.set(dojo.byId("lbl_metion"+r_index),'',{
			     parseContent: true});
			faculty=response.option;
			    select='<select class="full" dojoType="dijit.form.FilteringSelect" name="metion'+r_index+'" id="metion'+r_index+'" >'+faculty+'</select>';
				dojo.html.set(dojo.byId("lbl_metion"+r_index),select, {
				     parseContent: true
				});
				dijit.byId("metion"+r_index).attr( 'value',f_id);
				alert('<?php echo $tr->translate("INSERT_SUCCESS"); ?>');
				//dijit.byId('frm_service').reset();
		},error:function(err){
			alert(err);
		}
	});
}
var url_add_dept= '<?php echo $this->url(array('module'=>'global','controller'=>'index','action'=>'add-department')); ?>';
function addNewDepartment(){
	if(dijit.byId('frm_add_dept').validate()) { 
		dojo.xhrPost({
		    url: url_add_dept,
		    form: dojo.byId('frm_add_dept'),
		    content : { 
				'en_name':dijit.byId('en_name').get('value'),
			    'kh_name':dijit.byId('kh_name').get('value'),
			    'shortcut':dijit.byId('shortcut').get('value'),
			    'status':dijit.byId('status').get('value'),			    
			},				    
		   handleAs:"json", 
		   load: function(response) {
			   getAllFucaltyOption(response.id);
			   //location.reload();
		      hideDialog();
		    },
		    error: function(err) {
		    }
		});
		}
}
 function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
	}

 var url_add_grade = '<?php echo $this->url(array("module"=>"accounting","controller"=>"fee","action"=>"add-graddjax")); ?>';
 function addGrade(){
 	dijit.byId("savegrade").set('disabled',false);
 	
 	if(dijit.byId('frm_add_grade').validate()){
 		rr = dijit.byId("degree_popup1").get('value');
 	    if(rr==''){
 	       alert('Please Selece Degree !');
 	       dijit.byId("degree_popup1").focus();
 		   return false;
 		}
 		dijit.byId("savegrade").set('disabled',true);
 		dojo.xhrPost({
 				url:url_add_grade,
 				form: dojo.byId("frm_add_grade"),
 				handleAs:"json",
 				load: function(data) {
 					var Itemmake = { 
 					    	 id: data,
 						     name: dijit.byId('major_enname').get('value')+' ('+dijit.byId('degree_popup1').attr('displayedValue')+')'
 						   };
 			   addDataToSelectbox(dijit.byId('grade'), grade_store, Itemmake, data);
 			   dijit.byId('frm_add_grade').reset();
 			   dijit.byId("popup_grate").hide();	
 			   dijit.byId("savegrade").set('disabled',false);
 				},
 				error: function(err) {
 					alert(err);
 					dijit.byId("savegrade").set('disabled',false);
 				}
 		});
 	}
 }

 var url_degree = '<?php echo $this->url(array("module"=>"accounting","controller"=>"fee","action"=>"adddegree")); ?>';
 function adddegree(){
 	if(dijit.byId('frm_add_dep').validate()){
 		fac_enname=dijit.byId('en_name').get('value');
 		if(fac_enname==''){
 			alert('Please input degree !');
 			return false;
 		}
 		dojo.xhrPost({
 				url:url_degree,
 				form: dojo.byId("frm_add_dep"),
 				handleAs:"json",
 				load: function(data) {
 					var Itemmake = { 
 					    id: data,
 						name: dijit.byId('en_name').get('value')
 				};
 			   addDataToSelectbox(dijit.byId('degree_popup1'), dept_store, Itemmake, data);
 			   dijit.byId('frm_add_dep').reset();
 			   dijit.byId("popup_add_dept").hide();	
 				},
 				error: function(err) {
 					alert(err);
 				}
 		});
 	}
 }

 function submitDataClose(){
	 if( dijit.byId("branch").get("value")==''){
	    	alert("Please Select Branch Name!!!");
	        dijit.byId("branch").focus();
	        return false;
		}
	    if($('#identity').val()==''){
	        alert("Please Select Grade Name!!!");
			dijit.byId("grade").focus();
			return false;
		}
		if(dijit.byId('office_receipt').validate()) {
			dijit.byId('save_close').set('disabled',true);
			dijit.byId('save_new').set('disabled',true);
			var url_submit = '<?php echo $this->url(array('module'=>'accounting','controller'=>'fee','action'=>'add')); ?>';
			dojo.xhrPost({
			    url: url_submit,	
				form: dojo.byId("office_receipt"),		    
				load: function(data) {
					alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
					window.location.href ="<?php echo $this->baseUrl();?>/accounting/fee";
				},
				error: function(e) {
				}
			});
		}
	}
 
</script>