<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_STUDENT_SERVICE_PAYMENT')); 
	$base_url = Application_Form_FrmMessage::getUrl("/");
// 	print_r($this->service);exit();
?>	
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/convertion.js"></script>
<?php /*?><script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.14.1/moment.min.js"></script> <?php */ ?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>

<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require('dojox.form.BusyButton');
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dojo.store.Memory");
	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.form.Textarea");
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.CheckBox");
	
	var service_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->service));?>);
	dojo.ready(function(){ 
		displayNoneAddRow();
		addRow();
		changeControl();
		getNewLunchId('');
	
		new dijit.form.FilteringSelect({
			store: service_store,
			autoComplete: true,                        
		    id: "service",
		    name: "service",
			value:-1,
		    class: 'fullside',  
		   // placeHolder:"Selected service", 
		    onChange: function() {  
			    service = dijit.byId('service').get('value');
			    if(service==-2){
					dijit.byId('popup_add_service').show();
			    }
		    	getservicefee();
				getServiceCate(service);
				if(dijit.byId('student_type').get('value')==2){
					getStartDateService();
				}
		    } 
		}, "service");


		getValidate();
	});	

</script>
<style>
select{ width:100%;}
fieldset{  background:none;}
.red{ color: red; padding-left:5px;}
.head-td{font-size: 12px;}
</style>
<?php $register = $this->frm_register;
//print_r($register);
?>
<form id='office_receipt' action="<?php echo $this->url(array('module'=>'registrar','controller'=>'studentlunchpayment','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">   

	stu_type = dijit.byId('student_type').get('value');
	if(stu_type==1){
		stu_id = dijit.byId('student_name_new').get('value');
		if(stu_id==-1){
			dijit.byId('student_name_new').focus();
			return false;
		}
	}else{
		stu_id = dijit.byId('student_name_old').get('value');
		if(stu_id==-1){
			dijit.byId('student_name_old').focus();
			return false;
		}
	}

	total_payment = dijit.byId('total_payment').get('value');
	paid_amount = dijit.byId('paid_amount').get('value');
	if(paid_amount>total_payment){
		alert('You can not pay more than total payment')
		dijit.byId('paid_amount').focus();
		return false;
	}
    else if(this.validate()) {
    	return true;
    }else {
    	return false;
    }
</script>
<table id="head_tbl"  cellspacing="10" style="margin: 0 auto; width: 100%;">
	<tr>
		<td>
		<fieldset>
					<legend align="center"><strong​ style="font-size: 18px;"><?php echo $tr->translate("ADD_STUDENT_SERVICE_PAYMENT");?></strong></legend>
					<table style="margin: 0 auto; width: 100%;padding:10px;" cellspacing="7" cellpadding="10px" >
						&nbsp;&nbsp;&nbsp;&nbsp;<input type="checkbox" value="1" onchange="displayNoneAddRow();netTotal();" name="buy_product" id="buy_product" dojoType="dijit.form.CheckBox"  /> Buy Product
						<tr>
							<td style="width: 12%"><?php echo $tr->translate("STUDENT_TYPE");?></td>
							<td style="width: 37%">
								<select name="student_type" id="student_type" onchange="changeControl();getStudentInfo();" class="fullside" dojoType="dijit.form.FilteringSelect" >
									<option value="1">New Student</option>
									<option value="2">Old Student</option>
								</select>
							</td>
							
							<td align="right" style="width: 12%"><?php echo $tr->translate("RECEIPT_NO");?></td>
							<td align="center" style="width: 37%"><?php echo $register->getElement('reciept_no');?></td>
						</tr>
						<input type="hidden" name="service_cate" id="service_cate" dojoType="dijit.form.TextBox" />
						<input type="hidden" name="ex_rate" id="ex_rate" value="<?php echo $this->exchange_rate ;?>" dojoType="dijit.form.TextBox" />
						<tr>
							<td><?php echo $tr->translate("STUDENT_NAME");?></td>
							<td>
								<div id="new_name">
									<select name="student_name_new" id="student_name_new" onChange="getStudentInfo(1);" class="fullside" dojoType="dijit.form.FilteringSelect" >
										<option value="-1">----- select name -----</option>
										<?php if(!empty($this->new_stu_name)){foreach($this->new_stu_name as $new_stu_name){?>
											<option value="<?php echo $new_stu_name['stu_id']?>"><?php echo $new_stu_name['stu_name']?></option>
										<?php }}?>
									</select>
								</div>	
								<div id="old_name">
									<select name="student_name_old" id="student_name_old" onChange="setID();" class="fullside" dojoType="dijit.form.FilteringSelect" >
										<option value="-1">----- select name -----</option>
										<?php if(!empty($this->old_stu_name)){foreach($this->old_stu_name as $old_stu_name){?>
											<option value="<?php echo $old_stu_name['stu_id']?>"><?php echo $old_stu_name['stu_name']?></option>
										<?php }}?>
									</select>
								</div>	
							</td>
							
							<td align="right"><?php echo $tr->translate("STUDENT_ID");?></td>
							<td align="center">
								<div id="new_id">
									<input type="text" name="new_car_id" style="color:red;" id="new_car_id" readOnly="readOnly" class="fullside" dojoType="dijit.form.TextBox" >     
								</div>
								<div id="old_id">
									<select name="old_car_id" id="old_car_id" onChange="getStudentInfo(2);" class="fullside" dojoType="dijit.form.FilteringSelect" >
										<option value="-1">----- select id -----</option>
										<?php if(!empty($this->old_car_id)){foreach($this->old_car_id as $old_car_id){?>
											<option value="<?php echo $old_car_id['stu_id']?>"><?php echo $old_car_id['stu_code']?></option>
										<?php }}?>
									</select>
								</div>
							</td>
						</tr>
						
						<tr>
							<td><?php echo $tr->translate("NAME_EN");?></td>
							<td><?php echo $register->getElement('en_name');?></td>
							<td align="right"><?php echo $tr->translate("NAME_KH");?></td>
							<td align="center"><?php echo $register->getElement('kh_name');?></td>
						</tr>
						<tr>	
							<td><?php echo $tr->translate("SEX");?></td>
							<td ><?php echo $register->getElement('sex');?></td>
						   	<td align="right"><?php echo $tr->translate("PHONE");?></td>
							<td><input type="text" readOnly="readOnly"  class="fullside" name="phone" id="phone" dojoType="dijit.form.TextBox" /></td>
						</tr>
						
						<tr>
							<td><?php echo $tr->translate('SERVICE');?></td>
							<td> 
								<input id="service" />
							</td>
							<input type="hidden" name="balance_id" id="balance_id" dojoType="dijit.form.TextBox" />
							<td align="right"><?php echo $tr->translate('PAYMENT_TERM');?></td>
							<td> 
								<select class="fullside" name="term" id="term" onchange="getservicefee();getValidate();" dojoType="dijit.form.FilteringSelect" type="text"   >
									<?php if(!empty($this->payment_term)){foreach ($this->payment_term as $key => $term){?>
										<option value="<?php echo $key?>"><?php echo $term;?></option>
									<?php  }}?>
								</select>
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate('SERVICE_FEE');?></td>
							<td> 
								<input class="fullside" name="service_fee" id="service_fee" onkeyup="calculateTotalPayment();netTotal();" dojoType="dijit.form.TextBox" type="text" >
							</td>
							
							<td align="right"><?php echo $tr->translate('QTY');?></td>
							<td> 
								<input class="fullside" name="qty" id="qty" onkeyup="calculateTotalPayment();getValidate();netTotal();" dojoType="dijit.form.TextBox" value="1" type="text"   >
							</td>
							
							
						</tr>
						<tr>
						
							<td ><?php echo $tr->translate('DISCOUNT');?></td>
							<td> 
								<input class="fullside" name="discount" id="discount" onkeyup="calculateTotalPayment();netTotal();" dojoType="dijit.form.TextBox" value="0" type="text"   >
							</td>
						
							<td align="right" ><?php echo $tr->translate('TOTAL_PAYMENT');?></td>
							<td> 
								<input class="fullside" name="total_payment" id="total_payment" readOnly="readOnly" dojoType="dijit.form.TextBox" type="text" >
							</td>
							
							
						</tr>
						<tr>
						
							<td ><?php echo $tr->translate('PAID_AMOUNT');?></td>
							<td> 
								<input class="fullside" name="paid_amount" id="paid_amount" onkeyup="calculatBalanceAndReturn();netTotal();" dojoType="dijit.form.TextBox" type="text"   >
							</td>
						
							<td  align="right" ><?php echo $tr->translate('BALANCE');?></td>
							<td> 
								<input class="fullside" name="balance" id="balance"  readOnly="readOnly" dojoType="dijit.form.TextBox" type="text" >
							</td>
							
							
						</tr>
						<tr>
							<td ><?php echo $tr->translate('NOTE');?></td>
							<td> 
								<input class="fullside" name="other" id="other" dojoType="dijit.form.TextBox" type="text" >
							</td>
							
							<td align="right" ><?php echo $tr->translate('START_DATE');?></td>
							<td> 
								<input class="fullside" name="start_date" id="start_date" constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" onchange="getValidate();" value="now" type="text" >
							</td>
						</tr>
						<tr>
							<td colspan="2" align="left">
							</td>
						
							<td align="right" ><?php echo $tr->translate('END_DATE');?></td>
							<td> 
								<input class="fullside" name="end_date" id="end_date" constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" type="text"   >
							</td>
							
						</tr>
						
						
						<input type="hidden" id="identity" name="identity" />
						
						<tr>
							<td colspan="2" align="left">
									<input type="button" label="<?php echo $tr->translate('ADD_ROW');?>" dojoType="dijit.form.Button" 
										iconClass="dijitIconEditProperty" onclick="addRow();" />
							</td>
						
						</tr>
						
						<tr>
							<div id="addrow" >
								<td colspan="4">
									<table width="100%" border="1" id="table_row" style="border-collapse: collapse; border:1px solid #ccc;white-space: nowrap;">
											<tr id="head-title" class="head-td" align="right"></tr>
									</table>
								</td>
							</div>
						</tr>
						<tr>
							<td colspan="4" align="right">
								<table style="width:400px;border-collapse: collapse;white-space:nowrap;" cellpadding="10" cellspacing="10" >
									<tr>
										<td ><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
										<td align="right"><input type="text" readonly="readonly" onkeyup="calculatBalanceAndReturn();"  name="grand_total" id="grand_total" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
									<tr>	
										<td><?php echo $tr->translate("CONVERT_TO_RIELS");?> (៛)</td>
										<td align="right"><input  type="text" readonly="readonly"  name="convert_to_riels" id="convert_to_riels" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
									<tr>	
										<td><?php echo $tr->translate("RECEIVED_AMOUNT");?></td>
										<td align="right"><input  type="text" readonly="readonly" onkeyup="calculatBalanceAndReturn();" required="true"  name="total_received" id="total_received" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("BALANCE");?></td>
										<td align="right"><input type="text"  readonly="readonly" name="total_balance" value="<?php echo 0?>" id="total_balance" dojoType="dijit.form.NumberTextBox" /></td>
									</tr>
								</table>
							</td>
						</tr>
						
						<tr>
							<td colspan="4" align="center">
								<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
								<input type="submit" name="save_close" id="save_close" value="រក្សាទុក" label="<?php echo $tr->translate('SAVE_CLOSE');?>"  dojoType="dijit.form.Button" 
								 iconClass="dijitEditorIcon dijitEditorIconSave" />
								<input type="submit" name="save_new" id="save_new" value="រក្សាទុក" label="<?php echo $tr->translate('SAVE_NEW');?>"  dojoType="dijit.form.Button" 
								 iconClass="dijitEditorIcon dijitEditorIconSave" />
								 <input type="button" value="បោះពុម្ព" label="<?php echo $tr->translate('PRINT');?>" id="print" dojoType="dijit.form.Button" 
									iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="printSave('');"/> 
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>



<script type="text/javascript">

function setID(){
	stu_id = dijit.byId('student_name_old').get('value');
	dijit.byId('old_car_id').attr('value',stu_id);
}

function changeControl(){
	stu_type = dijit.byId('student_type').get('value');
	// alert(stu_type);
	if(stu_type==1){
		document.getElementById('new_id').style.display="block";
		document.getElementById('new_name').style.display="block";
		document.getElementById('old_id').style.display="none";
		document.getElementById('old_name').style.display="none";
	}else{
		document.getElementById('new_id').style.display="none";
		document.getElementById('new_name').style.display="none";
		document.getElementById('old_id').style.display="block";
		document.getElementById('old_name').style.display="block";
	}
}
	
var url_get_new_lunch_id = '<?php echo $this->url(array('module'=>'registrar','controller'=>'studentlunchpayment','action'=>'get-new-lunch-id')); ?>';
function getNewLunchId(condition){
	dojo.xhrPost({
		url:url_get_new_lunch_id,
		content:{
			
			},
		handleAs:"json",
		load: function(data) {
			// alert(data);
			if(data){
				dijit.byId('new_car_id').attr('value',data);
			}	
			
			if(condition==1){
				getNewReceiptNo(data,1);
			}
			
		},
		error: function(err) {
			alert(err);
		}
	});
	
}



function printSave(new_stu_id,new_receipt_no){		
	if(dijit.byId('office_receipt').validate()) {
		 
		 //degree = dijit.byId('dept').get('value');

		 stu_type = dijit.byId('student_type').get('value');
		 if(stu_type==1){
			 if(new_stu_id==''){
				 getNewLunchId(1);
			 }else{
				 dojo.byId("lb_receipt_no").innerHTML = new_receipt_no;
				 dojo.byId("lb_stu_id").innerHTML = new_stu_id;
			 }
		 }else{
			 if(new_receipt_no==''){
				getNewReceiptNo(1,1); 
			 }
			 
			 dojo.byId("lb_receipt_no").innerHTML = new_receipt_no;
			 dojo.byId("lb_stu_id").innerHTML = dijit.byId("old_car_id").attr('displayedValue');
		 }
		
		
		dojo.byId("lb_kh_name").innerHTML = dijit.byId("kh_name").get('value');
		dojo.byId("lb_en_name").innerHTML = dijit.byId("en_name").get('value');
		dojo.byId("lb_sex").innerHTML = dijit.byId("sex").attr('displayedValue');
		 
		dojo.byId("lb_phone").innerHTML = dijit.byId("phone").attr('displayedValue');
		dojo.byId("lb_address").innerHTML = dijit.byId("service").attr('displayedValue');
		 
		 
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////		 
		
	
	
		var rowId = $('#identity').val();
		var rowIDArray = rowId.split(',');
		
		temp='<table cellpadding="0" cellspacing="0" align="center" style=" width: 100%; padding: 0px; margin-top: 13px !important; border-collapse: collapse; border: 1px solid #000;font-family:Khmer OS Battambang !important;white-space:nowrap;  " id="table">'
			  temp+='<tr style=" font-size:12px; text-align:center;">';
				  temp+='<td rowspan="2" style="border:1px solid #000;"> <strong style="font-family: Khmer OS Battambang;  ">ល.រ<div class="tab_row fonteng">N<sup>o</sup></div></strong></td>';
				  temp+='<td rowspan="2" style="border:1px solid #000;"> <strong style="font-family: Khmer OS Battambang;  ">បរិយាយ<div class="tab_row fonteng">Description</div></strong></td>';
				  temp+='<td colspan="2" style="border:1px solid #000;><strong style="font-family: Khmer OS Battambang;  ">សេវាកម្ម/Service</strong></td>';
				  temp+='<td colspan="3" style="border:1px solid #000;><strong style="font-family: Khmer OS Battambang;  ">សុពលភាព/Payment Date</strong></td>';
				  temp+='<td width="8%" rowspan="2" style="border:1px solid #000;><strong style="font-family: Khmer OS Battambang;  ">ទឹកប្រាក់ <div class="tab_row fonteng">Amount</div></strong></td>';
				  temp+='<td width="8%" rowspan="2" style="border:1px solid #000;><strong style="font-family: Khmer OS Battambang;  ">បញ្ចុះតម្លៃ <div class="tab_row fonteng">Discount</div></strong></td>';
				  temp+='<td width="10%" rowspan="2" style="border:1px solid #000;><strong style="font-family: Khmer OS Battambang;  ">ទឹកប្រាក់សរុប <div class="tab_row fonteng">Total Amount</div></strong></td>';
				  temp+='<td width="12%" rowspan="2" style="border:1px solid #000;><strong style="font-family: Khmer OS Battambang;  ">ផ្សេងៗ <div class="tab_row fonteng">Others</div></strong></td>';
				  //temp+='<td rowspan="2" style="border:1px solid #000;><strong style="font-family: Khmer OS Battambang;  ">ឈ្មោះបេឡាទទួលប្រាក់<div class="tab_row fonteng">Cashier Name</div></strong></td>';
			  
			  temp+='</tr>';
			  
			  temp+='<tr style=" font-size:11px; text-align:center;">';
				  temp+='<td width="8%" style="border:1px solid #000;><strong style="font-family: Khmer OS Battambang; ">អាហារ </strong></td>';
				  temp+='<td width="8%" style="border:1px solid #000;><strong style="font-family: Khmer OS Battambang; ">ស្នាក់នៅ</strong></td>';
				  
				  temp+='<td width="10%" style="border:1px solid #000;><strong style="font-family: Khmer OS Battambang; ">ថ្ងៃចាប់ផ្តើម <div class="tab_row fonteng">Start Date</div></strong></td>';
				  temp+='<td width="10%" style="border:1px solid #000;><strong style="font-family: Khmer OS Battambang; ">ថ្ងៃបញ្ចប់ <div class="tab_row fonteng">End Date</div></strong></td>';
				  temp+='<td width="8%" style="border:1px solid #000;><strong style="font-family: Khmer OS Battambang; ">រយះពេល <div class="tab_row fonteng">Duration</div></strong></td>';
			  
			  temp+='</tr>';
			
			//check-mark.png  => black tick
			
			img_src = '<?php echo $this->baseUrl()."/images/Green_tick.png"?>';				
			style = '<?php echo 'style="width:15px;"';?>';
			
			service_id = dijit.byId('service').get('value');
			
			if(service_id==91 || service_id==93){  
				img_url1 = img_src;
				style1=style;
			}else{
				img_url1 = '';
				style1='';
			}
			
			if(service_id==92 || service_id==93){  
				img_url2 = img_src;
				style2=style;
			}else{
				img_url2 = '';
				style2='';
			}
			
			  temp+='<tr style="font-size:12px !important;height: 20px;border:1px solid #000; ">';
				  temp+='<td align="center" style="border:1px solid #000;">1</td>';
				  temp+='<td style="border:1px solid #000;">&nbsp;&nbsp;ម៉ោង 11:00 - 12:00</td>';
				  
				  temp+='<td align="center" style="border:1px solid #000;"><img ' +style1+ ' src="'+img_url1+'"></td>';
				  temp+='<td align="center" style="border:1px solid #000;"><img ' +style2+ ' src="'+img_url2+'"> </td>';
		
		///////////////////    format date 	//////////////////////// 
			
				  var b = new Date(dijit.byId("start_date").get('value'));
					mm = b.getMonth()+1;
					var dd = b.getDate();
					if(dd<10){
						dd = "0"+dd;
					}
					var mon = getMonthByNumber(mm);
					if(mm<10){
						mm = "0"+mm;
					}
					var y = b.getFullYear();
					var start_date = dd + '-' + mon + '-' + y ;
					
				  temp+='<td align="center" style="border:1px solid #000;"> '+start_date+'</td>';

					var a = new Date(dijit.byId("end_date").get('value'));
					mm = a.getMonth()+1;
					var dd = a.getDate();
					if(dd<10){
						dd = "0"+dd;
					}
					var months = getMonthByNumber(mm);
					if(mm<10){
						mm = "0"+mm;
					}
					var y = a.getFullYear();
					var epx_date = dd + '-' +months + '-' + y ;
					
				  //temp+='<td align="center" style="border:1px solid #000;"> ' + start_date + ' </td>';
				  temp+='<td align="center" style="border:1px solid #000;"> ' + epx_date + ' </td>';
				  
				  payment_term = dijit.byId('qty').get('value') + ' ' +  dijit.byId('term').attr('displayedValue');
				  
				  payment_term_id = dijit.byId('term').get('value');
				  if(payment_term_id!=5){
					  lunch_fee = dijit.byId('service_fee').get('value');
				  }else{
					  lunch_fee = dijit.byId('service_fee').get('value') * dijit.byId('qty').get('value');
				  }
				  
				  temp+='<td align="center" style="border:1px solid #000;">'+ payment_term +'</td>';
				  
				  temp+='<td align="center" style="border:1px solid #000;">$ '+lunch_fee+'</td>';
				  temp+='<td align="center" style="border:1px solid #000;">'+dijit.byId('discount').get('value')+' %</td>';
				  temp+='<td align="center" style="border:1px solid #000;">$ '+dijit.byId('total_payment').get('value')+'</td>';
				  temp+='<td align="center" style="border:1px solid #000;">'+dijit.byId('other').get('value')+'</td>';
			  temp+='</tr>';
			
	<?php ?>	
		i=2;
		if(dijit.byId('buy_product').checked){
			
		<?php ?>
			
			for(var n = 0; n < rowIDArray.length; n++) {
				 
			  temp+='<tr style=" font-size:12px !important;height: 20px;"​ align="center">';
			  temp+='<td align="center" style="border:1px solid #000;">'+i+'</td>';
			  temp+='<td align="left" style="border:1px solid #000;max-width:200px !important;line-height:18px;">&nbsp;&nbsp;'+dijit.byId("product_"+rowIDArray[n]).attr('displayedValue')+'</td>'; 
				
			  temp+='<td style="border:1px solid #000;"></td>';
			  temp+='<td style="border:1px solid #000;"></td>';			  
		
		
			  temp+='<td style="border:1px solid #000;"></td>';
			  temp+='<td align="center" style="border:1px solid #000;"> </td>';
			  temp+='<td align="center" style="border:1px solid #000;"> </td>';
			  
			  temp+='<td style="border:1px solid #000;">$ '+dijit.byId("price_"+rowIDArray[n]).get('value')+'</td>';
			 
			  temp+='<td style="border:1px solid #000;">'+dijit.byId("discount_"+rowIDArray[n]).get('value')+' %</td>';
			  temp+='<td style="border:1px solid #000;">$ '+dijit.byId("subtotal_"+rowIDArray[n]).get('value')+'</td>';
			   temp+='<td style="border:1px solid #000;">'+dijit.byId("remark"+rowIDArray[n]).get('value')+'</td>';
			  i++;
			  temp+='</tr>';
			}
		} 
		
		//alert(i);
		
		for(i;i<=5;i++){
			//alert(i);
			temp+='<tr style=" font-size:12px !important;height: 20px;"​ align="center"><td align="center" style="border:1px solid #000;">'+i+'</td>';
			  temp+='<td align="left" style="border:1px solid #000;max-width:200px !important;line-height:18px;">&nbsp;&nbsp;</td>'; 
				
			  temp+='<td style="border:1px solid #000;"></td>';
			  temp+='<td style="border:1px solid #000;"></td>';		
				
			  temp+='<td style="border:1px solid #000;"> </td>';
			  temp+='<td align="center" style="border:1px solid #000;"> </td>';
			  temp+='<td align="center" style="border:1px solid #000;"> </td>';
			  
			  temp+='<td style="border:1px solid #000;"></td>';
			 
			  temp+='<td style="border:1px solid #000;"></td>';
			  temp+='<td style="border:1px solid #000;"></td>';
			   temp+='<td style="border:1px solid #000;"></td>';
			  //i++;
			temp+='</tr>';
		}
		
		temp+='<tr style=" font-size:12px !important;height: 20px;"​ align="center">';
			
			temp+='<td colspan="9" align="center" style="border:1px solid #000;">ទឹកប្រាក់សរុប/Total Amount</td>';
			temp+='<td style="border:1px solid #000;">'+'$ '+dijit.byId("grand_total").get('value')+'</td>';
			temp+='<td style="border:1px solid #000;"><?php //echo date('l , jS / m / Y , H:i:s ',strtotime(Zend_Date::now()));?></td>';

  	    temp+='</tr>';
		
	<?php ?>	 
	
		temp+='</table>';
	dojo.byId('t_amountmoneytype').innerHTML = temp;
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////		 
		 
		 
		 
		dijit.byId("terms").show();	
	}
	
}


function getMonthByNumber(m){
	var monthName=[
		"Jan",
		 "Feb",
		 "Mar",
		 "Apr",
		 "May",
		 "Jun",
		 "Jul",
		 "Aug",
		 "Sep",
		 "Oct",
		 "Nov",
		 "Dec",
		];
		return (monthName[m-1]);
}


</script>


<div class="dijitHidden" style="width: 23cm !important; height: 11cm ; padding: 0px; margin: 0px;">
<?php $keycode = $this->keycode;?>
	<div data-dojo-type="dijit.Dialog" style="width:24cm;" align="center" data-dojo-props="title:'<?php echo $tr->translate("");?>'" id="terms" >
		
		<div id="divPrint" style="width: 23cm !important; height: 12cm ; padding: 0px; margin: 0px;">
			<style>
				.fontbig{
					font-size: 15px;	
				}
				.fonttel{
					font-size: 18px;	
				}
				.pleft{
					width: 110px;	
				}
				.label{ font-weight: bold;font-size: 22px;}
				.value{ font:bold 12px 'Khmer OS Battambang';border: 1px solid rgba(14, 0, 107, 1); height: 25px; padding: 0 2px;width: 98%; display: block;
						margin-top: -25px; line-height: 25px;
					    text-align: center;
						}
				.values{ border: 1px solid rgba(14, 0, 107, 1);; height: 25px; padding: 0 10px;display: block;
						line-height: 25px;}
				.h{ margin-top: -8px;/*margin-left:4px;*/}
​​               .print td{ font:bold 12px 'Khmer OS Battambang';}
			   .khmerbold{font:bold 12px 'Khmer OS Battambang';}
			   .khmer{font:12px 'Khmer OS Battambang';}
			   .one{white-space:nowrap;}
			   
				.underline{margin-top: -21px;text-align:center;}
				.data{font-size:13px;font-weight:bold;}
				.receiptno{font-size:15px;font-weight:bold;}
				.tab_row{ margin-top: -8px;}
				.fonteng{font-size:12px;}
				
			</style>	
			<table border="0"  class="print" cellspacing="0"  cellpadding="0" style="white-space: nowrap;font-size:12px;font-family:'Khmer OS Battambang';line-height: 23px;">
				<tr>
				    <td colspan="8"  align="center" style="">
						<table width="100%" style="white-space:nowrap; font-family:Khmer OS Battambang;margin-top:-10px;font-weight:bold;">
							<tr>
								<td width="25%" align="center" style="font-size:11px;"><?php echo date('l , jS / m / Y , H:i:s ',strtotime(Zend_Date::now()));?></td>
								<td width="50%" align="center" style="font-size:16px;">បង្កាន់ដៃទទួលប្រាក់ RECEIPT</td>
								<td width="25%" align="center" style="font-size:17px;color:red;">N<sup>o</sup> : <label id="lb_receipt_no" class="receiptno" ></label></td>
							</tr>
						</table>
						
				    </td>
				</tr>
				
				<tr>
					<td width="15%"></td>
					<td width="20%"></td>
					<td width="15%"></td>
					<td width="20%"></td>
					<td width="5%"></td>
					<td width="10%"></td>
					<td width="5%"></td>
					<td width="10%"></td>
				</tr>
			
				<tr>
					<td>ឈ្មោះភាសាខ្មែរ/Name in Khmer</td>
					<td>
						&nbsp;:&nbsp; <label id="lb_kh_name"  class="data" ></label>
						<div class="underline">........................................</div>
					</td>
					<td align="center"> អក្សរឡាតាំង/Latin&nbsp;</td>
					<td>
						:&nbsp; <label id="lb_en_name" class="data" ></label>
						<div class="underline">..........................................</div>
					</td>
					<td align="center">ភេទ/Sex</td>
					<td>
						&nbsp;:&nbsp; <label id="lb_sex" class="data" ></label>
						<div class="underline">...............</div>
					</td>
					
					<td align="center">&nbsp;អត្តលេខ/ID&nbsp;</td>
					<td>
						:&nbsp; <label id="lb_stu_id" class="data" ></label>
						<div class="underline">.................</div>
					</td>
				</tr>
				
				
				
				<tr>
					<td>អាសយដ្ឋាន/Address</td>
					<td colspan="7">
						&nbsp;:&nbsp; <label id="lb_address" class="data" ></label>
						<div class="underline">
							..........................................................................................................................................................................................................
						</div>
					</td>
				</tr>
				<tr>
					<td>លេខទូរស័ព្ទ/Phone Number</td>
					<td colspan="7">
						&nbsp;:&nbsp; <label id="lb_phone" class="data" ></label>
						<div class="underline">
							..........................................................................................................................................................................................................
						</div>
					</td>
				</tr>
					
				<tr>
					<td colspan="10">
						<div id="t_amountmoneytype"></div>
					</td>
				</tr>
		<?php ?>		
				<tr>
					<td colspan="10">
						<table width="100%" style="white-space:nowrap; font-size:12px;font-family:Khmer OS Muol;font-weight:bold;margin-top:10px;">
							<tr>
								<td width="25%" align="center">អគ្គនាយក/Director General</td>
								<td width="25%" align="center">អ្នកបង់ប្រាក់/Payer</td>
								<td width="25%" align="center">បេឡា/Cashier</td>
								<td width="25%" align="center">អ្នកផ្តល់ព័ត៌មាន​/Receiptionist</td>
							</tr>
							
							
							<tr>
								<td colspan="4" align="center">&nbsp;</td>
							</tr>
							<tr>
								<td align="center" style="font-size:12px;">ឯកឧត្តម ស៊ី លាង</td>
								<td align="center"></td>
								<td align="center">
									<div style=" font-size: 12px;"> 
										<?php 
										   $session_user=new Zend_Session_Namespace('auth');
										   $last_name=$session_user->last_name;
										   $username = $session_user->first_name;
										   echo $last_name." ".$username;
										?>
									</div>
								</td>
								<td align="center"></td>
							</tr>
						</table>
					</td>
				</tr>	
				<tr>
					<td colspan="10" >
						<table width="100%" style="margin-top:5px; font-family:Khmer OS Battambang; font-size:10px;white-space:nowrap;">
							<tr>
								<td width="3%" valign="top" style="font-family:Khmer OS Muol;">បញ្ជាក់ៈ</td>
								<td width="53%">
									&nbsp; ប្រាក់ដែលបង់ហើយមិនអាចដកវិញបានឡើយ។ <span style="font-weight:bold;">Notice:</span> Your payment is non-returnable.<br />
								</td>
								<td width="7%" valign="top">លេខទូរស័ព្ទ/Tel:</td>
								<td width="37%">
									- 010 277 869 (ការិយាល័យផ្តល់ព័ត៌មាន/Information Office)<br />
								</td>
							</tr>
							
							<tr>
								<td></td>
								<td>
									- រាល់ការបង់ប្រាក់ត្រូវមានបង្កាន់ដៃទទួលប្រាក់ និងហត្ថលេខារបស់អគ្គនាយក ទើបយើងខ្ញុំទទួលខុសត្រូវ<br />
								</td>
								<td></td>
								<td>
									- 077 211 546 (ការិយាល័យសិក្សាផ្នែកខ្មែរ/Khmer academic office)<br />
								</td>
							</tr>
							
							<tr>
								<td></td>
								<td>
									&nbsp; We are responsible for all paymentwith receipt and signature from Director General only.<br />
								</td>
								<td></td>
								<td>
									- 088 700 6789 (ការិយាល័យសិក្សាផ្នែកអង់គ្លេស/English academic office)
								</td>
							</tr>
							
							<tr>
								<td></td>
								<td colspan="3">
									- តម្លៃសិក្សាខាងលើ សម្រាប់តែសេវាកម្មអាហារសាលា តែប៉ុណ្ណោះ/  This fee is for school lunch service only.<br />
								</td>
							</tr>
							
							<tr>
								<td></td>
								<td colspan="3">
									- មតិអាណាព្យាបាល សូមទំនាក់ទំនងតាមលេខទូរស័ព្ទ/  Parent/Guadians comment Please call : 016 59 9999 / 097 55 66666 / 097 88 66666
								</td>
							</tr>
							
						</table>
					</td>
				</tr>
		<?php ?>					
			</table>
		</div>
		<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>	
		<button dojoType="dijit.form.Button" label="Cancel" iconClass="dijitEditorIcon dijitEditorIconCancel"
				showLabel="true" type="button" onclick="hideDialog();">Cancel</button>
		<button dojoType="dijit.form.Button" label="Print" iconClass="dijitEditorIcon dijitEditorIconPrint"
				showLabel="true" type="button" onclick="printSubmit();">Print</button>
	</div>
</div>

<script>


//save daata when sub button print 
function printSubmit(){
	//$('#office_receipt').submit();
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
}

function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    dijit.byId("terms").hide();	//hideDialog();
}


</script>
<script type="text/javascript">

var url_get_start_date = '<?php echo $this->url(array('module'=>'registrar','controller'=>'studentlunchpayment','action'=>'get-start-date-service')); ?>';
function getStartDateService(){
	service_id = dijit.byId('service').get('value');
	stu_id = dijit.byId('student_name_old').get('value');
	dojo.xhrPost({
		url:url_get_start_date,
		content:{
			'service_id':service_id,
			'stu_id':stu_id
			},
		handleAs:"json",
		load: function(data) {
			if(data){
				dijit.byId('start_date').attr('value',data);
			}	
		},
		error: function(err) {
			alert(err);
		}
	});
}

var url_get_service_cate = '<?php echo $this->url(array('module'=>'registrar','controller'=>'studentlunchpayment','action'=>'get-service-cate')); ?>';
function getServiceCate(service_id){
		//alert(service_id);
		dojo.xhrPost({
				url:url_get_service_cate,
				content:{
					'service_id':service_id
					},
				handleAs:"json",
				load: function(data) {
					dijit.byId('service_cate').attr('value',data)					 
				},
				error: function(err) {
					alert(err);
				}
		});
	
}



var url_getreceiptno = '<?php echo $this->url(array('module'=>'registrar','controller'=>'coursestudy','action'=>'get-receipt-no')); ?>';
	function getNewReceiptNo(new_stu_id,condition){
		
		dojo.xhrPost({
				url:url_getreceiptno,
				content:{
					'dept_id':1
					},
				handleAs:"json",
				load: function(data) {
					//alert(data);
					//url_getstuno  = getDataStorefromJSON('id','name', data);
					 dijit.byId('reciept_no').attr('value',data);   
					if(condition==1){ 
						printSave(new_stu_id,data);
					}
				},
				error: function(err) {
					alert(err);
				}
			});
			
	}

function showPopupDept() {
	if(dijit.byId('faculty').value==-1){
		dijit.byId("popup_dept").show();
	}
}
function hideDialog() {		
	dijit.byId("terms").hide();
}

function calculateTotalPayment(){
	service_fee = dijit.byId('service_fee').get('value');
	qty = dijit.byId('qty').get('value');
	qty = isNaN(qty)?1:qty;
	service_fee = service_fee * qty;
	discount = dijit.byId('discount').get('value');
	discount = isNaN(discount)?0:discount;
	dijit.byId('total_payment').attr('value',service_fee-(service_fee*discount/100));
	dijit.byId('paid_amount').attr('value',service_fee-(service_fee*discount/100));
	calculatBalanceAndReturn();
	
	netTotal();
}

function calculatBalanceAndReturn(){
	total_payment = dijit.byId('total_payment').get('value');
	paid_amount = dijit.byId('paid_amount').get('value');

	if(paid_amount>total_payment){
		//dijit.byId('return').attr('value',paid_amount-total_payment);
		
		dijit.byId('balance').attr('value',0);
	}
	else{
		dijit.byId('balance').attr('value',total_payment-paid_amount);
		//dijit.byId('return').attr('value',0);
	}
}

var url_student_info = "<?php echo $this->url(array('module'=>'registrar','controller'=>'studentlunchpayment','action'=>'get-student')); ?>";
function getStudentInfo(){
	stu_type = dijit.byId('student_type').get('value');
	if(stu_type==1){
		studentid = dijit.byId('student_name_new').get('value');
	}else{
		studentid = dijit.byId('old_car_id').get('value');
	}
	
	dojo.xhrPost({
		url:url_student_info,
		content:{
			'studentid':studentid
			},
		handleAs:"json",
		load: function(data) {
			//alert(data.tel);
			dijit.byId("kh_name").attr("value",data.stu_khname);
			dijit.byId("en_name").attr("value",data.stu_enname);
			dijit.byId("sex").attr("value",data.sex);
			dijit.byId("phone").attr("value",data.tel);
		},
		error: function(err) {
			//alert(err);
		}
	});
}
var url_service_fee = "<?php echo $this->url(array('module'=>'registrar','controller'=>'studentlunchpayment','action'=>'get-price')); ?>";
function getservicefee(){
			
	student_type = dijit.byId('student_type').get('value');
	if(student_type==1){
		studentid = dijit.byId('student_name_new').get('value');
	}else{
		studentid = dijit.byId('student_name_old').get('value');
	}
	
	service = dijit.byId('service').get('value');
	term = dijit.byId('term').get('value');
	//year = dijit.byId('study_year').get('value');
	
	dojo.xhrPost({
		url:url_service_fee,
		content:{
			'term':term,
			'service':service,
			'studentid':studentid,
		//	'year':year,
			},
		handleAs:"json",
		load: function(data) {
			if(data.balance>0){
				clear();
				dijit.byId("service_fee").attr("value",data.balance);
				dijit.byId("other").attr("value",'លុយជំពាក់ពីមុន');
				dijit.byId("start_date").attr("value",data.start_date);
				dijit.byId("end_date").attr("value",data.validate);
				dijit.byId("balance_id").attr("value",data.id);
				calculateTotalPayment();
				setDateReadOnly();
				//alert(1);
			}else{
				clear();
				dijit.byId("service_fee").attr("value",data.price_fee);
				calculateTotalPayment();
				getCurrentDate();
				removeDateReadOnly();
			}
		},
		error: function(err) {
			alert(err);
		}
	});
}
function clear(){
	dijit.byId("balance_id").attr("value",'');
	dijit.byId("service_fee").attr("value",0);
	dijit.byId("discount").attr("value",0);
	dijit.byId("total_payment").attr("value",0);
	dijit.byId("paid_amount").attr("value",0);
	dijit.byId("balance").attr("value",0);
	//dijit.byId("return").attr("value",0);
	dijit.byId("other").attr("value",'');
}
function setDateReadOnly(){
	//document.getElementById('start_date').readOnly = true;
	//document.getElementById("start_date").setAttribute("readonly", true);
	dijit.byId("start_date").set('readOnly',true);
	dijit.byId("end_date").set('readOnly',true);
}
function removeDateReadOnly(){
	dijit.byId("start_date").set('readOnly',false);
	dijit.byId("end_date").set('readOnly',false);
}
function getCurrentDate(){
	var currentDate = new Date();

    var day = currentDate.getDate();
	if(day<10){
		day='0'+day;
	}
    var month = currentDate.getMonth() + 1;
	if(month<10){
		month='0'+month;
	}
    var year = currentDate.getFullYear();
    var my_date = day+"/"+month+"/"+year;
    document.getElementById("start_date").value = my_date;
    getValidate();
}
function getValidate(){
	 term = dijit.byId('term').get('value');
	 qty = dijit.byId('qty').get('value');
	 qty = isNaN(qty)?1:qty;
	 start_date = dijit.byId('start_date').get('value');
	 if(term==1){
		 var a = new Date(start_date);
		  mm = a.getMonth()+(1*qty)+1;

		 var dd = a.getDate();
		  if(dd<10){
		   dd = "0"+dd;
		 }
		  if(mm<10){
		   mm = "0"+mm;
		 }
		 var y = a.getFullYear();
		 var epx_date = y + '-' + mm + '-' + dd ;

		 //alert(epx_date);
		 dijit.byId('end_date').attr('value',epx_date);
	 }
	 else if(term==2){
		 var a = new Date(start_date);
		  mm = a.getMonth()+(3*qty)+1;

		 var dd = a.getDate();
		  if(dd<10){
		   dd = "0"+dd;
		 }
		  if(mm<10){
		   mm = "0"+mm;
		 }
		 var y = a.getFullYear();
		 var epx_date = y + '-' + mm + '-' + dd ;

		 //alert(epx_date);
		 dijit.byId('end_date').attr('value',epx_date);
	 }
	 else if(term==3){
		 var a = new Date(start_date);
		  mm = a.getMonth()+(6*qty)+1;

		 var dd = a.getDate();
		  if(dd<10){
		   dd = "0"+dd;
		 }
		  if(mm<10){
		   mm = "0"+mm;
		 }
		 var y = a.getFullYear();
		 var epx_date = y + '-' + mm + '-' + dd ;

		 //alert(epx_date);
		 dijit.byId('end_date').attr('value',epx_date);
	 }
	 else if(term==4){
		 var a = new Date(start_date);
		  mm = a.getMonth()+(12*qty)+1;

		 var dd = a.getDate();
		  if(dd<10){
		   dd = "0"+dd;
		 }
		  if(mm<10){
		   mm = "0"+mm;
		 }
		 var y = a.getFullYear();
		 
		 var epx_date = y + '-' + mm + '-' + dd ;

		 //alert(epx_date);
		 dijit.byId('end_date').attr('value',epx_date);
	 }else if(term==5){
		var a = new Date(start_date);
		dd = a.getDate()+parseInt(qty); 
		 
		 if(dd<10){
		   dd = "0"+dd;
		 }
		 mm = a.getMonth()+1;
		 if(mm<10){
		   mm = "0"+mm;
		 }
		 var y = a.getFullYear(); 
		 var epx_date = y + '-' + mm + '-' + dd ;
		 
		 dijit.byId('end_date').attr('value',epx_date);
	 }
}
function getValue(){
	seperater='';
	i=0;
	$("#time_identity").val('');
	for(i=1;i<=4;i++){
		if(dijit.byId('time'+i).checked){
			//alert(dijit.byId('time'+i).get('value'));
			if($("#time_identity").val()!="") {
				var time_identity = $("#time_identity").val();
				$("#time_identity").val(time_identity+','+i);
			} else {$("#time_identity").val(i);}
		}
	}
}

var url_add_service = '<?php echo $this->url(array("module"=>"registrar","controller"=>"studentlunchpayment","action"=>"add-popup-lunch-service")); ?>';
function addService(){
	dojo.xhrPost({
			url:url_add_service,
			form: dojo.byId("frm_add_service"),
			handleAs:"json",
			load: function(data) {
				//alert(data); 
				var Itemmake = { 
				     id: data,
					         name: dijit.byId('service_name').get('value')
					   };
		 	addDataToSelectbox(dijit.byId('service'), service_store, Itemmake, data);
		    dijit.byId('frm_add_service').reset();
		    dijit.byId("popup_add_service").hide();
				
			},
			error: function(err) {
				alert(err);
			}
	});
}

function hidePopup() {		
	dijit.byId("popup_add_service").hide();
}


///////////////////////////////////////////////////////////// Add Row /////////////////////////////////////////////////////////

var template = '';
var service = '';
var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
date_format = '"dd/MM/yyyy"';
function addRow() {
		col++;no++;
		template='';
		if(title!=1){
			temp+='<th ><?php echo $tr->translate("DEL");?></th>';
			temp+='<th ><?php echo $tr->translate("N_O");?></th>';
			temp+='<th ><?php echo $tr->translate("PRODUCT");?></th>';
			temp+='<th  ><?php echo $tr->translate("PRICE");?></th>';
			temp+='<th  ><?php echo $tr->translate("AMOUNT");?></th>';
			temp+='<th  ><?php echo $tr->translate("DISCOUNT");?> %</th>';
			temp+='<th  ><?php echo $tr->translate("SUBTOTAL");?></th>';
			temp+='<th><?php echo $tr->translate("REMARK");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
			template+='<td align="center"  style="width:3%"><img onclick="deleteRecord('+col+');calculateTotal('+col+');" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td align="center" style="width:3%;">'+no+'</td>';
			
			template+='<td style="width:30%"><input type="hidden" dojoType="dijit.form.TextBox" name="id_balance_record_'+col+'" id="id_balance_record_'+col+'"/>';
			template+='<select style="width:100%"  onchange="getProductPrice('+col+');" dojoType="dijit.form.FilteringSelect" id="product_'+col+'" name="product_'+col+'">';
				template+='<option value="">Select </option>';
				<?php if(!empty($this->all_product)){foreach($this->all_product as $product){?>
					template+='<option value="'+<?php echo $product['id']?>+'"><?php echo $product['name'];?></option>';
				<?php }}?>
			template+='</select></td>';	

			
			column = 0;
			template+='<td style="width:10%"> <input class="fullside"  type="text"  onkeyup="calculateTotal('+col+');" name="price_'+col+'" id="price_'+col+'" dojoType="dijit.form.NumberTextBox" " /><label id="subsub"></label></td>';	
			template+='<td style="width:10%"> <input class="fullside" type="text"  onkeyup="calculateTotal('+col+');" name="qty_'+col+'" id="qty_'+col+'" value="1" dojoType="dijit.form.NumberTextBox" /><label id="qty"></label></td>';			
					
			template+='<td style="width:10%"> <input class="fullside"  type="text" onkeyup="calculateTotal('+col+');" name="discount_'+col+'" value="<?php echo 0;?>" id="discount_'+col+'" dojoType="dijit.form.NumberTextBox" /><label id="subsub"></label></td>';
			template+='<td style="width:10%"> <input class="fullside"  type="text"  readonly="readonly" name="subtotal_'+col+'" id="subtotal_'+col+'" dojoType="dijit.form.NumberTextBox"/><label id="qty"></label></td>';
			template+='<td style="width:24%"> <input class="fullside"  type="text" name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ" /><label id="subsub"></label></td>';

								//constraints="{datePattern:'dd/MM/yyyy'}"
			
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);

		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
		//getValidate(col);
 }
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
	if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
}



///////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////



/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

var url_getproductprice = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-product-price')); ?>';
function getProductPrice(index){
	
	product = dijit.byId('product_'+index).get('value');
	qty = dijit.byId('qty_'+index).get('value');
	discount = dijit.byId('discount_'+index).get('value');
	
	dojo.xhrPost({
		url:url_getproductprice,
		content:{
			'product':product,
			},
		handleAs:"json",
		load: function(data) {
			if(data){
				//alert(data);
				
				fee_discount = data * qty * (discount/100);
				//alert(fee_discount);
				
				dijit.byId('price_'+index).attr('value',data);
				dijit.byId('subtotal_'+index).attr('value',(data * qty) - fee_discount);
				
				netTotal();
			}
		},
		error: function(err) {
			//alert(err);
		}
	});
}

function calculateTotal(index){
	price = dijit.byId('price_'+index).get('value');
	qty = dijit.byId('qty_'+index).get('value');
	qty=isNaN(qty)?1:qty;
	//if(qty==1){dijit.byId('qty_'+index).attr('value',qty);}
	total = price*qty;
	discount = dijit.byId('discount_'+index).get('value');
	discount = isNaN(discount)?0:discount;
	dijit.byId('subtotal_'+index).attr('value',total-(total*(discount/100)));
	netTotal();
}

function netTotal() {
	// alert(1);
		var netTotal=0;
		var netPaidAmount=0;
		var rowId = $('#identity').val();
		var rowIDArray = rowId.split(',');
		//alert(rowIDArray);
		
		//tuition_fee = dijit.byId('tuitionfee').get('value');
		paid_amount = dijit.byId('paid_amount').get('value');
		total_payment = dijit.byId('total_payment').get('value');
		
		if(document.getElementById('buy_product').checked){
			for(var n = 0; n < rowIDArray.length; n++) {
				//netTotal += Number($('#subtotal_'+rowIDArray[n]).val());
				netTotal += dijit.byId('subtotal_'+rowIDArray[n]).get('value');
				netPaidAmount += dijit.byId('subtotal_'+rowIDArray[n]).get('value');
			}
		}
		
		grand_total_payment = parseFloat(netTotal) + parseFloat(total_payment) ;
		grand_total_paid = parseFloat(netPaidAmount) + parseFloat(paid_amount) ;
				
		ex_rate = dijit.byId('ex_rate').get('value');
		
		dijit.byId('grand_total').attr('value',grand_total_payment);
		dijit.byId('convert_to_riels').attr('value',grand_total_payment * ex_rate);
		dijit.byId('total_received').attr('value',grand_total_paid);
		
		dijit.byId('total_balance').attr('value',grand_total_payment - grand_total_paid);
		
		//calculatBalanceAndReturn();
}

function displayNoneAddRow(){
	
	if(document.getElementById('buy_product').checked){
		document.getElementById('table_row').style.display="block";
	}else{
		document.getElementById('table_row').style.display="none";
	}
	
}




///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////




</script>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:40%;" id="popup_add_service" >
		<form style="background-color: buttonface; width:100%;" id='frm_add_service' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
			<tr>
				<td>
					<fieldset style="background-color: buttonface;">
					<legend align="center" ><?php echo $tr->translate('ADD_SERVICE');?></legend><br />
						<table style="margin: 0 auto; width: 100%;  padding:10px;" cellspacing="7" >
							<tr>
								<td style="width:100px"><?php echo $tr->translate("SERVICE_TYPE")?></td>
								<td>
									<select dojoType="dijit.form.FilteringSelect"   class="fullside" id="service_type" name="service_type" value="" type="text">
										<?php if(!empty($this->service_type)){ foreach ($this->service_type as $service_type){?>
											<option value="<?php echo $service_type['id']?>"><?php echo $service_type['name']?></option>
										<?php }}?>
									</select>
								</td>
							</tr>
							<tr>
								<td style="width:100px"><?php echo $tr->translate("PROGRAM_TITLE")?></td>
								<td>
									<input dojoType="dijit.form.TextBox"  class="fullside" id="service_name" name="service_name" value="" type="text">
								</td>
							</tr>
							<tr>
							<tr>
								<td style="width: 5px"><?php echo $tr->translate("DISCRIPTION")?></td>
								<td>
									<input dojoType="dijit.form.TextBox"  class="fullside" id="description" name="description" value="" type="text">
								</td>
							</tr>
							<tr>
								<td style="width: 5px"><?php echo $tr->translate("STATUS")?></td>
								<td>
									<select name="status_popup" id="status_popup" dojoType="dijit.form.FilteringSelect"   class="fullside">
	    								<option value="1" label="active">Active</option>
	    								<option value="0" label="deactive">Deactive</option>
									</select>
								</td>
							</tr>
							<tr>
								<td colspan="4" align="center">
									<input type="button" value="ចាកចេញ" label="Close" id="close" name="close" dojoType="dijit.form.Button" 
									​ ​​iconClass="dijitIconUndo" onclick="hidePopup();"/>
									<input type="button" value="save" label="SAVE" id="save" name="save" dojoType="dijit.form.Button" 
									 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addService();"/>
								</td>
							</tr>
							
						</table>
				</fieldset>
				</td>
			</tr>
		</table>

		</form>
	</div>
</div>

