<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_STUDENT_LUNCH_PAYMENT')); 
	$base_url = Application_Form_FrmMessage::getUrl("/");
	// print_r($this->row);exit();
	// print_r($this->all_stu_name);exit();
?>	
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/convertion.js"></script>
<?php /*?><script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.14.1/moment.min.js"></script> <?php */ ?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>

<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require('dojox.form.BusyButton');
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dojo.data.ObjectStore");
	dojo.require("dojo.store.Memory");
	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.form.Textarea");
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.CheckBox");
	
	var service_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->service));?>);
	dojo.ready(function(){ 
		displayNoneAddRow();
		// addRow();
		changeControl();
		// getNewLunchId('');
		// getNewReceiptNo("","");
	
		new dijit.form.FilteringSelect({
			store: service_store,
			autoComplete: true,                        
		    id: "service",
		    name: "service",
			value:-1,
		    class: 'fullside',  
		   // placeHolder:"Selected service", 
		    onChange: function() {  
			    service = dijit.byId('service').get('value');
			    if(service==-2){
					dijit.byId('popup_add_service').show();
			    }
		    	//getservicefee();
				getServiceCate(service);
				if(dijit.byId('student_type').get('value')==2){
					getStartDateService();
				}
		    } 
		}, "service");
		dijit.byId('service').attr('value','<?php echo $this->detail['service_id']?>');
		getStudentInfo();
		//getValidate();
		Initialize();
		setReadonlyPageEdit();
		netTotal();
	});	

</script>
<style>
select{ width:100%;}
fieldset{  background:none;}
.red{ color: red; padding-left:5px;}
.head-td{font-size: 12px;}
</style>
<?php $register = $this->frm_register;
//print_r($register);
?>
<form id='office_receipt' action="<?php echo $this->url(array('module'=>'registrar','controller'=>'studentlunchpayment','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">  
 
	stu_type = dijit.byId('student_type').get('value');
	if(stu_type==1){
		stu_id = dijit.byId('student_name_new').get('value');
		if(stu_id==-1){
			dijit.byId('student_name_new').focus();
			return false;
		}
	}else{
		stu_id = dijit.byId('student_name_old').get('value');
		if(stu_id==-1){
			dijit.byId('student_name_old').focus();
			return false;
		}
	}

	total_payment = dijit.byId('total_payment').get('value');
	paid_amount = dijit.byId('paid_amount').get('value');
	if(paid_amount>total_payment){
		alert('You can not pay more than total payment')
		dijit.byId('paid_amount').focus();
		return false;
	}
    
	if(this.validate()) {
		dijit.byId('save_close').set('disabled',true);
    	return true;
    }else {
    	return false;
    }
</script>
<table id="head_tbl"  cellspacing="10" style="margin: 0 auto; width: 100%;">
	<tr>
		<td>
			<fieldset>
				<legend align="center"><strong​ style="font-size: 18px;"><?php echo $tr->translate("EDIT_STUDENT_LUNCH_PAYMENT");?></strong></legend>
				<table style="margin: 0 auto; width: 100%;padding:10px;" cellspacing="7" cellpadding="10px" >
					<td>
						<input type="checkbox" value="1" <?php if($this->row['buy_product']==1){echo "checked";}?> onclick="return false;" name="buy_product" id="buy_product" dojoType="dijit.form.CheckBox"  /> Buy Product
					</td>
					<td colspan="2"></td>
					<td>
						<input type="checkbox" value="1" name="is_void" id="is_void" <?php if($this->row['is_void']==1){echo 'onclick="return false;"';}?> dojoType="dijit.form.CheckBox"  /> Void
					</td>
					
					<tr>
						<td style="width: 12%"><?php echo $tr->translate("STUDENT_TYPE");?></td>
						<td style="width: 37%">
							<select name="student_type" id="student_type" onchange="changeControl();getStudentInfo();" class="fullside" dojoType="dijit.form.FilteringSelect" >
								<option value="1" <?php if($this->row['student_type']==1){echo 'selected="selected"';}?>>New Student</option>
								<option value="3" <?php if($this->row['student_type']==3){echo 'selected="selected"';}?>>Old Student</option>
								<option value="4" <?php if($this->row['student_type']==4){echo 'selected="selected"';}?>>Drop Student</option>
							</select>
						</td>
						
						<td align="right" style="width: 12%"><?php echo $tr->translate("RECEIPT_NO");?></td>
						<td align="center" style="width: 37%"><input type="text" name="receipt_no" style="color:red;" id="receipt_no" value="<?php echo $this->row['receipt_number'];?>" readOnly="readOnly" class="fullside" dojoType="dijit.form.TextBox" > </td>
					</tr>
					<input type="hidden" name="service_cate" id="service_cate" dojoType="dijit.form.TextBox" />
					<input type="hidden" name="ex_rate" id="ex_rate" value="<?php echo $this->exchange_rate ;?>" dojoType="dijit.form.TextBox" />
					<input type="hidden" name="parent_id" id="parent_id" value="<?php echo $this->row['is_parent'];?>" dojoType="dijit.form.TextBox" />
					<tr>
						<td><?php echo $tr->translate("STUDENT_NAME");?></td>
						<td>
							<div id="new_name">
								<select name="student_name_new" id="student_name_new" onChange="getStudentInfo(1);" class="fullside" dojoType="dijit.form.FilteringSelect" >
									<option value="-1">----- select name -----</option>
									<?php if(!empty($this->all_stu_name)){foreach($this->all_stu_name as $all_stu_name){?>
										<option value="<?php echo $all_stu_name['stu_id']?>" <?php if($all_stu_name['stu_id']==$this->row['student_id']){echo 'selected="selected"';}?> ><?php echo $all_stu_name['stu_name']?></option>
									<?php }}?>
								</select>
							</div>	
							<div id="old_name">
								<select name="student_name_old" id="student_name_old" onChange="setID();" class="fullside" dojoType="dijit.form.FilteringSelect" >
									<option value="-1">----- select name -----</option>
									<?php if(!empty($this->old_stu_name)){foreach($this->old_stu_name as $old_stu_name){?>
										<option value="<?php echo $old_stu_name['stu_id']?>" <?php if($old_stu_name['stu_id']==$this->row['student_id']){echo 'selected="selected"';}?>><?php echo $old_stu_name['stu_name']?></option>
									<?php }}?>
								</select>
							</div>	
							<div id="drop_name">
								<select name="drop_name" id="drop_name" onChange="setID(2);" class="fullside" dojoType="dijit.form.FilteringSelect" >
									<option value="-1">----- select name -----</option>
									<?php if(!empty($this->drop_stu_name)){foreach($this->drop_stu_name as $drop_stu_name){?>
										<option value="<?php echo $drop_stu_name['stu_id']?>" <?php if($drop_stu_name['stu_id']==$this->row['student_id']){echo 'selected="selected"';}?>><?php echo $drop_stu_name['stu_name']?></option>
									<?php }}?>
								</select>
							</div>
						</td>
						
						<td align="right"><?php echo $tr->translate("STUDENT_ID");?></td>
						<td align="center">
							<div id="new_id">
								<input type="text" name="new_car_id" style="color:red;" id="new_car_id" readOnly="readOnly" value="<?php echo $this->row['code']?>" class="fullside" dojoType="dijit.form.TextBox" >     
							</div>
							<div id="old_id">
								<select name="old_car_id" id="old_car_id" onChange="getStudentInfo(2);" class="fullside" dojoType="dijit.form.FilteringSelect" >
									<option value="-1">----- select id -----</option>
									<?php if(!empty($this->old_car_id)){foreach($this->old_car_id as $old_car_id){?>
										<option value="<?php echo $old_car_id['stu_id']?>"  <?php if($old_car_id['stu_id']==$this->row['student_id']){echo 'selected="selected"';}?>><?php echo $old_car_id['stu_code']?></option>
									<?php }}?>
								</select>
							</div>
							<div id="drop_id">
								<select name="drop_car_id" id="drop_car_id" onChange="getStudentInfo();" class="fullside" dojoType="dijit.form.FilteringSelect" >
									<option value="-1">----- select id -----</option>
									<?php if(!empty($this->drop_car_id)){foreach($this->drop_car_id as $drop_car_id){?>
										<option value="<?php echo $drop_car_id['stu_id']?>"  <?php if($drop_car_id['stu_id']==$this->row['student_id']){echo 'selected="selected"';}?>><?php echo $drop_car_id['stu_code']?></option>
									<?php }}?>
								</select>
							</div>
						</td>
					</tr>
					
					<tr>
						<td><?php echo $tr->translate("NAME_EN");?></td>
						<td><?php echo $register->getElement('en_name');?></td>
						<td align="right"><?php echo $tr->translate("NAME_KH");?></td>
						<td align="center"><?php echo $register->getElement('kh_name');?></td>
					</tr>
					<tr>	
						<td><?php echo $tr->translate("SEX");?></td>
						<td ><?php echo $register->getElement('sex');?></td>
						<td align="right"><?php echo $tr->translate("PHONE");?></td>
						<td><input type="text" readOnly="readOnly"  class="fullside" name="phone" id="phone" dojoType="dijit.form.TextBox" /></td>
					</tr>
					
					<tr>
						<td><?php echo $tr->translate('SERVICE');?></td>
						<td> 
							<input id="service" />
						</td>
						<input type="hidden" name="balance_id" id="balance_id" dojoType="dijit.form.TextBox" />
						<td align="right"><?php echo $tr->translate('PAYMENT_TERM');?></td>
						<td> 
							<select class="fullside" name="term" id="term" onchange="" dojoType="dijit.form.FilteringSelect" type="text"   >
								<?php if(!empty($this->payment_term)){foreach ($this->payment_term as $key => $term){?>
									<option value="<?php echo $key?>"<?php if($key==$this->detail['payment_term']){echo "selected='selected'";}?>><?php echo $term;?></option>
								<?php  }}?>
							</select>
						</td>
					</tr>
					<tr>
						<td><?php echo $tr->translate('SERVICE_FEE');?></td>
						<td> 
							<input class="fullside" name="service_fee" id="service_fee" value="<?php echo $this->detail['fee']?>" onkeyup="calculateTotalPayment();netTotal();" dojoType="dijit.form.TextBox" type="text" >
						</td>
						
						<td align="right"><?php echo $tr->translate('QTY');?></td>
						<td> 
							<input class="fullside" name="qty" id="qty" value="<?php echo $this->detail['qty']?>" onkeyup="calculateTotalPayment();getValidate();netTotal();" dojoType="dijit.form.TextBox" value="1" type="text"   >
						</td>
						
						
					</tr>
					<tr>
					
						<td ><?php echo $tr->translate('DISCOUNT');?></td>
						<td> 
							<input class="fullside" name="discount" id="discount" value="<?php echo $this->detail['discount_percent']?>" onkeyup="calculateTotalPayment();netTotal();" dojoType="dijit.form.TextBox" value="0" type="text"   >
						</td>
					
						<td align="right" ><?php echo $tr->translate('TOTAL_PAYMENT');?></td>
						<td> 
							<input class="fullside" name="total_payment" id="total_payment" value="<?php echo $this->detail['subtotal']?>" readOnly="readOnly" dojoType="dijit.form.TextBox" type="text" >
						</td>
					</tr>
					
					<tr>
						<td ><?php echo $tr->translate('PAID_AMOUNT');?></td>
						<td> 
							<input class="fullside" name="paid_amount" id="paid_amount" value="<?php echo $this->detail['paidamount']?>" onkeyup="calculatBalanceAndReturn();netTotal();" dojoType="dijit.form.TextBox" type="text"   >
						</td>
					
						<td  align="right" ><?php echo $tr->translate('BALANCE');?></td>
						<td> 
							<input class="fullside" name="balance" id="balance" value="<?php echo $this->detail['balance']?>" readOnly="readOnly" dojoType="dijit.form.TextBox" type="text" >
						</td>
					</tr>
					
					<tr>
						<td ><?php echo $tr->translate('NOTE');?></td>
						<td> 
							<input class="fullside" name="other" id="other" value="<?php echo $this->row['note']?>" dojoType="dijit.form.TextBox" type="text" >
						</td>
						
						<td align="right" ><?php echo $tr->translate('START_DATE');?></td>
						<td> 
							<input class="fullside" name="start_date" id="start_date" value="<?php echo $this->detail['start_date']?>" constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" onchange="getValidate();" value="now" type="text" >
						</td>
					</tr>
					
					<tr>
						<td colspan="2" align="left">
						</td>
					
						<td align="right" ><?php echo $tr->translate('END_DATE');?></td>
						<td> 
							<input class="fullside" name="end_date" id="end_date" value="<?php echo $this->detail['validate']?>" constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" type="text"   >
						</td>
					</tr>
					
					<input type="hidden" id="identity" name="identity" />
					
					<tr>
						<td colspan="2" align="left">
							&nbsp;
						</td>
					</tr>
					
					<tr>
						<div id="addrow" >
							<td colspan="4">
								<table width="100%" border="1" id="table_row" style="border-collapse: collapse; border:1px solid #ccc;white-space: nowrap;">
									<tr id="head-title" class="head-td" align="right"></tr>
								</table>
							</td>
						</div>
					</tr>
					<tr>
						<td colspan="2">
							<input type="text" class="fullside" name="readmoney" id="readmoney" dojoType="dijit.form.TextBox" />
						</td>
					
						<td colspan="2" align="right">
							<table style="width:400px;border-collapse: collapse;white-space:nowrap;" cellpadding="10" cellspacing="10" >
								<tr>
									<td ><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
									<td align="right"><input type="text" readonly="readonly" onkeyup="calculatBalanceAndReturn();"  name="grand_total" id="grand_total" dojoType="dijit.form.NumberTextBox" /></td>
								</tr>
								<tr>	
									<td><?php echo $tr->translate("CONVERT_TO_RIELS");?> (៛)</td>
									<td align="right"><input  type="text" readonly="readonly"  name="convert_to_riels" id="convert_to_riels" dojoType="dijit.form.NumberTextBox" /></td>
								</tr>
								<tr>	
									<td><?php echo $tr->translate("RECEIVED_AMOUNT");?></td>
									<td align="right"><input  type="text" readonly="readonly" onkeyup="calculatBalanceAndReturn();" required="true"  name="total_received" id="total_received" dojoType="dijit.form.NumberTextBox" /></td>
								</tr>
								<tr>
									<td><?php echo $tr->translate("BALANCE");?></td>
									<td align="right"><input type="text"  readonly="readonly" name="total_balance" value="<?php echo 0?>" id="total_balance" dojoType="dijit.form.NumberTextBox" /></td>
								</tr>
							</table>
						</td>
					</tr>
					
					<tr>
						<td colspan="4" align="center">
							<input type="submit" name="save_close" id="save_close" value="រក្សាទុក" label="<?php echo $tr->translate('GO_EDIT');?>"  dojoType="dijit.form.Button" 
								iconClass="dijitEditorIcon dijitEditorIconSave" />
							
							<input type="button" value="បោះពុម្ព" label="<?php echo $tr->translate('PRINT');?>" id="print" dojoType="dijit.form.Button" 
								iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="printSave('','');"/>
						</td>
					</tr>
				</table>	
				
			</fieldset>		
		</td>
	</tr>
</table>	
</form>



<script type="text/javascript">


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	var template = '';
	var service = '';
	var col = 0;
	var no = 0;
	var title = 0;
	tmp = '';
	temp='';
	date_format = '"dd/MM/yyyy"';

	function Initialize() {
		
		<?php if(!empty($this->row_product)){ //echo '111111';exit();
			foreach($this->row_product as $row){ 
		?>
		
			col++;no++;
			template='';
			if(title!=1){
				temp+='<th ><?php echo $tr->translate("DEL");?></th>';
				temp+='<th ><?php echo $tr->translate("N_O");?></th>';
				temp+='<th ><?php echo $tr->translate("PRODUCT");?></th>';
				temp+='<th  ><?php echo $tr->translate("PRICE");?></th>';
				temp+='<th  ><?php echo $tr->translate("AMOUNT");?></th>';
				temp+='<th  ><?php echo $tr->translate("DISCOUNT");?> %</th>';
				temp+='<th  ><?php echo $tr->translate("SUBTOTAL");?></th>';
				temp+='<th><?php echo $tr->translate("REMARK");?></th>';
				dojo.query("#head-title").append(temp);
				title=1;
			}
			template+='<td align="center"  style="width:3%"><img onclick="" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td align="center" style="width:3%;">'+no+'</td>';
			
			template+='<td style="width:30%"><input type="hidden" dojoType="dijit.form.TextBox" name="id_balance_record_'+col+'" id="id_balance_record_'+col+'"/>';
			template+='<select style="width:100%"  onchange="" readOnly dojoType="dijit.form.FilteringSelect" id="product_'+col+'" name="product_'+col+'">';
			template+='<option value="">Select </option>';
			<?php if(!empty($this->all_product)){foreach($this->all_product as $product){?>
			template+='<option value="'+<?php echo $product['id']?>+'"><?php echo $product['name'];?></option>';
			<?php }}?>
			template+='</select></td>';	
			
			
			column = 0;
			template+='<td style="width:10%"> <input class="fullside"  type="text" readOnly onkeyup="" name="price_'+col+'" id="price_'+col+'" dojoType="dijit.form.NumberTextBox" " /><label id="subsub"></label></td>';	
			template+='<td style="width:10%"> <input class="fullside" type="text" readOnly onkeyup="" name="qty_'+col+'" id="qty_'+col+'" value="1" dojoType="dijit.form.NumberTextBox" /><label id="qty"></label></td>';			
			
			template+='<td style="width:10%"> <input class="fullside"  type="text" readOnly onkeyup="" name="discount_'+col+'" value="<?php echo 0;?>" id="discount_'+col+'" dojoType="dijit.form.NumberTextBox" /><label id="subsub"></label></td>';
			template+='<td style="width:10%"> <input class="fullside" value="0" type="text"  readonly="readonly" name="subtotal_'+col+'" id="subtotal_'+col+'" dojoType="dijit.form.NumberTextBox"/><label id="qty"></label></td>';
			template+='<td style="width:24%"> <input class="fullside"  type="text" readOnly name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ" /><label id="subsub"></label></td>';

			//constraints="{datePattern:'dd/MM/yyyy'}"
			
			tmp='<tr id="row'+col+'">';
			tmp+="</tr>";
			dojo.query("#table_row").append(tmp);
			
			if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
			} else {$("#identity").val(col);}
			dojo.html.set(dojo.byId("row"+col),template , {
			parseContent: true,
			});
			//getValidate(col);
			
		dijit.byId('product_'+col).attr('value',<?php echo $row['service_id'];?>);
		dijit.byId('price_'+col).attr('value',<?php echo $row['fee'];?>);
		dijit.byId('qty_'+col).attr('value',<?php echo $row['qty'];?>);
		dijit.byId('discount_'+col).attr('value',<?php echo $row['discount_percent'];?>);
		dijit.byId('subtotal_'+col).attr('value',<?php echo $row['subtotal'];?>);
		dijit.byId('remark'+col).attr('value',"<?php echo $row['note'];?>");
		
		<?php }}?>
	}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	function setReadonlyPageEdit(){
		dijit.byId("student_type").set('readOnly',true);
		dijit.byId("student_name_old").set('readOnly',true);
		dijit.byId("old_car_id").set('readOnly',true);
		dijit.byId("student_name_new").set('readOnly',true);
		dijit.byId("service").set('readOnly',true);
		dijit.byId("term").set('readOnly',true);
		dijit.byId("service_fee").set('readOnly',true);
		dijit.byId("qty").set('readOnly',true);
		dijit.byId("discount").set('readOnly',true);
		dijit.byId("paid_amount").set('readOnly',true);
		dijit.byId("start_date").set('readOnly',true);
		dijit.byId("end_date").set('readOnly',true);
		dijit.byId("other").set('readOnly',true);
		dijit.byId("readmoney").set('readOnly',true);
	}

	function setID(){
		stu_id = dijit.byId('student_name_old').get('value');
		dijit.byId('old_car_id').attr('value',stu_id);
	}

	function changeControl(){
		document.getElementById('new_id').style.display="none";
		document.getElementById('new_name').style.display="none";
		document.getElementById('old_id').style.display="block";
		document.getElementById('old_name').style.display="block";
		document.getElementById('drop_name').style.display="none";
		document.getElementById('drop_id').style.display="none";
	}
		
	var url_get_new_lunch_id = '<?php echo $this->url(array('module'=>'registrar','controller'=>'studentlunchpayment','action'=>'get-new-lunch-id')); ?>';
	function getNewLunchId(condition){
		dojo.xhrPost({
			url:url_get_new_lunch_id,
			content:{
				
				},
			handleAs:"json",
			load: function(data) {
				// alert(data);
				if(data){
					dijit.byId('new_car_id').attr('value',data);
				}	
				
				if(condition==1){
					getNewReceiptNo(data,1);
				}
				
			},
			error: function(err) {
				alert(err);
			}
		});
		
	}



function printSave(new_stu_id,new_receipt_no){		
	if(dijit.byId('office_receipt').validate()) {
		 
		 //degree = dijit.byId('dept').get('value');

		 stu_type = dijit.byId('student_type').get('value');
		 
		 if(stu_type==1){
			 dojo.byId("lb_stu_type").innerHTML = "សិស្សថ្មី/New Student";
		 }else{
			 dojo.byId("lb_stu_type").innerHTML = "សិស្សចាស់/Old Student";;
		 }
		 
		 dojo.byId("lb_receipt_no").innerHTML = dijit.byId("receipt_no").get('value');
		 dojo.byId("lb_stu_id").innerHTML = dijit.byId("old_car_id").attr('displayedValue');
		
		dojo.byId("lb_kh_name").innerHTML = dijit.byId("kh_name").get('value');
		dojo.byId("lb_en_name").innerHTML = dijit.byId("en_name").get('value');
		dojo.byId("lb_sex").innerHTML = dijit.byId("sex").attr('displayedValue');
		 
		dojo.byId("lb_phone").innerHTML = dijit.byId("phone").attr('displayedValue');
		//dojo.byId("lb_address").innerHTML = dijit.byId("service").attr('displayedValue');
		 
		dojo.byId("lb_receipt_type").innerHTML = "Food and Stay"; 
		 
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////		 
		 
		checked =  "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/checked.png'?>'>";
		uncheck = "<img style='width: 15px;height:15px;margin-bottom:-3px;' src='<?php echo $this->baseUrl().'/images/uncheck.png'?>'>";
		 
		service = dijit.byId("service").get('value');
		if(service == 91){
			dojo.byId("checkbox1").innerHTML = uncheck;
			dojo.byId("checkbox2").innerHTML = checked;
			dojo.byId("checkbox3").innerHTML = uncheck;
		}else if(service == 92){
			dojo.byId("checkbox1").innerHTML = uncheck;
			dojo.byId("checkbox2").innerHTML = uncheck;
			dojo.byId("checkbox3").innerHTML = checked;
		}else if(service == 93){
			dojo.byId("checkbox1").innerHTML = checked;
			dojo.byId("checkbox2").innerHTML = uncheck;
			dojo.byId("checkbox3").innerHTML = uncheck;
		}
		
		dojo.byId("lb_discount").innerHTML = dijit.byId('discount').get('value')+" %"; 
		 
		dojo.byId("lb_grand_total").innerHTML = "$ "+dijit.byId('grand_total').get('value');
		 
		dojo.byId("lb_total_balance").innerHTML = "$ "+dijit.byId('total_balance').get('value');
		
		dojo.byId("lb_total_paid").innerHTML = " &nbsp;&nbsp;$ "+dijit.byId('total_received').get('value');
		
		dojo.byId("lb_read_money").innerHTML = dijit.byId('readmoney').get('value');
		
		total_product_fee = 0;
		
		checkbox = dijit.byId('buy_product').get('value');
		
		if(checkbox==1){
			var rowId = $('#identity').val();
			if(rowId==""){
				return false;
			}
			var rowIDArray = rowId.split(',');
			for(var n = 0; n < rowIDArray.length; n++) {
				total_product_fee += dijit.byId('subtotal_'+rowIDArray[n]).get('value');
			}
		}
		dojo.byId("lb_total_product_fee").innerHTML ="$ "+total_product_fee;
		
		
		pay_term = dijit.byId('qty').get('value') + dijit.byId('term').attr('displayedValue');
		dojo.byId("lb_payment_term").innerHTML = pay_term;
		
		var b = new Date(dijit.byId("start_date").get('value'));
			mm = b.getMonth()+1;
			var dd = b.getDate();
			if(dd<10){
				dd = "0"+dd;
			}
			var mon = getMonthByNumber(mm);
			if(mm<10){
				mm = "0"+mm;
			}
			var y = b.getFullYear();
			var start_date = dd + '-' + mon + '-' + y ;
			
		dojo.byId("lb_start_date").innerHTML = start_date;	
		
		var a = new Date(dijit.byId("end_date").get('value'));
			mm = a.getMonth()+1;
			var dd = a.getDate();
			if(dd<10){
				dd = "0"+dd;
			}
			var months = getMonthByNumber(mm);
			if(mm<10){
				mm = "0"+mm;
			}
			var y = a.getFullYear();
			var epx_date = dd + '-' +months + '-' + y ;
			
		dojo.byId("lb_epx_date").innerHTML = epx_date;
		
		
		 
		 
		 
		dijit.byId("terms").show();	
	}
	
}


function getMonthByNumber(m){
	var monthName=[
		"Jan",
		 "Feb",
		 "Mar",
		 "Apr",
		 "May",
		 "Jun",
		 "Jul",
		 "Aug",
		 "Sep",
		 "Oct",
		 "Nov",
		 "Dec",
		];
		return (monthName[m-1]);
}


</script>


<div class="dijitHidden" style="width: 25cm !important; height: 11cm ; padding: 0px; margin: 0px;">
<?php $keycode = $this->keycode;?>
	<div data-dojo-type="dijit.Dialog" style="width:25cm;" align="center" data-dojo-props="title:'<?php echo $tr->translate("");?>'" id="terms" >
		
		<div id="divPrint" style="width: 23cm !important; height: 12cm ; padding: 0px; margin: 0px;">
			<style>
				.fontbig{
					font-size: 15px;	
				}
				.fonttel{
					font-size: 18px;	
				}
				.pleft{
					width: 110px;	
				}
				.label{ font-weight: bold;font-size: 22px;}
				.value{ font:bold 12px 'Khmer OS Battambang';border: 1px solid rgba(14, 0, 107, 1); height: 25px; padding: 0 2px;width: 98%; display: block;
						margin-top: -25px; line-height: 25px;
					    text-align: center;
						}
				.values{ border: 1px solid rgba(14, 0, 107, 1);; height: 25px; padding: 0 10px;display: block;
						line-height: 25px;}
				.h{ margin-top: -8px;/*margin-left:4px;*/}
​​               .print td{ font:bold 12px 'Khmer OS Battambang';}
			   .khmerbold{font:bold 12px 'Khmer OS Battambang';}
			   .khmer{font:12px 'Khmer OS Battambang';}
			   .one{white-space:nowrap;}
			   
				.underline{margin-top: -19px;text-align:center;}
				.data{font-size:13px;font-weight:bold;}
				.data1{font-size:12px;font-weight:bold;}
				.receiptno{font-size:15px;font-weight:bold;}
				.tab_row{ margin-top: -8px;}
				.fonteng{font-size:12px;}
				
			</style>	
			<table border="0" width="100%" class="print" cellspacing="0"  cellpadding="0" style="white-space: nowrap;font-size:12px;font-family:'Khmer OS Battambang';line-height: 23px;">
				<tr>
				    <td colspan="8"  align="center" style="">
						<table width="100%" border="0" style="white-space:nowrap; font-family:Khmer OS Battambang;margin-top:-15px;font-weight:bold;line-height: 20px;">
							<tr>
								<td width="25%" align="left" style="font-size:11px;">
									<div style="font-size:15px;">Branch 17 </div><?php echo date('l , jS / m / Y , H:i:s ',strtotime(Zend_Date::now()));?>
								</td>
								<td width="50%" align="center">
									<img style="width: 20%;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br >
								</td>
								<td width="25%" align="center" style="font-size:17px;color:red;"><label id="lb_receipt_type" style="color:#000;font-size:16px;"> </label><div style="margin-top:-5px;">N<sup>o</sup> : <label id="lb_receipt_no" class="receiptno" ></div></label></td>
							</tr>
						</table>
				    </td>
				</tr>
				
				<tr>
					<td width="15%"></td>
					<td width="20%"></td>
					<td width="15%"></td>
					<td width="20%"></td>
					<td width="5%"></td>
					<td width="10%"></td>
					<td width="5%"></td>
					<td width="10%"></td>
				</tr>
			
				<tr >
					<td colspan="8">
						<table width="100%" style="white-space:nowrap; font-size:12px;font-family:'Khmer OS Battambang';line-height: 21px;margin-top: -25px;">
							<tr>
								<td width="40%"><img style="width: 100%;height:4px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/double_underline.png'?>"></td>
								<td width="20%" align="center" style="font-size:16px;">បង្កាន់ដៃទទួលប្រាក់ RECEIPT</td>
								<td width="40%"><img style="width: 100%;height:4px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/double_underline.png'?>"></td>
							</tr>
						</table>
					</td>
				</tr>
			
				<tr>
					<td>ឈ្មោះភាសាខ្មែរ/Name in Khmer</td>
					<td>
						&nbsp;:&nbsp; <label id="lb_kh_name"  class="data" ></label>
						<div class="underline">...............................................</div>
					</td>
					<td align="center"> អក្សរឡាតាំង/Latin&nbsp;</td>
					<td>
						:&nbsp; <label id="lb_en_name" class="data" ></label>
						<div class="underline">...............................................</div>
					</td>
					<td align="center">ភេទ/Sex</td>
					<td>
						&nbsp;:&nbsp; <label id="lb_sex" class="data" ></label>
						<div class="underline">..................</div>
					</td>
					
					<td align="center">&nbsp;អត្តលេខ/ID&nbsp;</td>
					<td>
						:&nbsp; <label id="lb_stu_id" class="data" ></label>
						<div class="underline">....................</div>
					</td>
				</tr>
				
				
				<tr>
					<td colspan="8">
						<table width="100%" style="white-space: nowrap;font-size:12px;font-family:'Khmer OS Battambang';line-height: 21px;">
							<tr>
								<td width="15%">លេខទូរស័ព្ទ/Phone Number</td>
								<td width="50%">
									&nbsp;:&nbsp; <label id="lb_phone" class="data" ></label>
									<div class="underline">
										...........................................................................................................................
									</div>
								</td>
								<td width="15%">
									ប្រភេទសិស្ស/Student Type
								</td>
								<td width="20%">
									&nbsp;:&nbsp; <label id="lb_stu_type" class="data" ></label>
									<div class="underline">
										&nbsp;&nbsp;................................................
									</div>
								</td>
							</tr>
						</table>
					</td>
				</tr>
					
				<tr>
					<td colspan="8" style="border:1px solid #000;">
						<table width="100%" border="0" class="data2" style="white-space:nowrap; font-family:Khmer OS Battambang,Times New Roman;font-size:11px;line-height: 21px;">
							<tr>
								<td width="8%"></td>
								<td width="3%"></td>
								<td width="4%"></td>
								<td width="7%"></td>
								<td width="7%"></td>
								<td width="7%"></td>
								<td width="8%"></td>
								<td width="7%"></td>
								<td width="8%"></td>
								<td width="6%"></td>
								<td width="10%"></td>
								<td width="6%"></td>
							</tr>
							
							<tr>
								<td colspan="8">
									<table width="100%" style="white-space:nowrap; font-family:Khmer OS Battambang,Times New Roman;font-size:11px;line-height: 21px;">
										<tr>
											<td>សម្រាប់សេវា/Services</td>
											<td>
												<label id="checkbox1"></label> អាហារ និងស្នាក់នៅ/Food&Stay Fee
											</td>
											<td>
												<label id="checkbox2"></label> អាហារ/Food Fee
											</td>
											<td>
												<label id="checkbox3"></label> ស្នាក់នៅ/Stay Fee
											</td>
										</tr>
									</table>
								</td>
								
								<td >បញ្ចុះថ្លៃ/Discount</td>
								<td>
									: <label id="lb_discount" class="data1" ></label>
									<div class="underline">................</div>
								</td>
								
								
								<td >ថ្លៃសម្ភារៈ/Material Fee</td>
								<td>
									: <label id="lb_total_product_fee" class="data1" ></label>
									<div class="underline">..............</div>
								</td>
							</tr>
							
							<tr>
								
								<td colspan="12">
									<table width="100%" border="0" style="margin-top: -5px;white-space:nowrap; font-family:Khmer OS Battambang,Times New Roman;font-size:11px;line-height: 21px;">
										<tr>
											<td width="15%">ទឹកប្រាក់សរុប/Total Amount : </td>
											<td width="15%" align="center">
												<label id="lb_grand_total" class="data1" ></label>
												<div class="underline">.......................................</div>
											</td>
											
											<td width="12%" align="center">ទឹកប្រាក់ជំពាក់/Credit : </td>
											<td width="15%" align="center">
												<label id="lb_total_balance" class="data1" > </label>
												<div class="underline">........................................</div>
											</td>
											
											<td width="25%">ទឹកប្រាក់ទទួលបានសរុប/Total Received Amount</td>
											<td width="18%" style="border:1px solid #000;" align="center">
												<label id="lb_total_paid" class="data1" > </label>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							
							<tr>
								<td colspan="12">
									<table width="100%" border="0" style="margin-top: -5px;white-space:nowrap; font-family:Khmer OS Battambang,Times New Roman;font-size:11px;line-height: 21px;">
										<tr>
											<td width="18%">ទឹកប្រាក់ទទួលបានជាអក្សរ/In Words : </td>
											<td width="82%" align="center">
												&nbsp;<label id="lb_read_money" class="data1" ></label>
												<div class="underline">.......................................................................................................................................................................................................................</div>
											</td>
										</tr>
									</table>
								</td>	
							</tr>
							
							<tr>
								<td colspan="12">
									<table  width="100%" border="0" style="margin-top: -5px;white-space:nowrap; font-family:Khmer OS Battambang,Times New Roman;font-size:11px;line-height: 21px;">
										<tr>
											<td width="18%">មានសុពលភាពរយៈពេល/Payment Period : </td>
											<td width="21%" align="center">
												<label id="lb_payment_term" class="data1" ></label>
												<div class="underline">...................................................</div>
											</td>
											
											<td width="10%">ចាប់ពីថ្ងៃទី/Start Date : </td>
											<td width="21%" align="center">
												<label id="lb_start_date" class="data1" ></label>
												<div class="underline">...................................................</div>
											</td>
											
											<td width="9%">ដល់ថ្ងៃទី/End Date : </td>
											<td width="21%" align="center">
												<label id="lb_epx_date" class="data1" ></label>
												<div class="underline">.......................................</div>
											</td>
										</tr>
									</table>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				
				<tr>
					<td colspan="12">
						<table width="100%" style="white-space:nowrap; font-size:12px;font-family:Khmer OS Battambang, Times New Roman;">
							<tr>
								<td width="70%">&nbsp;</td>
								<td width="30%"align="right" >រាជធានីភ្នំពេញ.ថ្ងៃទី <?php echo date('d');?> / <?php echo date('m');?> / <?php echo date('Y');?></td>
							</tr>
						</table>
					</td>
				</tr>
				
				<tr>
					<td colspan="12">
						<table width="100%" style="white-space:nowrap; font-size:12px;font-family:Khmer OS Muol;font-weight:bold;">
							<tr>
								<td width="25%" align="center">ប្រធានគណនេយ្យ/Accounting Manager</td>
								<td width="25%" align="center">អ្នកបង់ប្រាក់/Payer</td>
								<td width="25%" align="center">បេឡា/Cashier</td>
								<td width="25%" align="center">អ្នកផ្តល់ព័ត៌មាន​/Receiptionist</td>
							</tr>
							
							
							<tr>
								<td colspan="4" align="center">&nbsp;</td>
							</tr>
							<tr>
								<td align="center" style="font-size:12px;"></td>
								<td align="center"></td>
								<td align="center">
									<div style=" font-size: 12px;"> 
										<?php 
										   $session_user=new Zend_Session_Namespace('auth');
										   $last_name=$session_user->last_name;
										   $username = $session_user->first_name;
										   echo $last_name." ".$username;
										?>
									</div>
								</td>
								<td align="center"></td>
							</tr>
							
							<tr>
								<td colspan="4" align="center" style="border-top: 1px solid #000;">&nbsp;</td>
							</tr>

						</table>
					</td>
				</tr>	
				<tr>
					<td colspan="12" >
						<table width="100%" style="margin-top:-20px; font-family:Khmer OS Battambang, Times New Roman; font-size:10px;white-space:nowrap;line-height: 15px;">
							<tr>
								<td colspan="2" valign="top" style="font-family:Khmer OS Muol;"><u>បញ្ជាក់ៈ Note</u></td>
							</tr>
							
							<tr>
								<td width="70%">
									<table width="100%" style="white-space:nowrap; font-size:10px;font-family:Khmer OS Battambang,Times New Roman;line-height: 14px;">
										<tr>
											<td>
												<div>- សូមអញ្ជើញមកបង់ប្រាក់ម្តងទៀតនៅថ្ងៃទី........................./The next payment will be on....................</div>
											</td>
										</tr>
										<tr>
											<td>
												<div>- ការបង់ប្រាក់យឺតចាប៉ពី........ថ្ងៃ សាលានឹងពិន័យស្មើទឹកប្រាក់ ប្រាំដុល្លាមួយថ្ងៃ/Late payment after......days of the valid date will be fined 5$ per day.</div>
											</td>
										</tr>
										<tr>
											<td>
												<div>- ប្រា់ដែលបង់ហើយមិនអាចដកវិញបានឡើយ/Your payment is non-returnable.</div>
											</td>
										</tr>
										<tr>
											<td>
												<div>- ប្រា់ដែលបានបង់មិនអាចផ្ទេរអោយអ្នកផ្សេងបានឡើយ/Your payment is not transferable.</div>
											</td>
										</tr>
										<tr>
											<td>
												<div>- រាល់ការបង់ប្រាក់ត្រូវទទួលបង្កាន់ដៃទទួលប្រាក់/We are responsible for all payment with receipt.</div>
											</td>
										</tr>
										
										<tr>
											<td>
												<div>- តម្លៃសិក្សាខាងលើ សម្រាប់តែសេវាអាហារ និងស្នាក់នៅតែប៉ុណ្ណោះ/This fee is for​ food and stay service only.</div>
											</td>
										</tr>
										
										<tr>
											<td>
												<div>- មតិអាណាព្យាបាល សូមទំនាក់ទំនងតាមលេខទូរស័ព្ទ/  Parent/Guadian's comment, Please call : 016 59 9999</div>
											</td>
										</tr>
										
										<tr>
											<td>
												<div>- Facebook: American Bridge International School</div>
											</td>
										</tr>
									</table>
								</td>
								<td width="30%" valign="top" align="center"> 
									លេខទូរស័ព្ទ/Tel: ការិយាល័យផ្តល់ព័ត៌មាន/Information office <br />
									- 085 591 007 <br />
									- 069 25 6666 <br />
									- 097 81 88888 <br />
								</td>
								
							</tr>
						</table>
					</td>
				</tr>		
			</table>
		</div>
		<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>	
		<button dojoType="dijit.form.Button" label="Cancel" iconClass="dijitEditorIcon dijitEditorIconCancel"
				showLabel="true" type="button" onclick="hideDialog();">Cancel</button>
		<button dojoType="dijit.form.Button" label="Print" iconClass="dijitEditorIcon dijitEditorIconPrint"
				showLabel="true" type="button" onclick="printSubmit();">Print</button>
	</div>
</div>

<script>


//save daata when sub button print 
function printSubmit(){
	//$('#office_receipt').submit();
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
}

function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    dijit.byId("terms").hide();	//hideDialog();
}


</script>
<script type="text/javascript">

var url_get_start_date = '<?php echo $this->url(array('module'=>'registrar','controller'=>'studentlunchpayment','action'=>'get-start-date-service')); ?>';
function getStartDateService(){
	service_id = dijit.byId('service').get('value');
	stu_id = dijit.byId('student_name_old').get('value');
	dojo.xhrPost({
		url:url_get_start_date,
		content:{
			'service_id':service_id,
			'stu_id':stu_id
			},
		handleAs:"json",
		load: function(data) {
			if(data){
				dijit.byId('start_date').attr('value',data);
			}	
		},
		error: function(err) {
			alert(err);
		}
	});
}

var url_get_service_cate = '<?php echo $this->url(array('module'=>'registrar','controller'=>'studentlunchpayment','action'=>'get-service-cate')); ?>';
function getServiceCate(service_id){
		//alert(service_id);
		dojo.xhrPost({
				url:url_get_service_cate,
				content:{
					'service_id':service_id
					},
				handleAs:"json",
				load: function(data) {
					dijit.byId('service_cate').attr('value',data)					 
				},
				error: function(err) {
					alert(err);
				}
		});
	
}



var url_getreceiptno = '<?php echo $this->url(array('module'=>'registrar','controller'=>'coursestudy','action'=>'get-receipt-no')); ?>';
	function getNewReceiptNo(new_stu_id,condition){
		
		dojo.xhrPost({
			url:url_getreceiptno,
			content:{
				'type':4, // lunch payment
				'branch_id':0,
				},
			handleAs:"json",
			load: function(data) {
				
				dijit.byId('receipt_no').attr('value',data);   
				if(condition==1){ 
					printSave(new_stu_id,data);
				}
				
			},
			error: function(err) {
				alert(err);
			}
		});
			
	}

function showPopupDept() {
	if(dijit.byId('faculty').value==-1){
		dijit.byId("popup_dept").show();
	}
}
function hideDialog() {		
	dijit.byId("terms").hide();
}

function calculateTotalPayment(){
	service_fee = dijit.byId('service_fee').get('value');
	qty = dijit.byId('qty').get('value');
	qty = isNaN(qty)?1:qty;
	service_fee = service_fee * qty;
	discount = dijit.byId('discount').get('value');
	discount = isNaN(discount)?0:discount;
	dijit.byId('total_payment').attr('value',service_fee-(service_fee*discount/100));
	dijit.byId('paid_amount').attr('value',service_fee-(service_fee*discount/100));
	calculatBalanceAndReturn();
	
	netTotal();
}

function calculatBalanceAndReturn(){
	total_payment = dijit.byId('total_payment').get('value');
	paid_amount = dijit.byId('paid_amount').get('value');

	if(paid_amount>total_payment){
		//dijit.byId('return').attr('value',paid_amount-total_payment);
		
		dijit.byId('balance').attr('value',0);
	}
	else{
		dijit.byId('balance').attr('value',total_payment-paid_amount);
		//dijit.byId('return').attr('value',0);
	}
}

var url_student_info = "<?php echo $this->url(array('module'=>'registrar','controller'=>'studentlunchpayment','action'=>'get-student')); ?>";
function getStudentInfo(){
	stu_type = dijit.byId('student_type').get('value');
	if(stu_type==1){
		studentid = dijit.byId('student_name_new').get('value');
	}else{
		studentid = dijit.byId('old_car_id').get('value');
	}
	
	dojo.xhrPost({
		url:url_student_info,
		content:{
			'studentid':studentid
			},
		handleAs:"json",
		load: function(data) {
			//alert(data.tel);
			dijit.byId("kh_name").attr("value",data.stu_khname);
			dijit.byId("en_name").attr("value",data.stu_enname);
			dijit.byId("sex").attr("value",data.sex);
			dijit.byId("phone").attr("value",data.tel);
		},
		error: function(err) {
			//alert(err);
		}
	});
}
var url_service_fee = "<?php echo $this->url(array('module'=>'registrar','controller'=>'studentlunchpayment','action'=>'get-price')); ?>";
function getservicefee(){
			
	student_type = dijit.byId('student_type').get('value');
	if(student_type==1){
		studentid = dijit.byId('student_name_new').get('value');
	}else{
		studentid = dijit.byId('student_name_old').get('value');
	}
	
	service = dijit.byId('service').get('value');
	term = dijit.byId('term').get('value');
	//year = dijit.byId('study_year').get('value');
	
	dojo.xhrPost({
		url:url_service_fee,
		content:{
			'term':term,
			'service':service,
			'studentid':studentid,
		//	'year':year,
			},
		handleAs:"json",
		load: function(data) {
			if(data.balance>0){
				clear();
				dijit.byId("service_fee").attr("value",data.balance);
				dijit.byId("other").attr("value",'លុយជំពាក់ពីមុន');
				dijit.byId("start_date").attr("value",data.start_date);
				dijit.byId("end_date").attr("value",data.validate);
				dijit.byId("balance_id").attr("value",data.id);
				calculateTotalPayment();
				setDateReadOnly();
				//alert(1);
			}else{
				clear();
				dijit.byId("service_fee").attr("value",data.price_fee);
				calculateTotalPayment();
				//getCurrentDate();
				removeDateReadOnly();
			}
		},
		error: function(err) {
			alert(err);
		}
	});
}
function clear(){
	dijit.byId("balance_id").attr("value",'');
	dijit.byId("service_fee").attr("value",0);
	dijit.byId("discount").attr("value",0);
	dijit.byId("total_payment").attr("value",0);
	dijit.byId("paid_amount").attr("value",0);
	dijit.byId("balance").attr("value",0);
	//dijit.byId("return").attr("value",0);
	dijit.byId("other").attr("value",'');
}
function setDateReadOnly(){
	//document.getElementById('start_date').readOnly = true;
	//document.getElementById("start_date").setAttribute("readonly", true);
	dijit.byId("start_date").set('readOnly',true);
	dijit.byId("end_date").set('readOnly',true);
}
function removeDateReadOnly(){
	dijit.byId("start_date").set('readOnly',false);
	dijit.byId("end_date").set('readOnly',false);
}
function getCurrentDate(){
	var currentDate = new Date();

    var day = currentDate.getDate();
	if(day<10){
		day='0'+day;
	}
    var month = currentDate.getMonth() + 1;
	if(month<10){
		month='0'+month;
	}
    var year = currentDate.getFullYear();
    var my_date = day+"/"+month+"/"+year;
    document.getElementById("start_date").value = my_date;
    getValidate();
}
function getValidate(){
	 term = dijit.byId('term').get('value');
	 qty = dijit.byId('qty').get('value');
	 qty = isNaN(qty)?1:qty;
	 start_date = dijit.byId('start_date').get('value');
	 if(term==1){
		 var a = new Date(start_date);
		  mm = a.getMonth()+(1*qty)+1;

		 var dd = a.getDate();
		  if(dd<10){
		   dd = "0"+dd;
		 }
		  if(mm<10){
		   mm = "0"+mm;
		 }
		 var y = a.getFullYear();
		 var epx_date = y + '-' + mm + '-' + dd ;

		 //alert(epx_date);
		 dijit.byId('end_date').attr('value',epx_date);
	 }
	 else if(term==2){
		 var a = new Date(start_date);
		  mm = a.getMonth()+(3*qty)+1;

		 var dd = a.getDate();
		  if(dd<10){
		   dd = "0"+dd;
		 }
		  if(mm<10){
		   mm = "0"+mm;
		 }
		 var y = a.getFullYear();
		 var epx_date = y + '-' + mm + '-' + dd ;

		 //alert(epx_date);
		 dijit.byId('end_date').attr('value',epx_date);
	 }
	 else if(term==3){
		 var a = new Date(start_date);
		  mm = a.getMonth()+(6*qty)+1;

		 var dd = a.getDate();
		  if(dd<10){
		   dd = "0"+dd;
		 }
		  if(mm<10){
		   mm = "0"+mm;
		 }
		 var y = a.getFullYear();
		 var epx_date = y + '-' + mm + '-' + dd ;

		 //alert(epx_date);
		 dijit.byId('end_date').attr('value',epx_date);
	 }
	 else if(term==4){
		 var a = new Date(start_date);
		  mm = a.getMonth()+(12*qty)+1;

		 var dd = a.getDate();
		  if(dd<10){
		   dd = "0"+dd;
		 }
		  if(mm<10){
		   mm = "0"+mm;
		 }
		 var y = a.getFullYear();
		 
		 var epx_date = y + '-' + mm + '-' + dd ;

		 //alert(epx_date);
		 dijit.byId('end_date').attr('value',epx_date);
	 }else if(term==5){
		var a = new Date(start_date);
		dd = a.getDate()+parseInt(qty); 
		 
		 if(dd<10){
		   dd = "0"+dd;
		 }
		 mm = a.getMonth()+1;
		 if(mm<10){
		   mm = "0"+mm;
		 }
		 var y = a.getFullYear(); 
		 var epx_date = y + '-' + mm + '-' + dd ;
		 
		 dijit.byId('end_date').attr('value',epx_date);
	 }
}
function getValue(){
	seperater='';
	i=0;
	$("#time_identity").val('');
	for(i=1;i<=4;i++){
		if(dijit.byId('time'+i).checked){
			//alert(dijit.byId('time'+i).get('value'));
			if($("#time_identity").val()!="") {
				var time_identity = $("#time_identity").val();
				$("#time_identity").val(time_identity+','+i);
			} else {$("#time_identity").val(i);}
		}
	}
}

var url_add_service = '<?php echo $this->url(array("module"=>"registrar","controller"=>"studentlunchpayment","action"=>"add-popup-lunch-service")); ?>';
function addService(){
	dojo.xhrPost({
			url:url_add_service,
			form: dojo.byId("frm_add_service"),
			handleAs:"json",
			load: function(data) {
				//alert(data); 
				var Itemmake = { 
				     id: data,
					         name: dijit.byId('service_name').get('value')
					   };
		 	addDataToSelectbox(dijit.byId('service'), service_store, Itemmake, data);
		    dijit.byId('frm_add_service').reset();
		    dijit.byId("popup_add_service").hide();
				
			},
			error: function(err) {
				alert(err);
			}
	});
}

function hidePopup() {		
	dijit.byId("popup_add_service").hide();
}


///////////////////////////////////////////////////////////// Add Row /////////////////////////////////////////////////////////

var template = '';
var service = '';
var col = 0;
var no = 0;
var title = 0;
tmp = '';
temp='';
date_format = '"dd/MM/yyyy"';
function addRow() {
		col++;no++;
		template='';
		if(title!=1){
			temp+='<th ><?php echo $tr->translate("DEL");?></th>';
			temp+='<th ><?php echo $tr->translate("N_O");?></th>';
			temp+='<th ><?php echo $tr->translate("PRODUCT");?></th>';
			temp+='<th  ><?php echo $tr->translate("PRICE");?></th>';
			temp+='<th  ><?php echo $tr->translate("AMOUNT");?></th>';
			temp+='<th  ><?php echo $tr->translate("DISCOUNT");?> %</th>';
			temp+='<th  ><?php echo $tr->translate("SUBTOTAL");?></th>';
			temp+='<th><?php echo $tr->translate("REMARK");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
			template+='<td align="center"  style="width:3%"><img onclick="deleteRecord('+col+');calculateTotal('+col+');" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template+='<td align="center" style="width:3%;">'+no+'</td>';
			
			template+='<td style="width:30%"><input type="hidden" dojoType="dijit.form.TextBox" name="id_balance_record_'+col+'" id="id_balance_record_'+col+'"/>';
			template+='<select style="width:100%"  onchange="getProductPrice('+col+');" dojoType="dijit.form.FilteringSelect" id="product_'+col+'" name="product_'+col+'">';
				template+='<option value="">Select </option>';
				<?php if(!empty($this->all_product)){foreach($this->all_product as $product){?>
					template+='<option value="'+<?php echo $product['id']?>+'"><?php echo $product['name'];?></option>';
				<?php }}?>
			template+='</select></td>';	

			
			column = 0;
			template+='<td style="width:10%"> <input class="fullside"  type="text"  onkeyup="calculateTotal('+col+');" name="price_'+col+'" id="price_'+col+'" dojoType="dijit.form.NumberTextBox" " /><label id="subsub"></label></td>';	
			template+='<td style="width:10%"> <input class="fullside" type="text"  onkeyup="calculateTotal('+col+');" name="qty_'+col+'" id="qty_'+col+'" value="1" dojoType="dijit.form.NumberTextBox" /><label id="qty"></label></td>';			
					
			template+='<td style="width:10%"> <input class="fullside"  type="text" onkeyup="calculateTotal('+col+');" name="discount_'+col+'" value="<?php echo 0;?>" id="discount_'+col+'" dojoType="dijit.form.NumberTextBox" /><label id="subsub"></label></td>';
			template+='<td style="width:10%"> <input class="fullside"  type="text"  readonly="readonly" name="subtotal_'+col+'" id="subtotal_'+col+'" dojoType="dijit.form.NumberTextBox"/><label id="qty"></label></td>';
			template+='<td style="width:24%"> <input class="fullside"  type="text" name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ" /><label id="subsub"></label></td>';

								//constraints="{datePattern:'dd/MM/yyyy'}"
			
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);

		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
		//getValidate(col);
 }
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
	if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
}



///////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////



/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

var url_getproductprice = '<?php echo $this->url(array('module'=>'registrar','controller'=>'register','action'=>'get-product-price')); ?>';
function getProductPrice(index){
	
	product = dijit.byId('product_'+index).get('value');
	qty = dijit.byId('qty_'+index).get('value');
	discount = dijit.byId('discount_'+index).get('value');
	
	dojo.xhrPost({
		url:url_getproductprice,
		content:{
			'product':product,
			},
		handleAs:"json",
		load: function(data) {
			if(data){
				//alert(data);
				
				fee_discount = data * qty * (discount/100);
				//alert(fee_discount);
				
				dijit.byId('price_'+index).attr('value',data);
				dijit.byId('subtotal_'+index).attr('value',(data * qty) - fee_discount);
				
				netTotal();
			}
		},
		error: function(err) {
			//alert(err);
		}
	});
}

function calculateTotal(index){
	price = dijit.byId('price_'+index).get('value');
	qty = dijit.byId('qty_'+index).get('value');
	qty=isNaN(qty)?1:qty;
	//if(qty==1){dijit.byId('qty_'+index).attr('value',qty);}
	total = price*qty;
	discount = dijit.byId('discount_'+index).get('value');
	discount = isNaN(discount)?0:discount;
	dijit.byId('subtotal_'+index).attr('value',total-(total*(discount/100)));
	netTotal();
}

function netTotal() {
	// alert(1);
		var netTotal=0;
		var netPaidAmount=0;
		var rowId = $('#identity').val();
		var rowIDArray = rowId.split(',');
		//alert(rowIDArray);
		
		//tuition_fee = dijit.byId('tuitionfee').get('value');
		paid_amount = dijit.byId('paid_amount').get('value');
		total_payment = dijit.byId('total_payment').get('value');
		
		if(document.getElementById('buy_product').checked){
			for(var n = 0; n < rowIDArray.length; n++) {
				//netTotal += Number($('#subtotal_'+rowIDArray[n]).val());
				netTotal += dijit.byId('subtotal_'+rowIDArray[n]).get('value');
				netPaidAmount += dijit.byId('subtotal_'+rowIDArray[n]).get('value');
			}
		}
		
		grand_total_payment = parseFloat(netTotal) + parseFloat(total_payment) ;
		grand_total_paid = parseFloat(netPaidAmount) + parseFloat(paid_amount) ;
				
		ex_rate = dijit.byId('ex_rate').get('value');
		
		dijit.byId('grand_total').attr('value',grand_total_payment);
		dijit.byId('convert_to_riels').attr('value',grand_total_payment * ex_rate);
		dijit.byId('total_received').attr('value',grand_total_paid);
		
		dijit.byId('total_balance').attr('value',grand_total_payment - grand_total_paid);
		
		readMoneyInKhmer(grand_total_paid.toFixed(2));
}

function readMoneyInKhmer(netTotal){
	//alert(netTotal);
	var str = netTotal.toString();
	str_cent = 'សេន';
	first_decimal = str.substr(-2);
	last_decimal = str.substr(-1);
	if(first_decimal>0){string='ក្បៀស';}else{string="";str_cent=""}
	if(first_decimal!='00' && first_decimal<10 ){str_zero = "សូន្យ";}else{str_zero='';}
	first_money_decimal = read_in_khmer_from_10_to_99(first_decimal);
	last_money_decimal = read_in_khmer_from_0_to_9(last_decimal)
	money_khmer=read_money_in_khmer(netTotal);

	if(first_decimal>0){string_en='dot';}else{string_en="";str_cent_en=""}
	if(first_decimal!='00' && first_decimal<10 ){str_zero_en = "Zero";}else{str_zero_en='';}
	first_money_decimal_en = read_in_english_from_10_to_99(first_decimal);
	last_money_decimal_en = read_in_english_from_0_to_9(last_decimal)
	money_english=read_money_in_english(netTotal);
	read_eng = money_english.trim()+string+ first_money_decimal+str_zero+last_money_decimal+'ដុល្លាគត់'

	read_eng = '( '+money_english.trim()+string_en+ first_money_decimal_en+str_zero_en+last_money_decimal_en+' Dollar Only )'
	
	dijit.byId('readmoney').attr('value',money_khmer.trim()+string+ first_money_decimal+str_zero+last_money_decimal+'ដុល្លាគត់');
}


function displayNoneAddRow(){
	
	if(document.getElementById('buy_product').checked){
		document.getElementById('table_row').style.display="block";
	}else{
		document.getElementById('table_row').style.display="none";
	}
	
}




///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////




</script>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:40%;" id="popup_add_service" >
		<form style="background-color: buttonface; width:100%;" id='frm_add_service' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
			<tr>
				<td>
					<fieldset style="background-color: buttonface;">
					<legend align="center" ><?php echo $tr->translate('ADD_SERVICE');?></legend><br />
						<table style="margin: 0 auto; width: 100%;  padding:10px;" cellspacing="7" >
							<tr>
								<td style="width:100px"><?php echo $tr->translate("SERVICE_TYPE")?></td>
								<td>
									<select dojoType="dijit.form.FilteringSelect"   class="fullside" id="service_type" name="service_type" value="" type="text">
										<?php if(!empty($this->service_type)){ foreach ($this->service_type as $service_type){?>
											<option value="<?php echo $service_type['id']?>"><?php echo $service_type['name']?></option>
										<?php }}?>
									</select>
								</td>
							</tr>
							<tr>
								<td style="width:100px"><?php echo $tr->translate("PROGRAM_TITLE")?></td>
								<td>
									<input dojoType="dijit.form.TextBox"  class="fullside" id="service_name" name="service_name" value="" type="text">
								</td>
							</tr>
							<tr>
							<tr>
								<td style="width: 5px"><?php echo $tr->translate("DISCRIPTION")?></td>
								<td>
									<input dojoType="dijit.form.TextBox"  class="fullside" id="description" name="description" value="" type="text">
								</td>
							</tr>
							<tr>
								<td style="width: 5px"><?php echo $tr->translate("STATUS")?></td>
								<td>
									<select name="status_popup" id="status_popup" dojoType="dijit.form.FilteringSelect"   class="fullside">
	    								<option value="1" label="active">Active</option>
	    								<option value="0" label="deactive">Deactive</option>
									</select>
								</td>
							</tr>
							<tr>
								<td colspan="4" align="center">
									<input type="button" value="ចាកចេញ" label="Close" id="close" name="close" dojoType="dijit.form.Button" 
									​ ​​iconClass="dijitIconUndo" onclick="hidePopup();"/>
									<input type="button" value="save" label="SAVE" id="save" name="save" dojoType="dijit.form.Button" 
									 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addService();"/>
								</td>
							</tr>
							
						</table>
				</fieldset>
				</td>
			</tr>
		</table>

		</form>
	</div>
</div>

