<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_STUDENT_DROP_LUNCH_AND_STAY')); 
?>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.CheckBox");
</script>



<form id="" action="<?php echo $this->url(array('module'=>'foundation','controller'=>'studentdroplunchandstay','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		
	<script type="dojo/method" event="onSubmit">
		if(this.validate()) {
			student_id = dijit.byId('studentid').get('value');
			if(student_id == -1){
				alert("Please select student !!!");
				dijit.byId('studentid').focus();
				return false;
			}
			return true;
		} else {
			return false;
		}
	</script>
	
	<table cellspacing="20" style="margin: 0 auto; width: 100%">
		<tr>
			<td>
				<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("ADD_STUDENT_DROP_LUNCH_AND_STAY");?></strong></legend>
					<table cellspacing="20" width="100%" >
						<tr>
							<td align="center" valign="top">
								<table cellspacing="10" width="100%"​>
									<tr>
										<td><?php echo $tr->translate("STUDENT_ID")?></td>
										<td>
											<select class="fullside"  name="studentid" id="studentid" autoComplete="false" queryExpr="*${0}*" dojoType="dijit.form.FilteringSelect" placeholder="Select student " onchange="getStudentInfo(1);" >
										    	<option value="-1"> </option>
										    	<?php if(!empty($this->stu_id))foreach ($this->stu_id as $row){?>
													<option value="<?php echo $row['stu_id']?>"><?php echo $row['stu_code']?></option>
												<?php }?>
											</select>
										</td>
										
										<td><?php echo $tr->translate("STUDENT_NAME")?></td>
										<td>
											<select class="fullside"  name="studentname" id="studentname" autoComplete="false" queryExpr="*${0}*" dojoType="dijit.form.FilteringSelect" placeholder="Select student " onchange="getStudentInfo(2);" >
										    	<option value="-1"> </option>
										    	<?php if(!empty($this->stu_name))foreach ($this->stu_name as $row){?>
													<option value="<?php echo $row['stu_id']?>"><?php echo $row['name']?></option>
												<?php }?>
											</select>
										</td>
										
										<td><?php echo $tr->translate("SEX")?></td>
										<td>
											<select dojoType="dijit.form.FilteringSelect"  readonly="readonly" class="fullside" id="gender" name="gender" type="text">
												<option value="1">Male</option>
												<option value="2">Female</option>
											</select>
										</td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("PHONE")?></td>
										<td>
											<input dojoType="dijit.form.TextBox" readonly="readonly" class="fullside" id="phone" name="phone" value="" type="text">
										</td>
										
										<td><?php echo $tr->translate("SERVICE")?></td>
										<td>
											<select name="service" id="service" dojoType="dijit.form.FilteringSelect" readOnly class="fullside" >
												<option value="-1">No Service</option>
												<?php if(!empty($this->lunch_service)){foreach ($this->lunch_service as $transport){?>
													<option value="<?php echo $transport['id']?>"><?php echo $transport['name']?></option>
												<?php }}?>
											</select>
										</td>
										
										<td><?php echo $tr->translate("TYPE")?></td>
										<td>
											<select dojoType="dijit.form.FilteringSelect" required="true" autoComplete="false" queryExpr="*${0}*" class="fullside" id="type" name="type" type="text">
												<option value="1">Suspend</option>
												<option value="2">Stop</option>
											</select>
										</td>
									</tr>
									<tr>
									
										<td><?php echo $tr->translate("REASON")?></td>
										<td><input dojoType="dijit.form.TextBox" class="fullside" id="reason" name="reason" value="" type="text"></td>
									
										<td><?php echo $tr->translate("STOP_DATE")?></td>
										<td><input dojoType="dijit.form.DateTextBox" class="fullside" id="datestop" name="datestop" value="now" type="text"></td>
									
										<td><?php echo $tr->translate("STATUS")?></td>
										<td>
											<select dojoType="dijit.form.FilteringSelect"  class="fullside" id="status" name="status" type="text">
												<option value="1">Active</option>
												<option value="0">Deactive</option>
											</select>
										</td>
									</tr>
									<tr>
										<td colspan="6" align="center">
										<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
										<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" dojoType="dijit.form.Button" 
											iconClass="dijitEditorIcon dijitEditorIconSave" />
										<input type="submit" value="save_new" name="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" dojoType="dijit.form.Button" 
											iconClass="dijitEditorIcon dijitEditorIconSave" />
										</td>
									</tr>					
								</table>
							</td>							
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
		
	</table>	
</form>
<script type="text/javascript">
	var url_student = '<?php echo $this->url(array('module'=>'foundation','controller'=>'studentdroplunchandstay','action'=>'get-student')); ?>';
	function getStudentInfo(type){
		studentid = dijit.byId('studentid').get('value');

		if(type==1){
			studentid = dijit.byId('studentid').get('value');
			dijit.byId("studentname").attr("value",studentid);
		}else{
			studentid = dijit.byId('studentname').get('value');
			dijit.byId("studentid").attr("value",studentid);
		}
		if(studentid>0){
			dojo.xhrPost({
				url:url_student,
				content:{
					'studentid':studentid
					},
				handleAs:"json",
				load: function(data) {
					dijit.byId("phone").attr("value",data.tel);
					dijit.byId("gender").attr("value",data.sex);
					dijit.byId("service").attr("value",data.service);
				},
				error: function(err) {
					alert(err);
				}
			});
		}
	}
</script>