<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_STUDENT_DROP_LUNCH_AND_STAY')); 
?>
<form id="add_car" action="<?php echo $this->url(array('module'=>'foundation','controller'=>'studentdroplunchandstay','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table cellspacing="20" style="margin: 0 auto; width: 100%">
		<tr>
			<td>
				<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("EDIT_STUDENT_DROP");?></strong></legend>
					<table cellspacing="20" width="100%" >
						<tr>
							<td align="center" valign="top">
								<table cellspacing="10" width="100%"​>
									<tr>
										<td><?php echo $tr->translate("STUDENT_ID")?></td><input type="hidden" name="id" value="<?php echo $this->row['id'];?>" />
										<td>
											<select readonly="readonly" class="fullside" name="studentid" id="studentid" dojoType="dijit.form.FilteringSelect" onchange="getStudentInfo();" >
										    	<?php if(!empty($this->stu_id))foreach ($this->stu_id as $row){?>
													<option value="<?php echo $row['stu_id']?>"<?php if($row['stu_id']==$this->row['stu_id']) echo 'selected="selected"';?>><?php echo $row['stu_code']?></option>
												<?php }?>
											</select>
										</td>
										<td><?php echo $tr->translate("STUDENT_NAME")?></td>
										<td>
											<select class="fullside" name="studentname" id="studentname" readonly="readonly" dojoType="dijit.form.FilteringSelect"  >
										    	<?php if(!empty($this->stu_name))foreach ($this->stu_name as $row){?>
													<option value="<?php echo $row['stu_id']?>"<?php if($row['stu_id']==$this->row['stu_id']) echo 'selected="selected"';?>><?php echo $row['name']?></option>
												<?php }?>
											</select>
										</td>
										
										<td><?php echo $tr->translate("SEX")?></td>
										<td>
											<select dojoType="dijit.form.FilteringSelect"  readonly="readonly" class="fullside" id="gender" name="gender" type="text">
												<option value="1">Male</option>
												<option value="2">Female</option>
											</select>
										</td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("PHONE")?></td>
										<td>
											<input dojoType="dijit.form.TextBox" readonly="readonly" class="fullside" id="phone" name="phone" value="" type="text">
										</td>
										
										<td><?php echo $tr->translate("SERVICE")?></td>
										<td>
											<select name="service" id="service" dojoType="dijit.form.FilteringSelect" readOnly class="fullside" >
												<option value="-1">No Service</option>
												<?php if(!empty($this->lunch_service)){foreach ($this->lunch_service as $lunch){?>
													<option value="<?php echo $lunch['id']?>"><?php echo $lunch['name']?></option>
												<?php }}?>
											</select>
										</td>
										
										<td><?php echo $tr->translate("TYPE")?></td>
										<td>
											<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="type" name="type" type="text">
												<option value="1" <?php if($this->row['type']==1) echo 'selected="selected"';?>>Suspend</option>
												<option value="2" <?php if($this->row['type']==2) echo 'selected="selected"';?>>Stop</option>
											</select>
										</td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("REASON")?></td>
										<td>
											<input dojoType="dijit.form.TextBox" class="fullside" id="reason" name="reason" value="<?php echo $this->row['reason'];?>" type="text">
										</td>
										
										<td><?php echo $tr->translate("STOP_DATE")?></td>
										<td>
											<input dojoType="dijit.form.DateTextBox" class="fullside" id="datestop" name="datestop" value="<?php echo $this->row['date'];?>" type="text">
										</td>
										
										<td><?php echo $tr->translate("STATUS")?></td>
										<td>
											<select dojoType="dijit.form.FilteringSelect" required="true" class="fullside" id="status" name="status" type="text">
												<option value="1" <?php if($this->row['status']==1) echo 'selected="selected"';?>>Active</option>
												<option value="0" <?php if($this->row['status']==0) echo 'selected="selected"';?>>Deactive</option>
											</select>
										</td>
									</tr>
									<tr>
										<td colspan="6" align="center">
											<input iconClass="dijitIconClear" type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button"/>
											<input type="button" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
									 		iconClass="dijitIconUndo" onclick="window.location = '<?php echo $this->url(array('module'=>'foundation','controller'=>"studentdroplunchandstay",'action'=>'index'),null,true); ?>';" />
											<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('GO_EDIT');?>" dojoType="dijit.form.Button" 
											iconClass="dijitEditorIcon dijitEditorIconSave" />
										</td>
									</tr>					
								</table>
							</td>							
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
		
	</table>	
</form>
<script type="text/javascript">
var url_student = '<?php echo $this->url(array('module'=>'foundation','controller'=>'studentdroplunchandstay','action'=>'get-student')); ?>';

dojo.ready(function(){
	getStudentInfo();
});
function getStudentInfo(){
			studentid = dijit.byId('studentid').get('value');
			dojo.xhrPost({
				url:url_student,
				content:{
					'studentid':studentid
					},
				handleAs:"json",
				load: function(data) {
					dijit.byId("phone").attr("value",data.tel);
					dijit.byId("gender").attr("value",data.sex);
					dijit.byId("service").attr("value",data.service);
				},
				error: function(err) {
					alert(err);
				}
			});
}
</script>